<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="style.css" rel="stylesheet" type="text/css">
<base target="_blank">
</head>
	      
<body>
		<h2>&nbsp;&nbsp;&nbsp;Philippine NewsLink</h2>
		<div id="column2_text" class="scroll"><div>
<ul>
<li>Will the Philippines Finally Become an Asian Tiger Economy?<br />
We hope…but don’t hold your breath. We’ve been hearing a lot of rumblings about how great the Philippine economy is doing. The World Bank through its country director for the Philippines, Motoo Konishi stated that "The Philippines is no longer the sick man of Asia, but a rising tiger." And lately there are plenty of bright spots to point to, the most important of which is the country’s GDP (gross domestic product) growth: 6.6 percent in 2012—the highest in Southeast Asia—beating even the government’s high-end target of six percent ...
<li>Institute a Draft for All Filipino Men and Women of Military Age<br />
With China breathing down our necks and seizing islands inside the Philippine territorial limits, it is about time that the country institute a draft for all able-bodied men and women upon reaching the age of maturity. Singapore and South Korea, two of the most advanced countries in the region have had conscription for decades. Taiwan, another Southeast Asian powerhouse has been conscripting their young men—and some women—since 1949 ...
<li>With the RH Bill Becoming Law…Maybe there Is Hope for the PH After All<br />
It has taken us 491 years but we Filipinos have finally stood up to the Catholic Church and said “we’re not going to take it anymore!” It’s bad enough that condoms and contraceptives are readily available in pharmacies all over Rome—where the Vatican is located—so why shouldn’t they be readily available here?
<li>Americans Need to Open Their Eyes and End Their Fascination with Guns<br />
As a Filipino-American who migrated to the United States, I unabashedly admit that I have always been impressed with Americans and American society. They seem to really “have it together.” They can be frivolous and funny and never think twice about laughing at themselves, but at the end of the day, they are a can-do people living in a country of great consequence ...
<li>The Reproductive Health Bill—More Than Just a Family-planning Choice<br />
As if to remind everyone that the country’s future is in for a rough ride ahead, typhoon Pablo lashed the Visayas and Mindanao regions leaving death, devastation and mangled holiday displays in its wake. The Philippines already has the distinction of being one of the top five countries most affected by extreme weather conditions in 2011*—and from the looks of it, the climate isn’t likely to get better anytime soon ...
<li>When an Apology Really Isn’t an Apology<br />
Accusations of plagiarism have been hounding Senator Vicente “Tito” Sotto III for several weeks now. And the good senator appears to have spent most of his time hee-hawing around an apology instead of actually making one. On November 13th Sotto took to the Senate floor and offered more excuses—saying it was actually a SMS text message sent to him by a friend that he translated into Pilipino. He didn’t know they were the words of the late Robert F. Kennedy. Sotto then went on to say that though he may have unknowingly translated parts of RFK’s speech, “copying or imitation is the highest form of flattery” ...
<li>Women Got Barack Obama Reelected<br />
As the American women’s grassroots organization UltraViolet puts it: the just concluded US election has made 2012 is the year of the woman! Not only did women make up 54% of the electorate, but the gender gap which stood at 18 points was at record highs. Women showed up in force to put a stop to what they saw as the Republican Party’s blatant overreach to curtail women’s rights and possibly overturn Roe v. Wade ...
<li>Political Dynasties—One Reason Why the Philippines Has Fallen So Far Behind<br />
What’s in a name? In the Philippines unfortunately, a name is everything. Take product brands for example. To Filipinos, toothpaste is “colgate;” a refrigerator is a “frigidare;” to photocopy is to “xerox;” and picture-taking is of course “kodakan” ...
<li>Philippine Cybercrime Law: Curtailing Freedom of Speech Will Not Work<br />
The new Cybercrime Law is piece of legislation that has no place in contemporary Philippine society. The fact that some members of the Philippine Senate managed to insert in it a provision that incorporates the country’s draconian libel laws in order to stifle online speech shows that a few of our legislators still lack the maturity to handle criticism and prefer that no one say nasty things about them—true or otherwise ...
<li>Forty Years After Martial Law, and the Marcoses Still Haven't Apologized<br />
Forty years have come and gone since former President Ferdinand Marcos issued Presidential Decree 1081 on September 21, 1972. But to this day, not one of the Marcoses or any of his former cronies has ever apologized to the Filipino people for it. Instead the family and supporters of the late strongman have been trying to rewrite history with half-truths or outright falsehoods that paint Ferdinand Marcos as being something other than the lying, scheming, tyrant that he was ...
<li>An Obama Reelection and What It Will Mean for Filipinos<br />
Nowhere in recent American political history has there been such a polarization in political party ideology as we are seeing in this year’s presidential elections. It appears that both the Democrats and the Republicans have dug in their heels and are refusing to give an inch to the other side. That leaves only a sliver of undecided voters in swing states to determine the outcome of this presidential race ...
<li>Filipinos Pin Their Hopes for Judicial Reform on Chief Justice Sereno<br />
Filipinos now look to the appointment of Maria Lourdes Sereno as Chief Justice of the Philippines to herald a new age of transparency and justice. This is after all a supreme court perceived by many as highly secretive, arguably corrupt, and there not to dispense justice but to line the pockets of those working in it ...
<li>It is Time the Catholic Church Butt-out of RH Bill Discussions<br />
In Management classes students are taught that any “authority” comes with a corresponding dose of “responsibility.” In other words as one moves up an organization they acquire more power and authority but they also shoulder more responsibility not just for the decisions they make but also for the fate of the organization as a whole. An organization that grants individuals the authority to make decisions but does not hold them responsible for the consequences of those decisions is a dysfunctional—usually tyrannical—organization devoid of fairness and justice. No democracy can survive in such a setting as the essence of a democracy is popular representation and public accountability ...
<li>A New "Statehood" Movement? Pinoys for Annexation By China<br />
With Chinese ships maneuvering unimpeded all over the South China Sea, and the Philippines unable to do anything but watch, there is a miniscule yet growing number of Filipinos who are taking to heart the adage “If you can’t beat ‘em, join ‘em.” These folks are the 21st century version of the “Philippine Statehood” movement of the sixties and seventies. And while the rest of us might quickly dismiss them as an inconsequential, fringe group, they do make compelling arguments for their cause ...
<li>Decades of Mistakes Are Highlighted by the Pantag (Scarborough) Shoal Issue<br />
China is getting tough with the Philippines for a reason…it can easily afford to. As far as the Chinese are concerned, Scarborough Shoal is the “low hanging fruit” that is the easiest to pluck. Among the nations that claim ownership to parts of the Spratly and the Paracel Islands, the Philippine military appears the least able to stand up to China’s military might" ...
<li>Some Pinoy Public Servants Don't Take Their Jobs Seriously Enough<br />
On May 25, 2012 the Syrian military began bombarding the town of Houla located north of Damascus in the Homs region of Syria with heavy artillery. The town had become a stronghold of the Free Syrian Army and rebel forces seeking to overthrow the brutal regime of President Bashar Assad. After shelling the town for hours "government militia then went house to house slaughtering entire families without compassion or mercy" according to British Foreign Secretary William Hague who had earlier spoken with United Nations observers as well as independent witnesses inside Syria ...
<li>The Balangiga Bells: Why Do We Need Them Back?<br />
With President Aquino on a state visit to Washington this week, the issue regarding the return of the Balangiga bells has once again resurfaced. In 1901, three bells were taken from the church belfry in Balangiga, a town in Eastern Samar by responding American troops after 48 of their soldiers were killed by the townspeople. The bells’ tolling was used by the Filipinos to signal the surprise attack on the 75-man US garrison in the town ...
<li>The First Step in Taking Back Our Government<br />
The fat lady has finally sung and Chief Justice Renato Corona is now out of a job. The best laid plans of former President Gloria Arroyo is now teetering at the brink of collapse and may soon come crashing down on her and her cabal of former “high fliers” who thought themselves invincible a few years back. If this were a chess game, it would seem Arroyo just gave up her “queen.” ...
<li>Chief Justice Renato Corona: A Sorry Sight to See and Hear<br />
In all honesty Chief Justice Renato Corona appears to be an embarrassment to the Filipino people. Is this the best we Pinoys can do? He is supposed to be the country’s top lawyer; the leader of one of the three branches of government; the jurist who sits at the helm of the highest court of the land—as in other countries, people expect that individual to be a person of “unimpeachable” credentials—one who stands head and shoulders above the rest of us in his understanding of the law, his ethics, and his moral principles ...
<li>The CJ Corona Trial: Impeachments Are Definitely More “Fun” in the Philippines<br />
If the Senate impeachment court somehow manages to acquit Chief Justice Renato Corona after what transpired in court on May 22, you can bet your last centavo that the Filipino people will be up in arms against the senator-judges. Sadly Corona’s timing to throw the equivalent of a temper tantrum could not have been worse. He did it on live television on a day when most Filipinos who were anxious to hear what he had to say were glued to their TV sets ...
<li>Arrogant Pinoys: The Airport Brawl<br />
Most Filipinos believe they belong to a peaceful, fun loving, and gentle culture. The reality however is a bit more nuanced. Sure, you get plenty of smiles and much acquiescence from those whose job it is to serve you. But beyond that, the Philippines of 2012 is a dog-eat-dog world. There is none of the gentility that one almost takes for granted in Europe and North America. In Manila people cut in line at cues, cut you off on roadways, barge into elevators before you can exit, avoid eye contact, and exhibit overall boorish behavior ...
<li>Can the Philippines Stand up to China?<br />
The current standoff on Scarborough Shoal between the Philippines and China only serves to highlight this country’s marked inadequacy in patrolling and defending its borders. The fact that Scarborough (Panatag to Filipinos) Shoal is on the country’s continental shelf just 124 nautical miles from Zambales—well within its 200-mile exclusive economic zone—has not stopped the Chinese from claiming it as their own ...
<li>Remembering the Sacrifices of Our Forefathers During World War II<br />
It seems that as a general rule Filipinos refuse to be bothered with their past. We live for the present and look to the future, but seldom do we glance back at the past. Three hundred sixty-seven years of Spanish colonial policy made sure that Filipinos paid no mind to their past—their pre-Hispanic customs, traditions, folklore, beliefs, as well as their pagan Malay culture ...
</ul></div>

          </div>

</body>
</html>
