<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link href="style.css" rel="stylesheet" type="text/css">
<base target="_blank">
</head>

<body>
<div class="scroll">
<div id="main"><div>
<p>IPL News<br /><span></span></p>
<ul>
<li><a href='http://www.premierleaguenews.in/ipl-stats/ipl-2011-statistics/ipl-2011-batsman-with-maximum-half-century/' target="_blank">IPL 2011 Batsman With Maximum Half Century</a><br />
Indian Premier League 2011 Batsman With Highest Half Century Team Name Half Centuries Chennai Super Kings Subramaniam Badrinath 5 Mumbai Indians Ambati Rayudu 4 Kolkata Knight Riders Jacques Kallis 4 Chennai Super Kings Suresh Raina 4 Kings XI Punjab Shaun Marsh 4 Royal Challengers Bangalore Virat Kohli 4
<li><a href='http://www.premierleaguenews.in/ipl-stats/ipl-2011-statistics/ipl-2011-batsman-with-highest-score/' target="_blank">IPL 2011 Batsman With Highest Score</a><br />
Indian Premier League 2011 Batsman With Highest Score Team Name Score Kings XI Punjab Paul Valthaty 120 Delhi Daredevils Virender Sehwag 119 Royal Challengers Bangalore Chris Gayle 107 Kings XI Punjab Adam Gilchrist 106 Mumbai Indians Sachin Tendulkar 100
<li><a href='http://www.premierleaguenews.in/ipl-stats/ipl-2011-statistics/ipl-2011-batsman-with-maximum-boundaries/' target="_blank">IPL 2011 Batsman With Maximum Boundaries</a><br />
Indian Premier League 2011 Batsman With Highest Sixes / 6s Team Name 6s Royal Challengers Bangalore Chris Gayle 44 Chennai Super Kings MS Dhoni 21 Kings XI Punjab Paul Valthaty 20 Kings XI Punjab Shaun Marsh 20 Pune Warriors Yuvraj Singh 18 Kings XI Punjab Adam Gilchrist 18 Delhi Daredevils Virender Sehwag 18 &#160; Indian 
<li><a href='http://www.premierleaguenews.in/ipl-stats/ipl-2011-statistics/ipl-2011-team-performance-card/' target="_blank">IPL 2011 Team Performance Card</a><br />
Team Group Played Won Lost Draw / NR Points Net Run Rate Royal Challengers Bangalore B 14 9 4 1 19 +0.326 Chennai Super Kings B 14 9 5 0 18 +0.443 Mumbai Indians A 14 9 5 0 18 +0.040 Kolkata Knight Riders B 14 8 6 0 16 +0.433 Kings XI Punjab A 
<li><a href='http://www.premierleaguenews.in/ipl-stats/ipl-2011-statistics/ipl-2011-bowler-leading-wicket-taker/' target="_blank">IPL 2011 Bowler : Leading Wicket Taker</a><br />
Indian Premier League 2011 Bowler : Leading Wicket Taker Player Team Wckts Ov&#8217;s Matches ER Best Bowling Lasith Malinga Mumbai Indians 28 63.0 16 5.95 5/13 Munaf Patel Mumbai Indians 22 54.2 15 6.58 5/21 Sreenath Aravind Royal Challengers Bangalore 19 43.0 12 7.65 4/14 Amit Mishra Deccan Chargers 19 53.2 14 6.71 4/9 Ravichandran 
<li><a href='http://www.premierleaguenews.in/ipl-stats/ipl-2011-statistics/ipl-2011-match-top-scorer-batsman/' target="_blank">IPL 2011 Match Top Scorer Batsman</a><br />
Indian Premier League 2011 Match Top Scorer Batsman Player Team Matches Runs High Score 4s 6s Chris Gayle Royal Challengers Bangalore 11 608 107 56 44 Sachin Tendulkar Mumbai Indians 16 553 100* 67 5 Virat Kohli Royal Challengers Bangalore 15 522 71 54 15 Shaun Marsh Kings XI Punjab 14 504 95 52 20 
<li><a href='http://www.premierleaguenews.in/ipl-stats/ipl-2011-statistics/indian-premier-league-team-standings-%e2%80%93-2011/' target="_blank">Indian Premier League Team Standings – 2011</a><br />
Team Group Played Won Lost Draw / NR Points Net Run Rate Royal Challengers Bangalore B 14 9 4 1 19 +0.326 Chennai Super Kings B 14 9 5 0 18 +0.443 Mumbai Indians A 14 9 5 0 18 +0.040 Kolkata Knight Riders B 14 8 6 0 16 +0.433 Kings XI Punjab A 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-semi-final-3-video-rcb-vs-mi-eliminator-match-video/' target="_blank">IPL 2011 Semi-Final 3 Video – RCB vs MI – Eliminator Match Video</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Semi-Final 3 Video &#8211; RCB vs MI
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-qualifier-2-mumbai-indians-vs-royal-challengers-bangalore/' target="_blank">IPL 2011 Qualifier 2 – Mumbai Indians vs Royal Challengers Bangalore</a><br />
Mumbai Indians vs Royal Challengers Bangalore, Qualifier 2 (Winner Eliminator v Loser Qualifier 1) May 27, 2011, IPL 2011, MA Chidambaram Stadium, Chepauk, Chennai (D/N) Umpires: A Rauf (PAK) and S Taufel (AUS) Third Umpire: K Dharmasena (SL) Match Referee: R Mahanama (SL) Match Result: Royal Challengers Bangalore won by 43 runs&#124;Man of the Match: 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-semi-final-2-video-kkr-vs-mi-qualifier-2-match-video/' target="_blank">IPL 2011 Semi-Final 2 Video – KKR vs MI – Qualifier 2 – Match Video</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Semi-Final 2 Video &#8211; KKR vs MI
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-eliminator-mumbai-indians-vs-kolkata-knight-riders/' target="_blank">IPL 2011 Eliminator – Mumbai Indians vs Kolkata Knight Riders</a><br />
Mumbai Indians vs Kolkata Knight Riders, Eliminator (3rd v 4th) May 25, 2011, IPL 2011, Wankhede Stadium, Mumbai (D/N) Umpires: A Rauf (PAK) and S Taufel (AUS) Third Umpire: P Reiffel (AUS) Match Referee: R Mahanama (SL) Match Result: Mumbai Indians won by 4 wickets&#124;Man of the Match: Munaf Patel Mumbai Indians : 148 / 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-semi-final-1-video-rcb-vs-csk-qualifier-1-match-video/' target="_blank">IPL 2011 Semi-Final 1 Video – RCB vs CSK – Qualifier 1 – Match Video</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Semi-Final 1 Video &#8211; RCB vs CSK
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-qualifier-1-royal-challengers-bangalore-vs-chennai-super-kings/' target="_blank">IPL 2011 Qualifier 1 – Royal Challengers Bangalore vs Chennai Super Kings</a><br />
Royal Challengers Bangalore vs Chennai Super Kings, Qualifier 1 (1st v 2nd) May 24, 2011, IPL 2011, Wankhede Stadium, Mumbai (D/N) Umpires: A Rauf (PAK) and S Taufel (AUS) Third Umpire: P Reiffel (AUS) Match Referee: R Mahanama (SL) Match Result: Chennai Super Kings won by 6 wickets&#124;Man of the Match: Suresh Raina Chennai Super 
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-70-may-22-kolkata-knight-riders-v-mumbai-indians/' target="_blank">IPL 2011 Match 70 May-22 Kolkata Knight Riders v Mumbai Indians</a><br />
Kolkata Knight Riders vs Mumbai Indians, 70th Match May 22, 2011, IPL 2011, Eden Gardens, Kolkata (D/N) Umpires: S Tarapore (IND) and S Taufel (AUS) Third Umpire: S Ravi (IND) Match Referee: D Govindjee (SA) Match Result: Mumbai Indians won by 5 wickets&#124;Man of the Match: James Franklin Mumbai Indians : 178 / 5 in 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-70-video-kolkata-knight-riders-v-mumbai-indians/' target="_blank">IPL 2011 Match 70 Video – Kolkata Knight Riders v Mumbai Indians</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 70 Video &#8211; Kolkata Knight Riders v Mumbai Indians
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-69-may-22-royal-challengers-bangalore-v-chennai%c2%a0super-kings/' target="_blank">IPL 2011 Match 69 May-22 Royal Challengers Bangalore v Chennai Super Kings</a><br />
Royal Challengers Bangalore vs Chennai Super Kings, 69th Match May 22, 2011, IPL 2011, M Chinnaswamy Stadium, Bangalore Umpires: K Hariharan (IND) and R Koertzen (SA) Third Umpire: K Dharmasena (SL) Match Referee: R Mahanama (SL) Match Result: Royal Challengers Bangalore won by 8 wickets&#124;Man of the Match: Chris Gayle Royal Challengers Bangalore : 129 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-69-video-royal-challengers-bangalore-v-chennai%c2%a0super-kings/' target="_blank">IPL 2011 Match 69 Video – Royal Challengers Bangalore v Chennai Super Kings</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 69 Video &#8211; Royal Challengers Bangalore v Chennai Super Kings
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-68-may-21-delhi-daredevils-v-pune-warriors/' target="_blank">IPL 2011 Match 68 May-21 Delhi Daredevils v Pune Warriors</a><br />
Delhi Daredevils vs Pune Warriors, 68th Match May 21, 2011, IPL 2011, Feroz Shah Kotla, Delhi (D/N) Umpires: S Hazare (IND) and R Tucker (AUS) Third Umpire: R Tiffin (ZIM) Match Referee: A Pycroft (ZIM) Match Result: No Results (Match Abandoned Due To Rain)&#124;Man of the Match: Delhi Daredevils : 56 / 3 in 10.1 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-68-video-delhi-daredevils-v-pune-warriors/' target="_blank">IPL 2011 Match 68 Video – Delhi Daredevils v Pune Warriors</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 68 Video &#8211; Delhi Daredevils v Pune Warriors
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-67-may-21-kings-xi-punjab-v-deccan-chargers/' target="_blank">IPL 2011 Match 67 May-21 Kings XI Punjab v Deccan Chargers</a><br />
Kings XI Punjab vs Deccan Chargers, 67th Match May 21, 2011, IPL 2011, Himachal Pradesh Cricket Association Stadium, Dharamsala Umpires: A Rauf (PAK) and A Saheba (IND) Third Umpire: S Shastri (IND) Match Referee: G Labrooy (SL) Match Result: Deccan Chargers won by 82 runs&#124;Man of the Match: Shikhar Dhawan Kings XI Punjab : 116 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-67-video-kings-xi-punjab-v-deccan-chargers/' target="_blank">IPL 2011 Match 67 Video – Kings XI Punjab v Deccan Chargers</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 67 Video &#8211; Kings XI Punjab v Deccan Chargers
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-66-may-20-mumbai-indians-v-rajasthan-royals/' target="_blank">IPL 2011 Match 66 May-20 Mumbai Indians v Rajasthan Royals</a><br />
Mumbai Indians vs Rajasthan Royals, 66th Match May 20, 2011, IPL 2011, Wankhede Stadium, Mumbai (D/N) Umpires: P Reiffel (AUS) and R Koertzen (SA) Third Umpire: S Asnani (IND) Match Referee: J Srinath (IND) Match Result: Rajasthan Royals won by 10 wickets&#124;Man of the Match: Shane Watson Rajasthan Royals : 134 / 0 in 13.1 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-66-video-mumbai-indians-v-rajasthan-royals/' target="_blank">IPL 2011 Match 66 Video – Mumbai Indians v Rajasthan Royals</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 66 Video &#8211; Mumbai Indians v Rajasthan Royals
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-65-may-19-pune-warriors-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 65 May-19 Pune Warriors v Kolkata Knight Riders</a><br />
Pune Warriors vs Kolkata Knight Riders, 65th Match May 19, 2011, IPL 2011, Dr DY Patil Sports Academy, Mumbai (D/N) Umpires: S Ravi (IND) and S Taufel (IND) Third Umpire: S Tarapore (IND) Match Referee: D Govindjee (SA) Match Result: Kolkata Knight Riders won by 7 wickets&#124;Man of the Match: Yusuf Pathan Kolkata Knight Riders 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-65-video-pune-warriors-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 65 Video – Pune Warriors v Kolkata Knight Riders</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 65 Video &#8211; Pune Warriors v Kolkata Knight Riders
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-64-may-18-chennai%c2%a0super-kings%c2%a0v-kochi-tuskers-kerala/' target="_blank">IPL 2011 Match 64 May-18 Chennai Super Kings v Kochi Tuskers Kerala</a><br />
Chennai Super Kings vs Kochi Tuskers Kerala, 64th Match May 18, 2011, IPL 2011, MA Chidambaram Stadium, Chepauk, Chennai (D/N) Umpires: K Dharmasena (SL) and R Koertzen (SA) Third Umpire: K Hariharan (IND) Match Referee: R Mahanama (SL) Match Result: Chennai Super Kings won by 11 runs&#124;Man of the Match: Wriddhiman Saha Kochi Tuskers Kerala 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-64-video-chennai%c2%a0super-kings%c2%a0v-kochi-tuskers-kerala/' target="_blank">IPL 2011 Match 64 Video – Chennai Super Kings v Kochi Tuskers Kerala</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 64 Video &#8211; Chennai Super Kings v Kochi Tuskers Kerala
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-63-may-17-kings-xi-punjab-v-royal-challengers-bangalore/' target="_blank">IPL 2011 Match 63 May-17 Kings XI Punjab v Royal Challengers Bangalore</a><br />
Kings XI Punjab vs Royal Challengers Bangalore, 63rd Match May 17, 2011, IPL 2011, Himachal Pradesh Cricket Association Stadium, Dharamsala (D/N) Umpires: A Rauf (PAK) and A Saheba (IND) Third Umpire: S Shastri (IND) Match Referee: G Labrooy (SL) Match Result: Kings XI Punjab won by 111 runs&#124;Man of the Match: Adam Gilchrist Royal Challengers 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-63-video-kings-xi-punjab-v-royal-challengers-bangalore/' target="_blank">IPL 2011 Match 63 Video – Kings XI Punjab v Royal Challengers Bangalore</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 63 Video &#8211; Kings XI Punjab v Royal Challengers Bangalore
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-62-may-16-pune-warriors-v-deccan-chargers/' target="_blank">IPL 2011 Match 62 May-16 Pune Warriors v Deccan Chargers</a><br />
Pune Warriors vs Deccan Chargers, 62nd Match May 16, 2011, IPL 2011, Dr DY Patil Sports Academy, Mumbai (D/N) Umpires: S Ravi (IND) and S Tarapore (IND) Third Umpire: S Taufel (AUS) Match Referee: D Govindjee (SA) Match Result: Deccan Chargers won by 6 wickets&#124;Man of the Match: Amit Mishra Deccan Chargers : 138 / 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-62-video-pune-warriors-v-deccan-chargers/' target="_blank">IPL 2011 Match 62 Video – Pune Warriors v Deccan Chargers</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 62 Video &#8211; Pune Warriors v Deccan Chargers
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-61-video-kochi-tuskers-kerala-v-rajasthan-royals/' target="_blank">IPL 2011 Match 61 Video – Kochi Tuskers Kerala v Rajasthan Royals</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 61 Video &#8211; Kochi Tuskers Kerala v Rajasthan Royals
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-61-may-15-kochi-tuskers-kerala-v-rajasthan-royals/' target="_blank">IPL 2011 Match 61 May-15 Kochi Tuskers Kerala v Rajasthan Royals</a><br />
Kochi Tuskers Kerala vs Rajasthan Royals, 61st Match May 15, 2011, IPL 2011, Holkar Cricket Stadium, Indore (D/N) Umpires: P Reiffel (AUS) and R Tucker (AUS) Third Umpire: S Asnani (IND) Match Referee: R Mahanama (SL) Match Result: Kochi Tuskers Kerala won by 8 wickets&#124;Man of the Match: Brad Hodge Kochi Tuskers Kerala : 98 
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-60-may-15-kings-xi-punjab-v-delhi-daredevils/' target="_blank">IPL 2011 Match 60 May-15 Kings XI Punjab v Delhi Daredevils</a><br />
Kings XI Punjab vs Delhi Daredevils, 60th Match May 15, 2011, IPL 2011, Himachal Pradesh Cricket Association Stadium, Dharamsala Umpires: A Rauf (PAK) and S Shastri (IND) Third Umpire: A Saheba (IND) Match Referee: G Labrooy (SL) Match Result: Kings XI Punjab won by 29 runs&#124;Man of the Match: Piyush Chawla Delhi Daredevils : 141 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-60-video-kings-xi-punjab-v-delhi-daredevils/' target="_blank">IPL 2011 Match 60 Video – Kings XI Punjab v Delhi Daredevils</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 60 Video &#8211; Kings XI Punjab v Delhi Daredevils
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-59-may-14-mumbai-indians-v-deccan-chargers/' target="_blank">IPL 2011 Match 59 May-14 Mumbai Indians v Deccan Chargers</a><br />
Mumbai Indians vs Deccan Chargers, 59th Match May 14, 2011, IPL 2011, Wankhede Stadium, Mumbai (D/N) Umpires: S Ravi (IND) and S Tarapore (IND) Third Umpire: S Taufel (AUS) Match Referee: D Govindjee (SA) Match Result: Deccan Chargers won by 10 runs&#124;Man of the Match: Amit Mishra Mumbai Indians : 125 / 8 in 20.0 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-59-video-mumbai-indians-v-deccan-chargers/' target="_blank">IPL 2011 Match 59 Video – Mumbai Indians v Deccan Chargers</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 59 Video &#8211; Mumbai Indians v Deccan Chargers
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-58-may-14-royal-challengers-bangalore-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 58 May-14 Royal Challengers Bangalore v Kolkata Knight Riders</a><br />
Royal Challengers Bangalore vs Kolkata Knight Riders, 58th Match May 14, 2011, IPL 2011, M Chinnaswamy Stadium, Bangalore Umpires: A Dar (PAK) and R Tiffin (ZIM) Third Umpire: S Hazare (IND) Match Referee: A Pycroft (ZIM) Match Result: Royal Challengers Bangalore won by 4 wickets (D/L method)&#124;Man of the Match: Chris Gayle Royal Challengers Bangalore 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-58-video-royal-challengers-bangalore-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 58 Video – Royal Challengers Bangalore v Kolkata Knight Riders</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 58 Video &#8211; Royal Challengers Bangalore v Kolkata Knight Riders
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-57-may-13-kochi-tuskers-kerala-v-kings-xi-punjab/' target="_blank">IPL 2011 Match 57 May-13 Kochi Tuskers Kerala v Kings XI Punjab</a><br />
Kochi Tuskers Kerala vs Kings XI Punjab, 57th Match May 13, 2011, IPL 2011, Holkar Cricket Stadium, Indore (D/N) Umpires: S Asnani (IND) and R Tucker (AUS) Third Umpire: P Reiffel (AUS) Match Referee: S Mukherjee (IND) Match Result: Kings XI Punjab won by 6 wickets &#124; Man of the Match: Dinesh Karthik Kings XI 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-57-video-kochi-tuskers-kerala-v-kings-xi-punjab/' target="_blank">IPL 2011 Match 57 Video – Kochi Tuskers Kerala v Kings XI Punjab</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 57 Video &#8211; Kochi Tuskers Kerala v Kings XI Punjab
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-56-may-12-chennai%c2%a0super-kings%c2%a0v-delhi-daredevils/' target="_blank">IPL 2011 Match 56 May-12 Chennai Super Kings v Delhi Daredevils</a><br />
Chennai Super Kings vs Delhi DareDevils, 56th Match May 12, 2011, IPL 2011, MA Chidambaram Stadium, Chepauk, Chennai (D/N) Umpires: A Saheba (IND) and S Shastri (IND) Third Umpire: A Rauf (PAK) Match Referee: G Labrooy (SL) Match Result: Chennai Super Kings won by 18 runs &#124; Man of the Match: MS Dhoni Delhi DareDevils 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-56-video-chennai%c2%a0super-kings%c2%a0v-delhi-daredevils/' target="_blank">IPL 2011 Match 56 Video – Chennai Super Kings v Delhi Daredevils</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 56 Video &#8211; Chennai Super Kings v Delhi Daredevils
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-55-may-11-rajasthan-royals-v-royal-challengers-bangalore/' target="_blank">IPL 2011 Match 55 May-11 Rajasthan Royals v Royal Challengers Bangalore</a><br />
Rajasthan Royals vs Royal Challengers Bangalore, 55th Match May 11, 2011, IPL 2011, Sawai Mansingh Stadium, Jaipur (D/N) Umpires: K Dharmasena (SL) and K Hariharan (IND) Third Umpire: S Taufel (AUS) Match Referee: R Mahanama (SL) Match Result: Royal Challengers Bangalore won by 9 wickets &#124; Man of the Match: Sreenath Aravind Royal Challengers Bangalore 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-55-video-rajasthan-royals-v-royal-challengers-bangalore/' target="_blank">IPL 2011 Match 55 Video – Rajasthan Royals v Royal Challengers Bangalore</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 55 Video &#8211; Rajasthan Royals v Royal Challengers Bangalore
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-54-may-10-kings-xi-punjab-v-mumbai-indians/' target="_blank">IPL 2011 Match 54 May-10 Kings XI Punjab v Mumbai Indians</a><br />
Kings XI Punjab vs Mumbai Indians, 54th Match May 10, 2011, IPL 2011, Punjab Cricket Association Stadium, Mohali, Chandigarh (D/N) Umpires: S Tarapore (IND) and R Tucker (AUS) Third Umpire: S Ravi (IND) Match Referee: D Govindjee (SA) Match Result: Kings XI Punjab won by 76 runs &#124; Man of the Match: Bhargav Bhatt Mumbai 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-54-video-kings-xi-punjab-v-mumbai-indians/' target="_blank">IPL 2011 Match 54 Video – Kings XI Punjab v Mumbai Indians</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 54 Video &#8211; Kings XI Punjab v Mumbai Indians
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-53-may-10-deccan-chargers-v-pune-warriors/' target="_blank">IPL 2011 Match 53 May-10 Deccan Chargers v Pune Warriors</a><br />
Deccan Chargers vs Pune Warriors, 53rd Match May 10, 2011, IPL 2011, Rajiv Gandhi International Stadium, Uppal, Hyderabad Umpires: A Rauf (PAK) and A Saheba (IND) Third Umpire: S Shastri (IND) Match Referee: G Labrooy (SL) Match Result: Pune Warriors won by 6 wickets &#124; Man of the Match: Mitchell Marsh Pune Warriors : 137 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-53-video-deccan-chargers-v-pune-warriors/' target="_blank">IPL 2011 Match 53 Video – Deccan Chargers v Pune Warriors</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 53 Video &#8211; Deccan Chargers v Pune Warriors
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-52-may-9-rajasthan-royals-v-chennai%c2%a0super-kings/' target="_blank">IPL 2011 Match 52 May-9 Rajasthan Royals v Chennai Super Kings</a><br />
Rajasthan Royals vs Chennai Super Kings, 52nd Match May 9, 2011, IPL 2011, Sawai Mansingh Stadium, Jaipur (D/N) Umpires: K Hariharan (IND) and S Taufel (AUS) Third Umpire: K Dharmasena (SL) Match Referee: R Mahanama (SL) Match Result: Chennai Super Kings won by 63 runs &#124; Man of the Match: Murali Vijay Rajasthan Royals : 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-52-video-rajasthan-royals-v-chennai%c2%a0super-kings/' target="_blank">IPL 2011 Match 52 Video – Rajasthan Royals v Chennai Super Kings</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 52 Video &#8211; Rajasthan Royals v Chennai Super Kings
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-51-may-8-kings-xi-punjab-v-pune-warriors/' target="_blank">IPL 2011 Match 51 May-8 Kings XI Punjab v Pune Warriors</a><br />
Kings XI Punjab vs Pune Warriors, 51st Match May 8, 2011, IPL 2011, Punjab Cricket Association Stadium, Mohali, Chandigarh (D/N) Umpires: S Tarapore (IND) and R Tucker (AUS) Third Umpire: S Ravi (IND) Match Referee: D Govindjee (SA) Match Result: Pune Warriors won by 5 wickets &#124; Man of the Match: Rahul Sharma Pune Warriors 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-51-video-kings-xi-punjab-v-pune-warriors/' target="_blank">IPL 2011 Match 51 Video – Kings XI Punjab v Pune Warriors</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 51 Video &#8211; Kings XI Punjab v Pune Warriors
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-50-video-royal-challengers-bangalore-v-kochi-tuskers-kerala/' target="_blank">IPL 2011 Match 50 Video – Royal Challengers Bangalore v Kochi Tuskers Kerala</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 50 Video &#8211; Royal Challengers Bangalore v Kochi Tuskers Kerala
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-50-may-8-royal-challengers-bangalore-v-kochi-tuskers-kerala/' target="_blank">IPL 2011 Match 50 May-8 Royal Challengers Bangalore v Kochi Tuskers Kerala</a><br />
Royal Challengers Bangalore vs Kochi Tuskers Kerala, 50th Match May 8, 2011, IPL 2011, M Chinnaswamy Stadium, Bangalore Umpires: Aleem Dar (PAK) and S Hazare (IND) Third Umpire: R Tiffin (ZIM) Match Referee: A Pycroft (ZIM) Match Result: Royal Challengers Bangalore won by 9 wickets &#124; Man of the Match: Chris Gayle Royal Challengers Bangalore 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-49-video-mumbai-indians-v-delhi-daredevils/' target="_blank">IPL 2011 Match 49 Video – Mumbai Indians v Delhi Daredevils</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 49 Video &#8211; Mumbai Indians v Delhi Daredevils
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-49-may-7-mumbai-indians-v-delhi-daredevils/' target="_blank">IPL 2011 Match 49 May-7 Mumbai Indians v Delhi Daredevils</a><br />
Mumbai Indians vs Delhi DareDevils, 49th Match May 7, 2011, IPL 2011, Wankhede Stadium, Mumbai (D/N) Umpires: K Hariharan (IND) and S Taufel (AUS) Third Umpire: K Dharmasena (SL) Match Referee: R Mahanama (SL) Match Result: Mumbai Indians won by 32 runs &#124; Man of the Match: Ambati Rayudu Delhi DareDevils : 146 / 10 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-48-video-kolkata-knight-riders-v-chennai%c2%a0super-kings/' target="_blank">IPL 2011 Match 48 Video – Kolkata Knight Riders v Chennai Super Kings</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 48 Video &#8211; Kolkata Knight Riders v Chennai Super Kings
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-48-may-7-kolkata-knight-riders-v-chennai%c2%a0super-kings/' target="_blank">IPL 2011 Match 48 May-7 Kolkata Knight Riders v Chennai Super Kings</a><br />
Kolkata Knight Riders vs Chennai Super Kings, 48th Match May 7, 2011, IPL 2011, Eden Gardens, Kolkata Umpires: A Rauf (PAK) and P Reiffel (AUS) Third Umpire: S Asnani (IND) Match Referee: S Mukherjee (IND) Match Result: Kolkata Knight Riders won by 10 runs (D/L method) &#124; Man of the Match: Iqbal Abdulla Kolkata Knight 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-47-video-royal-challengers-bangalore-v-kings-xi-punjab/' target="_blank">IPL 2011 Match 47 Video – Royal Challengers Bangalore v Kings XI Punjab</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 47 Video &#8211; Royal Challengers Bangalore v Kings XI Punjab
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-47-may-6-royal-challengers-bangalore-v-kings-xi-punjab/' target="_blank">IPL 2011 Match 47 May-6 Royal Challengers Bangalore v Kings XI Punjab</a><br />
Royal Challengers Bangalore vs Kings XI Punjab, 47th Match May 6, 2011, IPL 2011, M Chinnaswamy Stadium, Bangalore (D/N) Umpires: A Dar (PAK) and R Tiffin (ZIM) Third Umpire: S Hazare (IND) Match Referee: A Pycroft (ZIM) Match Result: Royal Challengers Bangalore won by 85 runs &#124; Man of the Match: Chris Gayle Kings XI 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-46-video-deccan-chargers-v-delhi-daredevils/' target="_blank">IPL 2011 Match 46 Video – Deccan Chargers v Delhi Daredevils</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 46 Video &#8211; Deccan Chargers v Delhi Daredevils
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-46-may-5-deccan-chargers-v-delhi-daredevils/' target="_blank">IPL 2011 Match 46 May-5 Deccan Chargers v Delhi Daredevils</a><br />
Deccan Chargers vs Delhi DareDevils, 46th Match May 5, 2011, IPL 2011, Rajiv Gandhi International Stadium, Uppal, Hyderabad (D/N) Umpires: A Rauf (PAK) and A Saheba (IND) Third Umpire: S Shastri (IND) Match Referee: G Labrooy (SL) Match Result: Delhi DareDevils won by 4 wickets &#124; Man of the Match: Virender Sehwag Delhi DareDevils : 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-45-video-kochi-tuskers-kerala-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 45 Video – Kochi Tuskers Kerala v Kolkata Knight Riders</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 45 Video &#8211; Kochi Tuskers Kerala v Kolkata Knight Riders
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-45-may-5-kochi-tuskers-kerala-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 45 May-5 Kochi Tuskers Kerala v Kolkata Knight Riders</a><br />
Kochi Tuskers Kerala vs Kolkata Knight Riders, 45th Match May 5, 2011, IPL 2011, Nehru Stadium, Kochi Umpires: S Ravi (IND) and R Tucker (AUS) Third Umpire: S Tarapore (IND) Match Referee: D Govindjee (SA) Match Result: Kochi Tuskers Kerala won by 17 runs &#124; Man of the Match: Brad Hodge Kolkata Knight Riders : 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-44-video-pune-warriors-v-mumbai-indians/' target="_blank">IPL 2011 Match 44 Video – Pune Warriors v Mumbai Indians</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 44 Video &#8211; Pune Warriors v Mumbai Indians
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-44-may-4-pune-warriors-v-mumbai-indians/' target="_blank">IPL 2011 Match 44 May-4 Pune Warriors v Mumbai Indians</a><br />
Pune Warriors vs Mumbai Indians, 44th Match May 4, 2011, IPL 2011, Dr DY Patil Sports Academy, Mumbai (D/N) Umpires: K Dharmasena (SL) and S Taufel (AUS) Third Umpire: K Hariharan (IND) Match Referee: S Mukherjee (IND) Match Result: Mumbai Indians won by 21 runs &#124; Man of the Match: Rahul Sharma Pune Warriors : 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-43-video-chennai%c2%a0super-kings%c2%a0v-rajasthan-royals/' target="_blank">IPL 2011 Match 43 Video – Chennai Super Kings v Rajasthan Royals</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 43 Video &#8211; Chennai Super Kings v Rajasthan Royals
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-43-may-4-chennai%c2%a0super-kings%c2%a0v-rajasthan-royals/' target="_blank">IPL 2011 Match 43 May-4 Chennai Super Kings v Rajasthan Royals</a><br />
Chennai Super Kings vs Rajasthan Royals, 43rd Match May 4, 2011, IPL 2011, MA Chidambaram Stadium, Chepauk, Chennai Umpires: S Hazare (IND) and R Tiffin (ZIM) Third Umpire: A Dar (PAK) Match Referee: A Pycroft (ZIM) Match Result: Chennai Super Kings won by 8 wickets &#124; Man of the Match: Michael Hussey Chennai Super Kings 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-42-video-deccan-chargers-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 42 Video – Deccan Chargers v Kolkata Knight Riders</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 42 Video &#8211; Deccan Chargers v Kolkata Knight Riders
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-42-may-3-deccan-chargers-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 42 May-3 Deccan Chargers v Kolkata Knight Riders</a><br />
Deccan Chargers vs Kolkata Knight Riders, 42nd Match May 3, 2011, IPL 2011, Rajiv Gandhi International Stadium, Uppal, Hyderabad Umpires: S Asnani (IND) and R Tucker (AUS) Third Umpire: P Reiffel (AUS) Match Referee: J Srinath (IND) Match Result: Kolkata Knight Riders won by 20 runs &#124; Man of the Match: Yusuf Pathan Deccan Chargers 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-41-video-delhi-daredevils-v-kochi-tuskers-kerala/' target="_blank">IPL 2011 Match 41 Video – Delhi Daredevils v Kochi Tuskers Kerala</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 41 Video &#8211; Delhi Daredevils v Kochi Tuskers Kerala
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-41-may-2-delhi-daredevils-v-kochi-tuskers-kerala/' target="_blank">IPL 2011 Match 41 May-2 Delhi Daredevils v Kochi Tuskers Kerala</a><br />
Delhi DareDevils vs Kochi Tuskers Kerala, 41st Match May 2, 2011, IPL 2011, Feroz Shah Kotla, Delhi (D/N) Umpires: A Rauf (PAK) and S Shastri (IND) Third Umpire: A Saheba (IND) Match Referee: G Labrooy (SL) Match Result: Kochi Tuskers Kerala won by 7 wickets &#124; Man of the Match: P Parameswaran Kochi Tuskers Kerala 
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-40-may-2-mumbai-indians-v-kings-xi-punjab/' target="_blank">IPL 2011 Match 40 May-2 Mumbai Indians v Kings XI Punjab</a><br />
Mumbai Indians vs Kings XI Punjab, 40th Match May 2, 2011, IPL 2011, Wankhede Stadium, Mumbai Umpires: K Dharmasena (SL) and P Reiffel (AUS) Third Umpire: K Hariharan (IND) Match Referee: S Mukherjee (IND) Match Result: Mumbai Indians won by 23 runs &#124; Man of the Match: Kieron Pollard Kings XI Punjab : 136 / 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-40-video-mumbai-indians-v-kings-xi-punjab/' target="_blank">IPL 2011 Match 40 Video – Mumbai Indians v Kings XI Punjab</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 40 Video &#8211; Mumbai Indians v Kings XI Punjab
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-39-may-1-chennai%c2%a0super-kings%c2%a0v-deccan-chargers/' target="_blank">IPL 2011 Match 39 May-1 Chennai Super Kings v Deccan Chargers</a><br />
Chennai Super Kings vs Deccan Chargers, 39th Match May 1, 2011, IPL 2011, MA Chidambaram Stadium, Chepauk, Chennai (D/N) Umpires: A Dar (PAK) and R Tiffin (ZIM) Third Umpire: S Hazare (IND) Match Referee: A Pycroft (ZIM) Match Result: Chennai Super Kings won by 19 runs &#124; Man of the Match: Albie Morkel Deccan Chargers 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-39-video-chennai%c2%a0super-kings%c2%a0v-deccan-chargers/' target="_blank">IPL 2011 Match 39 Video – Chennai Super Kings v Deccan Chargers</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 39 Video &#8211; Chennai Super Kings v Deccan Chargers
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-38-may-1-rajasthan-royals-v-pune-warriors/' target="_blank">IPL 2011 Match 38 May-1 Rajasthan Royals v Pune Warriors</a><br />
Rajasthan Royals vs Pune Warriors, 38th Match May 1, 2011, IPL 2011, Sawai Mansingh Stadium, Jaipur Umpires: S Tarapore (IND) and S Taufel (AUS) Third Umpire: S Ravi (IND) Match Referee: D Govindjee (SA) Match Result: Rajasthan Royals won by 6 wickets &#124; Man of the Match: Ross Taylor Rajasthan Royals : 144 / 4 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-38-video-rajasthan-royals-v-pune-warriors/' target="_blank">IPL 2011 Match 38 Video – Rajasthan Royals v Pune Warriors</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 38 Video &#8211; Rajasthan Royals v Pune Warriors
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-37-apr-30-kolkata-knight-riders-v-kings-xi-punjab/' target="_blank">IPL 2011 Match 37 Apr-30 Kolkata Knight Riders v Kings XI Punjab</a><br />
Kolkata Knight Riders vs Kings XI Punjab, 37th Match April 30, 2011, IPL 2011, Eden Gardens, Kolkata (D/N) Umpires: A Saheba (IND) and S Shastri (IND) Third Umpire: R Tucker (AUS) Match Referee: G Labrooy (SL) Match Result: Kolkata Knight Riders won by 8 wickets &#124; Man of the Match: Iqbal Abdulla Kolkata Knight Riders 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-37-video-kolkata-knight-riders-v-kings-xi-punjab/' target="_blank">IPL 2011 Match 37 Video – Kolkata Knight Riders v Kings XI Punjab</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 37 Video &#8211; Kolkata Knight Riders v Kings XI Punjab
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-36-apr-30-kochi-tuskers-kerala-v-delhi-daredevils/' target="_blank">IPL 2011 Match 36 Apr-30 Kochi Tuskers Kerala v Delhi Daredevils</a><br />
Kochi Tuskers Kerala vs Delhi DareDevils, 36th Match April 30, 2011, IPL 2011, Nehru Stadium, Kochi Umpires: K Dharmasena (SL) and T Hill (NZ) Third Umpire: K Hariharan (IND) Match Referee: S Mukherjee (IND) Match Result: Delhi DareDevils won by 38 runs &#124; Man of the Match: Virender Sehwag Kochi Tuskers Kerala : 119 / 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-36-video-kochi-tuskers-kerala-v-delhi-daredevils/' target="_blank">IPL 2011 Match 36 Video – Kochi Tuskers Kerala v Delhi Daredevils</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 36 Video &#8211; Kochi Tuskers Kerala v Delhi Daredevils
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-35-apr-29-royal-challengers-bangalore-v-pune-warriors/' target="_blank">IPL 2011 Match 35 Apr-29 Royal Challengers Bangalore v Pune Warriors</a><br />
Royal Challengers Bangalore vs Pune Warriors, 35th Match April 29, 2011, IPL 2011, M Chinnaswamy Stadium, Bangalore (D/N) Umpires: A Dar (PAK) and S Hazare (IND) Third Umpire: R Tiffin (ZIM) Match Referee: A Pycroft (ZIM) Match Result: Royal Challengers Bangalore won by 26 runs &#124; Man of the Match: Virat Kohli Pune Warriors : 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-35-video-royal-challengers-bangalore-v-pune-warriors/' target="_blank">IPL 2011 Match 35 Video – Royal Challengers Bangalore v Pune Warriors</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 35 Video &#8211; Royal Challengers Bangalore v Pune Warriors
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-34-apr-29-rajasthan-royals-v-mumbai-indians/' target="_blank">IPL 2011 Match 34 Apr-29 Rajasthan Royals v Mumbai Indians</a><br />
Rajasthan Royals vs Mumbai Indians, 34th Match April 29, 2011, IPL 2011, Sawai Mansingh Stadium, Jaipur Umpires: A Rauf (PAK) and S Tarapore (IND) Third Umpire: S Ravi (IND) Match Referee: D Govindjee (SA) Match Result: Rajasthan Royals won by 7 wickets &#124; Man of the Match: Johan Botha Rajasthan Royals : 95 / 3 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-34-video-rajasthan-royals-v-mumbai-indians/' target="_blank">IPL 2011 Match 34 Video – Rajasthan Royals v Mumbai Indians</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 34 Video &#8211; Rajasthan Royals v Mumbai Indians
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-33-apr-28-delhi-daredevils-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 33 Apr-28 Delhi Daredevils v Kolkata Knight Riders</a><br />
Delhi DareDevils vs Kolkata Knight Riders, 33rd Match April 28, 2011, IPL 2011, Feroz Shah Kotla, Delhi (D/N) Umpires: P Reiffel (AUS) and R Tucker (AUS) Third Umpire: S Asnani (IND) Match Referee: J Srinath (IND) Match Result: Kolkata Knight Riders won by 17 runs &#124; Man of the Match: Manoj Tiwary Delhi DareDevils : 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-33-video-delhi-daredevils-v-kolkata-knight-riders/' target="_blank">IPL 2011 Match 33 Video – Delhi Daredevils v Kolkata Knight Riders</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 33 Video &#8211; Delhi Daredevils v Kolkata Knight Riders
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/' target="_blank">IPL 2011 Videos</a><br />

<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-32-apr-27-kochi-tuskers-kerala-v-deccan-chargers/' target="_blank">IPL 2011 Match 32 Apr-27 Kochi Tuskers Kerala v Deccan Chargers</a><br />
Kochi Tuskers Kerala vs Deccan Chargers, 32nd Match April 27, 2011, IPL 2011, Nehru Stadium, Kochi (D/N) Umpires: K Dharmasena (SL) and T Hill (NZ) Third Umpire: K Hariharan (IND) Match Referee: S Mukherjee (IND) Match Result: Deccan Chargers won by 55 runs &#124; Man of the Match: Ishant Sharma Kochi Tuskers Kerala : 74 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-32-video-kochi-tuskers-kerala-v-deccan-chargers/' target="_blank">IPL 2011 Match 32 Video – Kochi Tuskers Kerala v Deccan Chargers</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 32 Video &#8211; Kochi Tuskers Kerala v Deccan Chargers
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-31-apr-27-pune-warriors-v-chennai%c2%a0super-kings/' target="_blank">IPL 2011 Match 31 Apr-27 Pune Warriors v Chennai Super Kings</a><br />
Pune Warriors vs Chennai Super Kings, 31st Match April 27, 2011, IPL 2011, Dr DY Patil Sports Academy, Mumbai Umpires: A Rauf (PAK) and S Shastri (IND) Third Umpire: A Saheba (IND) Match Referee: G Labrooy (SL) Match Result: Chennai Super Kings won by 8 wickets &#124; Man of the Match: Doug Bollinger Chennai Super 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-31-video-pune-warriors-v-chennai%c2%a0super-kings/' target="_blank">IPL 2011 Match 31 Video – Pune Warriors v Chennai Super Kings</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 31 Video &#8211; Pune Warriors v Chennai Super Kings
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-30-video-delhi-daredevils-v-royal-challengers-bangalore/' target="_blank">IPL 2011 Match 30 Video – Delhi Daredevils v Royal Challengers Bangalore</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 30 Video &#8211; Delhi Daredevils v Royal Challengers Bangalore
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-30-apr-26-delhi-daredevils-v-royal-challengers-bangalore/' target="_blank">IPL 2011 Match 30 Apr-26 Delhi Daredevils v Royal Challengers Bangalore</a><br />
Delhi Daredevils vs Royal Challengers Bangalore, 30th Match April 26, 2011, IPL 2011, Feroz Shah Kotla, Delhi (D/N) Umpires: S Asnani (IND) and R Tucker (AUS) Third Umpire: P Reiffel (AUS) Match Referee: J Srinath (IND) Match Result: Royal Challengers Bangalore won by 3 wickets &#124; Man of the Match: Virat Kohli Royal Challengers Bangalore 
<li><a href='http://www.premierleaguenews.in/photo/ipl-2011-photos/' target="_blank">IPL 2011 Photos</a><br />

<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-29-video-chennai%c2%a0super-kings%c2%a0v-pune-warriors/' target="_blank">IPL 2011 Match 29 Video – Chennai Super Kings v Pune Warriors</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 29 Video &#8211; Chennai Super Kings v Pune Warriors
<li><a href='http://www.premierleaguenews.in/ipl-2011-score-card/ipl-2011-match-29-apr-25-chennai%c2%a0super-kings%c2%a0v-pune-warriors/' target="_blank">IPL 2011 Match 29 Apr-25 Chennai Super Kings v Pune Warriors</a><br />
Chennai Super Kings vs Pune Warriors, 29th Match April 25, 2011, IPL 2011, MA Chidambaram Stadium, Chepauk, Chennai (D/N) Umpires: A Dar (PAK) and R Tiffin (ZIM) Third Umpire: S Hazare (IND) Match Referee: A Pycroft (ZIM) Match Result: Chennai Super Kings won by 25 runs &#124; Man of the Match: Michael Hussey Pune Warriors 
<li><a href='http://www.premierleaguenews.in/ipl-video/2011/match-video-2011/ipl-2011-match-28-video-rajasthan-royals-v-kochi-tuskers-kerala/' target="_blank">IPL 2011 Match 28 Video – Rajasthan Royals v Kochi Tuskers Kerala</a><br />
[There is a video that cannot be displayed in this feed. Visit the blog entry to see the video.] IPL 2011 Match 28 Video &#8211; Rajasthan Royals v Kochi Tuskers Kerala
</ul></div>
   


  </div>
</div>

</body>
</html>
