<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link href="daily.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body>
<div id="column2">
	<div id="col2_text" class="scroll">
	<ul></li>
<div class="rss-box">
<p class="rss-title"><a class="rss-title" href="http://www.cnn.com/HEALTH/index.html?eref=rss_health" target="_blank">CNN.com - Health</a><br /><span class="rss-item">CNN.com delivers up-to-the-minute news and information on the latest top stories, weather, entertainment, politics and more.</span></p>
<ul class="rss-items">
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/86bzNcaDGgs/index.html"  title="U.S. charities are helping treat kids from the nuclear disas..." target="_blank">Chernobyl children seek answers</a> <br />
U.S. charities are helping treat kids from the nuclear disaster area, but some experts say there's little chance radiation still lingers.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=86bzNcaDGgs:5_0kymm1rvg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=86bzNcaDGgs:5_0kymm1rvg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=86bzNcaDGgs:5_0kymm1rvg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=86bzNcaDGgs:5_0kymm1rvg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=86bzNcaDGgs:5_0kymm1rvg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=86bzNcaDGgs:5_0kymm1rvg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=86bzNcaDGgs:5_0kymm1rvg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/86bzNcaDGgs" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/lNDsvRjYRkA/index.html"  title="Anthony Stokes, 15, received a heart transplant Tuesday nigh..." target="_blank">New heart after transplant saga</a> <br />
Anthony Stokes, 15, received a heart transplant Tuesday night at Children's Healthcare of Atlanta, according to a family spokesman. Anthony is recovering and "doing great," Mark Bell said.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lNDsvRjYRkA:9M9gH1SvfDw:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lNDsvRjYRkA:9M9gH1SvfDw:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lNDsvRjYRkA:9M9gH1SvfDw:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=lNDsvRjYRkA:9M9gH1SvfDw:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lNDsvRjYRkA:9M9gH1SvfDw:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lNDsvRjYRkA:9M9gH1SvfDw:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=lNDsvRjYRkA:9M9gH1SvfDw:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/lNDsvRjYRkA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/uqxuZBHvCWg/index.html"  title="Over the last year, I have been working on a new documentary..." target="_blank">Why I changed my mind on weed</a> <br />
Over the last year, I have been working on a new documentary called "Weed." The title "Weed" may sound cavalier, but the content is not.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=uqxuZBHvCWg:iTzBVYdleyU:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=uqxuZBHvCWg:iTzBVYdleyU:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=uqxuZBHvCWg:iTzBVYdleyU:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=uqxuZBHvCWg:iTzBVYdleyU:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=uqxuZBHvCWg:iTzBVYdleyU:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=uqxuZBHvCWg:iTzBVYdleyU:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=uqxuZBHvCWg:iTzBVYdleyU:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/uqxuZBHvCWg" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/_eRVpY6p484/index.html"  title="All that stood between Tim McCarty and the thrill-promising ..." target="_blank">He's now a 175-pound 'ninja'</a> <br />
All that stood between Tim McCarty and the thrill-promising roller coaster was a seat belt. There was just one problem: he was too big<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_eRVpY6p484:cuaWvam8kgM:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_eRVpY6p484:cuaWvam8kgM:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_eRVpY6p484:cuaWvam8kgM:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=_eRVpY6p484:cuaWvam8kgM:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_eRVpY6p484:cuaWvam8kgM:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_eRVpY6p484:cuaWvam8kgM:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=_eRVpY6p484:cuaWvam8kgM:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/_eRVpY6p484" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/a2heg4lIXRI/index.html"  title="Caroline Mickey wanted to marry Jon Balajthy. But the couple..." target="_blank">Sweethearts drop 220 pounds</a> <br />
Caroline Mickey wanted to marry Jon Balajthy. But the couple knew they had to get healthy first.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=a2heg4lIXRI:DXjOrWN31O4:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=a2heg4lIXRI:DXjOrWN31O4:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=a2heg4lIXRI:DXjOrWN31O4:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=a2heg4lIXRI:DXjOrWN31O4:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=a2heg4lIXRI:DXjOrWN31O4:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=a2heg4lIXRI:DXjOrWN31O4:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=a2heg4lIXRI:DXjOrWN31O4:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/a2heg4lIXRI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/DzsN9_J9ehc/index.html"  title="Ryan &quot;Mac&quot; McDonald lost 300 pounds in less than t..." target="_blank">Taking the 'big' out of Mac</a> <br />
Ryan "Mac" McDonald lost 300 pounds in less than three years after breaking two treadmills and surviving a flesh-eating bacteria.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=DzsN9_J9ehc:idXaj4p6zao:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=DzsN9_J9ehc:idXaj4p6zao:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=DzsN9_J9ehc:idXaj4p6zao:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=DzsN9_J9ehc:idXaj4p6zao:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=DzsN9_J9ehc:idXaj4p6zao:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=DzsN9_J9ehc:idXaj4p6zao:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=DzsN9_J9ehc:idXaj4p6zao:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/DzsN9_J9ehc" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/2rs94IggEh8/index.html"  title="Nobody ages backward, but you don't need to be genetically b..." target="_blank">How to get super fit at any age</a> <br />
Nobody ages backward, but you don't need to be genetically blessed or have plastic surgery to keep your body in remarkable shape.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=2rs94IggEh8:oFdPs3ZHOwA:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=2rs94IggEh8:oFdPs3ZHOwA:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=2rs94IggEh8:oFdPs3ZHOwA:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=2rs94IggEh8:oFdPs3ZHOwA:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=2rs94IggEh8:oFdPs3ZHOwA:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=2rs94IggEh8:oFdPs3ZHOwA:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=2rs94IggEh8:oFdPs3ZHOwA:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/2rs94IggEh8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/i6BB0DCZxio/index.html"  title="Rae Timme decided to end her 57th year doing something that ..." target="_blank">Good health for my birthday</a> <br />
Rae Timme decided to end her 57th year doing something that was unthinkable when she turned 57.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=i6BB0DCZxio:vEVM13djWXo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=i6BB0DCZxio:vEVM13djWXo:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=i6BB0DCZxio:vEVM13djWXo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=i6BB0DCZxio:vEVM13djWXo:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=i6BB0DCZxio:vEVM13djWXo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=i6BB0DCZxio:vEVM13djWXo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=i6BB0DCZxio:vEVM13djWXo:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/i6BB0DCZxio" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/rqMkQZiqiiQ/index.html"  title="In my life, I've often heard that &quot;comparison is the th..." target="_blank">Don't bother with comparison</a> <br />
In my life, I've often heard that "comparison is the thief of joy." I never really thought much about it until taking on CNN's Fit Nation challenge.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=rqMkQZiqiiQ:ZoY8Jv4ix-g:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=rqMkQZiqiiQ:ZoY8Jv4ix-g:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=rqMkQZiqiiQ:ZoY8Jv4ix-g:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=rqMkQZiqiiQ:ZoY8Jv4ix-g:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=rqMkQZiqiiQ:ZoY8Jv4ix-g:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=rqMkQZiqiiQ:ZoY8Jv4ix-g:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=rqMkQZiqiiQ:ZoY8Jv4ix-g:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/rqMkQZiqiiQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/nwHwdyWcyU8/index.html"  title="U.S. researchers say they've successfully tested a vaccine f..." target="_blank">Malaria vaccine successful</a> <br />
U.S. researchers say they've successfully tested a vaccine for malaria on a small group of volunteers and hope to conduct large-scale tests soon.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nwHwdyWcyU8:7lvvXW2pkVg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nwHwdyWcyU8:7lvvXW2pkVg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nwHwdyWcyU8:7lvvXW2pkVg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=nwHwdyWcyU8:7lvvXW2pkVg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nwHwdyWcyU8:7lvvXW2pkVg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nwHwdyWcyU8:7lvvXW2pkVg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=nwHwdyWcyU8:7lvvXW2pkVg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/nwHwdyWcyU8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/8jYjo02v1BA/hm-avoid-megavitamins-dr-paul-offit.cnn.html"  title="Susan Hendricks tells us about a new book that warns that me..." target="_blank">Should you avoid megavitamins?</a> <br />
Susan Hendricks tells us about a new book that warns that megavitamins are bad for our health.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=8jYjo02v1BA:QLrFzWaF_nk:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=8jYjo02v1BA:QLrFzWaF_nk:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=8jYjo02v1BA:QLrFzWaF_nk:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=8jYjo02v1BA:QLrFzWaF_nk:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=8jYjo02v1BA:QLrFzWaF_nk:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=8jYjo02v1BA:QLrFzWaF_nk:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=8jYjo02v1BA:QLrFzWaF_nk:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/8jYjo02v1BA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/bmGhUSTVFss/exp-hm-genes-alcohol-eating-disorders.cnn.html"  title="Holly Firfer reports on a new study that finds alcoholism an..." target="_blank">Some disorders genetically linked</a> <br />
Holly Firfer reports on a new study that finds alcoholism and eating disorders could be gentically linked.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=bmGhUSTVFss:RbMDKyeGeyc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=bmGhUSTVFss:RbMDKyeGeyc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=bmGhUSTVFss:RbMDKyeGeyc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=bmGhUSTVFss:RbMDKyeGeyc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=bmGhUSTVFss:RbMDKyeGeyc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=bmGhUSTVFss:RbMDKyeGeyc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=bmGhUSTVFss:RbMDKyeGeyc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/bmGhUSTVFss" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/E_vR6z33ix4/biomarker-test-could-detect-heart-attack-risks.cnn.html"  title="New test may detect heart attacks..." target="_blank">Blood test for heart attacks</a> <br />
New test may detect heart attacks<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=E_vR6z33ix4:UI2DTLikQh4:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=E_vR6z33ix4:UI2DTLikQh4:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=E_vR6z33ix4:UI2DTLikQh4:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=E_vR6z33ix4:UI2DTLikQh4:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=E_vR6z33ix4:UI2DTLikQh4:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=E_vR6z33ix4:UI2DTLikQh4:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=E_vR6z33ix4:UI2DTLikQh4:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/E_vR6z33ix4" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/cQByjGFAbVQ/exp-hm-school-germs.cnn.html"  title="CNN's Holly Firfer has tips on how to keep your little schol..." target="_blank">Elementary ways to keep germs away</a> <br />
CNN's Holly Firfer has tips on how to keep your little scholars healthy.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=cQByjGFAbVQ:zQViJPv9uA0:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=cQByjGFAbVQ:zQViJPv9uA0:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=cQByjGFAbVQ:zQViJPv9uA0:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=cQByjGFAbVQ:zQViJPv9uA0:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=cQByjGFAbVQ:zQViJPv9uA0:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=cQByjGFAbVQ:zQViJPv9uA0:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=cQByjGFAbVQ:zQViJPv9uA0:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/cQByjGFAbVQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/vAq2wkzyi1U/hm-texting-and-walking.cnn.html"  title="HLN's Susan Hendricks reports on a new study that finds when..." target="_blank">Why you shouldn't walk & text</a> <br />
HLN's Susan Hendricks reports on a new study that finds when you walk and text you are courting danger.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=vAq2wkzyi1U:n3Xkv7GmClo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=vAq2wkzyi1U:n3Xkv7GmClo:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=vAq2wkzyi1U:n3Xkv7GmClo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=vAq2wkzyi1U:n3Xkv7GmClo:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=vAq2wkzyi1U:n3Xkv7GmClo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=vAq2wkzyi1U:n3Xkv7GmClo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=vAq2wkzyi1U:n3Xkv7GmClo:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/vAq2wkzyi1U" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/m0Dpra7DAfM/exp-hm-student-vaccinations.cnn.html"  title="CNN's April Williams has a look at what vaccines pre-teens a..." target="_blank">What vaccines do chlldren need?</a> <br />
CNN's April Williams has a look at what vaccines pre-teens and teens need.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=m0Dpra7DAfM:N9DAVwR16fI:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=m0Dpra7DAfM:N9DAVwR16fI:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=m0Dpra7DAfM:N9DAVwR16fI:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=m0Dpra7DAfM:N9DAVwR16fI:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=m0Dpra7DAfM:N9DAVwR16fI:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=m0Dpra7DAfM:N9DAVwR16fI:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=m0Dpra7DAfM:N9DAVwR16fI:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/m0Dpra7DAfM" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/0k-I-2xNoOo/hm-kids-and-screen-time.cnn.html"  title="Melisa Raney reports on why it's important to limit screen t..." target="_blank">Limit time kids spend in front of screen</a> <br />
Melisa Raney reports on why it's important to limit screen time by kids in today's Health Minute.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=0k-I-2xNoOo:3PjqCWvyeVY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=0k-I-2xNoOo:3PjqCWvyeVY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=0k-I-2xNoOo:3PjqCWvyeVY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=0k-I-2xNoOo:3PjqCWvyeVY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=0k-I-2xNoOo:3PjqCWvyeVY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=0k-I-2xNoOo:3PjqCWvyeVY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=0k-I-2xNoOo:3PjqCWvyeVY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/0k-I-2xNoOo" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/IZmjDX_6L4I/hm-high-heels.cnn.html"  title="Reporter Holly Firfer tells us that wearing high heels can b..." target="_blank">Dangers of high-heel shoes</a> <br />
Reporter Holly Firfer tells us that wearing high heels can be harmful to our feet and our health.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=IZmjDX_6L4I:4UQt3TU2X84:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=IZmjDX_6L4I:4UQt3TU2X84:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=IZmjDX_6L4I:4UQt3TU2X84:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=IZmjDX_6L4I:4UQt3TU2X84:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=IZmjDX_6L4I:4UQt3TU2X84:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=IZmjDX_6L4I:4UQt3TU2X84:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=IZmjDX_6L4I:4UQt3TU2X84:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/IZmjDX_6L4I" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/23xjEWppBHE/hm-back-to-school-doctor.cnn.html"  title="A pediatrician can address issues in children that could imp..." target="_blank">Kids' back-to-school health</a> <br />
A pediatrician can address issues in children that could impact school performance during their annual exam.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=23xjEWppBHE:zKrr7-DRIuc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=23xjEWppBHE:zKrr7-DRIuc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=23xjEWppBHE:zKrr7-DRIuc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=23xjEWppBHE:zKrr7-DRIuc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=23xjEWppBHE:zKrr7-DRIuc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=23xjEWppBHE:zKrr7-DRIuc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=23xjEWppBHE:zKrr7-DRIuc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/23xjEWppBHE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/_6o-88GJjPI/exp-hm-smoking-family.cnn.html"  title="CNN's Shelby Lin examines a study looking at the role of a c..." target="_blank">Smoking parents influence kids</a> <br />
CNN's Shelby Lin examines a study looking at the role of a child's household environment in their decision to smoke.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_6o-88GJjPI:Gzf-luEb3r8:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_6o-88GJjPI:Gzf-luEb3r8:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_6o-88GJjPI:Gzf-luEb3r8:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=_6o-88GJjPI:Gzf-luEb3r8:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_6o-88GJjPI:Gzf-luEb3r8:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=_6o-88GJjPI:Gzf-luEb3r8:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=_6o-88GJjPI:Gzf-luEb3r8:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/_6o-88GJjPI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/7ggQ0MGt4Ak/hm-summer-sports-injuries.cnn.html"  title="Reporter Susan Hendricks looks at how injuries can result wh..." target="_blank">Ease in to summer exercise</a> <br />
Reporter Susan Hendricks looks at how injuries can result when we overdo it with our summer exercise.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=7ggQ0MGt4Ak:TWUgHPSU5-Y:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=7ggQ0MGt4Ak:TWUgHPSU5-Y:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=7ggQ0MGt4Ak:TWUgHPSU5-Y:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=7ggQ0MGt4Ak:TWUgHPSU5-Y:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=7ggQ0MGt4Ak:TWUgHPSU5-Y:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=7ggQ0MGt4Ak:TWUgHPSU5-Y:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=7ggQ0MGt4Ak:TWUgHPSU5-Y:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/7ggQ0MGt4Ak" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/Ys3WI2TKvDY/exp-cyclospora-update.cnn.html"  title="CDC has announced the cause of the cyclospora outbreak in Io..." target="_blank">Cause found for virus outbreak</a> <br />
CDC has announced the cause of the cyclospora outbreak in Iowa and Nebraska.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Ys3WI2TKvDY:uZ_dwFAB-ww:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Ys3WI2TKvDY:uZ_dwFAB-ww:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Ys3WI2TKvDY:uZ_dwFAB-ww:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=Ys3WI2TKvDY:uZ_dwFAB-ww:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Ys3WI2TKvDY:uZ_dwFAB-ww:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Ys3WI2TKvDY:uZ_dwFAB-ww:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=Ys3WI2TKvDY:uZ_dwFAB-ww:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/Ys3WI2TKvDY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/Fok4LEW8h6U/hm-breastfeeding-101.cnn.html"  title="Reporter Holly Firfer tells us about the benefits of breastf..." target="_blank">Breastfeeding 101</a> <br />
Reporter Holly Firfer tells us about the benefits of breastfeeding a new baby.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Fok4LEW8h6U:oRQunoGFnVY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Fok4LEW8h6U:oRQunoGFnVY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Fok4LEW8h6U:oRQunoGFnVY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=Fok4LEW8h6U:oRQunoGFnVY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Fok4LEW8h6U:oRQunoGFnVY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Fok4LEW8h6U:oRQunoGFnVY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=Fok4LEW8h6U:oRQunoGFnVY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/Fok4LEW8h6U" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/I0xQVHxmwpw/exp-hm-kids-and-choking.cnn.html"  title="Choking on food still remains a problem for young children. ..." target="_blank">Candy presents choking risk</a> <br />
Choking on food still remains a problem for young children. So what are some common culprits?<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=I0xQVHxmwpw:Rc3Fmpq7xfw:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=I0xQVHxmwpw:Rc3Fmpq7xfw:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=I0xQVHxmwpw:Rc3Fmpq7xfw:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=I0xQVHxmwpw:Rc3Fmpq7xfw:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=I0xQVHxmwpw:Rc3Fmpq7xfw:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=I0xQVHxmwpw:Rc3Fmpq7xfw:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=I0xQVHxmwpw:Rc3Fmpq7xfw:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/I0xQVHxmwpw" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/iVtTsTMx44g/hm-sleep-back-to-school.cnn.html"  title="HLN's Susan Hendricks explains the importance of getting kid..." target="_blank">Back-to-school bedtimes</a> <br />
HLN's Susan Hendricks explains the importance of getting kids on a regular bedtime schedule before school starts.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=iVtTsTMx44g:K82Y8Je7aQo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=iVtTsTMx44g:K82Y8Je7aQo:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=iVtTsTMx44g:K82Y8Je7aQo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=iVtTsTMx44g:K82Y8Je7aQo:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=iVtTsTMx44g:K82Y8Je7aQo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=iVtTsTMx44g:K82Y8Je7aQo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=iVtTsTMx44g:K82Y8Je7aQo:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/iVtTsTMx44g" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/1qYkFb4Vtvo/hm-vitamin-d.cnn.html"  title="HLN's Susan Hendricks tells us that getting enough Vitamin D..." target="_blank">Benefits of Vitamin D</a> <br />
HLN's Susan Hendricks tells us that getting enough Vitamin D each day is vital for good health.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1qYkFb4Vtvo:uO0MtvstZh4:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1qYkFb4Vtvo:uO0MtvstZh4:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1qYkFb4Vtvo:uO0MtvstZh4:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=1qYkFb4Vtvo:uO0MtvstZh4:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1qYkFb4Vtvo:uO0MtvstZh4:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1qYkFb4Vtvo:uO0MtvstZh4:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=1qYkFb4Vtvo:uO0MtvstZh4:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/1qYkFb4Vtvo" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/-3P2pMLs78U/hm-kids-and-hot-cars.cnn.html"  title="A car can overheat within minutes, risking severe injury or ..." target="_blank">Prevent a deadly mistake</a> <br />
A car can overheat within minutes, risking severe injury or even death for a child accidentally left behind.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-3P2pMLs78U:ouWCsmQSiCo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-3P2pMLs78U:ouWCsmQSiCo:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-3P2pMLs78U:ouWCsmQSiCo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=-3P2pMLs78U:ouWCsmQSiCo:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-3P2pMLs78U:ouWCsmQSiCo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-3P2pMLs78U:ouWCsmQSiCo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=-3P2pMLs78U:ouWCsmQSiCo:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/-3P2pMLs78U" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/EKmVdT1ifTY/exp-hm-stress-and-weight.cnn.html"  title="Studies show stress can cause weight gain. CNN's Mary Ellen ..." target="_blank">Stress can cause weight gain</a> <br />
Studies show stress can cause weight gain. CNN's Mary Ellen Hopkins has more.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EKmVdT1ifTY:7K3SuVDjWJY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EKmVdT1ifTY:7K3SuVDjWJY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EKmVdT1ifTY:7K3SuVDjWJY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=EKmVdT1ifTY:7K3SuVDjWJY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EKmVdT1ifTY:7K3SuVDjWJY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EKmVdT1ifTY:7K3SuVDjWJY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=EKmVdT1ifTY:7K3SuVDjWJY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/EKmVdT1ifTY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/gxCGuocc3bo/index.html"  title="From autism to Alzheimer's disease, music therapy is a growi..." target="_blank">Therapists singing a new tune</a> <br />
From autism to Alzheimer's disease, music therapy is a growing profession that's being used to help patients of all ages.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:Oa7QvACW68s:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:Oa7QvACW68s:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:Oa7QvACW68s:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=gxCGuocc3bo:Oa7QvACW68s:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:Oa7QvACW68s:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:Oa7QvACW68s:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=gxCGuocc3bo:Oa7QvACW68s:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/gxCGuocc3bo" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/9H8e4wtodIk/index.html"  title="Most of us assume our doctors are trustworthy. But after rec..." target="_blank">Should you trust your doctor?</a> <br />
Most of us assume our doctors are trustworthy. But after recent cases of fraud made headlines, some patients aren't so sure.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=9H8e4wtodIk:tNeWY1mgYCc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=9H8e4wtodIk:tNeWY1mgYCc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=9H8e4wtodIk:tNeWY1mgYCc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=9H8e4wtodIk:tNeWY1mgYCc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=9H8e4wtodIk:tNeWY1mgYCc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=9H8e4wtodIk:tNeWY1mgYCc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=9H8e4wtodIk:tNeWY1mgYCc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/9H8e4wtodIk" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/jScqVP_Bba8/index.html"  title="It's often toward the finish line, when the body is screamin..." target="_blank">Champ: Getting to the finish line</a> <br />
It's often toward the finish line, when the body is screaming for respite, calling on you to quit, that the most powerful weapon of all comes into its own.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:4nWyYcFBnMY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:4nWyYcFBnMY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:4nWyYcFBnMY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=jScqVP_Bba8:4nWyYcFBnMY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:4nWyYcFBnMY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:4nWyYcFBnMY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=jScqVP_Bba8:4nWyYcFBnMY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/jScqVP_Bba8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/VlyyDbOWVAg/index.html"  title="Many schools are adding yoga to ensure students are meeting ..." target="_blank">Is yoga too religious for schools?</a> <br />
Many schools are adding yoga to ensure students are meeting the mandated physical fitness requirements. But some parents say the practice's religious ties aren't appropriate for government-funded education.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=VlyyDbOWVAg:CLMen-2GVAQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=VlyyDbOWVAg:CLMen-2GVAQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=VlyyDbOWVAg:CLMen-2GVAQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=VlyyDbOWVAg:CLMen-2GVAQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=VlyyDbOWVAg:CLMen-2GVAQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=VlyyDbOWVAg:CLMen-2GVAQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=VlyyDbOWVAg:CLMen-2GVAQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/VlyyDbOWVAg" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/lyAnamUKhSg/index.html"  title="Michael Boatwright was born in Florida and served in the U.S..." target="_blank">Navy vet can't remember English</a> <br />
Michael Boatwright was born in Florida and served in the U.S. Navy, but he awoke in a California hospital earlier this year speaking only Swedish. Now, his ex-girlfriend is helping him get himself together.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lyAnamUKhSg:a070-YXS664:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lyAnamUKhSg:a070-YXS664:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lyAnamUKhSg:a070-YXS664:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=lyAnamUKhSg:a070-YXS664:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lyAnamUKhSg:a070-YXS664:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=lyAnamUKhSg:a070-YXS664:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=lyAnamUKhSg:a070-YXS664:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/lyAnamUKhSg" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/gxCGuocc3bo/index.html"  title="Music therapy is a profession that's slowly growing, and can..." target="_blank">Fight fear with tunes</a> <br />
Music therapy is a profession that's slowly growing, and can help people at any age.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:xNte6QbAyCc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:xNte6QbAyCc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:xNte6QbAyCc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=gxCGuocc3bo:xNte6QbAyCc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:xNte6QbAyCc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=gxCGuocc3bo:xNte6QbAyCc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=gxCGuocc3bo:xNte6QbAyCc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/gxCGuocc3bo" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/jScqVP_Bba8/index.html"  title="It's often toward the finish line, when the body is screamin..." target="_blank">Ironman champ: Finish strong</a> <br />
It's often toward the finish line, when the body is screaming for respite, calling on you to quit, that the most powerful weapon of all comes into its own.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:uikRinSXRPY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:uikRinSXRPY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:uikRinSXRPY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=jScqVP_Bba8:uikRinSXRPY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:uikRinSXRPY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jScqVP_Bba8:uikRinSXRPY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=jScqVP_Bba8:uikRinSXRPY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/jScqVP_Bba8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/yyjPAu2Ydqk/oppmann-cuba-cholera-outbreak.cnn.html"  title="CNN's Patrick Oppmann says diplomats are warning travelers a..." target="_blank">Cholera outbreak spreads</a> <br />
CNN's Patrick Oppmann says diplomats are warning travelers about an outbreak of cholera in Cuba.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:v9NSEzNAi_Q:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:v9NSEzNAi_Q:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:v9NSEzNAi_Q:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=yyjPAu2Ydqk:v9NSEzNAi_Q:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:v9NSEzNAi_Q:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:v9NSEzNAi_Q:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=yyjPAu2Ydqk:v9NSEzNAi_Q:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/yyjPAu2Ydqk" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/n275YmiQSes/index.html"  title="Tests done on 12-year-old Zachary Reyna show no signs of act..." target="_blank">Drug beats brain-eating amoeba</a> <br />
Tests done on 12-year-old Zachary Reyna show no signs of activity from the brain-eating parasite he contracted earlier this month, according to his father. Doctors had given Zachary the same experimental anti-amoeba drug used to treat 12-year-old Kali Hardig recently in Arkansas. The Arkansas girl is only the third person in the last 50 years to survive this deadly parasite.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:UCBqXxj6X2w:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:UCBqXxj6X2w:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:UCBqXxj6X2w:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=n275YmiQSes:UCBqXxj6X2w:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:UCBqXxj6X2w:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:UCBqXxj6X2w:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=n275YmiQSes:UCBqXxj6X2w:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/n275YmiQSes" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/baeSEOzf-Ew/index.html"  title="As more details about Bradley Manning's new life as Chelsea ..." target="_blank">Famous transgender people</a> <br />
As more details about Bradley Manning's new life as Chelsea emerge, here's what we know -- and what we don't -- about gender identity.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:YKwjuK7h0Lw:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:YKwjuK7h0Lw:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:YKwjuK7h0Lw:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=baeSEOzf-Ew:YKwjuK7h0Lw:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:YKwjuK7h0Lw:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:YKwjuK7h0Lw:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=baeSEOzf-Ew:YKwjuK7h0Lw:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/baeSEOzf-Ew" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/-aTpGqojiB4/index.html"  title="We sustain psychological injuries such as rejection and fail..." target="_blank">How to heal from emotional pain</a> <br />
We sustain psychological injuries such as rejection and failure as we go through life just as often as we do physical injuries. But while we have access to ointments and bandages to treat cuts and sprains, we have no such tools to treat emotional pain.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-aTpGqojiB4:lYyxdWztU6k:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-aTpGqojiB4:lYyxdWztU6k:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-aTpGqojiB4:lYyxdWztU6k:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=-aTpGqojiB4:lYyxdWztU6k:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-aTpGqojiB4:lYyxdWztU6k:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=-aTpGqojiB4:lYyxdWztU6k:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=-aTpGqojiB4:lYyxdWztU6k:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/-aTpGqojiB4" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/jot6I27Uih0/index.html"  title="Belly-flops rarely cause serious injuries, but you should st..." target="_blank">The danger of belly-flopping</a> <br />
Belly-flops rarely cause serious injuries, but you should still take care to minimize the risks, Dr. Sonu Ahluwalia says.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jot6I27Uih0:tr01m3-fmK0:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jot6I27Uih0:tr01m3-fmK0:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jot6I27Uih0:tr01m3-fmK0:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=jot6I27Uih0:tr01m3-fmK0:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jot6I27Uih0:tr01m3-fmK0:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=jot6I27Uih0:tr01m3-fmK0:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=jot6I27Uih0:tr01m3-fmK0:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/jot6I27Uih0" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/5uvpk7HRz-M/index.html"  title="The evolutionary background of human reproduction can shed m..." target="_blank">Weird facts about sex, childbirth</a> <br />
The evolutionary background of human reproduction can shed much-needed light on some of life's most intimate mysteries.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=5uvpk7HRz-M:NKpDdBQSmkg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=5uvpk7HRz-M:NKpDdBQSmkg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=5uvpk7HRz-M:NKpDdBQSmkg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=5uvpk7HRz-M:NKpDdBQSmkg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=5uvpk7HRz-M:NKpDdBQSmkg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=5uvpk7HRz-M:NKpDdBQSmkg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=5uvpk7HRz-M:NKpDdBQSmkg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/5uvpk7HRz-M" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/4ZjzTvNRWu4/index.html"  title="Cat poop could be a &quot;vast and underappreciated&quot; pu..." target="_blank">Is cat poop dangerous?</a> <br />
Cat poop could be a "vast and underappreciated" public health problem, according to Drs. Fuller Torrey and Robert Yolken.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4ZjzTvNRWu4:TFTWO0BC2LQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4ZjzTvNRWu4:TFTWO0BC2LQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4ZjzTvNRWu4:TFTWO0BC2LQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=4ZjzTvNRWu4:TFTWO0BC2LQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4ZjzTvNRWu4:TFTWO0BC2LQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4ZjzTvNRWu4:TFTWO0BC2LQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=4ZjzTvNRWu4:TFTWO0BC2LQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/4ZjzTvNRWu4" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/4EaufNVzq7I/index.html"  title="A new study reports that poor oral health is an independent ..." target="_blank">Brushing your teeth may lower your risk of cancer</a> <br />
A new study reports that poor oral health is an independent risk factor for oral HPV infection, and by extension, could also contribute to oral cancers.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4EaufNVzq7I:CTwyxArq6h8:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4EaufNVzq7I:CTwyxArq6h8:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4EaufNVzq7I:CTwyxArq6h8:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=4EaufNVzq7I:CTwyxArq6h8:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4EaufNVzq7I:CTwyxArq6h8:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4EaufNVzq7I:CTwyxArq6h8:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=4EaufNVzq7I:CTwyxArq6h8:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/4EaufNVzq7I" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/baeSEOzf-Ew/index.html"  title="As more details about Bradley Manning's new life as Chelsea ..." target="_blank">5 things to know about gender identity</a> <br />
As more details about Bradley Manning's new life as Chelsea emerge, here's what we know -- and what we don't -- about gender identity.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:CsJQsP_6DEA:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:CsJQsP_6DEA:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:CsJQsP_6DEA:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=baeSEOzf-Ew:CsJQsP_6DEA:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:CsJQsP_6DEA:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=baeSEOzf-Ew:CsJQsP_6DEA:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=baeSEOzf-Ew:CsJQsP_6DEA:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/baeSEOzf-Ew" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/67WJZ_LXtOk/index.html"  title="Ronney Jenkins suspects CTE is clawing through his brain tis..." target="_blank">Former NFL player: 'Sometimes I think I'm going crazy'</a> <br />
Ronney Jenkins suspects CTE is clawing through his brain tissue right now, but the only way to diagnose the disease is after death.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=67WJZ_LXtOk:uLIJHTL9jCo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=67WJZ_LXtOk:uLIJHTL9jCo:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=67WJZ_LXtOk:uLIJHTL9jCo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=67WJZ_LXtOk:uLIJHTL9jCo:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=67WJZ_LXtOk:uLIJHTL9jCo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=67WJZ_LXtOk:uLIJHTL9jCo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=67WJZ_LXtOk:uLIJHTL9jCo:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/67WJZ_LXtOk" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/yyjPAu2Ydqk/oppmann-cuba-cholera-outbreak.cnn.html"  title="CNN's Patrick Oppmann says diplomats are warning travelers a..." target="_blank">Cholera outbreak spreads throughout Cuba</a> <br />
CNN's Patrick Oppmann says diplomats are warning travelers about an outbreak of cholera in Cuba.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:5BoHo6clo8g:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:5BoHo6clo8g:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:5BoHo6clo8g:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=yyjPAu2Ydqk:5BoHo6clo8g:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:5BoHo6clo8g:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=yyjPAu2Ydqk:5BoHo6clo8g:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=yyjPAu2Ydqk:5BoHo6clo8g:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/yyjPAu2Ydqk" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/n275YmiQSes/index.html"  title="Tests done on 12-year-old Zachary Reyna show no signs of act..." target="_blank">Experimental drug beats brain-eating amoeba in Florida</a> <br />
Tests done on 12-year-old Zachary Reyna show no signs of activity from the brain-eating parasite he contracted earlier this month, according to his father. Doctors had given Zachary the same experimental anti-amoeba drug used to treat 12-year-old Kali Hardig recently in Arkansas. The Arkansas girl is only the third person in the last 50 years to survive this deadly parasite.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:WDb4LYujHao:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:WDb4LYujHao:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:WDb4LYujHao:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=n275YmiQSes:WDb4LYujHao:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:WDb4LYujHao:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=n275YmiQSes:WDb4LYujHao:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=n275YmiQSes:WDb4LYujHao:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/n275YmiQSes" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/N7v2JqoQDK8/index.html"  title="From phantom pains to &quot;sympathy&quot; weight gain, part..." target="_blank">Moms aren't alone in sex-drive drop</a> <br />
From phantom pains to "sympathy" weight gain, partners of pregnant women can develop some of the physical symptoms of pregnancy. Now, a recent study suggests that these partners may undergo the same shifts in sexuality after childbirth as new mothers do.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=N7v2JqoQDK8:7rNPyzFD5uA:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=N7v2JqoQDK8:7rNPyzFD5uA:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=N7v2JqoQDK8:7rNPyzFD5uA:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=N7v2JqoQDK8:7rNPyzFD5uA:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=N7v2JqoQDK8:7rNPyzFD5uA:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=N7v2JqoQDK8:7rNPyzFD5uA:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=N7v2JqoQDK8:7rNPyzFD5uA:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/N7v2JqoQDK8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/LOriO0Xkk8Q/index.html"  title="The blacklegged ticks are out, and they're infecting hundred..." target="_blank">CDC: Lyme disease more common than we thought</a> <br />
The blacklegged ticks are out, and they're infecting hundreds of thousands of Americans each year with a bacterial illness.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=LOriO0Xkk8Q:-CYmKcGdqPk:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=LOriO0Xkk8Q:-CYmKcGdqPk:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=LOriO0Xkk8Q:-CYmKcGdqPk:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=LOriO0Xkk8Q:-CYmKcGdqPk:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=LOriO0Xkk8Q:-CYmKcGdqPk:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=LOriO0Xkk8Q:-CYmKcGdqPk:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=LOriO0Xkk8Q:-CYmKcGdqPk:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/LOriO0Xkk8Q" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/1q2K-paKt5g/index.html"  title="Children get an average of eight to 12 colds or cases of the..." target="_blank">Avoid 'back-to-school plague'</a> <br />
Children get an average of eight to 12 colds or cases of the flu each school year. But there are simple ways to keep your kids healthy.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1q2K-paKt5g:XLoMqBoYbwQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1q2K-paKt5g:XLoMqBoYbwQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1q2K-paKt5g:XLoMqBoYbwQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=1q2K-paKt5g:XLoMqBoYbwQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1q2K-paKt5g:XLoMqBoYbwQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=1q2K-paKt5g:XLoMqBoYbwQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=1q2K-paKt5g:XLoMqBoYbwQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/1q2K-paKt5g" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/T_yfZmFC1OU/index.html"  title="It's too much to expect kids to navigate this difficult peri..." target="_blank">When Mom or Dad has cancer</a> <br />
It's too much to expect kids to navigate this difficult period alone, but parents need a strategy to help.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=T_yfZmFC1OU:TeEFpMVqu7o:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=T_yfZmFC1OU:TeEFpMVqu7o:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=T_yfZmFC1OU:TeEFpMVqu7o:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=T_yfZmFC1OU:TeEFpMVqu7o:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=T_yfZmFC1OU:TeEFpMVqu7o:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=T_yfZmFC1OU:TeEFpMVqu7o:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=T_yfZmFC1OU:TeEFpMVqu7o:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/T_yfZmFC1OU" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/ybfMpmfEWPA/index.html"  title="Researchers are looking to see if they can test the retina f..." target="_blank">Test the eyes for Alzheimer's</a> <br />
Researchers are looking to see if they can test the retina for signs of Alzheimer's even before patients show symptoms.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=ybfMpmfEWPA:BdrDUKU-Kzk:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=ybfMpmfEWPA:BdrDUKU-Kzk:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=ybfMpmfEWPA:BdrDUKU-Kzk:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=ybfMpmfEWPA:BdrDUKU-Kzk:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=ybfMpmfEWPA:BdrDUKU-Kzk:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=ybfMpmfEWPA:BdrDUKU-Kzk:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=ybfMpmfEWPA:BdrDUKU-Kzk:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/ybfMpmfEWPA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/Hi245odiyQk/index.html"  title="Unless you've been living under a rock, you know to apply su..." target="_blank">Golden rules of sun protection</a> <br />
Unless you've been living under a rock, you know to apply sunscreen. There's lifesaving reason to: About 3.5 million cases of skin cancer will be diagnosed this year.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Hi245odiyQk:9SYMnSwVLPk:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Hi245odiyQk:9SYMnSwVLPk:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Hi245odiyQk:9SYMnSwVLPk:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=Hi245odiyQk:9SYMnSwVLPk:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Hi245odiyQk:9SYMnSwVLPk:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=Hi245odiyQk:9SYMnSwVLPk:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=Hi245odiyQk:9SYMnSwVLPk:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/Hi245odiyQk" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/GyoTL8nt2Xw/index.html"  title="Flo Meiler holds 15 world records and 12 U.S. records in tra..." target="_blank">79-year-old pole-vaulting star</a> <br />
Flo Meiler holds 15 world records and 12 U.S. records in track and field. And she's on her way to the National Senior Games to win more.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=GyoTL8nt2Xw:OsD5fyNHWHI:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=GyoTL8nt2Xw:OsD5fyNHWHI:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=GyoTL8nt2Xw:OsD5fyNHWHI:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=GyoTL8nt2Xw:OsD5fyNHWHI:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=GyoTL8nt2Xw:OsD5fyNHWHI:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=GyoTL8nt2Xw:OsD5fyNHWHI:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=GyoTL8nt2Xw:OsD5fyNHWHI:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/GyoTL8nt2Xw" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/4UpeWVO59f0/index.html"  title="The truth is, even young, fit women have urologic troubles. ..." target="_blank">Solve your 'plumbing' problems</a> <br />
The truth is, even young, fit women have urologic troubles. And with all the simple solutions out there, there's no reason to hold it in.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4UpeWVO59f0:PYp1a4LZZ2Q:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4UpeWVO59f0:PYp1a4LZZ2Q:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4UpeWVO59f0:PYp1a4LZZ2Q:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=4UpeWVO59f0:PYp1a4LZZ2Q:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4UpeWVO59f0:PYp1a4LZZ2Q:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=4UpeWVO59f0:PYp1a4LZZ2Q:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=4UpeWVO59f0:PYp1a4LZZ2Q:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/4UpeWVO59f0" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/nSlvKdb9EaI/index.html"  title="Jason Benetti has cerebral palsy, and he's living the dream ..." target="_blank">Living with cerebral palsy in sports</a> <br />
Jason Benetti has cerebral palsy, and he's living the dream as the announcer for the Syracuse Chiefs<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nSlvKdb9EaI:8jJPlQRAfV8:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nSlvKdb9EaI:8jJPlQRAfV8:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nSlvKdb9EaI:8jJPlQRAfV8:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=nSlvKdb9EaI:8jJPlQRAfV8:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nSlvKdb9EaI:8jJPlQRAfV8:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=nSlvKdb9EaI:8jJPlQRAfV8:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=nSlvKdb9EaI:8jJPlQRAfV8:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/nSlvKdb9EaI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/EbByGNXNIFg/index.html"  title="Tired of negative news? Check out these 10 survivors -- they..." target="_blank">10 amazing survivor stories</a> <br />
Tired of negative news? Check out these 10 survivors -- they'll make you feel a bit better about the human race.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EbByGNXNIFg:Fhy0Zqy1z3Y:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EbByGNXNIFg:Fhy0Zqy1z3Y:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EbByGNXNIFg:Fhy0Zqy1z3Y:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=EbByGNXNIFg:Fhy0Zqy1z3Y:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EbByGNXNIFg:Fhy0Zqy1z3Y:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=EbByGNXNIFg:Fhy0Zqy1z3Y:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=EbByGNXNIFg:Fhy0Zqy1z3Y:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/EbByGNXNIFg" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_health/~3/v-bBHlNcC0Q/index.html"  title="Urban Miyares has diabetes and has been legally blind since ..." target="_blank">Blind sailor wants to go solo</a> <br />
Urban Miyares has diabetes and has been legally blind since the 1970s. Neither has stopped him from following his passion for sailing.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=v-bBHlNcC0Q:atocWH-zC00:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=v-bBHlNcC0Q:atocWH-zC00:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=v-bBHlNcC0Q:atocWH-zC00:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=v-bBHlNcC0Q:atocWH-zC00:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=v-bBHlNcC0Q:atocWH-zC00:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_health?a=v-bBHlNcC0Q:atocWH-zC00:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_health?i=v-bBHlNcC0Q:atocWH-zC00:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_health/~4/v-bBHlNcC0Q" height="1" width="1"/>
</li>
</ul></div>
</li></ul>

	</div>
</div>
</body>
</html>
