<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link href="daily.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body>
<div id="column2">
	<div id="col2_text" class="scroll">
		<ul>
	<li>
<div class="rss-box">
<p class="rss-title"><a class="rss-title" href="http://www.bignewsnetwork.com/index.php/cat/88176adfdf246af5/" target="_blank">Europe News latest RSS headlines - Big News Network.com</a></p>
<ul class="rss-items">
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216567567/scat/88176adfdf246af5"  title="PARIS, France - If the use of chemical weapons in Syria is c..." target="_blank">Military force mooted by France if Syria chemical weapons claims verified</a> <br />
PARIS, France - If the use of chemical weapons in Syria is confirmed the international community must respond with "a reaction with force", France said Thursday amid calls for the Syrian authorities to permit United Nations experts to examine the site of an alleged poison gas attack outside Damascus. "There would have to be reaction with force in Syria from the international community," ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216575941/scat/88176adfdf246af5"  title="A TV commentator in Belgium has landed himself in trouble af..." target="_blank">Soccer player seeks damages over fat as a pig insult by Belgian TV host</a> <br />
A TV commentator in Belgium has landed himself in trouble after he described a soccer player as a 'fat pig' on live TV. Harlem Gnohere, who plays for Charleroi, has demanded a public apology and damages for the comment made by Stephane Pauwels at the weekend. According to metro.co.uk, Pauwels told viewers during Charleroi's 2-1 defeat by KV Kortrijk that Gnohere was 'too heavy.' Gnohere is ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216575271/scat/88176adfdf246af5"  title="The Russian government has reportedly defended its controver..." target="_blank">Russia defends controversial anti-gay propaganda law in letter to IOC</a> <br />
The Russian government has reportedly defended its controversial law against gay 'propaganda', which has promoted an international backlash, in a letter to the International Olympic Committee (IOC). However, the government has assured the IOC that it will not discriminate against homosexuals during the 2014 Winter Olympics at Sochi. According to the New York Daily News, the IOC received a ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216587443/scat/88176adfdf246af5"  title="A six-member jury at a military base in (the western state o..." target="_blank">US Soldier Gets Life Sentence Without Parole in Killing of 16 Afghans</a> <br />
A six-member jury at a military base in (the western state of) Washington returned its sentence Friday against Sergeant Robert Bales after deliberating for less than two hours. The 40-year-old Bales was on his fourth combat deployment when he carried out the middle-of-the-night attack in March 2012. In what came to be known as the Kandahar Massacre, Bales walked by himself to two neighboring ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216587442/scat/88176adfdf246af5"  title="TBILISI -- Before Russia fought a shooting war with Georgia,..." target="_blank">Russia Concerned Over Georgias Presidential Election</a> <br />
TBILISI -- Before Russia fought a shooting war with Georgia, it fought a trade war with its small neighbor. First, Russia lifted a 7-year-old ban on Georgian wine - and wine bottles started flowing north this year to Moscow. Next, Russia re-opened its borders to Georgian mineral water. Here is Gennady Onishchenko, Russia&amp;rsquo;s chief sanitary inspector, welcoming Georgian wine: But, ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216587440/scat/88176adfdf246af5"  title="New clashes at key oil terminals in Libya this week and a da..." target="_blank">Strikes And Political Instability Threaten Libya</a> <br />
New clashes at key oil terminals in Libya this week and a daring robbery of the European Union ambassador in Tripoli are raising new concerns about economic and political chaos in the North African nation. The government had hoped to re-open several key oil terminals this week that had been closed by striking guards from the recently formed Petroleum Facilities Guard, or PFG. The group is ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216587468/scat/88176adfdf246af5"  title="Greece is the crisis German Chancellor Merkel wants as she a..." target="_blank">Greece fits Merkel?s re-election plan Italy not so much</a> <br />
Greece is the crisis German Chancellor Merkel wants as she and her Christian Democrats go to the polls on Sept. 22. The next Greek bailout will be a classic fudge consistent with her European policy, allowing her to claim that she is both pro-European and the great defender of the interests of the German taxpayer. (MICHAEL ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216587467/scat/88176adfdf246af5"  title="Russian authorities have given &amp;amp;quot;strong&amp;amp;..." target="_blank">Russia vows no discrimination at Olympics</a> <br />
Russian authorities have given &amp;quot;strong&amp;quot; assurances that gay and lesbian competitors at next year&amp;#039;s Winter Olympics will not face discrimination, International Olympic Committee (IOC) chief Jacques Rogge said Friday during a visit to the United Nations. Gay rights activists have led calls for a boycott of the 2014 Sochi Games in protest at Russia&amp;#039;s notorious &amp;quot;gay ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216587152/scat/88176adfdf246af5"  title="Labor is proposing to give small business a greater role in ..." target="_blank">PM gives small business place at IR table</a> <br />
Labor is proposing to give small business a greater role in workplace relations policy. Prime Minister Kevin Rudd is set to announce a new small business package, starting with the appointment of an adviser with proven small business experience to the Fair Work Ombudsman. This adviser will work across the Ombudsman and Fair Work Commission to develop policy and practice to reflect the needs of ...
</li>
<li class="rss-item"><a class="rss-item" href="http://www.bignewsnetwork.com/index.php/sid/216587466/scat/88176adfdf246af5"  title="JOINT BASE LEWIS-MCCHORD, United States, Aug 23 AFP - A US a..." target="_blank">Soldier in Afghan massacre worst kind</a> <br />
JOINT BASE LEWIS-MCCHORD, United States, Aug 23 AFP - A US army sergeant who killed 16 Afghan villagers during a rampage is the &amp;quot;worst kind of criminal&amp;quot; and should spend life behind bars, a prosecutor says. In final submissions before a military hearing passes sentence on Robert Bales, 40, the prosecution said on Friday the soldier had shown no remorse and should never be given parole. ...
</li>
</ul></div>
</li>
</ul>

	</div>
</div>
</body>
</html>

<!--<div class="rss-box">
<p class="rss-title"><a class="rss-title" href="http://www.euronews.com" target="_blank">euronews</a><br /><span class="rss-item">The leading European News TV-channel. All the International news in 14.</span></p>
<ul class="rss-items">
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/-SiryIWhrps/story01.htm"  title="There were protests in Cairo on Friday but not on the scale ..." target="_blank">Egypt: low turnout for Muslim Brotherhood demonstrations</a> <br />
There were protests in Cairo on Friday but not on the scale the Muslim Brotherhood had called for. A week after a violent crackdown by the military?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/30532ff2/sc/40/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fegypt-low-turnout-for-muslim-brotherhood-demonstrations%2F&t=Egypt%3A+low+turnout+for+Muslim+Brotherhood+demonstrations" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fegypt-low-turnout-for-muslim-brotherhood-demonstrations%2F&t=Egypt%3A+low+turnout+for+Muslim+Brotherhood+demonstrations" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fegypt-low-turnout-for-muslim-brotherhood-demonstrations%2F&t=Egypt%3A+low+turnout+for+Muslim+Brotherhood+demonstrations" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fegypt-low-turnout-for-muslim-brotherhood-demonstrations%2F&t=Egypt%3A+low+turnout+for+Muslim+Brotherhood+demonstrations" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fegypt-low-turnout-for-muslim-brotherhood-demonstrations%2F&t=Egypt%3A+low+turnout+for+Muslim+Brotherhood+demonstrations" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/-SiryIWhrps" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/5Hcru2WEEQ8/story01.htm"  title="The authorities in Russia's Far East - already under pressur..." target="_blank">Russia's Far East braced for more record floods</a> <br />
The authorities in Russia's Far East - already under pressure from record floods - are expecting a further rise in water levels over the weekend. As?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/3051f65b/sc/11/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Frussia-s-far-east-braced-for-more-record-floods%2F&t=Russia%27s+Far+East+braced+for+more+record+floods" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Frussia-s-far-east-braced-for-more-record-floods%2F&t=Russia%27s+Far+East+braced+for+more+record+floods" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Frussia-s-far-east-braced-for-more-record-floods%2F&t=Russia%27s+Far+East+braced+for+more+record+floods" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Frussia-s-far-east-braced-for-more-record-floods%2F&t=Russia%27s+Far+East+braced+for+more+record+floods" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Frussia-s-far-east-braced-for-more-record-floods%2F&t=Russia%27s+Far+East+braced+for+more+record+floods" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/5Hcru2WEEQ8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/0UqfH3spUQ8/story01.htm"  title="Doctors and hospital staff in Greece have been on strike in ..." target="_blank">Greece: Doctors strike over plans to close hospitals</a> <br />
Doctors and hospital staff in Greece have been on strike in protest at their government's plans to close hospitals and lay off staff. The Greek?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/30519304/sc/14/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fgreece-doctors-strike-over-plans-to-close-hospitals%2F&t=Greece%3A+Doctors+strike+over+plans+to+close+hospitals" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fgreece-doctors-strike-over-plans-to-close-hospitals%2F&t=Greece%3A+Doctors+strike+over+plans+to+close+hospitals" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fgreece-doctors-strike-over-plans-to-close-hospitals%2F&t=Greece%3A+Doctors+strike+over+plans+to+close+hospitals" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fgreece-doctors-strike-over-plans-to-close-hospitals%2F&t=Greece%3A+Doctors+strike+over+plans+to+close+hospitals" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fgreece-doctors-strike-over-plans-to-close-hospitals%2F&t=Greece%3A+Doctors+strike+over+plans+to+close+hospitals" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/0UqfH3spUQ8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/IQrgpOZu1RI/story01.htm"  title="Tunisian rapper Weld El 15 claims he was beaten by the polic..." target="_blank">Tunisian rapper claims police brutality</a> <br />
Tunisian rapper Weld El 15 claims he was beaten by the police after a concert. His lawyer stated that police said he should be taken to court over?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/3051f65f/sc/40/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Ftunisian-rapper-claims-police-brutality%2F&t=Tunisian+rapper+claims+police+brutality" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Ftunisian-rapper-claims-police-brutality%2F&t=Tunisian+rapper+claims+police+brutality" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Ftunisian-rapper-claims-police-brutality%2F&t=Tunisian+rapper+claims+police+brutality" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Ftunisian-rapper-claims-police-brutality%2F&t=Tunisian+rapper+claims+police+brutality" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Ftunisian-rapper-claims-police-brutality%2F&t=Tunisian+rapper+claims+police+brutality" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/IQrgpOZu1RI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/nScs8wOtoew/story01.htm"  title="There is something fishy going on in Brazil. Ten tons of dea..." target="_blank">Brazil: Ten tons of dead fish found in Rio lake</a> <br />
There is something fishy going on in Brazil. Ten tons of dead fish have been found floating in a Rio de Janeiro lake. Biologists said it was likely?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/3050e676/sc/42/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fbrazil-ten-tons-of-dead-fish-found-in-rio-lake%2F&t=Brazil%3A+Ten+tons+of+dead+fish+found+in+Rio+lake" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fbrazil-ten-tons-of-dead-fish-found-in-rio-lake%2F&t=Brazil%3A+Ten+tons+of+dead+fish+found+in+Rio+lake" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fbrazil-ten-tons-of-dead-fish-found-in-rio-lake%2F&t=Brazil%3A+Ten+tons+of+dead+fish+found+in+Rio+lake" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fbrazil-ten-tons-of-dead-fish-found-in-rio-lake%2F&t=Brazil%3A+Ten+tons+of+dead+fish+found+in+Rio+lake" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fbrazil-ten-tons-of-dead-fish-found-in-rio-lake%2F&t=Brazil%3A+Ten+tons+of+dead+fish+found+in+Rio+lake" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/nScs8wOtoew" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/wQ8cyOQeJSI/story01.htm"  title="Ukraine's President Victor Yanukovych have been in Kharkiv t..." target="_blank">Kharkiv celebrates 70th anniversary of liberation from the Nazis</a> <br />
Ukraine's President Victor Yanukovych have been in Kharkiv to celebrate the 70th anniversary of the liberation of the city from the Nazis. The event?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/3051f665/sc/8/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fkharkiv-celebrates-70th-anniversary-of-liberation-from-the-nazis%2F&t=Kharkiv+celebrates+70th+anniversary+of+liberation+from+the+Nazis" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fkharkiv-celebrates-70th-anniversary-of-liberation-from-the-nazis%2F&t=Kharkiv+celebrates+70th+anniversary+of+liberation+from+the+Nazis" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fkharkiv-celebrates-70th-anniversary-of-liberation-from-the-nazis%2F&t=Kharkiv+celebrates+70th+anniversary+of+liberation+from+the+Nazis" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fkharkiv-celebrates-70th-anniversary-of-liberation-from-the-nazis%2F&t=Kharkiv+celebrates+70th+anniversary+of+liberation+from+the+Nazis" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fkharkiv-celebrates-70th-anniversary-of-liberation-from-the-nazis%2F&t=Kharkiv+celebrates+70th+anniversary+of+liberation+from+the+Nazis" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/wQ8cyOQeJSI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/Pr9nb9iUkkE/story01.htm"  title="Hollywood actor and Oscar winning director Ben Affleck is to..." target="_blank">Ben Affleck to play caped crusader in Superman film</a> <br />
Hollywood actor and Oscar winning director Ben Affleck is to be the new Batman. He is the eighth actor to take on the role of the caped crusader but?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/3051f664/sc/38/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fben-affleck-to-play-caped-crusader-in-superman-film%2F&t=Ben+Affleck+to+play+caped+crusader+in+Superman+film" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fben-affleck-to-play-caped-crusader-in-superman-film%2F&t=Ben+Affleck+to+play+caped+crusader+in+Superman+film" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fben-affleck-to-play-caped-crusader-in-superman-film%2F&t=Ben+Affleck+to+play+caped+crusader+in+Superman+film" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fben-affleck-to-play-caped-crusader-in-superman-film%2F&t=Ben+Affleck+to+play+caped+crusader+in+Superman+film" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fben-affleck-to-play-caped-crusader-in-superman-film%2F&t=Ben+Affleck+to+play+caped+crusader+in+Superman+film" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/Pr9nb9iUkkE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/TtZVxvm3wiM/story01.htm"  title="&quot;We have been very clear to the Assad regime and also t..." target="_blank">Obama's Syrian options</a> <br />
"We have been very clear to the Assad regime and also to other players on the ground that a red line for us is : we start seeing a whole bunch of?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/30524c8f/sc/13/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fobama-s-syrian-options%2F&t=Obama%27s+Syrian+options" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fobama-s-syrian-options%2F&t=Obama%27s+Syrian+options" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fobama-s-syrian-options%2F&t=Obama%27s+Syrian+options" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fobama-s-syrian-options%2F&t=Obama%27s+Syrian+options" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fobama-s-syrian-options%2F&t=Obama%27s+Syrian+options" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/TtZVxvm3wiM" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/KLwRZQb5ogE/story01.htm"  title="Twin car bomb blasts have hit the northern Lebanese city of ..." target="_blank">Deadly car bomb carnage in the Lebanese city of Tripoli</a> <br />
Twin car bomb blasts have hit the northern Lebanese city of Tripoli killing at least 42 people and injuring over 500. The explosions happened?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/3050e67a/sc/20/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fdeadly-car-bomb-carnage-in-the-lebanese-city-of-tripoli%2F&t=Deadly+car+bomb+carnage+in+the+Lebanese+city+of+Tripoli" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fdeadly-car-bomb-carnage-in-the-lebanese-city-of-tripoli%2F&t=Deadly+car+bomb+carnage+in+the+Lebanese+city+of+Tripoli" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fdeadly-car-bomb-carnage-in-the-lebanese-city-of-tripoli%2F&t=Deadly+car+bomb+carnage+in+the+Lebanese+city+of+Tripoli" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fdeadly-car-bomb-carnage-in-the-lebanese-city-of-tripoli%2F&t=Deadly+car+bomb+carnage+in+the+Lebanese+city+of+Tripoli" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fdeadly-car-bomb-carnage-in-the-lebanese-city-of-tripoli%2F&t=Deadly+car+bomb+carnage+in+the+Lebanese+city+of+Tripoli" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/KLwRZQb5ogE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feedproxy.google.com/~r/euronews/en/world/~3/D_cpH5-5UL8/story01.htm"  title="The number of children who have fled the conflict has now to..." target="_blank">A Syrian child's wish as the number of refugees tops the million mark</a> <br />
The number of children who have fled the conflict has now topped the one million mark. That according to the United Nations is half the total of?<img width='1' height='1' src='http://Euronews.net.feedsportal.com/c/32800/f/536661/s/304ff320/sc/20/mf.gif' border='0'/><br clear='all'/><div class='mf-viral'><table border='0'><tr><td valign='middle'><a href="http://share.feedsportal.com/share/twitter/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fa-syrian-child-s-wish-as-the-number-of-refugees-tops-the-million-mark%2F&t=A+Syrian+child%27s+wish+as+the+number+of+refugees+tops+the+million+mark" target="_blank"><img src="http://res3.feedsportal.com/social/twitter.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/facebook/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fa-syrian-child-s-wish-as-the-number-of-refugees-tops-the-million-mark%2F&t=A+Syrian+child%27s+wish+as+the+number+of+refugees+tops+the+million+mark" target="_blank"><img src="http://res3.feedsportal.com/social/facebook.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/linkedin/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fa-syrian-child-s-wish-as-the-number-of-refugees-tops-the-million-mark%2F&t=A+Syrian+child%27s+wish+as+the+number+of+refugees+tops+the+million+mark" target="_blank"><img src="http://res3.feedsportal.com/social/linkedin.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/gplus/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fa-syrian-child-s-wish-as-the-number-of-refugees-tops-the-million-mark%2F&t=A+Syrian+child%27s+wish+as+the+number+of+refugees+tops+the+million+mark" target="_blank"><img src="http://res3.feedsportal.com/social/googleplus.png" border="0" /></a>&nbsp;<a href="http://share.feedsportal.com/share/email/?u=http%3A%2F%2Fwww.euronews.com%2F2013%2F08%2F23%2Fa-syrian-child-s-wish-as-the-number-of-refugees-tops-the-million-mark%2F&t=A+Syrian+child%27s+wish+as+the+number+of+refugees+tops+the+million+mark" target="_blank"><img src="http://res3.feedsportal.com/social/email.png" border="0" /></a></td><td valign='middle'></td></tr></table></div><img src="http://feeds.feedburner.com/~r/euronews/en/world/~4/D_cpH5-5UL8" height="1" width="1"/>
</li>
</ul></div>
-->
