<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="style.css" rel="stylesheet" type="text/css">
<base target="_blank" />
</head>

<body style="background-color: #ffffff;">
<div id="business2" class="format2 scrollbar">
       <UL>
      <LI> <A HREF="http://www.adexitalia.com/">Adex  	Italia</A> - Italian exporter of extra virgin olive oil, pasta, wine  	and truffles. Company profile. 
      <LI> <A HREF="http://www.agholland.nl/">AG  	Holland</A> - Service area is primarily in the Netherlands,  	Antilles, Aruba, South America and Suriname. Trades in various items  	such as juices, fresh produce, snacks, beer, cookies, cosmetics,  	wines, soup ingredients, sauces, and mixes. processed meats, and  	condiments. Located in The Netherlands. 
      <LI> <A HREF="http://www.agratrading.com/">Agra  	Trading Brasil LTDA</A> - Traders of beef, poultry, lamb, fish and  	dairy products throughout the world. Company profile and product  	details. 
      <LI> <A HREF="http://www.alifood.it/">Alifood  	Italian</A> - Exports Italian food including pasta, olive oil,  	parmesan cheese, sauces and sweet preserves. 
      <LI> <A HREF="http://www.allana.com/">Allanasons  	Limited</A> - Exporters of agricultural and processed food products  	from India. 
      <LI> <A HREF="http://www.almafood.com/">Alma  	Food Imports Inc.</A> - Fine imported Italian foods including pasta,  	olive oil, cakes, cookies and bottled water. 
      <LI> <A HREF="http://amfex.net/">American  	Foods Export Services, Inc.</A> - Service company specializing in  	food product labeling and dating of consigned goods; also trucks  	full containers and less than truckload loads. 
      <LI> <A HREF="http://www.ampro.co.th/">Ampro  	Intertrade Co.,Ltd.</A> - Exporters of a wide array of food items  	from Thailand. Company profile, and product and contact details. 
      <LI> <A HREF="http://www.aqholdings.com/">AQ  	Holdings</A> - Direct importers and exporters of spices, rice,  	sugar, pulses and grains. Company profile and contact details. 
      <LI> <A HREF="http://www.atlantica-co.com/">Atlantica</A> - Worldwide exports of Spanish food products including cheese,  	seafood, rice, and organic goods. Company profile, product details,  	and contact links. 
      <LI> <A HREF="http://www.ozebiz.com.au/honey">Australian  	Rainforest Honey</A> - Exporting Australian honey worldwide. 
      <LI> <A HREF="http://www.terfloth.com/">B.  	Terfloth and Associates</A> - International food trading house  	providing worldwide import and export services, transportation,  	finance, and supply management. 
      <LI> <A HREF="http://www.bedessee.com/">Bedessee  	Imports, Ltd.</A> - Importers of West Indian and tropical foods.  	Company history, product listings, and contact details. 
      <LI> <A HREF="http://www.bcwltd.com/">Bedford  	Continental Wholesale</A> - Importers of fine Italian foods and  	monopack products for coffee shops, restaurants, retail and catering  	trades. 
      <LI> <A HREF="http://www.bethco.com/">Bethco  	International, Inc</A> - Market driven company focused on specialty  	foods, fast foods, food service products and institutional and  	industrial foods. 
      <LI> <A HREF="http://www.beyondoz.com/">Beyond  	Oz Trading</A> - Exporting meat, wine, seafood, grains, fruit and  	other products from Australia. Company profile and contact details. 
      <LI> <A HREF="http://www.blueplanetfoods.com/">Blue  	Planet Foods</A> - Specializes in the importation and trading of  	difficult-to-find specialty foods and ingredients. Company profile,  	products and contact details. 
      <LI> <A HREF="http://www.brecon.ca/">Brecon  	Foods</A> - Canadian traders of a variety of food commodities.  	Product details. 
      <LI> <A HREF="http://www.britishaisles.com/">The  	British Aisles Ltd</A> - Importers and distributors of British food  	products. 
      <LI> <A HREF="http://www.brothersinternational.com/">Brothers  	International Food Corporation</A> - Imports wine from Portugal,  	fruit juice concentrates and purees, freeze dried fruit and other  	agricultural products. 
      <LI> <A HREF="http://bulgariandepot.com/">Bulgarian  	Depot</A> - Importing relishes, processed goods and seasonings from  	the Balkans, with illustrated product catalog and contact details.  	Pompano Beach, Florida, USA. 
      <LI> <A HREF="http://www.canintrad.com/">Caravan  	Trade</A> - A recognized trading house located in the heart of the  	business district of Montreal, Canada. Specializes in the trade of  	coffee mostly of Mexican origin. 
      <LI> <A HREF="http://www.cai-sa.pt/">Casa  	Angola Internacional SA</A> - Exporter of dairy products, preserves,  	beverages, frozen meat and fish, tobacco, and hygiene products.  	Portugal. 
      <LI> <A HREF="http://www.castella.com/">Castella  	Imports, Inc.</A> - Importer, manufacturer and distributor of  	specialty foods from around the world. Company profile and product  	details. 
      <LI> <A HREF="http://www.roeper.de/">C.E.  	Roeper GmbH</A> - Trading Company with natural raw materials, gums,  	waxes and resins, for use in food, pharma and technical  	applications. 
      <LI> <A HREF="http://www.yonghuat.com.sg/">Chop  	Yong Huat</A> - Importer and exporter in Singapore that trades  	Chinese delicacies: bird's nest, shark's fin, sea cucumbers and fish  	maw. 
      <LI> <A HREF="http://www.ceisa.org/">Circle  	of Specialty Food Distributors</A> - International trade association  	for food and beverage importers. Profile, membership information,  	and contact link. 
      <LI> <A HREF="http://www.clippertonmarketing.com/">Clipperton  	Marketing Inc.</A> - Imports and distributes fine food from France  	in Canada and the USA. 
      <LI> <A HREF="http://www.neo.lv/">Company  	Neo Ltd</A> - Offers trading, supply and consulting services of food  	raw materials and ingredients. Company profile, product and contact  	information. 
      <LI> <A HREF="http://www.cwlservices.com/">CWL  	Import Export Services</A> - Malaysia exporter of food,  	confectionery, beverages and handicrafts. Company profile, product  	listing, and contact details. 
      <LI> <A HREF="http://www.dainamcorp.com/">Dainam  	Corporation</A> - Traders of rice, nuts, spices, packed foods,  	related packaging material and equipment. Product and contact  	information. 
      <LI> <A HREF="http://www.deboerfood.com/">de  	Boer Food Importers</A> - United States importer of fine foods from  	Holland, Belgium and France. Representing sixteen different  	manufacturers. Company profile, product lines, contact details. 
      <LI> <A HREF="http://www.deniztarim.com/">Deniz  	Agricultural Products</A> - Turkish exporters of capers, nuts, and  	pulses. Product and contact details. 
      <LI> <A HREF="http://www.dicalgroup.com/">Dical  	Group</A> - Maltese importer, exporter, and distributor of  	international food related product specialties and delicatessen.  	Also operates a apiary. 
      <LI> <A HREF="http://www.doraliceimports.com/">Doralice  	Imports</A> - Importer of authentic South American specialty foods  	including dairy, condiments, spices, wine, and cocoa products. 
      <LI> <A HREF="http://www.organic.nl/">Dutch  	Organic International Trade</A> - Dutch import and export company of  	organic food products. Company profile, products, agent and contact  	details. 
      <LI> <A HREF="http://www.ewtaonline.com/">East  	West Trading &amp; Agencies Ltd.</A> - Distributor of imported dairy  	products, pastas, condiments, preservatives, oils, and canned items  	in Thailand. Product figures and photos. Yannawa, Bangkok, Thailand. 
      <LI> <A HREF="http://www.economictropicalfoods.com/">Economic  	Tropical Foods, Ltd.</A> - Importers and distributors of Hispanic  	and Jamaican specialty foods. Rochester, New York. 
      <LI> <A HREF="http://www.etna-tr.com/">Etna  	Gida San. Ve Dis Tic Ltd. Sti.</A> - Exporter of both conventional  	and organic products from Turkey. Company profile, products and  	contact details. 
      <LI> <A HREF="http://www.expandingfrontiers.com/">Expanding  	Frontiers</A> - Exporter and distributor of Argentina food products  	to specialty stores in United States. Company profile and contact  	details. 
      <LI> <A HREF="http://www.fintrader.nl/">Fintrader</A> - Intermediary between Western Europe and Finland, dealing in  	vegetables, food products, and beverages. Includes contact details. 
      <LI> <A HREF="http://www.fomarusa.com/">Fomar  	Import and Export, Inc.</A> - Import and export Mexican produce,  	including chillies, spices, cereals, snacks, corn husk, and seafood.  	Locations in Mexico and California. 
      <LI> <A HREF="http://www.foodfromdenmark.dk/">Food  	from Denmark</A> - Group of 10 professional Danish food suppliers  	focusing on export promotion to the US retail and catering sectors.  	Supplier profiles, product and contact information. 
      <LI> <A HREF="http://www.frenchfoodexports.com/">French  	Food Exports</A> - Agents and consignees for French food companies.  	Company profile, product and contact information. 
      <LI> <A HREF="http://www.frusol.com/">Frusol  	International Inc.</A> - Canadian company specialized in the import  	and distribution of fresh and dehydrated produce, imported from  	European and Latin American and marketed throughout Canada and the  	United States. 
      <LI> <A HREF="http://www.gamauk.com/">Gama  	(Import/Export) Ltd</A> - Imports Turkish food products into the  	United Kingdom. Company profile, item listing, and contact details. 
      <LI> <A HREF="http://www.best-italian-food.it/">G.D.A.X.  	S.r.l.</A> - Company specialized in the export of Italian food and  	drink. Company profile, product information, and contact link. 
      <LI> <A HREF="http://www.gfr.cc/">Global  	Food Resources, Inc.</A> - U.S. trading company with an expertise in  	exports to the Pacific Rim and Latin America. Company and product  	information, contact details. 
      <LI> <A HREF="http://www.globalorganicsltd.com/">GO!  	Global Organics, Ltd.</A> - Importer and exporter of organic  	commodities and ingredients including certified organic cocoa  	products, dried fruit, nuts, spices, and sugar cane products. 
      <LI> <A HREF="http://www.handibazaar.com/handi.html">Handi  	Bazaar</A> - Direct and indirect exporters of processed foods.  	Authenticated indian curried vegetables in cans. dal makhani, dal  	mughlai, sarson ka saag, and matar paneer. 
      <LI> <A HREF="http://www.haramchris.com/">Haram-Christensen  	Corporation</A> - Specialized in importing and distributing of fine  	foods from Europe. Product details by country of origin. Broker and  	contact details. 
      <LI> <A HREF="http://www.helix.web.pt/">Helix</A> - Portuguese exporters of farmed snails for consumption to France.  	[English, French, Portuguese] 
      <LI> <A HREF="http://www.herrawigroup.com/">Herrawi  	Group</A> - Egyptian firm offering artichoke products, citrus  	packing, and rice export. Product information, company history, and  	contact details. 
      <LI> <A HREF="http://www.himneel.com/">Himneel  	Overseas Pvt., Ltd</A> - Merchant exporter of food colors and  	dyestuffs. Company profile, product and contact details. 
      <LI> <A HREF="http://www.hines.com.au/">Hines  	Group Australia</A> - Exporters of food and wine from Australia. 
      <LI> <A HREF="http://www.hinrichstrading.com/">Hinrichs  	Trading</A> - Exporter of specialty crops such as garbanzo beans,  	whole and split green and yellow peas, lentils, canola, popcorn,  	bird feed, and feed bi-products. 
      <LI> <A HREF="http://www.hmexport.com/">HM  	Export</A> - Exporter of fruits, vegetables, fish, and other seafood  	from Peru. 
      <LI> <A HREF="http://www.indu.com/">Indu  	Industries</A> - Tea, coffee, pepper, and tobacco grown and packed  	in India. Offices in India. Site in English and Russian. 
      <LI> <A HREF="http://ishmeetagencies.com/">Ishmeet  	Agencies</A> - Importers and exporters of Indian grocery food  	products. Company profile and product details. 
      <LI> <A HREF="http://www.italcomex.it/">Italcomex</A> - Italian food trader specialised in exporting tomatoes, boiled  	vegetables, pasta and macaroni. Company profile and product details. 
      <LI> <A HREF="http://www.jayfresh.com.au/">Jayfresh  	Alliance</A> - Exporter of Australian food and beverages, including  	fruit, seafood, wine, and olive oil. Company profile and contact  	details. 
      <LI> <A HREF="http://www.kanwaltrading.com/">Kanwal  	Trading</A> - Exporter of Pakistan sourced pulses, spices, herbs,  	rice, and dry fruits to international markets. Company history,  	product details, quality control, and contact links. 
      <LI> <A HREF="http://www.khdejong.nl/">K.H.  	de Jong</A> - Exporter of Dutch cheese including gouda, edam,  	maasdam, and vincent. Company information and product details. 
      <LI> <A HREF="http://kilbanfoods.com/">Kilban  	Foods (India) Pvt. Ltd.</A> - Exports to Gulf countries a variety of  	condiments, produce products, and soft drink concentrates. Company  	profile and product details. 
      <LI> <A HREF="http://www.kiricilar.com.tr/">Kırıcılar  	Ltd.</A> - Exporters of fruits and vegetables, processed foods, and  	sauces. Turkey. 
      <LI> <A HREF="http://www.kremlin-ebusiness.cz/">Kremlin  	SRO Ltd</A> - Import-export of a wide array of food items. 
      <LI> <A HREF="http://www.barkath.com/">Kumpulan  	Barkath</A> - Malaysian exporter of seafood, beverages, condiments  	and candy. Company profile, products, and contact links. 
      <LI> <A HREF="http://www.kwanyick.com/">Kwan  	Yick (UK) LTD</A> - Importers and distributors of speciality  	Oriental foods, sauces and packaging materials to the catering  	trade, based in South Wales, UK. Company profile, products,  	distribution range, and contact details. 
      <LI> <A HREF="http://www.aishwaryaoverseas.com/">Laishwarya  	Overseas</A> - Progressive full service exporting company, focusing  	especially on agricultural products and garments. 
      <LI> <A HREF="http://www.lat-traders.com/">Latin  	American Traders</A> - Exporters of Argentine products including  	wine, olive oil, vinegars, seasonings, and specialty cheeses.  	Company profile, product information, and contact details. 
      <LI> <A HREF="http://www.ld-enterprise.com/">L&amp;D  	ENTERPRISE</A> - Supplier of seafood, cake, candy, rice, juice,  	sauces, coffee, tea and pickled foods. Includes list of products and  	photos. Located in Ho Chi Minh City, Vietnam. 
      <LI> <A HREF="http://www.lettieri.com/">Lettieri  	and Company</A> - Importer of specialty food and beverage items from  	Europe. Company profile, products, online market and contact  	details. 
      <LI> <A HREF="http://www.lhianthai.com/">Lhian  	Thai Rice Vermicelli Co.,Ltd</A> - Thai exporter of rice vermicelli  	and other rice products. 
      <LI> <A HREF="http://www.libertyrichter.com/">Liberty  	Richter</A> - Importer of specialty foods and confections. 
      <LI> <A HREF="http://www.ligustica.com/">Ligustica  	Products</A> - Exporters of Italian food and beverages including  	pasta, biscuits, olive oil and wine. Company profile, product and  	contact details. 
      <LI> <A HREF="http://www.lshworld.com/">Lim  	Siang Hhuat</A> - Major importer and exporter of canned foods and  	grocery products into Singapore. Company profile, products,  	promotions and contact details. 
      <LI> <A HREF="http://markethalkos.com.sapo.pt/">Markethalkos</A> - Exports kosher wines, extra virgin olive oil, canned tuna fish and  	sardines. Located in Lisbon, Portugal. [English and Portuguese] 
      <LI> <A HREF="http://www.atasteofgreece.net/">Mavrikos  	Imports S. A.</A> - Buys and sells Greek olive oil, herbs, halva,  	pasta, fish, vegetables, prepared dishes, brandies, Ouzo, and wine. 
      <LI> <A HREF="http://www.alfalfa.it/">Medimedica</A> - Alfalfa dehydrated, sugar beet pulps and cotton seeds. 
      <LI> <A HREF="http://www.mega.biz.pl/">Mega  	Ltd</A> - Poland. Distributes canned and frozen fish, margarines and  	dairy products. [English, Polish and Russian] 
      <LI> <A HREF="http://www.meis-isc.de/">Meis  	- International Sales Consulting</A> - General distributor of  	chocolate and other foods from Brandt, Niederegger, Falize, Gottena,  	Kaiser and Pauly. 
      <LI> <A HREF="http://www.contelfood.com/">Natural  	Mediterranean Food</A> - Exports an innovative range of pre-packed  	Italian food. Product information and contact details. 
      <LI> <A HREF="http://www.nectrafood.com/">Nectra  	Food SA</A> - Imports and distributes specialty food products from  	Greece and Bolivia. Based in the USA and Switzerland. 
      <LI> <A HREF="http://www.nordicimpex.ro/">Nordic  	Import Export CO</A> - Providing import, logistic and marketing for  	food products including seafood, cheese, sausage, whipped cream and  	coffee from Europe. General details about the company, history and  	products. Romania. 
      <LI> <A HREF="http://www.ofistrade.com/">Ofistrade</A> - Spanish importer and distributor for finest delikatessen, ethnic  	food and drink. 
      <LI> <A HREF="http://www.omega-foods.com/">Omega  	Food Importers Co. Ltd.</A> - Importer of European food products  	into Canada. 
      <LI> <A HREF="http://www.orchedeus.com/">Orchedeus  	Trade Services</A> - Trading company specialising in sourcing and  	export of food products from Europe. Product and contact  	information. 
      <LI> <A HREF="http://orientalconcept.net/">Oriental  	Concept Company Limited</A> - Food exporter and trader of canned  	seafood, vegetables, and frozen food. Company profile and product  	details. 
      <LI> <A HREF="http://www.pikzern.com/">Pikzern  	Marketing Sdn. Bhd.</A> - Imports, exports, and distributes food  	products, beverages, and confectionery items. Includes a product  	catalog and contact information. 
      <LI> <A HREF="http://www.pjexports.com/">P.J.  	Exports</A> - Indian exporter of snacks, groceries, spices and  	pulses, ready-to-eat products, and mixes. 
      <LI> <A HREF="http://www.psimports.net/">Power-Selles  	Imports</A> - Importer of specialty gourmet food items from Spain  	including olive oil, olives, vinegar, saffron, sauces, seafood, and  	sweets. 
      <LI> <A HREF="http://www.pramsel.co.kr/food.php">Pramsel  	Trading Corporation</A> - Specializing in frozen foods especially  	for Korean residents in foreign countries. 
      <LI> <A HREF="http://www.premaorganics.com/">Prema  	Organics</A> - Importers and suppliers of innovative food products  	and organic food products to the major Australian supermarkets.  	Company profile, product and contact details. 
      <LI> <A HREF="http://www.terra.es/personal/vitalian">Productos  	Lombardi, S.L.</A> - Importer of fresh, frozen and live fish and  	seafood for Madrid. Also imports olive oil and fresh fruits. 
      <LI> <A HREF="http://www.qureshiinternational.com/">Qureshi  	International</A> - Offers beef and sheep casings and other animal  	by-products. 
      <LI> <A HREF="http://www.rileyfoods.com/">Riley  	Foods International</A> - US-based independent export broker of  	dehydrated beans and peas suitable for retail sales or the food  	service market. Site is in English and Spanish. 
      <LI> <A HREF="http://www.farmsassasa.com/">Samy  	Fathy Assasa Co.</A> - Exporters of rice, garlic, onion, spices, and  	medicinal herbs. Company profile and contact information. 
      <LI> <A HREF="http://www.sapnafoods.com/">Sapna  	Foods</A> - Importer of dried mushrooms, vanilla beans, chiles, and  	saffron. Company profile and product information. 
      <LI> <A HREF="http://www.satnamoverseas.com/">Satnam  	Overseas</A> - India exporter of basmati rice, pulses, spices,  	cumin, coriander, sesame, groundnut, oilseeds, fennel, black pepper,  	turmeric, dill seed, fenugreek, and chilly. 
      <LI> <A HREF="http://www.saybrex.com/">Saybrex  	International, Inc.</A> - Exporter and distributor of wines,  	spirits, fruit juices and concentrates, and specialty foods. Company  	profile, product and contact details. 
      <LI> <A HREF="http://www.scan-neva.ru/">Scan-Neva  	Ltd.</A> - Exporter of wild mushrooms and frozen and dried berries.  	Products are organic (Bio) and Kosher. 
      <LI> <A HREF="http://www.schlueter-maack.com/">Schlüter  	and Maack</A> - Trader in sugar, coffee, cocoa and food-aid  	products. Company profile, product and contact details. 
      <LI> <A HREF="http://www.sevenseascom.net/">Seven  	Seas Commodities Private, Ltd.</A> - Involved in the international  	trade of spices, coffee beans, condiments, coconut products, and  	tea. Company profile, product and contact details. 
      <LI> <A HREF="http://www.sfcommodities.com/">SF  	Commodities Khi.</A> - Exporter of rice, spices, seeds, pulses, and  	other foodstuffs from Pakistan. Includes product information and  	contacts. 
      <LI> <A HREF="http://www.shilpaagro.com/">Shilpa  	Agro Overseas Pvt. Ltd. (India)</A> - Exporters of rice, pulses,  	sesame seeds, mango pulp, and fresh fruits and vegetables from  	India. 
      <LI> <A HREF="http://www.shrilalmahal.org/">Shivnath  	Rai Harnarain (India) Ltd.</A> - Exporters of basmati rice, pulses,  	sugar, Indian spices, and tea. Company profile and product listing.  	Multi-lingual. 
      <LI> <A HREF="http://www.shivtex.com/">Shivtex</A> - United States trading company focused on food products. Product  	listing and contact information. 
      <LI> <A HREF="http://www.silbury.co.uk/">Silbury  	Marketing Limited</A> - Sells food ingredients to the food industry. 
      <LI> <A HREF="http://www.sinodis.com.cn/">Sinodis</A> - Distributors of imported food products in China to retail and food  	service customers. 
      <LI> <A HREF="http://www.sitaramgroup.com/">Sitaram  	Group of Companies</A> - Distributors and c of f agents for consumer  	products like tea, coffee, baby items, confectioneries, vegetable  	oils and dealers of bajaj automobiles. 
      <LI> <A HREF="http://spanisholiveoil.freeservers.com/">Smiling  	S.A.</A> - Exporters of olive oil, olives and canned sea food. 
      <LI> <A HREF="http://www.sopariwala.com/">Sopariwala  	Exports</A> - Traders of botanicals, rice, oilseeds, spices,  	pulses,and cereals. 
      <LI> <A HREF="http://www.southnettradeaust.com/">Southnet  	Trade Australia</A> - A Riverina Region based trade organisation  	which promotes and sells a diversity of Australian agrifoods to the  	world. Company profile, product and contact details. 
      <LI> <A HREF="http://www.scifargo.com/">Specialty  	Commodities Incorporated</A> - A worldwide importer, manufacturer  	and distributor of specialty products for the snack food, health  	food, pet food and bakery industries. 
      <LI> <A HREF="http://www.stomos.net/">Stomas  	AB</A> - Swedish firm importing and exporting food products  	including reindeer, forest berries, and mushrooms. 
      <LI> <A HREF="http://www.sunpackers.com.pe/">Sun  	Packers</A> - Peruvian producer, packer, and exporter of dry edible  	beans, peas, and other agricultural products. Company information,  	product range, and contact details. 
      <LI> <A HREF="http://www.sunrisefoods.ca/">Sunrise  	Foods International Inc.</A> - Canadian exporter and importer of  	conventional and organic agri-food commodities. 
      <LI> <A HREF="http://www.takari.com/">Takari  	International Inc.</A> - A trading company specializing in Japanese  	snack foods and restaurant supplies. 
      <LI> <A HREF="http://www.tan-viet.com.pl/">Tan-Viet  	International Ltd..</A> - Specializes in export-import of oriental  	food and export of Polish agricultural products. Company profile,  	product and distribution information; contact details. 
      <LI> <A HREF="http://www.tecksang.com/">Teck  	Sang (Pte) Ltd.</A> - Importer, exporter and wholesaler of  	traditional Chinese food products including seafood, nuts, pulses,  	and spices. Contact and product information. 
      <LI> <A HREF="http://www.thaiindochine.com/">Thai  	Indochine Trading Inc.</A> - Specializes in importing food products  	from Thailand, Vietnam, Taiwan, China and other parts of Asia and  	sells to wholesalers throughout Canada. Provides a list of sales  	outlets and some recipes. 
      <LI> <A HREF="http://www.tw.co.th/">Thai  	World Import and Export Co., Ltd.</A> - Exporters of a large range  	of foods and beverages from Thailand, including fruits, vegetables,  	meats, seafoods, eggs, noodles, and condiments. Company history,  	product details, and contact information. 
      <LI> <A HREF="http://web.singnet.com.sg/~beckch/">Tong  	Seng Trading Company, LTD.</A> - Provides a range of dried  	agricultural, marine and herbal products from various countries. 
      <LI> <A HREF="http://www.twf-foods.com/">Traditional  	World Foods</A> - Holding company features services in sourcing new  	food products, importation, logistics, finance, marketing and  	management. Company profile, product and contact details. 
      <LI> <A HREF="http://www.trialiafoods.com.au/">Trialia  	Foods</A> - Distributor and importer of specialty food products.  	Includes a company profile and product lists. 
      <LI> <A HREF="http://www.tuscanfarm.com/">Tuscan  	Farm</A> - Wine, oils and specialty deli foods available for export  	from Tuscany. 
      <LI> <A HREF="http://www.italianfoodexport.com/">Union  	Export</A> - An Italian export pool promoting and representing  	Italian food firms. Profile of business partners, e-mail link. 
      <LI> <A HREF="http://www.vaghasiatrading.com/">Vaghasia  	Trading Pvt. Ltd.</A> - Exporter of whole and ground spices, sesame  	seed, nuts, and rice. Company profile, and product and contact  	details. 
      <LI> <A HREF="http://www.veder-supplies.nl/">Veder  	Supplies B.V.</A> - Exporter of a variety of products, including  	powdered milk, margarine, alcoholic beverages, canned fruits and  	vegetables, and canned fish. Includes product information and  	contact details. 
      <LI> <A HREF="http://mitglied.lycos.de/morsel14/">Vintex  	Trading</A> - Exporter of German food and beverage items for  	retailers, caterers, and for the hospitality industry. Includes  	portion packs, and diet/vegetarian items. 
      <LI> <A HREF="http://www.wsdepots.com/">Weddel  	Swift</A> - Pork, beef, poultry, fish, oils, fruit juice and wines  	exported worldwide by email request. 
      <LI> <A HREF="http://www.yasminmyanmar.com/">Yasmin  	Enterprise Co., Ltd</A> - Exporter of tamarind, beans and pulses,  	and seafood. Company profile and product information. 
      <LI> <A HREF="http://www.yewming.com.sg/">Yew Ming Trading Pte Ltd</A> - Importer, exporter, and wholesaler of dried seafood, fruits,  	vegetables, and legumes. Singapore. 
    </UL>\</div>
</body>
</html>
