<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link href="daily.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body>
<div id="column2">
	<div id="col2_text" class="scroll">
	<ul><li>
<div class="rss-box">
<p class="rss-title"><a class="rss-title" href="http://www.reuters.com" target="_blank">Reuters: Science News</a><br /><span class="rss-item">Reuters.com is your source for breaking news, business, financial and investing news, including personal finance and stocks. Reuters is the leading global provider of news, financial information and technology solutions to the world's media, financial institutions, businesses and individuals.</span></p>
<ul class="rss-items">
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/y9q1qN60bFg/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - As his helmet filled wit..." target="_blank">Italian astronaut recounts near-drowning during spacewalk</a> <br />
CAPE CANAVERAL, Florida (Reuters) - As his helmet filled with water, blurring his vision and cutting off radio communications, Italian astronaut Luca Parmitano says his thoughts quickly turned to the possibility of drowning during a recent spacewalk outside the International Space Station.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/3046deae/sc/38/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/sc/38/rc/1/rc.htm"><img src="http://da.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/sc/38/rc/1/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/sc/38/rc/2/rc.htm"><img src="http://da.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/sc/38/rc/2/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/sc/38/rc/3/rc.htm"><img src="http://da.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/sc/38/rc/3/rc.img" border="0"/></a><br/><br/><a href="http://da.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/a2.htm"><img src="http://da.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/173608112205/u/49/f/654220/c/35217/s/3046deae/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=y9q1qN60bFg:ZdMURRNfvUo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=y9q1qN60bFg:ZdMURRNfvUo:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=y9q1qN60bFg:ZdMURRNfvUo:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=y9q1qN60bFg:ZdMURRNfvUo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=y9q1qN60bFg:ZdMURRNfvUo:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/y9q1qN60bFg" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/knoo0RLXxEs/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - NASA will reactivate a m..." target="_blank">Mothballed telescope gets new life as asteroid hunter</a> <br />
CAPE CANAVERAL, Florida (Reuters) - NASA will reactivate a mothballed infrared space telescope for a three-year mission to search for potentially dangerous asteroids on a collision course with Earth, officials said on Wednesday.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/303d4cb8/sc/21/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=knoo0RLXxEs:ggGYeJlD5Rw:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=knoo0RLXxEs:ggGYeJlD5Rw:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=knoo0RLXxEs:ggGYeJlD5Rw:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=knoo0RLXxEs:ggGYeJlD5Rw:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=knoo0RLXxEs:ggGYeJlD5Rw:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/knoo0RLXxEs" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/I-Li3xrkEoc/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - While NASA considers com..." target="_blank">NASA adds more space launch platforms for sale to private firms</a> <br />
CAPE CANAVERAL, Florida (Reuters) - While NASA considers competing bids to take over a shuttle launch pad at Kennedy Space Center, it added three mobile launch platforms to its list of excess equipment available to private industry, officials said on Tuesday.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/30319c64/sc/21/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/sc/21/rc/1/rc.htm"><img src="http://da.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/sc/21/rc/1/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/sc/21/rc/2/rc.htm"><img src="http://da.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/sc/21/rc/2/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/sc/21/rc/3/rc.htm"><img src="http://da.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/sc/21/rc/3/rc.img" border="0"/></a><br/><br/><a href="http://da.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/a2.htm"><img src="http://da.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/173608137941/u/49/f/654220/c/35217/s/30319c64/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=I-Li3xrkEoc:yZtHJFqUB6k:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=I-Li3xrkEoc:yZtHJFqUB6k:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=I-Li3xrkEoc:yZtHJFqUB6k:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=I-Li3xrkEoc:yZtHJFqUB6k:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=I-Li3xrkEoc:yZtHJFqUB6k:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/I-Li3xrkEoc" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/Ecyq_ucXduc/story01.htm"  title="SINGAPORE (Reuters) - Malaysian entrepreneur Matt Chandran w..." target="_blank">Sliced and diced, digitally: autopsy as a service</a> <br />
SINGAPORE (Reuters) - Malaysian entrepreneur Matt Chandran wants to revive the moribund post-mortem by replacing the scalpel with a scanner and the autopsy slab with a touchscreen computer.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/30303824/sc/21/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=Ecyq_ucXduc:Ttacb-_VIHY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=Ecyq_ucXduc:Ttacb-_VIHY:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=Ecyq_ucXduc:Ttacb-_VIHY:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=Ecyq_ucXduc:Ttacb-_VIHY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=Ecyq_ucXduc:Ttacb-_VIHY:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/Ecyq_ucXduc" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/SIyZrI8hEhw/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - Two Russian cosmonauts f..." target="_blank">Cosmonauts prepare for new lab in record Russian spacewalk</a> <br />
CAPE CANAVERAL, Florida (Reuters) - Two Russian cosmonauts floated outside the International Space Station on Friday to set up power and ethernet cables for a new research laboratory scheduled to arrive in December.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/3009b9ac/sc/3/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/sc/3/rc/1/rc.htm"><img src="http://da.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/sc/3/rc/1/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/sc/3/rc/2/rc.htm"><img src="http://da.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/sc/3/rc/2/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/sc/3/rc/3/rc.htm"><img src="http://da.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/sc/3/rc/3/rc.img" border="0"/></a><br/><br/><a href="http://da.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/a2.htm"><img src="http://da.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/173607988891/u/49/f/654220/c/35217/s/3009b9ac/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=SIyZrI8hEhw:wFVp3MboSW0:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=SIyZrI8hEhw:wFVp3MboSW0:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=SIyZrI8hEhw:wFVp3MboSW0:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=SIyZrI8hEhw:wFVp3MboSW0:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=SIyZrI8hEhw:wFVp3MboSW0:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/SIyZrI8hEhw" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/B7ldWPdyPLs/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - NASA's long-lived Voyage..." target="_blank">Voyager left solar system last year, new research shows</a> <br />
CAPE CANAVERAL, Florida (Reuters) - NASA's long-lived Voyager probe crossed into interstellar space last year, becoming the first man-made object to leave the solar system, new research shows.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/30019341/sc/29/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=B7ldWPdyPLs:qLlkpW4nHh4:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=B7ldWPdyPLs:qLlkpW4nHh4:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=B7ldWPdyPLs:qLlkpW4nHh4:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=B7ldWPdyPLs:qLlkpW4nHh4:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=B7ldWPdyPLs:qLlkpW4nHh4:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/B7ldWPdyPLs" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/NsGE4RTT0Zg/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - The Kepler space telesco..." target="_blank">NASA calls off attempts to fix Kepler space telescope</a> <br />
CAPE CANAVERAL, Florida (Reuters) - The Kepler space telescope's planet-hunting days are over because its broken positioning system cannot be fixed, NASA officials said on Thursday.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/30009211/sc/3/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/sc/3/rc/1/rc.htm"><img src="http://da.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/sc/3/rc/1/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/sc/3/rc/2/rc.htm"><img src="http://da.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/sc/3/rc/2/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/sc/3/rc/3/rc.htm"><img src="http://da.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/sc/3/rc/3/rc.img" border="0"/></a><br/><br/><a href="http://da.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/a2.htm"><img src="http://da.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/173607858797/u/49/f/654220/c/35217/s/30009211/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=NsGE4RTT0Zg:UKhffO2aLRw:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=NsGE4RTT0Zg:UKhffO2aLRw:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=NsGE4RTT0Zg:UKhffO2aLRw:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=NsGE4RTT0Zg:UKhffO2aLRw:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=NsGE4RTT0Zg:UKhffO2aLRw:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/NsGE4RTT0Zg" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/5WOTCqwgGu4/story01.htm"  title="WASHINGTON (Reuters) - The long-tailed, orange-furred, big-e..." target="_blank">Introducing the olinguito, the newest mammal discovery</a> <br />
WASHINGTON (Reuters) - The long-tailed, orange-furred, big-eyed olinguito - said to resemble a cross between a house cat and a teddy bear - is the newest mammal and the first carnivore discovered in the Americas in 35 years, the Smithsonian Institution announced on Thursday.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2ffeb612/sc/6/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=5WOTCqwgGu4:Oe7wdQN4IrU:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=5WOTCqwgGu4:Oe7wdQN4IrU:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=5WOTCqwgGu4:Oe7wdQN4IrU:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=5WOTCqwgGu4:Oe7wdQN4IrU:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=5WOTCqwgGu4:Oe7wdQN4IrU:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/5WOTCqwgGu4" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/SwDaw-aROyM/story01.htm"  title="LONDON (Reuters) - Researchers in Britain have set out the f..." target="_blank">Gene study uncovers origins of many common cancers</a> <br />
LONDON (Reuters) - Researchers in Britain have set out the first comprehensive map of mutational processes behind the development of tumors - work that should in future lead to better ways to treat and prevent a wide range of cancers.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2ff4294a/sc/14/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/sc/14/rc/1/rc.htm"><img src="http://da.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/sc/14/rc/1/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/sc/14/rc/2/rc.htm"><img src="http://da.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/sc/14/rc/2/rc.img" border="0"/></a><br/><a href="http://da.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/sc/14/rc/3/rc.htm"><img src="http://da.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/sc/14/rc/3/rc.img" border="0"/></a><br/><br/><a href="http://da.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/a2.htm"><img src="http://da.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/173607908381/u/49/f/654220/c/35217/s/2ff4294a/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=SwDaw-aROyM:_h9tYJnU67A:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=SwDaw-aROyM:_h9tYJnU67A:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=SwDaw-aROyM:_h9tYJnU67A:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=SwDaw-aROyM:_h9tYJnU67A:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=SwDaw-aROyM:_h9tYJnU67A:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/SwDaw-aROyM" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/PaQJBUoVVm8/story01.htm"  title="SAN FRANCISCO (Reuters) - California billionaire Elon Musk t..." target="_blank">California billionaire unveils futuristic 'Hyperloop' transport</a> <br />
SAN FRANCISCO (Reuters) - California billionaire Elon Musk took the wraps off his vision of a futuristic "Hyperloop" transport system on Monday, proposing to build a solar-powered network of crash-proof capsules that would whisk people from San Francisco to Los Angeles in half an hour.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fe3bba3/sc/21/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=PaQJBUoVVm8:G6KhPaQcSq4:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=PaQJBUoVVm8:G6KhPaQcSq4:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=PaQJBUoVVm8:G6KhPaQcSq4:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=PaQJBUoVVm8:G6KhPaQcSq4:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=PaQJBUoVVm8:G6KhPaQcSq4:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/PaQJBUoVVm8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/VChlAvfhULA/story01.htm"  title="(Reuters) - A U.S. horse association soon will be required t..." target="_blank">U.S. horse association will be ordered to allow clones on registry</a> <br />
(Reuters) - A U.S. horse association soon will be required to add cloned horses and their offspring to its prestigious registry, a federal judge in Texas ruled on Monday.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fe132ca/sc/3/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/173952535602/u/49/f/654220/c/35217/s/2fe132ca/a2.htm"><img src="http://da.feedsportal.com/r/173952535602/u/49/f/654220/c/35217/s/2fe132ca/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/173952535602/u/49/f/654220/c/35217/s/2fe132ca/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=VChlAvfhULA:UfSHi9KZxT8:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=VChlAvfhULA:UfSHi9KZxT8:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=VChlAvfhULA:UfSHi9KZxT8:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=VChlAvfhULA:UfSHi9KZxT8:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=VChlAvfhULA:UfSHi9KZxT8:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/VChlAvfhULA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/tDOgURmQpaU/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - NASA's only identical tw..." target="_blank">Identical twin U.S. astronauts to serve as research subjects</a> <br />
CAPE CANAVERAL, Florida (Reuters) - NASA's only identical twin astronauts are planning to serve as guinea pigs for studies investigating the genetic impacts of long-duration spaceflight.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fca6a11/sc/42/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=tDOgURmQpaU:YBvwHvgar5w:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=tDOgURmQpaU:YBvwHvgar5w:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=tDOgURmQpaU:YBvwHvgar5w:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=tDOgURmQpaU:YBvwHvgar5w:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=tDOgURmQpaU:YBvwHvgar5w:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/tDOgURmQpaU" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/8G9l6-8KtAI/story01.htm"  title="PARIS (Reuters) - When the world's first test-tube beef burg..." target="_blank">Religions asking if test-tube burgers allow them to keep the faith</a> <br />
PARIS (Reuters) - When the world's first test-tube beef burger was cooked and eaten this week, food critics all asked about its taste. For many Jews, Muslims and Hindus, the first question was whether their faith allowed them to try it.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fc4a3da/sc/26/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/173607658082/u/49/f/654220/c/35217/s/2fc4a3da/kg/391/a2.htm"><img src="http://da.feedsportal.com/r/173607658082/u/49/f/654220/c/35217/s/2fc4a3da/kg/391/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/173607658082/u/49/f/654220/c/35217/s/2fc4a3da/kg/391/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=8G9l6-8KtAI:76Kzj6a7ZpY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=8G9l6-8KtAI:76Kzj6a7ZpY:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=8G9l6-8KtAI:76Kzj6a7ZpY:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=8G9l6-8KtAI:76Kzj6a7ZpY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=8G9l6-8KtAI:76Kzj6a7ZpY:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/8G9l6-8KtAI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/FRSdGH9d2hk/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - NASA's only identical tw..." target="_blank">Identical twin U.S. astronauts to serve as research subjects</a> <br />
CAPE CANAVERAL, Florida (Reuters) - NASA's only identical twin astronauts are planning to serve as guinea pigs for studies investigating the genetic impacts of long-duration spaceflight.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fc4c3be/sc/32/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=FRSdGH9d2hk:wkPPFr-n57U:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=FRSdGH9d2hk:wkPPFr-n57U:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=FRSdGH9d2hk:wkPPFr-n57U:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=FRSdGH9d2hk:wkPPFr-n57U:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=FRSdGH9d2hk:wkPPFr-n57U:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/FRSdGH9d2hk" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/03R_aPou8bY/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - Privately owned Space Ex..." target="_blank">SpaceX adds German satellite network to launch calendar</a> <br />
CAPE CANAVERAL, Florida (Reuters) - Privately owned Space Exploration Technologies won a two-flight contract to launch a radar satellite network for Germany, the company announced on Thursday.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fbc1982/sc/5/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/173607699865/u/49/f/654220/c/35217/s/2fbc1982/a2.htm"><img src="http://da.feedsportal.com/r/173607699865/u/49/f/654220/c/35217/s/2fbc1982/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/173607699865/u/49/f/654220/c/35217/s/2fbc1982/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=03R_aPou8bY:PnE0JOGGkF4:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=03R_aPou8bY:PnE0JOGGkF4:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=03R_aPou8bY:PnE0JOGGkF4:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=03R_aPou8bY:PnE0JOGGkF4:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=03R_aPou8bY:PnE0JOGGkF4:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/03R_aPou8bY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/ZpNF9yaFHNQ/story01.htm"  title="CAPE CANAVERAL, Florida (Reuters) - An unmanned Delta 4 rock..." target="_blank">U.S. military satellite, paid for by Australia, launched into orbit</a> <br />
CAPE CANAVERAL, Florida (Reuters) - An unmanned Delta 4 rocket blasted off from Cape Canaveral Air Force Station in Florida on Wednesday carrying a communications satellite for the U.S. military and its partners, including Australia, which paid for the spacecraft and launch services.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fb0fad5/sc/11/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=ZpNF9yaFHNQ:Ci47JcodbRI:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=ZpNF9yaFHNQ:Ci47JcodbRI:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=ZpNF9yaFHNQ:Ci47JcodbRI:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=ZpNF9yaFHNQ:Ci47JcodbRI:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=ZpNF9yaFHNQ:Ci47JcodbRI:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/ZpNF9yaFHNQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/DtOFzdIWtVM/story01.htm"  title="NEW YORK (Reuters) - Information about the most famous and v..." target="_blank">For Henrietta Lacks' famous cells, new and unique protection</a> <br />
NEW YORK (Reuters) - Information about the most famous and valuable human cells in the history of science is about to become a little harder for researchers to get.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fadcd41/sc/14/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/172487805418/u/49/f/654220/c/35217/s/2fadcd41/a2.htm"><img src="http://da.feedsportal.com/r/172487805418/u/49/f/654220/c/35217/s/2fadcd41/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/172487805418/u/49/f/654220/c/35217/s/2fadcd41/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=DtOFzdIWtVM:mEDR6dtGhFg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=DtOFzdIWtVM:mEDR6dtGhFg:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=DtOFzdIWtVM:mEDR6dtGhFg:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=DtOFzdIWtVM:mEDR6dtGhFg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=DtOFzdIWtVM:mEDR6dtGhFg:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/DtOFzdIWtVM" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/8mP5jqSVyXQ/story01.htm"  title="LONDON (Reuters) - Scientists are to create mutant forms of ..." target="_blank">Scientists to make mutant forms of new bird flu to assess risk</a> <br />
LONDON (Reuters) - Scientists are to create mutant forms of the H7N9 bird flu virus that has emerged in China so they can gauge the risk of it becoming a lethal human pandemic.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fadea8e/sc/14/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=8mP5jqSVyXQ:r0xD3gsJpHc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=8mP5jqSVyXQ:r0xD3gsJpHc:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=8mP5jqSVyXQ:r0xD3gsJpHc:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=8mP5jqSVyXQ:r0xD3gsJpHc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=8mP5jqSVyXQ:r0xD3gsJpHc:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/8mP5jqSVyXQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/xuLa8314oeg/story01.htm"  title="BUENOS AIRES (Reuters) - China has approved its first major ..." target="_blank">Exclusive: China OKs entry of first big cargo of Argentine corn</a> <br />
BUENOS AIRES (Reuters) - China has approved its first major shipment of genetically modified Argentine corn, Buenos Aires officials said on Tuesday, signaling an increase in competition for a market long dominated by U.S. exporters.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fa6e3ec/sc/43/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/172487819096/u/49/f/654220/c/35217/s/2fa6e3ec/kg/391/a2.htm"><img src="http://da.feedsportal.com/r/172487819096/u/49/f/654220/c/35217/s/2fa6e3ec/kg/391/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/172487819096/u/49/f/654220/c/35217/s/2fa6e3ec/kg/391/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=xuLa8314oeg:p0_P0Vd142M:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=xuLa8314oeg:p0_P0Vd142M:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=xuLa8314oeg:p0_P0Vd142M:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=xuLa8314oeg:p0_P0Vd142M:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=xuLa8314oeg:p0_P0Vd142M:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/xuLa8314oeg" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/jRhqRIeBzSU/story01.htm"  title="(Reuters) - The NASA rover Curiosity survived its daredevil ..." target="_blank">NASA has high hopes Mars rover's winning streak will continue</a> <br />
(Reuters) - The NASA rover Curiosity survived its daredevil landing on Mars one year ago Tuesday and went on to discover that the planet most like Earth in the solar system could indeed have supported microbial life, the primary goal of the mission.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fa5a0d9/sc/32/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=jRhqRIeBzSU:iATmDAf-A_k:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=jRhqRIeBzSU:iATmDAf-A_k:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=jRhqRIeBzSU:iATmDAf-A_k:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=jRhqRIeBzSU:iATmDAf-A_k:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=jRhqRIeBzSU:iATmDAf-A_k:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/jRhqRIeBzSU" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/ulOV4foLs6o/story01.htm"  title="WASHINGTON (Reuters) - Last year was one of the 10 hottest o..." target="_blank">Signs of new climate 'normal' apparent in hot 2012: report</a> <br />
WASHINGTON (Reuters) - Last year was one of the 10 hottest on record, with sea levels at record highs, Arctic ice at historic lows and extreme weather in various corners of the globe signaling a "new normal," scientists said Tuesday in the 2012 State of the Climate report.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fa40de9/sc/11/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/172487806738/u/49/f/654220/c/35217/s/2fa40de9/a2.htm"><img src="http://da.feedsportal.com/r/172487806738/u/49/f/654220/c/35217/s/2fa40de9/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/172487806738/u/49/f/654220/c/35217/s/2fa40de9/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=ulOV4foLs6o:QBguP46wXJ0:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=ulOV4foLs6o:QBguP46wXJ0:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=ulOV4foLs6o:QBguP46wXJ0:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=ulOV4foLs6o:QBguP46wXJ0:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=ulOV4foLs6o:QBguP46wXJ0:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/ulOV4foLs6o" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/F7ZUXV-NHIU/story01.htm"  title="BUENOS AIRES (Reuters) - China has approved its first shipme..." target="_blank">Exclusive: China approves genetically modified Argentine corn shipment</a> <br />
BUENOS AIRES (Reuters) - China has approved its first shipment of genetically modified Argentine corn, Buenos Aires said on Tuesday, signaling that the Asian country may eventually import GMO crops from other producers like the United States.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2fa40c24/sc/30/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=F7ZUXV-NHIU:HqcMuhS49RI:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=F7ZUXV-NHIU:HqcMuhS49RI:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=F7ZUXV-NHIU:HqcMuhS49RI:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=F7ZUXV-NHIU:HqcMuhS49RI:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=F7ZUXV-NHIU:HqcMuhS49RI:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/F7ZUXV-NHIU" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/cNCM_0fVxFc/story01.htm"  title="LONDON (Reuters) - The world's first laboratory-grown beef b..." target="_blank">First taste of test-tube burger declared 'close to meat'</a> <br />
LONDON (Reuters) - The world's first laboratory-grown beef burger was flipped out of a petri dish and into a frying pan on Monday, with food tasters declaring it tasted "close to meat".<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2f9c3aad/sc/26/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/172487771968/u/49/f/654220/c/35217/s/2f9c3aad/a2.htm"><img src="http://da.feedsportal.com/r/172487771968/u/49/f/654220/c/35217/s/2f9c3aad/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/172487771968/u/49/f/654220/c/35217/s/2f9c3aad/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=cNCM_0fVxFc:0cjPEYRctBY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=cNCM_0fVxFc:0cjPEYRctBY:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=cNCM_0fVxFc:0cjPEYRctBY:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=cNCM_0fVxFc:0cjPEYRctBY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=cNCM_0fVxFc:0cjPEYRctBY:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/cNCM_0fVxFc" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/y5_a7yQ6AWY/story01.htm"  title="(Reuters) - The NASA rover Curiosity survived its daredevil ..." target="_blank">NASA has high hopes Mars rover's winning streak will continue</a> <br />
(Reuters) - The NASA rover Curiosity survived its daredevil landing on Mars one year ago Tuesday and went on to discover that the planet most like Earth in the solar system could indeed have supported microbial life, the primary goal of the mission.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2f98868b/sc/21/mf.gif' border='0'/><br clear='all'/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=y5_a7yQ6AWY:q0y2l1Mtfq0:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=y5_a7yQ6AWY:q0y2l1Mtfq0:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=y5_a7yQ6AWY:q0y2l1Mtfq0:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=y5_a7yQ6AWY:q0y2l1Mtfq0:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=y5_a7yQ6AWY:q0y2l1Mtfq0:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/y5_a7yQ6AWY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://feeds.reuters.com/~r/reuters/scienceNews/~3/H8fRy3EcwGQ/story01.htm"  title="LONDON (Reuters) - A corner of west London will see culinary..." target="_blank">Scientists to cook world's first in-vitro beef burger</a> <br />
LONDON (Reuters) - A corner of west London will see culinary and scientific history made on Monday when scientists cook and serve up the world's first lab-grown beef burger.<img width='1' height='1' src='http://reuters.us.feedsportal.com/c/35217/f/654220/s/2f93d031/sc/32/mf.gif' border='0'/><br clear='all'/><br/><br/><a href="http://da.feedsportal.com/r/172487753609/u/49/f/654220/c/35217/s/2f93d031/a2.htm"><img src="http://da.feedsportal.com/r/172487753609/u/49/f/654220/c/35217/s/2f93d031/a2.img" border="0"/></a><img width="1" height="1" src="http://pi.feedsportal.com/r/172487753609/u/49/f/654220/c/35217/s/2f93d031/a2t.img" border="0"/><div class="feedflare"> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=H8fRy3EcwGQ:ARkmL7aztnc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=H8fRy3EcwGQ:ARkmL7aztnc:F7zBnMyn0Lo"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=H8fRy3EcwGQ:ARkmL7aztnc:F7zBnMyn0Lo" border="0"></img></a> <a href="http://feeds.reuters.com/~ff/reuters/scienceNews?a=H8fRy3EcwGQ:ARkmL7aztnc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/reuters/scienceNews?i=H8fRy3EcwGQ:ARkmL7aztnc:V_sGLiPBpWU" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/reuters/scienceNews/~4/H8fRy3EcwGQ" height="1" width="1"/>
</li>
</ul></div>

</li>
</ul>
	</div>
</div>
</body>
</html>
