<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link href="fdstyle.css" rel="stylesheet" type="text/css"></head>
<body>
<div class="title">The Golf Blog</div>
<div id="content-block">

<div>
<ul>
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-adam-scott-shoots-66-to-win-barclays-besting-tiger-woods-justin-rose-gary-woodland.html' target="_blank">The Golf Blog: Adam Scott shoots 66 to win Barclays, besting Tiger Woods, Justin Rose, Gary Woodland</a><br />
Scott wins Barclays with bogey-free round http://t.co/NQJNiNI01x &mdash; Scotty Dog Golf Ltd (@scottydoggolf) August 25, 2013 The Golf Blog says: Adam Scott finished with a 66 to go -11 for the tourney and then waited as the other golfers couldn&#8217;t match his score. Tiger Woods almost pulled off a miracle birdie-birdie-birdie finish, despite back spasms that derailed his game midround. The final putt fell a few inches short. The 54 hole leader Gary Woodland had two decent looks for birdie on the last two holes, but he couldn&#8217;t make a putt all day. Phil Mickelson, who shot a 65, came very close to matching -11, but his bomb on 17 lipped out and he bogeyed 18. Phil correctly predicted, however, that the winning score would be -11. Click here for video highlights
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-pres-clinton-tweets-rory-mcilroy-as-clinton-works-on-short-game-with-niece-and-nephew.html' target="_blank">The Golf Blog: Pres. Clinton tweets Rory McIlroy as Clinton works on short game with niece and nephew</a><br />
Hey @McIlroyRory &#8211; I&#39;m working on my short game. (Only a few strokes behind my niece Fiona and nephew Simon.) pic.twitter.com/8xUbkkYVKS &mdash; Bill Clinton (@billclinton) August 22, 2013
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-video-of-scott-brown-eagling-no-16-at-barclays-after-his-drive-bounces-off-rocks-onto-green.html' target="_blank">The Golf Blog: Video of Scott Brown eagling No. 16 at Barclays after his drive bounces off rocks onto green</a><br />
The Golf Blog says: Scott Brown got a really lucky bounce off the rocks near the bridge in the water hazard on No. 16 at the Barclays Tournament. The ball bounced onto the green for a near tap in eagle. One of the funkiest and luckiest eagles in recent memory. Click here for the video
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-kevin-stadler-leads-barclays-7-camillo-villegas-tied-for-second.html' target="_blank">The Golf Blog: Kevin Stadler leads Barclays (-7), Camillo Villegas tied for second</a><br />
.@CamiloVillegasR on his opening-round 65: &quot;I had three breakfasts, two lunches and a whole bunch of birdies.&quot; pic.twitter.com/VNpX6Oto1l &mdash; TaylorMade Golf (@TaylorMadeGolf) August 23, 2013 The Golf Blog says: The Barclays brought out some names of promising golfers who have sort of fizzled in their careers. Kevin Stadler leads at -7, while Camillo Villegas (who led much of the day and has abandoned his Spiderman routine), Henrik Stenson, and Ryan Palmer are one back. Tiger Woods is at -4, tied with a bunch of guys. Click here for the Leaderboard
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-video-tour-of-rory-mcilroys-home-in-florida.html' target="_blank">The Golf Blog: Video tour of Rory McIlroy’s home in Florida</a><br />
The Golf Blog says: Rory McIlroy&#8217;s home in Florida is modern and sleek, with water views.
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-photos-of-pres-obama-playing-golf-on-marthas-vineyard-during-vacation.html' target="_blank">The Golf Blog: Photos of Pres. Obama playing golf on Martha’s Vineyard during vacation</a><br />
The Golf Blog says: Pres. Obama is on vacation with his family in Martha&#8217;s Vineyard. He&#8217;s been playing a lot of golf. Wash Post has photos here.
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-more-dufnering-from-the-golf-channel-crew.html' target="_blank">The Golf Blog: More Dufnering from the Golf Channel crew</a><br />
Looking lazy kids! RT .@GolfChannel&#39;s Live From crew Dufnering in honor of Jason Dufner&#39;s win at Oak Hill CC. pic.twitter.com/emg5oEnoPi &mdash; Kelly Tilghman (@KellyTilghmanGC) August 12, 2013
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-charlie-rose-norah-odonnell-michael-strahan-dufnering-with-jason-dufner.html' target="_blank">The Golf Blog: Charlie Rose, Norah O’Donnell, Michael Strahan Dufnering with Jason Dufner</a><br />
Norah O&#39;Donnell, Jason Dufner and Charlie Rose #Dufnering on @CBSThisMorning. That is all. pic.twitter.com/5s1I80KP8n &mdash; PGA.COM (@PGA_com) August 13, 2013 @KellyandMichael @PGATour @JasonDufner How&#39;s this?#Dufnering pic.twitter.com/T9sl3epAme &mdash; Michael Strahan (@michaelstrahan) August 12, 2013
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-tiger-woods-no-longer-ahead-of-jack-nicklauss-pace-of-18-majors.html' target="_blank">The Golf Blog: Tiger Woods no longer ahead of Jack Nicklaus’s pace of 18 majors</a><br />
The Golf Blog says: For most of Tiger Woods&#8217; career, he&#8217;s been ahead of the pace that Jack Nicklaus set in winning 18 majors. Well, finally, after a 5 year drought in the majors and another disappointing showing this year, especially at yesterday&#8217;s PGA Championship, Tiger has fallen back to even with Jack&#8217;s pace. Both had 14 majors at age 37. Jack won his 15th at age 38, the same age that Tiger will turn this December. That means that Tiger now will have to win a major in 2014 in order not to fall behind Jack&#8217;s pace. Just a few years ago, Tiger looked to be a lock to beat Jack&#8217;s record. Now, it&#8217;s not so clear he will even tie 18 majors. The competition is definitely stiffer, and Tiger seems to have lost his magic or mo-jo at the majors after the scandal that unraveled his marriage. If Tiger doesn&#8217;t win a major next year, that may be it for his quest to beat Jack. For a chart comparing Tiger versus Jack in majors, click here. John Daly still thinks Tiger will do it, but we&#8217;re not so sure Tiger will be playing at age 65: Tiger has 112 majors to play from now til he&#39;s 65 only needs 5 I say yes he will break Jacks record #GRIPITANDRIPITYALL &mdash; John Daly (@PGA_JohnDaly) August 12, 2013 ESPN: Tiger &#39;didn&#39;t hit it good enough&#39; to compete: Another major championship season passed Sunday with&#8230; http://t.co/lu1vpU7oUV #golf &mdash; Golf tweets (@_golf) August 11, 2013
<li><a href='http://www.thegolfblog.com/2013/08/the-golf-blog-jason-dufner-wins-pga-championship-shooting-final-round-68-10.html' target="_blank">The Golf Blog: Jason Dufner wins PGA Championship shooting final round 68 (-10)</a><br />
Jason Dufner shoots two-under in the final round and is your 2013 PGA Championship winner! #PGAChamp pic.twitter.com/5tM6ajXMUt &mdash; Bleacher Report (@BleacherReport) August 11, 2013 The Golf Blog says: Jason Dufner redeemed himself from his last round meltdown 2 years ago at the PGA Championship. This time around, Dufner was steady all day and stuffed three very close approach shots for kick-in birdies. Jason put himself to win with the record-setting 63 on Friday. Jim Furyk put up a decent fight on Sunday (-71) but couldn&#8217;t close the gap once Dufner took the lead away. Which photo of Dufner do you find to be the most memorable? Let me guess&#8230; http://t.co/Y2aJNFwv8I &mdash; Kelly Tilghman (@KellyTilghmanGC) August 12, 2013
</ul></div>


</div>
</body>
</html>