<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link href="daily.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body>
<div id="column2">
	<div id="col2_text" class="scroll">
	<ul></li>
<div class="rss-box">
<p class="rss-title"><a class="rss-title" href="http://www.cnn.com/SHOWBIZ/index.html?eref=rss_showbiz" target="_blank">CNN.com - Entertainment</a><br /><span class="rss-item">CNN.com delivers up-to-the-minute news and information on the latest top stories, weather, entertainment, politics and more.</span></p>
<ul class="rss-items">
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/63xjkwhfWrM/index.html"  title="It looks like a new generation may get to experience the hig..." target="_blank">Ben Stiller bringing 'Reality Bites' to NBC</a> <br />
It looks like a new generation may get to experience the highs and lows of Lelaina Pierce, Troy Dyer, and the rest of the gang as a comedy series based on the seminal 1994 flick "Reality Bites" has gotten a script order at NBC.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=63xjkwhfWrM:Jt6uvk-MkmY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=63xjkwhfWrM:Jt6uvk-MkmY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/63xjkwhfWrM" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/H1KumMWCVhY/index.html"  title="..." target="_blank">Photos: Coming out in Hollywood</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=H1KumMWCVhY:RasOziXf1Wc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=H1KumMWCVhY:RasOziXf1Wc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/H1KumMWCVhY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/qEGs0xAhTfs/index.html"  title="..." target="_blank">Memorable VMA moments</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:kn6Sw0XAGlc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:kn6Sw0XAGlc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:kn6Sw0XAGlc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=qEGs0xAhTfs:kn6Sw0XAGlc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:kn6Sw0XAGlc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:kn6Sw0XAGlc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=qEGs0xAhTfs:kn6Sw0XAGlc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/qEGs0xAhTfs" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/Nkb22aiCMJw/fod-will-ferrell-zach-galifianakis-debate-kids.funny-or-die.html"  title="Will Ferrell and Zach Galifianakis take on elementary school..." target="_blank">Ferrell, Galifianakis battle kids</a> <br />
Will Ferrell and Zach Galifianakis take on elementary school students in a battle of wits. For more go to Funnyordie.com.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nkb22aiCMJw:rKLRJ7oOO08:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nkb22aiCMJw:rKLRJ7oOO08:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nkb22aiCMJw:rKLRJ7oOO08:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=Nkb22aiCMJw:rKLRJ7oOO08:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nkb22aiCMJw:rKLRJ7oOO08:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nkb22aiCMJw:rKLRJ7oOO08:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=Nkb22aiCMJw:rKLRJ7oOO08:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/Nkb22aiCMJw" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/6EWjFOAY9jQ/index.html"  title="Kanye West has been called many things, but these days the b..." target="_blank">Kanye West shows off baby North</a> <br />
Kanye West has been called many things, but these days the best description -- according to him -- is family man.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=6EWjFOAY9jQ:9lIzUtiLsow:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=6EWjFOAY9jQ:9lIzUtiLsow:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=6EWjFOAY9jQ:9lIzUtiLsow:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=6EWjFOAY9jQ:9lIzUtiLsow:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=6EWjFOAY9jQ:9lIzUtiLsow:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=6EWjFOAY9jQ:9lIzUtiLsow:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=6EWjFOAY9jQ:9lIzUtiLsow:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/6EWjFOAY9jQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/I9s3ar96rW4/index.html"  title="Back in 2004, Edgar Wright's brilliantly subversive zombie c..." target="_blank">Review: 'The World's End'</a> <br />
Back in 2004, Edgar Wright's brilliantly subversive zombie comedy, "Shaun of the Dead," introduced American audiences to Simon Pegg and Nick Frost.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=I9s3ar96rW4:ekaWz7rJgjY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=I9s3ar96rW4:ekaWz7rJgjY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=I9s3ar96rW4:ekaWz7rJgjY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=I9s3ar96rW4:ekaWz7rJgjY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=I9s3ar96rW4:ekaWz7rJgjY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=I9s3ar96rW4:ekaWz7rJgjY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=I9s3ar96rW4:ekaWz7rJgjY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/I9s3ar96rW4" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/rx0hKjWKXtA/spc-talk-asia-billy-corgan-smashing-pumpkins.cnn.html"  title="Smashing Pumpkins singer Billy Corgan on why rock music need..." target="_blank">Corgan: God future of rock</a> <br />
Smashing Pumpkins singer Billy Corgan on why rock music needs God and how suffering isn't good for business.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=rx0hKjWKXtA:t7hWxqc88nY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=rx0hKjWKXtA:t7hWxqc88nY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=rx0hKjWKXtA:t7hWxqc88nY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=rx0hKjWKXtA:t7hWxqc88nY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=rx0hKjWKXtA:t7hWxqc88nY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=rx0hKjWKXtA:t7hWxqc88nY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=rx0hKjWKXtA:t7hWxqc88nY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/rx0hKjWKXtA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/5h99KSNIhBE/index.html"  title="The last time Ben Affleck played a superhero, the world crie..." target="_blank">Affleck as Batman might not be so bad</a> <br />
The last time Ben Affleck played a superhero, the world cried.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=5h99KSNIhBE:ULi7oKEAt-E:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=5h99KSNIhBE:ULi7oKEAt-E:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=5h99KSNIhBE:ULi7oKEAt-E:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=5h99KSNIhBE:ULi7oKEAt-E:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=5h99KSNIhBE:ULi7oKEAt-E:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=5h99KSNIhBE:ULi7oKEAt-E:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=5h99KSNIhBE:ULi7oKEAt-E:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/5h99KSNIhBE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/Zbfp5nYUofo/index.html"  title="Ben Affleck will play Batman in the sequel to the Superman m..." target="_blank">Affleck to play Batman in Superman sequel</a> <br />
Ben Affleck will play Batman in the sequel to the Superman movie "Man of Steel," Warner Bros. said Thursday.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Zbfp5nYUofo:6NvALvP-9CE:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Zbfp5nYUofo:6NvALvP-9CE:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Zbfp5nYUofo:6NvALvP-9CE:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=Zbfp5nYUofo:6NvALvP-9CE:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Zbfp5nYUofo:6NvALvP-9CE:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Zbfp5nYUofo:6NvALvP-9CE:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=Zbfp5nYUofo:6NvALvP-9CE:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/Zbfp5nYUofo" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/qEGs0xAhTfs/index.html"  title="..." target="_blank">Memorable VMA moments</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:Jt49v9cBiig:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:Jt49v9cBiig:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:Jt49v9cBiig:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=qEGs0xAhTfs:Jt49v9cBiig:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:Jt49v9cBiig:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=qEGs0xAhTfs:Jt49v9cBiig:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=qEGs0xAhTfs:Jt49v9cBiig:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/qEGs0xAhTfs" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/H1KumMWCVhY/index.html"  title="..." target="_blank">Photos: Coming out in Hollywood</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=H1KumMWCVhY:RasOziXf1Wc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=H1KumMWCVhY:RasOziXf1Wc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=H1KumMWCVhY:RasOziXf1Wc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/H1KumMWCVhY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/j_GvCNadhck/index.html"  title="The guessing game of who will star in the adaptation of &quo..." target="_blank">More 'Fifty Shades' casting rumors</a> <br />
The guessing game of who will star in the adaptation of "Fifty Shades of Grey" ? the erotic novel by E L James that has sold over 70 million copies worldwide ? continues!<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=j_GvCNadhck:_GJ0zEtPCpY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=j_GvCNadhck:_GJ0zEtPCpY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=j_GvCNadhck:_GJ0zEtPCpY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=j_GvCNadhck:_GJ0zEtPCpY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=j_GvCNadhck:_GJ0zEtPCpY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=j_GvCNadhck:_GJ0zEtPCpY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=j_GvCNadhck:_GJ0zEtPCpY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/j_GvCNadhck" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/63xjkwhfWrM/index.html"  title="It looks like a new generation may get to experience the hig..." target="_blank">Ben Stiller bringing 'Reality Bites' to NBC</a> <br />
It looks like a new generation may get to experience the highs and lows of Lelaina Pierce, Troy Dyer, and the rest of the gang as a comedy series based on the seminal 1994 flick "Reality Bites" has gotten a script order at NBC.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=63xjkwhfWrM:Jt6uvk-MkmY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=63xjkwhfWrM:Jt6uvk-MkmY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=63xjkwhfWrM:Jt6uvk-MkmY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/63xjkwhfWrM" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/VkHLWrUyhz0/index.html"  title="MIchael Jackson and Dr. Conrad Murray tried to recruit an an..." target="_blank">Anesthesiologist: Jackson recruited me</a> <br />
MIchael Jackson and Dr. Conrad Murray tried to recruit an anesthesiologist to join them on his comeback tour, according to testimony in the AEG Live wrongful death trial.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=VkHLWrUyhz0:8WraKlWuyho:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=VkHLWrUyhz0:8WraKlWuyho:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=VkHLWrUyhz0:8WraKlWuyho:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=VkHLWrUyhz0:8WraKlWuyho:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=VkHLWrUyhz0:8WraKlWuyho:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=VkHLWrUyhz0:8WraKlWuyho:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=VkHLWrUyhz0:8WraKlWuyho:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/VkHLWrUyhz0" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/0rxp8_P6p-8/index.html"  title="The Calling's lead singer, Alex Band, told police he was abd..." target="_blank">The Calling singer: I was abducted</a> <br />
The Calling's lead singer, Alex Band, told police he was abducted, beaten and robbed Sunday, just hours before his group announced a comeback effort.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=0rxp8_P6p-8:iS9yrdl7CGw:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=0rxp8_P6p-8:iS9yrdl7CGw:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=0rxp8_P6p-8:iS9yrdl7CGw:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=0rxp8_P6p-8:iS9yrdl7CGw:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=0rxp8_P6p-8:iS9yrdl7CGw:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=0rxp8_P6p-8:iS9yrdl7CGw:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=0rxp8_P6p-8:iS9yrdl7CGw:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/0rxp8_P6p-8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/TSsF4USDjeY/index.html"  title="Jazz great George Duke, a visionary keyboardist, producer, c..." target="_blank">Music industry mourns George Duke</a> <br />
Jazz great George Duke, a visionary keyboardist, producer, composer and arranger, has died in Los Angeles. He was 67.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=TSsF4USDjeY:zqakRYbxeeU:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=TSsF4USDjeY:zqakRYbxeeU:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=TSsF4USDjeY:zqakRYbxeeU:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=TSsF4USDjeY:zqakRYbxeeU:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=TSsF4USDjeY:zqakRYbxeeU:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=TSsF4USDjeY:zqakRYbxeeU:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=TSsF4USDjeY:zqakRYbxeeU:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/TSsF4USDjeY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/7Uq5xG8PqcQ/index.html"  title="If someone in your house is mad for One Direction, get ready..." target="_blank">Summer concert tickets scarce, expensive</a> <br />
If someone in your house is mad for One Direction, get ready to lay out some serious cash.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=7Uq5xG8PqcQ:q2v37hp6z-c:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=7Uq5xG8PqcQ:q2v37hp6z-c:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=7Uq5xG8PqcQ:q2v37hp6z-c:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=7Uq5xG8PqcQ:q2v37hp6z-c:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=7Uq5xG8PqcQ:q2v37hp6z-c:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=7Uq5xG8PqcQ:q2v37hp6z-c:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=7Uq5xG8PqcQ:q2v37hp6z-c:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/7Uq5xG8PqcQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/pVLuJQysaYM/index.html"  title="..." target="_blank">'N SYNC reuniting at VMAs?</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=pVLuJQysaYM:sbqXb4Z9Gsg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=pVLuJQysaYM:sbqXb4Z9Gsg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=pVLuJQysaYM:sbqXb4Z9Gsg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=pVLuJQysaYM:sbqXb4Z9Gsg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=pVLuJQysaYM:sbqXb4Z9Gsg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=pVLuJQysaYM:sbqXb4Z9Gsg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=pVLuJQysaYM:sbqXb4Z9Gsg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/pVLuJQysaYM" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/nIr86T2B1B8/index.html"  title="He commanded fear and respect as a hitman/fixer on &quot;Bre..." target="_blank">'Breaking Bad' vet joins 'Community'</a> <br />
He commanded fear and respect as a hitman/fixer on "Breaking Bad," and now he will command fear and respect as... a community college professor. Jonathan Banks will appear in 11 episodes of "Community"'s fifth season, EW has learned.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nIr86T2B1B8:4jB2tQjRlIo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nIr86T2B1B8:4jB2tQjRlIo:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nIr86T2B1B8:4jB2tQjRlIo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=nIr86T2B1B8:4jB2tQjRlIo:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nIr86T2B1B8:4jB2tQjRlIo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nIr86T2B1B8:4jB2tQjRlIo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=nIr86T2B1B8:4jB2tQjRlIo:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/nIr86T2B1B8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/UvwPE4mttgM/index.html"  title="Kris Jenner worked her magic ? and familial connections, of ..." target="_blank">Kanye stops by Jenner's talk show</a> <br />
Kris Jenner worked her magic ? and familial connections, of course ? to land an interview with the typically media-shy Kanye West, the father of her granddaughter North. Kanye stopped by the set of Kris on Monday to tape an hour-long interview that will air this week.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UvwPE4mttgM:vLboZwDaxec:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UvwPE4mttgM:vLboZwDaxec:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UvwPE4mttgM:vLboZwDaxec:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=UvwPE4mttgM:vLboZwDaxec:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UvwPE4mttgM:vLboZwDaxec:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UvwPE4mttgM:vLboZwDaxec:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=UvwPE4mttgM:vLboZwDaxec:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/UvwPE4mttgM" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/wnB4NdcI7jY/index.html"  title="Sunday night marked the first time we've heard from Lindsay ..." target="_blank">When Lohan met Oprah we learned...</a> <br />
Sunday night marked the first time we've heard from Lindsay Lohan since her most recent stint in rehab, in her eagerly awaited pow wow with Oprah Winfrey.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wnB4NdcI7jY:TnsMatf209U:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wnB4NdcI7jY:TnsMatf209U:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wnB4NdcI7jY:TnsMatf209U:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=wnB4NdcI7jY:TnsMatf209U:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wnB4NdcI7jY:TnsMatf209U:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wnB4NdcI7jY:TnsMatf209U:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=wnB4NdcI7jY:TnsMatf209U:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/wnB4NdcI7jY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/nnTnp7P2Vec/index.html"  title="With all of the fake sharks flying around TV lately, some vi..." target="_blank">Discovery defends shark special</a> <br />
With all of the fake sharks flying around TV lately, some viewers wish the Discovery Channel would stick just to the facts.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nnTnp7P2Vec:n_Wk09Mew_o:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nnTnp7P2Vec:n_Wk09Mew_o:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nnTnp7P2Vec:n_Wk09Mew_o:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=nnTnp7P2Vec:n_Wk09Mew_o:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nnTnp7P2Vec:n_Wk09Mew_o:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=nnTnp7P2Vec:n_Wk09Mew_o:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=nnTnp7P2Vec:n_Wk09Mew_o:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/nnTnp7P2Vec" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/oNvYzgEHxrI/index.html"  title="Two residents of Pawnee will soon bid farewell: Rob Lowe and..." target="_blank">Two to leave 'Parks and Rec'</a> <br />
Two residents of Pawnee will soon bid farewell: Rob Lowe and Rashida Jones are exiting "Parks and Recreation" during the show's sixth season, EW has confirmed. (Buzzfeed first reported the news.) The pair will depart about halfway through the season, in the 13th episode.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=oNvYzgEHxrI:GtwXpb6908g:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=oNvYzgEHxrI:GtwXpb6908g:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=oNvYzgEHxrI:GtwXpb6908g:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=oNvYzgEHxrI:GtwXpb6908g:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=oNvYzgEHxrI:GtwXpb6908g:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=oNvYzgEHxrI:GtwXpb6908g:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=oNvYzgEHxrI:GtwXpb6908g:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/oNvYzgEHxrI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/x2p8ZogrElw/index.html"  title="..." target="_blank">Celebrity hoaxes: It's just not true</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=x2p8ZogrElw:VKZBm8UaXQg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=x2p8ZogrElw:VKZBm8UaXQg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=x2p8ZogrElw:VKZBm8UaXQg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=x2p8ZogrElw:VKZBm8UaXQg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=x2p8ZogrElw:VKZBm8UaXQg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=x2p8ZogrElw:VKZBm8UaXQg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=x2p8ZogrElw:VKZBm8UaXQg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/x2p8ZogrElw" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/BSChQABJoPw/index.html"  title="..." target="_blank">Sexy celebs in their 50s</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BSChQABJoPw:qGp4AQSR2sE:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BSChQABJoPw:qGp4AQSR2sE:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BSChQABJoPw:qGp4AQSR2sE:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=BSChQABJoPw:qGp4AQSR2sE:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BSChQABJoPw:qGp4AQSR2sE:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BSChQABJoPw:qGp4AQSR2sE:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=BSChQABJoPw:qGp4AQSR2sE:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/BSChQABJoPw" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/mOL7OmQ82aI/index.html"  title="..." target="_blank">Photos: Hollywood takes on porn</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=mOL7OmQ82aI:KXgG-78XN-M:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=mOL7OmQ82aI:KXgG-78XN-M:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=mOL7OmQ82aI:KXgG-78XN-M:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=mOL7OmQ82aI:KXgG-78XN-M:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=mOL7OmQ82aI:KXgG-78XN-M:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=mOL7OmQ82aI:KXgG-78XN-M:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=mOL7OmQ82aI:KXgG-78XN-M:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/mOL7OmQ82aI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/ECA_RP0-Pk4/index.html"  title="..." target="_blank">Photos: Celebs with the star gene</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=ECA_RP0-Pk4:cTQKQ4cWQ2Q:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=ECA_RP0-Pk4:cTQKQ4cWQ2Q:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=ECA_RP0-Pk4:cTQKQ4cWQ2Q:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=ECA_RP0-Pk4:cTQKQ4cWQ2Q:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=ECA_RP0-Pk4:cTQKQ4cWQ2Q:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=ECA_RP0-Pk4:cTQKQ4cWQ2Q:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=ECA_RP0-Pk4:cTQKQ4cWQ2Q:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/ECA_RP0-Pk4" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/UGLO23-LxSc/index.html"  title="..." target="_blank">Stars clash with paparazzi</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UGLO23-LxSc:3VzqmE5VPnQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UGLO23-LxSc:3VzqmE5VPnQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UGLO23-LxSc:3VzqmE5VPnQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=UGLO23-LxSc:3VzqmE5VPnQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UGLO23-LxSc:3VzqmE5VPnQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=UGLO23-LxSc:3VzqmE5VPnQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=UGLO23-LxSc:3VzqmE5VPnQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/UGLO23-LxSc" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/JxhfnTZ81EU/index.html"  title="..." target="_blank">'Real Housewives' with real legal troubles</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=JxhfnTZ81EU:jzw1J1ODLHQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=JxhfnTZ81EU:jzw1J1ODLHQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=JxhfnTZ81EU:jzw1J1ODLHQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=JxhfnTZ81EU:jzw1J1ODLHQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=JxhfnTZ81EU:jzw1J1ODLHQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=JxhfnTZ81EU:jzw1J1ODLHQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=JxhfnTZ81EU:jzw1J1ODLHQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/JxhfnTZ81EU" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/udONqQOnT_Y/vo-strombo-aisha-tyler-outsiders.cnn.html"  title="Actress and author Aisha Tyler tells George Stroumboulopoulo..." target="_blank">Aisha Tyler feels like an outsider</a> <br />
Actress and author Aisha Tyler tells George Stroumboulopoulos that she wants to be a voice for nerds and outsiders.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=udONqQOnT_Y:Mj_iPDFlXVQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=udONqQOnT_Y:Mj_iPDFlXVQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=udONqQOnT_Y:Mj_iPDFlXVQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=udONqQOnT_Y:Mj_iPDFlXVQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=udONqQOnT_Y:Mj_iPDFlXVQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=udONqQOnT_Y:Mj_iPDFlXVQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=udONqQOnT_Y:Mj_iPDFlXVQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/udONqQOnT_Y" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/4mNVT_iIsQ4/str-stromboulopolos-walking-dead-kirkman.cnn.html"  title="&quot;The Walking Dead&quot; creator Robert Kirkman explains..." target="_blank">'Walking Dead' creator on show's success</a> <br />
"The Walking Dead" creator Robert Kirkman explains why the show resonates. See the full interview Friday at 11 p.m. ET.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4mNVT_iIsQ4:4Y0JPK4bjDo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4mNVT_iIsQ4:4Y0JPK4bjDo:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4mNVT_iIsQ4:4Y0JPK4bjDo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=4mNVT_iIsQ4:4Y0JPK4bjDo:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4mNVT_iIsQ4:4Y0JPK4bjDo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4mNVT_iIsQ4:4Y0JPK4bjDo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=4mNVT_iIsQ4:4Y0JPK4bjDo:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/4mNVT_iIsQ4" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/4InXiBi8Yw8/str-stroumboulopoulos-keanu-reeves-motorcycle.stroumboulopoulos.html"  title="Strombo visits Keanu Reeves' Arch Motorcycles where the acto..." target="_blank">George and Keanu's excellent adventure</a> <br />
Strombo visits Keanu Reeves' Arch Motorcycles where the actor reveals a previously unknown side of himself.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4InXiBi8Yw8:Q_mUMKLxfww:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4InXiBi8Yw8:Q_mUMKLxfww:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4InXiBi8Yw8:Q_mUMKLxfww:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=4InXiBi8Yw8:Q_mUMKLxfww:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4InXiBi8Yw8:Q_mUMKLxfww:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=4InXiBi8Yw8:Q_mUMKLxfww:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=4InXiBi8Yw8:Q_mUMKLxfww:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/4InXiBi8Yw8" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/PI9imxLByJA/index.html"  title="The mother of Michael Jackson's two oldest children broke do..." target="_blank">Mom: Paris 'has no life' since dad's death</a> <br />
The mother of Michael Jackson's two oldest children broke down in tears when she was asked to describe the impact of the singer's death on his daughter Paris.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=PI9imxLByJA:HI3kLEEQ7AE:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=PI9imxLByJA:HI3kLEEQ7AE:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=PI9imxLByJA:HI3kLEEQ7AE:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=PI9imxLByJA:HI3kLEEQ7AE:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=PI9imxLByJA:HI3kLEEQ7AE:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=PI9imxLByJA:HI3kLEEQ7AE:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=PI9imxLByJA:HI3kLEEQ7AE:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/PI9imxLByJA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/2TR5O_jiEJQ/index.html"  title="The doctor convicted in Michael Jackson's death did not appe..." target="_blank">Expert: Promoter didn't pressure Jackson's doc</a> <br />
The doctor convicted in Michael Jackson's death did not appeared to be pressured by AEG Live, an expert hired by the concert promoter testified Friday.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=2TR5O_jiEJQ:fGCsKvevoNc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=2TR5O_jiEJQ:fGCsKvevoNc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=2TR5O_jiEJQ:fGCsKvevoNc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=2TR5O_jiEJQ:fGCsKvevoNc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=2TR5O_jiEJQ:fGCsKvevoNc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=2TR5O_jiEJQ:fGCsKvevoNc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=2TR5O_jiEJQ:fGCsKvevoNc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/2TR5O_jiEJQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/wmlwGvFDbPI/index.html"  title="Two German doctors treated Michael Jackson's insomnia with p..." target="_blank">Ex-wife: Docs competed to give Jackson meds</a> <br />
Two German doctors treated Michael Jackson's insomnia with propofol 12 years before he died from an overdose of the surgical anesthetic, his former wife testified Wednesday.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wmlwGvFDbPI:BZMhu0FZZ4w:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wmlwGvFDbPI:BZMhu0FZZ4w:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wmlwGvFDbPI:BZMhu0FZZ4w:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=wmlwGvFDbPI:BZMhu0FZZ4w:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wmlwGvFDbPI:BZMhu0FZZ4w:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=wmlwGvFDbPI:BZMhu0FZZ4w:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=wmlwGvFDbPI:BZMhu0FZZ4w:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/wmlwGvFDbPI" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/IxMze4fJTyE/index.html"  title="Debbie Rowe has said she doesn't want fame. But as Michael J..." target="_blank">Who is Debbie Rowe?</a> <br />
Debbie Rowe has said she doesn't want fame. But as Michael Jackson's ex-wife and the mother of two of his children, she may now be thrust into the center of the latest high-profile trial related to the superstar's death.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=IxMze4fJTyE:VXrR_4_-ZvQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=IxMze4fJTyE:VXrR_4_-ZvQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=IxMze4fJTyE:VXrR_4_-ZvQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=IxMze4fJTyE:VXrR_4_-ZvQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=IxMze4fJTyE:VXrR_4_-ZvQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=IxMze4fJTyE:VXrR_4_-ZvQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=IxMze4fJTyE:VXrR_4_-ZvQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/IxMze4fJTyE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/BaPKzcK1ZRg/index.html"  title="A lawyer for Michael Jackson's estate gave an entertainment ..." target="_blank">Jackson's consultant helps defense in trial</a> <br />
A lawyer for Michael Jackson's estate gave an entertainment industry consultant permission to help AEG Live in its defense of the wrongful death lawsuit filed by the pop singer's mother, the expert testified.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BaPKzcK1ZRg:112zah6CWzg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BaPKzcK1ZRg:112zah6CWzg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BaPKzcK1ZRg:112zah6CWzg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=BaPKzcK1ZRg:112zah6CWzg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BaPKzcK1ZRg:112zah6CWzg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=BaPKzcK1ZRg:112zah6CWzg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=BaPKzcK1ZRg:112zah6CWzg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/BaPKzcK1ZRg" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/Vg0IU0iuEJY/index.html"  title="..." target="_blank">Photos: Who's who in the Jackson trial</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Vg0IU0iuEJY:234441j90xg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Vg0IU0iuEJY:234441j90xg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Vg0IU0iuEJY:234441j90xg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=Vg0IU0iuEJY:234441j90xg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Vg0IU0iuEJY:234441j90xg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Vg0IU0iuEJY:234441j90xg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=Vg0IU0iuEJY:234441j90xg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/Vg0IU0iuEJY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/Nh6F1pxOIFE/index.html"  title="&quot;Lee Daniels' The Butler&quot; follows the life of Ceci..." target="_blank">10 secrets of 'The Butler'</a> <br />
"Lee Daniels' The Butler" follows the life of Cecil Gaines, an African-American butler who serves in the White House under eight presidencies. Inspired by real-life butler Eugene Allen, Gaines (played by Forest Whitaker) witnesses the rise of the civil rights movement, the Rev. Martin Luther King Jr.'s assassination, Vietnam and the election of the Barack Obama, all while simultaneously balancing the highs and lows of his family life.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nh6F1pxOIFE:ZrmxVvmWL70:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nh6F1pxOIFE:ZrmxVvmWL70:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nh6F1pxOIFE:ZrmxVvmWL70:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=Nh6F1pxOIFE:ZrmxVvmWL70:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nh6F1pxOIFE:ZrmxVvmWL70:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=Nh6F1pxOIFE:ZrmxVvmWL70:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=Nh6F1pxOIFE:ZrmxVvmWL70:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/Nh6F1pxOIFE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/G0p4Ei0CDFQ/index.html"  title="Matthew McConaughey lost 40 pounds for December's &quot;Dall..." target="_blank">Becoming Steve Jobs</a> <br />
Matthew McConaughey lost 40 pounds for December's "Dallas Buyers Club," and Matt Damon worked out for four hours a day to get ripped for "Elysium."<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=G0p4Ei0CDFQ:v8JPMtE2GyI:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=G0p4Ei0CDFQ:v8JPMtE2GyI:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=G0p4Ei0CDFQ:v8JPMtE2GyI:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=G0p4Ei0CDFQ:v8JPMtE2GyI:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=G0p4Ei0CDFQ:v8JPMtE2GyI:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=G0p4Ei0CDFQ:v8JPMtE2GyI:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=G0p4Ei0CDFQ:v8JPMtE2GyI:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/G0p4Ei0CDFQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_showbiz/~3/B5fyxzy09gc/index.html"  title="This year's summer movie season is all about asking &quot;Wh..." target="_blank">Summer movie guide: Top 20 picks</a> <br />
This year's summer movie season is all about asking "What if?"<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=B5fyxzy09gc:tb7W7C2OTPc:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=B5fyxzy09gc:tb7W7C2OTPc:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=B5fyxzy09gc:tb7W7C2OTPc:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=B5fyxzy09gc:tb7W7C2OTPc:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=B5fyxzy09gc:tb7W7C2OTPc:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_showbiz?a=B5fyxzy09gc:tb7W7C2OTPc:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_showbiz?i=B5fyxzy09gc:tb7W7C2OTPc:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_showbiz/~4/B5fyxzy09gc" height="1" width="1"/>
</li>
</ul></div>
</li>
</ul>

	</div>
</div>
</body>
</html>
