<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="style.css" rel="stylesheet" type="text/css">
</head>

<body style="background: url(images/kidding_img_12.jpg) no-repeat fixed">
<div class="linkheader">Topix | Business News</div>
<div class="mainfeed scroll">
<div class="rss-box">
<ul class="rss-items">
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/straight-sets-hewitt-flashes-old-self-in-upset-victory-over-raonic?fromrss=1"  title="Though he is nearly 10 years removed from his last Grand Sla..." target="_blank">Straight Sets: Hewitt Flashes Old Self in Upset Victory Over Raonic</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 17:18:07 GMT</span><br />
Though he is nearly 10 years removed from his last Grand Slam title, Lleyton Hewitt pushed his way back into the business end of a major tournament, reaching the second week of the 2012 Australian Open with a surprising four-set win over the Canadian Milos Raonic.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/millennials-divorce-marriage?fromrss=1"  title="In Millennials Divorce Marriage we looked at the facts gener..." target="_blank">Millennials Divorce Marriage</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 15:08:22 GMT</span><br />
In Millennials Divorce Marriage we looked at the facts generated by the Millennial lifestyle and discovered that love, sex, and power are being unbundled.A We also saw that men are becoming increasingly un-necessary and the nuclear family is likewise changing drastically.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/rendezvous-blog-red-faces-over-vienna-culture-bid?fromrss=1"  title="The winter season of Vienna balls is at its glittering heigh..." target="_blank">Rendezvous Blog: Red Faces Over Vienna Culture Bid</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 15:08:21 GMT</span><br />
The winter season of Vienna balls is at its glittering height but there were red faces in the Austrian capital this weekend over a bid to have them officially designated as an international cultural treasure.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/online-classes-bring-new-revenue-for-urban-farmers?fromrss=1"  title="The tech industry has brought about many recent innovations ..." target="_blank">Online Classes Bring New Revenue for Urban Farmers</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 15:08:20 GMT</span><br />
The tech industry has brought about many recent innovations in business, but perhaps one of the most important for those in food+tech is the trend toward monetizing knowledge.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/investors-should-be-wary-of-google-analysts?fromrss=1"  title="Set against this backdrop, investors may want to stay away f..." target="_blank">Investors Should be Wary of Google: Analysts</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 14:03:29 GMT</span><br />
Set against this backdrop, investors may want to stay away from the bellwether for the time being, analysts say.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/ibooks2-not-a-silver-bullet-for-publishers?fromrss=1"  title="Apple 's iBooks2 platform has received some breathless cover..." target="_blank">iBooks2: Not a silver bullet for publishers</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 14:03:28 GMT</span><br />
Apple 's iBooks2 platform has received some breathless coverage since it was announced on Thursday.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/ipad-iphone-gain-momentum-with-businesses?fromrss=1"  title="Apple 's devices are appearing more frequently in business, ..." target="_blank">IPad, IPhone Gain Momentum with Businesses</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 14:03:27 GMT</span><br />
Apple 's devices are appearing more frequently in business, pointing to early success for the company's push into the corporate sector.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/ge-sells-solar-to-wind-farms?fromrss=1"  title="As renewable energy deals ago, General Electric 's announcem..." target="_blank">GE Sells Solar to Wind Farms</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 13:07:28 GMT</span><br />
As renewable energy deals ago, General Electric 's announcement this week that it would supply 23 megawatts of solar panels for an Illinois photovoltaic farm was rather small change.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/think-outside-the-cube-why-the-office-isnt-the-best-workspace?fromrss=1"  title="If you were to land on Earth as an outsider and observe the ..." target="_blank">Think Outside the Cube: Why the Office Isn't the Best Workspace</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 13:07:27 GMT</span><br />
If you were to land on Earth as an outsider and observe the way we work, you would assume the following: that we are our most creative, prolific selves between 9 AM and 5 PM, that group meetings are bastions of productivity, and that the best way to accelerate thought is by confining it inside walls.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/branding-lessons-from-angelina-jolie?fromrss=1"  title="Angelina Jolie has been in the headlines recently as the wri..." target="_blank">Branding Lessons from Angelina Jolie</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 13:07:26 GMT</span><br />
Angelina Jolie has been in the headlines recently as the writer and director of In the Land of Blood and Honey , a serious look at the Bosnian war.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/google-kills-photo-sharing-service-picnik-plus-more-products?fromrss=1"  title="In the wake of yesterday's earnings miss, Google has announc..." target="_blank">Google Kills Photo-Sharing Service Picnik, Plus More Products</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 12:02:26 GMT</span><br />
In the wake of yesterday's earnings miss, Google has announced it will shutter online photo sharing service Picnik , which it acquired in 2010, plus a handful of other products.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/are-mayors-asking-washington-for-the-wrong-thing?fromrss=1"  title="Each year, as the halls of the Capitol open anew, the United..." target="_blank">Are Mayors Asking Washington for the Wrong Thing?</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 12:02:25 GMT</span><br />
Each year, as the halls of the Capitol open anew, the United States Conference of Mayors hauls in the nation's city executives to convene.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/ge-4q-profit-falls-sales-miss-estimates?fromrss=1"  title="General Electric Co. said Friday its fourth-quarter earnings..." target="_blank">GE 4Q profit falls, sales miss estimates</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 12:02:24 GMT</span><br />
General Electric Co. said Friday its fourth-quarter earnings fell 18 percent as revenue declined after it sold its stake in the NBC network.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/sears-shares-surge-back-to-life?fromrss=1"  title="In just nine trading days, Sears stock has surged almost 80%..." target="_blank">Sears Shares Surge Back to Life</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 10:57:35 GMT</span><br />
In just nine trading days, Sears stock has surged almost 80% as Wall Street reconsiders its view on the embattled retailer and traders ponder majority owner Edward Lampert's next move.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/dare-to-become-a-great-investor?fromrss=1"  title="Stock market volatility makes people nervous. They associate..." target="_blank">Dare To Become A Great Investor</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 10:57:34 GMT</span><br />
Stock market volatility makes people nervous. They associate big price swings with instability and risk.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/citi-stock-still-worth-35-despite-disappointing-quarter?fromrss=1"  title="Citigroup released disappointing results for the fourth quar..." target="_blank">Citi Stock Still Worth $35 Despite Disappointing Quarter</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 10:57:33 GMT</span><br />
Citigroup released disappointing results for the fourth quarter of 2011 on Tuesday, as evidenced by the fact that the bank's shares tanked well over 8% over trading during the day.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/stocks-open-mixed-driven-by-earnings-debt-talks?fromrss=1"  title="Microsoft and IBM drove the Dow Jones industrial average up ..." target="_blank">Stocks open mixed, driven by earnings, debt talks</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 09:57:45 GMT</span><br />
Microsoft and IBM drove the Dow Jones industrial average up in Friday morning trading, after the established tech giants reported stronger earnings than analysts had expected.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/feds-to-finance-small-nuclear-reactor-designs?fromrss=1"  title="The U.S. Department of Energy on Friday announced a plan to ..." target="_blank">Feds To Finance Small Nuclear Reactor Designs</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 09:57:44 GMT</span><br />
The U.S. Department of Energy on Friday announced a plan to support the design of the so-called "small modular nuclear reactors" and popularize their use for power generation.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/greek-debt-talks-in-day-3?fromrss=1"  title="Charles Dallara, left, and and Jean Lemiere, representatives..." target="_blank">Greek debt talks in day 3</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 09:57:43 GMT</span><br />
Charles Dallara, left, and and Jean Lemiere, representatives for Greece's private bondholders leave after a meeting with Greek Prime Minister Lucas Papademos and Finance Minister Evangelos Venizelos in Athens, late Thursday.
</li>
<li class="rss-item"><a class="rss-item" href="http://www.topix.com/business/2012/01/hollywood-regroups-after-losing-battle-over-anti-piracy-bills?fromrss=1"  title="After a full-on counterattack by the tech industry, the ente..." target="_blank">Hollywood regroups after losing battle over anti-piracy bills</a> <br />
<span class="rss-date">Sat, 21 Jan 2012 08:57:47 GMT</span><br />
After a full-on counterattack by the tech industry, the entertainment industry must conduct PR damage control and convince tech-savvy Americans that it isn't the bad guy.
</li>
</ul></div>

</div>
</body>
</html>
