<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="style.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body style="background: url(images/ssn-img-info-bkgd.jpg) no-repeat">
<h4>Central America Trips</h4>
<div id="info" class="scroll">
<div>
<ul>
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2145'>Central American Journey</a><br />
Spend a month in Central America, from Costa Rica to Mexico. Spend days marvelling at the cultures, scenery, Mayan ruins, bird life and beaches that offer up a dynamic mix of adventure. Remember that"mañana"is not just Spanish for tomorrow, but also the local philosophy for taking it easy.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2136'>Costa Rica Adventure</a><br />
Costa Rica is one of the most biologically diverse countries in the world - a true Garden of Eden. Let Costa Rica mesmerize you as we explore its rainforests, rushing rivers, pristine beaches and towering volcanoes. This trip combines world-class highlights with more remote areas for an authentic adventure experience.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2165'>Mayan Sun</a><br />
Find paradise somewhere between the blazing Yucatan sun and the cool Guatemalan highlands on this 17-day odyssey. From active volcanoes and remote jungle to fascinating ruins and beaches, this tour has something for every type of adventurer.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3167'>EDUCATIONAL - Marine Biology, Maya Archaeology, & Natural History</a><br />
This Belize program is ideal for teachers and students of biology, history, Spanish, and Social Studies. It focuses on three areas 1) Marine biology; 2) Maya archaeology; and 3) Tropical forest ecology. The program is highly instructive and includes both classroom & field work. Instruction is provided by highly trained individuals with graduate degrees. HIGHLIGHTS INCLUDE: 1) Black Howler Monkey Behavior Training & Data Collection; 2) Ancient Maya Farming Techniques & Traditional Cooking Techniques; 3) Reef Survey & Fish Behavior Obervation; 4) Community Development Project; and 5) Educational Archaeological Treasure Hunt. ***** ONE INSTRUCTOR FREE OF CHARGE FOR EVERY 10 PAYING STUDENTS *****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2132'>Mayan Adventure</a><br />
A 3-week pilgrimage through Mexico, Belize and Guatemala. This all-encompassing adventure combines the beauty of the highlands, the mystery of great Mayan sites and the crystalline waters and beaches of the Caribbean.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2139'>Costa Rica Quest</a><br />
An action-packed tour of some of Costa Ricas must-see highlights, with amazing wildlife, intense volcanic landscapes and superb Pacific beaches. If you are a traveller with limited time and a desire to explore Costa Rica's lush interior, this is the tour for you.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip1996'>Lamanai & New River Safari by Royal Mayan Tours</a><br />
This tour package is an archaeological/historical and wildlife tour wrapped up in one.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip1997'>Snorkling Adventure by Royal Mayan Tours</a><br />
Go island hopping towards snorkeling sites. Snorkel along barrier reef in water 3-30 ft. deep. Walking tour of island.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2111'>Tikal One Day</a><br />
Fly round trip from Guatemala to Flores and spend a spectacular day in the beautiful Tikal museum and park.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2113'>ATITLAN AND CHICHICASTENANGO</a><br />
Arguably the most beautiful lake in the world, Atitlan owes its grandeur to its enormous size and spectacular, volcanic setting. Lake Atitlan was formed when a volcanic caldera depleted of its magma. Three stately volcanoes, Atitlan, Toliman and San Pedro rise gracefully from its southern shore, their perfect cones reflected in the azure mirror of the lake. Chichicastenango is home to what is surely the most colorful native market in North and Central America. Market days are Sundays and Thursdays, and draw not only the K'iche' Maya of the surrounding region, but vendors from all over Guatemala, representing many of Guatemala's linguistic groups such as Mam, Ixil, Kaqchikel and others, each hawking his or her products in a riotous cacophony of color, dialects and costumes, smoke, and smells.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2276'>Tikal 2 days</a><br />
In this tour you will be able to visit Tikal and Ixpanpajul Park
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2832'>iExplore Panama Gold</a><br />
Panama reminds us of a promising actress. There&#039;s no denying she has the potential to hit the big time: rain forest, mountains, historical sites, palm trees, beaches, coral reefs, deep-sea fishing, Spanish-colonial architecture and unusual Amerindian cultures. And she has the Panama Canal, a one-of-a-kind tourist attraction for cruise-ship passengers and those who opt for smaller boat tours. With a few breaks, Panama could be a star.Panama is a narrow country of mountains and rain forests - it&#039;s only 50 mi/80 km across at the narrowest point (along the canal) and 120 mi/193 km at its widest. It forms a land bridge between the two American continents, but it does not lie north-south. It actually stretches east and west in an S shape. That is why, in Panama, it&#039;s possible to see the sun rise over the Pacific and set in the Caribbean. The country&#039;s shape also means that a boat moving from the Caribbean to the Pacific leaves the canal farther to the east than it enters.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2927'>iExplore Belize Gold</a><br />
For much of its history, Belize has been a wild place, attractive to the adventurous and the hardy - pirates, loggers, settlers who could carve a place to live from the forbidding jungle. It was only a matter of time until adventurous eco-travelers found this corner of Central America. Today, Belize has become a rising star among those seeking active and educational vacations. They go to see its vast expanses of rain forest, rich collection of birds and animals, long stretch of coral reef and plentiful Maya ruins.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2933'>iExplore Costa Rica Gold</a><br />
Giving Eden a run for its money, Costa Rica is one of the most biologically rich countries in the world. Its rainforests are literally teeming with wildlife, making it an animal-lover&#039;s paradise. On your visit to the misty Monteverde Cloud Forest, you may see the brilliantly plumed resplendent quetzal, considered one of the most beautiful birds in the world.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2934'>iExplore Costa Rica Silver</a><br />
Costa Rica is practically synonymous with eco-tourism - travel that incorporates education about the environment and promotes preservation of natural resources. Costa Rica boasts a large number of national parks and nature preserves with a rich array of birds, mammals, reptiles and rain-forest plants. Here, you will explore the incredible beauty of one of the worlds most biologically diverse countries  where unique varieties of plants and animals thrive and multiply.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2935'>iExplore Costa Rica Silver - Active</a><br />
Costa Rica is practically synonymous with eco-tourism - travel that incorporates education about the environment and promotes preservation of natural resources. The country has a large number of national parks and nature preserves that boast a rich array of birds, mammals, reptiles and rain-forest plants. The variety of birds, in particular, is astounding: Some 850 species are packed into a relatively small area. Approximately 25% of the country&#039;s land has been set aside in protected areas, earning Costa Rica a reputation as an environmentally sensitive country and leader in ecological conservation.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2965'>iExplore Guatemala Gold</a><br />
When you list its assets, Guatemala seems to be one of the best travel destinations in Central America: the stunning Maya ruins at Tikal, the well-preserved colonial city of Antigua, a vibrant indigenous culture, active volcanoes, highland lakes, exotic wildlife.One of the best of the best is Tikal: the greatest of the ruins left from the age of the Maya, whose accomplishments in the fields of medicine, mathematics and astronomy are a source of national pride and universal awe. We think Tikal is one of the most impressive ruins in the world (in a class with places like Machu Picchu in Peru or the Valley of the Kings in Egypt). Frankly, Tikal alone is worth the trip.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2966'>iExplore Guatemala, Honduras&amp;Belize Gold</a><br />
When you list its assets, Guatemala seems to be one of the best travel destinations in Central America: the stunning Maya ruins at Tikal, the well-preserved colonial city of Antigua, a vibrant indigenous culture, active volcanoes, highland lakes, exotic wildlife.Honduras offers an array of different vacation experiences - perhaps more than any other country in Central America. It can be a resort-oriented getaway for divers and snorkelers (in the Bay Islands), a showplace of Mayan archaeological treasures (at Copan), or an eco- and adventure-travel playground (on the north coast and in the rain forest).Belize has become a rising star among those seeking active and educational vacations. They go to see its vast expanses of rain forest, rich collection of birds and animals, long stretch of coral reef and plentiful Maya ruins. And despite a weak international travel market, tourism has replaced agriculture as the largest industry in Belize, generating almost one-fifth of the country&#039;s GDP.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2968'>iExplore Honduras Silver</a><br />
Honduras offers an array of different vacation experiences - perhaps more than any other country in Central America. It can be a resort-oriented getaway for divers and snorkelers (in the Bay Islands), a showplace of Mayan archaeological treasures (at Copan), or an eco- and adventure-travel playground (on the north coast and in the rain forest).The country is defined by a 460-mi/735-km Caribbean coastline in the north and a small Pacific coastline in the south. It has land borders with Guatemala, El Salvador and Nicaragua. Two mountain ranges covered by pine forests and creased with fast-moving rivers run through the center of Honduras, giving way to low flatlands and tropical vegetation along both coasts. The Bay Islands, off the northern coast, are typical of the Caribbean - white-sand beaches, crystal waters and teeming tropical reefs. Rainfall is heaviest on the northern shore and in the eastern part of the country.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3183'>Best of Belize II</a><br />
BELIZEAN SHORES CONDO - You've found a great affordable high end PRIVATE ecotour featuring the highlights of Belize. You'll explore & see inland areas [tropical forests & ancient Maya ruins] as well as the islands [over 170 mile barrier reef]. This Eco Trip features  aside from 'giving back' to the local residents & attempting to minimally impact the environment - 1) behind-the-scenes of the LAMANAI Archaeological Project, 2) New River Safari(s), 3) British Sugar Mill & 16th Century Spanish Church, 4) Ancient Maya Cooking & Farming Techniques, 5) Cave's Branch Cave Tubing, 6)Canoeing, 7) Birding, 8) Tropical Education Center, 9) Indian Church Village Artisans, 10) UNESCO World Heritage Reef, 11) Beach & Pool Time, 12) Snorkeling, Diving..in Belize you'll EXPLORE, LAUGH, LEARN, SWIM, RELAX, &.Look at Your Life from a Different Perspective!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2123'>Full Belize</a><br />
3 weeks covering the best of coastal Belize and cultural Guatemala. Explore the cayes by kayak and enjoy inland Mayan ruins and wildlife.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2124'>Hummingbird Highway</a><br />
A popular 2-week tour for good reasonits a great combination of beach, ruins, wildlife, activity and culture in Belize and Guatemala.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3020'>Maya Archaeology Focus - TIKAL & LAMANAI</a><br />
TIKAL & LAMANAI - You'll explore the most important ancient Maya city-states in Belize as well as Tikal in Guatemala. 'Behind-the-scenes', offering the latest discoveries by research projects permitted by Belize's Institute of Archaeology (http://wwww.nichBelize.org), a special focus on the site of Lamanai which boasts one of the longest occupational histories of alll Maya city-states. You'll have access to the Lamanai collection that other visitors do not see. **** 13 Activities & 5 Major Maya Sites ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3191'>BELIZE - Beach, Snorkel, Dive - TURNEFFE LODGE & ATOLL</a><br />
TURNEFFE ATOLL - Swim, explore, & relax while you enjoy Belize's only UNESCO World Heritage Site, a barrier reef that covers over 180 miles and is second only to the Great Barrier Reef. This trip finds you on the unique island of Turneffe, adjacent to Turneffe Atoll off the northern Belize coast. You will enjoy an AFFORDABLE high end eco vacation that focuses on the barrier reef but also offers a chance to see the ancient Maya ruins of Lamanai. OPTIONS INCLUDE: 1) staying a few nights in the Lamanai area to experience Indian Church Village, tropical forest birding, & Black Howler Monkeys. TRIP HIGHLIGHTS: 1) Daily snorkel or dive adventures, 2) Private island get-away, & 3) Many other extras **** FREE GIFT - Reef Fish Identification by Humann & DeLoach ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4302'>AMAZING GUATEMALA</a><br />
Seven extraordinary days visiting the most traditional tour spots in the country: Antigua, Atitlan, Tikal, Yaxha and Chichicastenango. You will be amazed by this places.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2112'>Lake Atitlan and Panajachel</a><br />
Arguably the most beautiful lake in the world, Atitlan owes its grandeur to its enormous size and spectacular, volcanic setting. Lake Atitlan was formed when a volcanic caldera depleted of its magma. Three stately volcanoes, Atitlan, Toliman and San Pedro rise gracefully from its southern shore, their perfect cones reflected in the azure mirror of the lake. Weaving made and worn by the Maya-Tzutujil and Cakchiquel women who live around the lake are some of the most beautiful in Guatemala, and many of the men also wear traditional, hand-woven clothing.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2143'>Panama Experience</a><br />
The best of southern Costa Rica and northern Panama, featuring an abundance of both natural and manmade wonders. As Panama is still off most travellers radars, its the perfect place for a genuine discovery experience, with plenty of activities ranging from fantastic bird watching to exhilarating white water rafting.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3172'>Colonial Guatemala</a><br />
Three extraordinary days visiting the most traditional tour spots in the country: Antigua, Atitlan and Chichicastenango. You will be amazed by this places. We add an amazing tour to tikal for 2 days
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3016'>Best of Belize I</a><br />
You've found a great affordable high end PRIVATE ecotour featuring the highlights of Belize. You'll explore & see inland areas [tropical forests & ancient Maya ruins] as well as the islands [over 170 mile barrier reef]. This Eco Trip features  aside from 'giving back' to the local residents & attempting to minimally impact the environment - 1) behind-the-scenes of the LAMANAI Archaeological Project, 2) New River Safari(s), 3) British Sugar Mill & 16th Century Spanish Church, 4) Ancient Maya Cooking & Farming Techniques, 5) Cave's Branch Cave Tubing, 6)Canoeing, 7) Birding, 8) Tropical Education Center, 9) Indian Church Village Artisans, 10) UNESCO World Heritage Reef, 11) Beach & Pool Time, 12) Snorkeling, Diving..in Belize you'll EXPLORE, LAUGH, LEARN, SWIM, RELAX, &.Look at Your Life from a Different Perspective! **** FREE GIFT w/ each trip purchase - L. Beletsky's Belize Field Guide & a Guide to Belize Ruins ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3017'>Birding Focus</a><br />
As you may be aware there are over 540 species of birds that call Belize home. The entire United States has only about 200 more species! The tropical birding in Belize is varied and diverse, with many species being found only in this area including some toucans, cotingas, and motmots. To be honest the birds in the tropics are some of the most beautifully decorated birds in the world and you can see them with us! Belize as you know has a varied geography including the relatively low elevation Maya Mountains, the pine ridge, the broadleaf forest, savannah areas, riverine systems, and the cayes. The majority of these areas will be visited on Beyond Touring trips. **** FREE GIFT w/ each trip purchase - L. Jones's, Belize Bird Field Guide ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3168'>BELIZE - Beach, Snorkel, Dive - SUNBREEZE</a><br />
SUNBREEZE - Swim, explore, & relax while you enjoy Belize's only UNESCO World Heritage Site, a barrier reef that covers over 180 miles and is second only to the Great Barrier Reef. This trip finds you on the unique island of AMBERGRIS CAYE (San Pedro), on the northern Belize coast. You will enjoy an AFFORDABLE high end eco vacation that focuses on the barrier reef but also offers a chance to see the ancient Maya ruins of Lamanai. OPTIONS INCLUDE: 1) staying a few nights in the Lamanai area to experience Indian Church Village, tropical forest birding, & Black Howler Monkeys. TRIP HIGHLIGHTS: 1) Daily snorkel or dive adventures, 2) Private island get-away, 3) Golf cart rental to explore San Pedro, & 4) Many other extras **** FREE GIFT - Reef Fish Identification by Humann & DeLoach ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2134'>Mayan Explorer</a><br />
The Mayan world straddles several modern-day countries, but a shared culture and history give modern Maya an identity beyond borders. From ancient ruins in the Yucatan to colonial Chiapas and colourful traditional Guatemalan markets, immerse yourself in the ancient and the thriving on this journey through the land of the Maya.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2167'>Nicaragua - Volcanoes&Islands</a><br />
Adventure travel off the beaten track and away from the pack. A friendly country with great highlights ranging from islands and deserted beaches to volcano climbs and colonial cathedrals.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2137'>Costa Rica Explorer</a><br />
An action-packed exploration with rafting, horseback riding and zip-lining as options in between the bird spotting, hiking and volcanoes. From the Pacific to the Caribbean beaches this stunning 2-week tour embodies some of the best that Costa Rica has to offer.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2142'>Volcano Trail</a><br />
Take the road less travelled on this expedition through Guatemala, Honduras, Nicaragua and Costa Rica. This is one of our most exciting trips, even for the seasoned traveller, filled with breathtaking scenery, from crystal blue ocean teeming with marine life to tropical rainforest alive with jungle melodies.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3015'>Best of Costa Rica</a><br />
We have designed this 12-day / 11-night honeymoon package to feature many of the Costa Rica highlights to combine lush rainforest, volcanoes, hot springs, mystic Cloud Forest, spending wildlife by the Pacific Ocean ending in an unforgettable 2 day Class IV White Water rafting expedition. A wonderful blend of adventure, nature and luxury accommodations in four of the countrys most visited regions.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2125'>Kayak Belize</a><br />
One of the original G.A.P Adventures tours! Enjoy a week of island-hopping off the coast of Belize and the second largest barrier reef in the world. An ultimate sea-kayaking tour with plenty of independent time to relax.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3189'>Birding Focus II - TIKAL, LAMANAI, BARRIER REEF</a><br />
TIKAL & LAMANAI - As you may be aware there are over 540 species of birds that call Belize home. The entire United States has only about 200 more species! The tropical birding in Belize is varied and diverse, with many species being found only in this area including some toucans, cotingas, and motmots. To be honest the birds in the tropics are some of the most beautifully decorated birds in the world and you can see them with us! Belize as you know has a varied geography including the relatively low elevation Maya Mountains, the pine ridge, the broadleaf forest, savannah areas, riverine systems, and the cayes. The majority of these areas will be visited on Beyond Touring trips. **** FREE GIFT w/ each trip purchase - L. Jones's, Belize Bird Field Guide ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3185'>Maya Archaeology Focus - CARACOL & LAMANAI</a><br />
CARACOL & LAMANAI - You'll explore the most important ancient Maya city-states in Belize, including the largest, Caracol. 'Behind-the-scenes', offering the latest discoveries by research projects permitted by Belize's Institute of Archaeology (http://wwww.nichBelize.org), a special focus on the site of Lamanai which boasts one of the longest occupational histories of alll Maya city-states. You'll have access to the Lamanai collection that other visitors do not see. **** 13 Activities & 5 Major Maya Sites ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4341'>DISCOVER GUATEMALA</a><br />
Six extraordinary days visiting the most traditional tour spots in the country: Antigua, Atitlan, Tikal, Yaxha and Chichicastenango. You will be amazed by these incredible places where you can appreciate the Mayan culture. This trip is composed by the following activities: Archaeology, Culture, Ecotourism and Adventure.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3188'>Maya Archaeology Focus - CERROS & LAMANAI</a><br />
CERROS & LAMANAI - You'll explore the most important ancient Maya city-states in Belize. 'Behind-the-scenes', offering the latest discoveries by research projects permitted by Belize's Institute of Archaeology (http://wwww.nichBelize.org), a special focus on the site of Lamanai which boasts one of the longest occupational histories of alll Maya city-states. You'll have access to the Lamanai collection that other visitors do not see. **** 12 Activities & 4 Major Maya Sites ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3190'>BELIZE - Beach, Snorkel, Dive - BELIZEAN SHORES</a><br />
BELIZEAN SHORES - Swim, explore, & relax while you enjoy Belize's only UNESCO World Heritage Site, a barrier reef that covers over 180 miles and is second only to the Great Barrier Reef. This trip finds you on the unique island of AMBERGRIS CAYE (San Pedro), on the northern Belize coast. You will enjoy an AFFORDABLE high end eco vacation that focuses on the barrier reef but also offers a chance to see the ancient Maya ruins of Lamanai. OPTIONS INCLUDE: 1) staying a few nights in the Lamanai area to experience Indian Church Village, tropical forest birding, & Black Howler Monkeys. TRIP HIGHLIGHTS: 1) Daily snorkel or dive adventures, 2) Private island get-away, 3) Golf cart rental to explore San Pedro, & 4) Many other extras **** FREE GIFT - Reef Fish Identification by Humann & DeLoach ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3184'>Best of Belize III</a><br />
VICTORIA HOUSE, San Pedro - You've found a great affordable high end PRIVATE ecotour featuring the highlights of Belize. You'll explore & see inland areas [tropical forests & ancient Maya ruins] as well as the islands [over 170 mile barrier reef]. This Eco Trip features  aside from 'giving back' to the local residents & attempting to minimally impact the environment - 1) behind-the-scenes of the LAMANAI Archaeological Project, 2) New River Safari(s), 3) British Sugar Mill & 16th Century Spanish Church, 4) Ancient Maya Cooking & Farming Techniques, 5) Cave's Branch Cave Tubing, 6)Canoeing, 7) Birding, 8) Tropical Education Center, 9) Indian Church Village Artisans, 10) UNESCO World Heritage Reef, 11) Beach & Pool Time, 12) Snorkeling, Diving..in Belize you'll EXPLORE, LAUGH, LEARN, SWIM, RELAX, &.Look at Your Life from a Different Perspective! **** FREE GIFT w/ each trip purchase - L. Beletsky's Belize Field Guide & a Guide to Belize Ruins ****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2135'>Costa Rica Hike, Bike&Raft</a><br />
Costa Rica is one of the worlds great adventure destinations. This 15-day adrenaline-filled journey has you hiking some of its highest peaks, biking down a Volcano and whitewater rafting the Reventazon and Pacuare Rivers.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2140'>Guatemala Encompassed</a><br />
Take in all the Guatemalan highlights, from Mayan ruins and beautiful beaches, to the lakes, volcanoes and caves that make this country famous. Add to this the most traditional and varied indigenous population in Central America and its most charming colonial city, and you can see why many consider Guatemala the most fascinating destination in the Americas.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2281'>Cloud Forests, Rainforests, Volcanoes and Beaches of Costa Rica</a><br />
Resplendent Quetzals, Howler monkeys, Toucans, and the unmistakable call of the Bellbird, the sights and sounds of this trip will not soon be forgotten. Included is a white-water rafting adventure on the Sarapiqui, during two days in the lowland rainforest. Enjoy a dip in the thermal pools near the fiery-topped Arenal Volcano and enjoy cocktails as we watch fiery lava tumble down the slopes of the volcano. Travel on horseback from the Arenal area, through the rainforest and up to the Monteverde Cloud Forest. A highlight is sure to be our time at the Monteverde Cloud Forest Reserve with Debra Hamilton De Roser of the Costa Rican Conservation Foundation. Debra devotes her life to studying the bird species of this rare and mystical Cloud Forest habitat and will share with us her insights into the unique and various creatures found here, especially the Three-wattled bellbird. We end our adventure in the exclusive Villa Caletas overlooking the Pacific Ocean and the Nicoya Peninsula.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2282'>Nicaragua: Colonial Cities, Volcanoes, Sea Turtles and so much more.</a><br />
Nicaragua is the hot, new destination - safe and friendly - Nicaragua is being called the "next Costa Rica." This tour combines culture and nature, and Nicaragua has plenty of both! Importantly, Nicaragua has enjoyed fifteen years of peace and stability, since the free and democratic elections of 1990, and democracy has been the norm for over 15 years now. Nicaragua is the largest country in Central America, still has large areas of forest and plentiful wildlife, indeed, Nicaragua devotes over 18 percent of its land area to Parks and Reserves.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2283'>Rainforest, Reef and Ruins of Belize</a><br />
with Lascelle Tillet, Belize Audubon Society. This tiny country has so much to discover! We will travel by motor launch through riverine forest on the New River to visit the ancient Maya ruins of Lamanai. We shall paddle canoes on the Macal River as we spend three nights in the exquisite thatched cabanas of the exclusive Chaa Creek Resort. We will ride horses through the rain forest. We will track the elusive big cats in the Worlds only Jaguar Preserve. We will end our land adventure with snorkeling or scuba adventures on the largest Barrier Reef in the Northern Hemisphere. Our guide for this ecotour will be Lascelle Tillet, a Board Member of the Belize Audubon Society, the organization responsible for managing most of Belizes National Parks for the Government of Belize.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3023'>Costa Rica Los Angeles Cloud Forest EcoSpa</a><br />
Up in the mild highlands of Costa Rica on a former hacienda a delicious vacation retreat awaits you. During the day, explore the beautiful cloud forests and the surrounding quaint towns, then relax in the spa. Private, exclusive, deluxe, and with a wedding chapel on the site, this is a wonderful location for special occasions. Package includes 2 nights accommodation, return transfers from/to San Jose, breakfasts, 1 guided nature walk or birding walk. Can combine with other trips and can also add additional nights for $129 pp. See our Organic Gourmet and Eco-Spa Tour as well.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip1974'>90-10 Embera Indian Village</a><br />
Meet embera natives just as you would encounter them on the dense jungles of Darién, by the Panama-Colombia border, but at Chagres National Park. Apreciate their cultural adaptation to rain forest and the beauty of its surroundings. An unforgettable memory !
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip1675'>100-25 Jungle and Cloud Forest Adventure ( 7 nights)</a><br />
In one week get a taste of Panama, paddling its best rivers and exploring its surroundings. From the pristine jungle of Chagres National Park to the cloud forest of Chiriqui Highland.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2170'>Go Costa Rica</a><br />
Hitting some of Costa Rica's best natural highlights, this 15 day tour emphasizes nature, with ample opportunities for hiking, horseback riding and swimming.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4359'>100-10 The Chagres Challenge ( 2 nights)</a><br />
Our leading destination: Chagres National Park. You will explore the pristine jungles of Chagres National Park and get to known campesinos and embera indians. It includes 4x4 transportation, hiking, rafting/kayaking, and more.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3192'>EDUCATIONAL - Maya Archaeology, Culture, & Natural History</a><br />
This Belize program is ideal for teachers and students of biology, history, Spanish, and Social Studies. It focuses on three areas 1) Cross-culture experiences; 2) Maya archaeology; and 3) Tropical forest ecology. The program is highly instructive and includes both classroom & field work. Instruction is provided by highly trained individuals with graduate degrees. HIGHLIGHTS INCLUDE: 1) Black Howler Monkey Behavior Training & Data Collection; 2) Ancient Maya Farming Techniques & Traditional Cooking Techniques; 3) Community Development Project; and 4) Educational Archaeological Treasure Hunt. ***** ONE INSTRUCTOR FREE OF CHARGE FOR EVERY 10 PAYING STUDENTS *****
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip1684'>The Chagres Challenge</a><br />
Our leading one day adventure tour in Panama. You will explore the pristine jungle of Chagres National Park. It includes 4x4 transportation, hiking, rafting/kayaking, and more.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2138'>Costa Rica Family Adventure</a><br />
Costa Rica is the ideal destination for the active family seeking adventure. Choose from rafting, cave tours, a volcano hike, night turtle watching and more.
</ul></div>

</div>
</body>
</html>
