<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="allstyle.css" rel="stylesheet" type="text/css">
<base target="_blank">
</head>

<body bgcolor="#fbfbf0">
<div id="column2_wrap">
<h2>Background Information & Statistics </h2><p>
	<div id="column2_text" class="scrollable">
	  	<a href="http://news.bbc.co.uk/1/shared/bsp/hi/country_profiles/html/default.stm">BBC News: Country Profiles</a> - Full profiles provide an instant guide to history, politics and economic background of countries. They also include audio and video clips from the BBC archives. <br>
          <a href="http://www.who.int/quantifying_ehimpacts/countryprofiles/en/index.html">Country Profiles of Environmental Burden of Disease</a> - The country profiles provide an overview of summary information on selected parameters that describe the environmental health situation of a country, as well as a preliminary estimate of health impacts caused by environmental risks. <br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?clio5805402">Country Studies/Area Handbook Series</a> - The Country Studies Series presents a description and analysis of the historical setting and the social, economic, political, and national security systems and institutions of countries throughout the world and examines the interrelationships of those systems and the ways they are shaped by cultural factors. At present, 101 countries and regions are covered, published between 1988 and 1998. Check CLIO under &quot;[country name] a country study&quot; for location of print versions. <br>
<a href="http://www.columbia.edu/cgi-bin/cul/resolve?clio5805409">Country Profiles</a>: &quot;The profiles offer reasonably current country information independent of the existence of a recently published Country Study and will be updated annually or more frequently as events warrant.&quot;<br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?ARS4166">CountryWatch</a> - CountryWatch is a world leader in providing country specific geopolitical intelligence on each of the 192 countries of the world. The annual Country Reviews are typically over 100 pages long. <br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?clio6308236">DOLPHN (Data Online for Population, Health and Nutrition)</a> - DOLPHN is an online statistical  data resource of selected demographic and health indicators gathered from various sources for several countries of the world. The DOLPHN system is designed to provide users with quick and easy access to frequently used  statistics. DOLPHN was created in response to the numerous data requirements of USAID health staff and AIM Project data analysts to meet indicator-reporting needs. DOLPHN contains over 70 key health indicators obtained from 11 carefully selected and internationally recognized data sources. The various sources of the data use a variety of research methodologies including population-based surveys, estimates, and projections to derive the statistics. <br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?ARE1578">The Economist Intelligence Unit</a> - The Economist Intelligence Unit is a leading provider of country, industry and management analysis. Through its global network of analysts and economists, EIU continuously assesses and forecasts the political, economic and business climates of 200 countries. <br>
          <a href="http://www.eldis.org/country/">Eldis Regional and Country Profiles</a> - Links to hundreds of authoritative sites for developing countries, in the areas of: agriculture, environment, poverty, education, gender, health &amp; population, governance, trade, economics, aid, microcredit, and security.<br>
          The Europa World Year Book. Annual. London: Europa Publications Limited, c1959- JN 1 .Eu74 - Business, Butler, Lehman The online version is <a href="http://www.columbia.edu/cgi-bin/cul/resolve?clio6284281">Europa World Plus</a>. Each country's chapter includes an introductory survey with history and recent political &amp; economic events; a statistical survey; and a directory, information about the political system, government &amp; parties, the press, banking, industry, transport, etc. Europa's regional  volumes have more detailed information about each country: Africa South of the Sahara; Central and South Eastern Europe; Eastern Europe, Russia, and Central Asia; The Far East and Australasia; The Middle East and North Africa; South America, Central America and the Caribbean; Western Europe.<br>
          <a href="http://epp.eurostat.ec.europa.eu/guip/introAction.do?profile=cpro&theme=eurind&lang=en">EuroStat Country Profiles</a> - An easy way to look at all major statistical indicators for the European Union (13, 15, 25, or 27 countries) or each individual country, and to do comparisons. The data generally goes back 10 years, and can be displayed as a table, graph, or on a map.<br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?clio5489467">FAO Country Profiles</a> - The Food and Agriculture  Organization for the United Nations and its 183 members highlight information as one of the priority areas in fighting hunger and achieving food security. The FAO Country Profiles and Mapping Information System is a pioneering information retrieval tool which groups the organization's vast archive of information on its global activities in agriculture and development in a single  area and catalogues it exclusively by country. <br>
          <a href="http://www.library.northwestern.edu/govpub/resource/internat/foreign.html">Foreign Governments</a> - A comprehensive resource maintained by Northwestern University Library.<br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?clio5330138">GeoHive</a> - GeoHive provides demographic and economic statistics  for all countries, at both the national and subnational levels. The site is divided into four main parts. One dealing with the whole world and its regions, a second with the major regions, a third with all major countries separately and a fourth with rankings (the most, largest, longest, wealthiest, etc.).<br>
          <a href="http://www.gksoft.com/govt/en/">Governments on the  WWW</a> - Very detailed links for every country.<br>
          <a href="http://www.crisisweb.org/home/index.cfm?id=1144&l=1">International Crisis Group: Reports by Country</a> - Not all countries are represented, just those which are involved or potentially involved in conflict situations. <br>
          <a href="http://www.imf.org/external/country/index.htm">International Monetary Fund Country Information</a> - IMF operations — which involve surveillance, financial assistance, and technical assistance — have developed to meet the changing needs of its 184 member countries in an evolving world economy. <br>
          <a href="http://www1.lanic.utexas.edu/project/archives/lagda/">Latin American Government Documents Archive</a>, University  of Texas at Austin. The Latin American Government Documents Archive (LAGDA) seeks to preserve and facilitate access to a wide range of ministerial and presidential documents from 18 Latin American and Caribbean countries. The Archive contains copies of the Web sites of approximately 300 government ministries and presidencies. Capture of sites began on multiple dates in 2005 and 2006, and will continue with regularly scheduled captures. Content in the Archive includes not only the full-text versions of official documents, but also original video and audio recordings of key regional leaders.<br>
          <a href="http://www.msuglobalaccess.net/">MSU Global Access</a>, Michigan State University - Provides information about the world - its regions and peoples and important international issues. You can search simultaneously by world region or country and by thematic area. <br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?clio4800696">NationMaster.com</a> - Allows users to generate graphs based on numerical data extracted from numerous sources. All sources are documented.<br>
          <a href="http://www.ssa.gov/international/links.html">Social Security in Other Countries</a>: links to each country's social security program, from the U.S. Social Security Administration.<br>
          <a href="http://www.socialwatch.org/">Social Watch</a> - Social Watch is an international network informed by national citizens' groups aiming at following up the fulfillment of the internationally agreed commitments on poverty eradication and equality. It produces an&nbsp;annual report as well as individual country reports.<br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?clio4166324">The UC Atlas of Global Inequality</a> - The Atlas of Global Inequality explores aspects of inequality using online, downloadable maps and graphics. It includes sections on Health, Income Inequality, Economic Globalization, Gender Connections, and Inequality &amp; Growth. The country pages provied useful data  and graphs on these and other topics and provide the option to compare countries with each other.<br>
          <a href="http://www.uis.unesco.org/profiles/selectCountry_en.aspx">UNESCO Institute for Statistics Country Profiles</a> - Country profiles feature key  statistics and indicators on education, science and technology, and culture and communication on a country-by-country or regional basis.<br>
          <a href="http://www.columbia.edu/cgi-bin/cul/resolve?ATT2119%20">UNdata</a> - UNdata provides a vast array of statistical data from  numerous UN sources. <br>
          <a href="http://web.worldbank.org/WBSITE/EXTERNAL/COUNTRIES/0,,pagePK:180619~theSitePK:136917,00.html">World Bank Countries and Regions</a> <br>
          <a href="http://data.worldbank.org/country">World Bank Data by Country</a> - Links to all  information regarding the World Bank mission in a country, including the Country Assistance Strategy, project reports, Country Economic Memorandum, and other in-depth analysis. Choose from -- Country at a Glance tables: two pages of key indicators tracing the trends in social and economic development from the last three decades; Data Profile tables: data profiles available here are drawn from the World Development Indicators database. The profiles cover the  208 countries (184 World Bank members and 24 other economies with populations of more than 30,000) and 18 country groups reported on in the World Development Indicators; EdStats: short for Education Statistics, is a comprehensive education statistics database; GenderStats: a database of gender statistics, showing summary gender indicators, basic demographic data, population dynamics, labor force structure, and education and health statistics; HNPStats: short for Health, Nutrition, and Population Statistics offers country data sheets showing summary indicators for health status, health determinants, and health finance. <br>
          <a href="http://www.who.int/countries/en/">World Health Organization Country Profiles</a> - Includes basic vital and health statistics, health expenditures, provision/coverage, health system organization and regulation, summary measures, country-specific conditions, and human resources.<p>
        Source: <a href="http://www.columbia.edu/cu/lweb/indiv/lehman/guides/countries.html">http://www.columbia.edu</a>
	</div>
</div>

</body>
</html>
