<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="style.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body style="background: url(images/ssn-img-info-bkgd.jpg) no-repeat">
<h4>Africa Trips</h4>
<div id="info" class="scroll">
<div>
<ul>
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4372'>Kilimanjaro Trek and Safari Package #2</a><br />
A shorter adventure of climbing Kilimanjaro and safari experience! This package includes a 6-day Machame Route trek with a 4-day safari. Itinerary in brief: Day 1: Arrive at Kilimanjaro Airport, overnight at Springlands Hotel Day 2-7: 6-day Machame Route Day 8-11: 4-day Safari 3 days of game drives, including Lake Manyara, Ngorongoro Crater, and Tarangire 1-day walking tour of Karatu or Empakai Crater; Depart from Kilimanjaro Airport
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4373'>Kilimanjaro Trek and Safari Package #3</a><br />
Try the most popular trek/safari package. This combines a 5-day Marangu Route trek (in huts) with a Northern Tanzanian 5-day safari. Itinerary in brief: Day 1: Arrive at Kilimanjaro Airport, overnight at Springlands Hotel Day 2-6: 5-day Marangu Route Day 7-11: 5-day Safari 5 days of game drives, including Lake Manyara, Serengeti, and Ngorongoro Crater Depart from Kilimanjaro Airport
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2197'>Delta and Falls Experience</a><br />
For Africa enthusiasts Botswana is the place to be. Explore the wildlife meccas of Okavango and Chobe, and finish off at the magnificent Victoria Falls, Mosi Oa Tunya&quot;the smoke that thunders&quot;- a natural wonder of the world.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2233'>South Africa Coastal Adventure</a><br />
An ideal adventure for those looking to explore South Africa&#039;s rugged green coast, vibrant cultures, abundant wildlife and one of the world&#039;s more cosmopolitan cities, Cape Town.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2332'>Windhoek to Nairobi</a><br />
From the deserts and dunes of Namibia, to the wildlife rich parks of Botswana and Tanzania, and all the culture inbetween, this trip captures the essence of the African experience.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2303'>Serengeti and Masai Mara Experience</a><br />
This safari offers fantastic insight into the diverse nature, culture and landscape of East Africa. The annual wildebeest migration from the Serengeti to the Masai Mara is a breathtaking sight not to be missed! Virtually unlimited wildlife experiences, encounters with indigenious tribes and sleeping under the African stars make this a trip to remember.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2310'>Masai Mara Experience</a><br />
This safari offers fantastic insight into the diverse nature and landscape of Kenya. With visits to the forested highlands, the semi-arid north, the Great Rift Valley and the savannah grasslands, this trip is an excellent all-encompassing introduction to East Africa. Virtually unlimited wildlife experiences and encounters with indigenious tribes make this a trip to remember.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2324'>Kenya Safari&amp;Zanzibar</a><br />
A great mix of culture, wildlife and nature. The combination of Zanzibar with a popular wildlife safari in Kenya provides a well-rounded African experience.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2738'>iExplore Botswana Gold - Okavango Delta&amp;Chobe National Park</a><br />
As one of the most developed and progressive countries in Africa, Botswana has much to offer travelers. The Okavango Delta, a labyrinth of islands, flood plains, and waterways best explored by dugout canoe, teems with wildlife like hippos, elephants, crocodiles, zebras, and giraffes.East of Okavango is Chobe National Park, a huge stretch of flat, dry land that boasts the greatest variety of animals in Botswana, including lions, wildebeest, cheetah, hyena, buffalo, jackal, and warthog. On this trip you can choose either park, or go to both!The best time to visit is August-October, but anytime March-November is great. Nights are surprisingly cold during the dry season, so take along a warm sweater. Many of the Okavango Delta camps are closed at the height of (the southern-hemisphere&#039;s) summer, December-March, when it&#039;s very hot and when there are short daily thunderstorms.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2739'>iExplore Botswana Silver</a><br />
As one of the most developed and progressive countries in Africa, Botswana has much to offer travelers. The Okavango Delta, a labyrinth of islands, flood plains, and waterways best explored by dugout canoe, teems with wildlife like hippos, elephants, crocodiles, zebras, and giraffes.East of Okavango is Chobe National Park, a huge stretch of flat, dry land that boasts the greatest variety of animals in Botswana, including lions, wildebeest, cheetah, hyena, buffalo, jackal, and warthog.You have chosen three comfortable lodges or tented camps, all of which offer morning, afternoon, and evening game drives or waterborne game viewing. You&#039;ll stay two nights at each camp, enjoying amenities like swimming pools, private rooms, air conditioning, and raised game viewing decks.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2743'>iExplore Cape to Cairo</a><br />
Cape Town is the oldest and most beautiful city in South Africa and one of the top destinations in the world. Although Cape Town is better known for stunning beaches and beautiful landscapes, the regions around Cape Town offer a range of activities and attractions, like wildlife safaris in the Cedarberg Mountains, wine tasting in the glorious Winelands, expeditions to see thousand-year-old San rock art and adventure activities such as sandboarding, surfing, bungee jumping, kloofing, abseiling and much more.The Masai Mara National Reserve was established in 1961. It is situated some 168km (105 miles) south of the equator. Bordering on its southern edge are the mighty Serengeti plains of Tanzania. The entire reserve is 1530km2 in size, with the inner, core reserve covering 320km2. The inner reserve is what is known by visitors as the Masai Mara with its entrance gates and no human settlements within its boundaries. Yhe Oloololo Escarpment to the west rises 300m above the plains and forms the boundary with the TransMara district. The escarpment was formed by the Mara river which itself is the scene for the spectacular crossing of thousands of wildebeests and zebra on their annual migration from the Serengeti Plains.Travelers have been marveling at Egypt&#039;s wondrous antiquities for thousands of years -- even the ancient Greeks and Romans were awed by them. But today, a visit to Egypt is more than an immersion into past glories -- mud-brick villages sprout TV antennae, stone and glass high-rises tower over ancient monuments and pop music blaring from radios counterpoints the call to prayer. Although modern life coexists with the legacies of the past, it has also opened up possibilities for exploring a wider area of Egypt. In addition to the great monuments of the Nile Valley, an Egyptian itinerary could also include diving along the Red Sea coast, a desert trek to remote oases or a visit to the Sinai Peninsula. The hub of transportation -- and most likely your first and last stop in the country -- remains Cairo, a city that never fails to make a strong impression.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2756'>iExplore Rwanda Silver</a><br />
The Mountain Gorillas in the Parc Nationale des Volcanes are part of a worldwide population of just 600 individuals. The gorillas we are allowed to track belong either one of four habituated family groups. For up to five years each, these groups have undergone an extremely delicate process that has gradually brought them to tolerate the presence of humans for a brief period every day and allowed a few privileged visitors to interact with them in the wild.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2760'>iExplore South Africa Family</a><br />
The best of South Africa is yours to explore on this spectacular 8-day Family tour.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2761'>iExplore South Africa Gold</a><br />
The charming luxury lodges and intimate hotels selected here are, quite simply, the very best in the region: the best locations for exploring, the best design and style, the best atmosphere, the best food and wine, and the most friendly, welcoming and unobtrusive service.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2763'>iExplore Southern Africa Gold</a><br />
Explore both South Africa and Botswana on this 10 day journey through Africa featuring Capetown, Victoria Falls, and the fabulous Okavango Delta!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2774'>iExplore Tanzania Family</a><br />
The Lake Manyara National Park, famed for its tree-climbing lion, is made up of acacia woodlands, grassy floodplains and verdant groundwater forests and is home to an incredible diversity of birds, especially waterfowl, as well as antelope, primates and predators.From there it&#039;s on to the Serengeti National Park, famous for the annual wildebeest and zebra migration. During June and July, mind-boggling numbers of hoofed animals make the long trek from Tanzania to Kenya, allowing for superb wildlife viewing.Next stop is the famed Ngorongoro Crater. At the eastern edge of the Serengeti, and nearly three million years old, the ancient caldera of the once-volcanic Ngorongoro shelters the most beautiful wildlife haven left on Earth. The Crater is home to countless cheetah, serval, wildebeest, gazelle, zebra, leopard, and jackal.Continue to Tarangire National Park for a stop over before returning to Arusha. It is the vast number of baobabs that first capture the eye as you enter Tarangire National Park. The gently rolling countryside is dotted with these majestic trees, which seem to dwarf the animals that feed beneath them.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2775'>iExplore Tanzania Gold</a><br />
The Lake Manyara National Park, famed for its tree-climbing lion, is made up of acacia woodlands, grassy floodplains and verdant groundwater forests and is home to an incredible diversity of birds, especially waterfowl, as well as antelope, primates and predators.After two nights at Manyara, you will travel on to the Serengeti National Park, famous for the annual wildebeest and zebra migration. During June and July, mind-boggling numbers of hoofed animals make the long trek from Tanzania to Kenya, allowing for superb wildlife viewing.After three nights in the Serengeti, you will enjoy luxury accommodation at the Ngorongoro Crater Lodge for two nights, complete with butler service. From there you&#039;ll travel to the famed Ngorongoro Crater. At the eastern edge of the Serengeti, and nearly three million years old, the ancient caldera of the once-volcanic Ngorongoro shelters the most beautiful wildlife haven left on Earth. The Crater is home to countless cheetah, serval, wildebeest, gazelle, zebra, leopard, and jackal.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2776'>iExplore Tanzania Silver</a><br />
Lake Manyara National Park, famed for its tree-climbing lion, is made up of acacia woodlands, grassy floodplains and verdant groundwater forests and is home to an incredible diversity of birds, especially waterfowl, as well as antelope, primates and predators.After two nights at Manyara, you&#039;ll travel to the Serengeti National Park, famous for the annual wildebeest and zebra migration. During June and July, mind-boggling numbers of hoofed animals make the long trek from Tanzania to Kenya, allowing for superb wildlife viewing.And then on to the famed Ngorongoro Crater. At the eastern edge of the Serengeti, and nearly three million years old, the ancient caldera of the once-volcanic Ngorongoro shelters the most beautiful wildlife haven left on Earth. The Crater is home to countless cheetah, serval, wildebeest, gazelle, zebra, leopard, and jackal.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2785'>iExplore Uganda - Gorilla Tracking</a><br />
Uganda has once again become an outpost of hope in East Africa. As it makes steady progress toward peace and works to improve its tourist facilities, travelers have begun to trickle back to enjoy its stunning landscape - green rolling hills, snowcapped mountains, majestic rivers and massive lakes - and its fascinating wildlife, including Africa&#039;s largest population of mountain gorillas.The country&#039;s progress was brutally interrupted in early 1999 when Rwandan rebels murdered eight tourists who had traveled to Uganda to view the mountain gorillas in Bwindi National Park. It was not the first incident where travelers were harmed. Although most of the recent unrest has been confined to areas bordering Rwanda and the Democratic Republic of the Congo, bombings in Kampala, the capital, and rebels on other fringes of the country have raised questions about Uganda&#039;s safety for travelers. But the Ugandan government seems to have finally recognized the possible benefits of tourism. The army now patrols Bwindi, and tourists can once again feel safe visiting the park, the best place in the world to see mountain gorillas. It may be some time before Uganda achieves its full potential, but the country once known as &quot;the pearl of Africa&quot; has regained some of its luster.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2793'>iExplore Zambia</a><br />
This desperately poor country is extravagantly rich in wildlife and wild terrain. Its game parks are among the best in the world, and it shares with Zimbabwe two of the scenic highlights of southern Africa: Victoria Falls and the Zambezi River. But Zambia&#039;s attractions are a bit difficult and expensive to reach, which means they&#039;re unspoiled but also a challenge for independent travelers. We think Zambia is well worth the challenge, particularly if you&#039;re interested in pursuing the raw edges of the &quot;real&quot; Africa, and if you&#039;re keen on seeing wild animals in a truly wild setting. We do, however, think Lusaka, the capital, is best avoided: It&#039;s dreary and can be dangerous.Landlocked Zambia is set on a high plateau (averaging 4,265 ft/1,300 m in altitude), with mountains and hills in the east and north. Almost half the land area is savanna and bush, a quarter is forest or woodland and less than 10% is cropland (tobacco, corn and peanuts are the main crops). The Copper Belt, where most of the mines are located, stretches across the northern part of the country. The Zambezi River begins in the west and runs southeast, eventually delineating the Zambian border with Nambia, Botswana and Zimbabwe. The country is also bordered by Angola to the west, Democratic Republic of Congo (formerly Zaire) and Tanzania to the north and Malawi and Mozambique to the east.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2930'>iExplore Wings Over Botswana Gold</a><br />
Botswana is literally an oasis in the desert  the desert being the Kalahari, cut into jigsaw shapes by the tributaries that vitalize the Okavango Delta. And where there is water there is life, lush and green and teeming with animals and birds.Aptly described as &quot;a sea of land, a land of water,&quot; Botswana is home to some of the most spectacular vistas on Earth, reminiscent of an &quot;Africa as it used to be.&quot; Botswana is home to 10,000 square miles of lagoon, marsh and papyrus channel, much of it protected wildlife habitat. Here you will find, for example, the largest concentration of elephants in all of Africa, along with buffalo, zebra, giraffe, gazelle and dozens of other mammals and birds.We have been sharing this unique safari experience with the world for decades, in a variety of programs to suit every type of traveler  from adventurers, to families, to connoisseurs  led by the regions finest safari escorts, in small, intimate groups traveling in open game-viewing vehicles. You will stay at Botswana&#039;s finest camps and lodges  Chobe Chilwero Lodge, Chief&#039;s Camp, and Stanley&#039;s Camp  far from civilization, but also far from rustic.Discover Africas best-kept safari secret  the breath-taking and beautiful water wilderness that is Botswana.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2942'>iExplore East Africa Gold</a><br />
Get the heart-pounding thrill of a safari while still enjoying the comforts of luxury accommodations on this eleven-day East Africa adventure. Depart early morning for a game drive just as the dawn sunlight begins to stir the sleeping lions, zebras, and giraffes.At the eastern edge of the Serengeti, and nearly three million years old, the ancient caldera of the once-volcanic Ngorongoro shelters the most beautiful wildlife haven left on Earth. The Crater is home to countless cheetah, serval, wildebeest, gazelle, zebra, leopard, and jackal.From there it&#039;s on to the Serengeti National Park, famous for the annual wildebeest and zebra migration. During June and July, mind-boggling numbers of hoofed animals make the long trek from Tanzania to Kenya, allowing for superb wildlife viewing.You will next visit the vast grasslands of the Masai Mara, Kenya. This is when the elephants, wildebeest, and hippos are most visible as they take to watering holes to cool off. Return to your rooms and sip a sundowner on your private verandah as inky darkness washes over the landscape and the night sounds of the Masai Mara come alive.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2943'>iExplore East Africa Silver</a><br />
Get the heart-pounding thrill of a safari while still enjoying the comforts of luxury accommodations on this ten-day East Africa adventure. Depart early morning for a game drive just as the dawn sunlight begins to stir the sleeping lions, zebras, and giraffes.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2947'>iExplore Egypt&amp;Jordan</a><br />
Travelers have been marveling at Egypt&#039;s wondrous antiquities for thousands of years - even the ancient Greeks and Romans were awed by them. But today, a visit to Egypt is more than an immersion in past glories. The clamorous present is ever-present: Mud-brick villages sprout TV antennae, stone and glass high-rises tower over ancient monuments and pop music from boom boxes counterpoints the call to prayers.Set on the ancient crossroads between Arabia and the Mediterranean Sea, Jordan is full of historic sites. Crusaders&#039; forts along old trade routes and ancient cities carved from stone will captivate anyone in search of the past. And while the land might be ancient, Jordan&#039;s cities offer the modern conveniences that help make your trip to the past a little less demanding. When you tire of desert ardors, you can relax at a Dead Sea spa or go scuba diving in the Red Sea.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2948'>iExplore Egypt Family</a><br />
Travelers have been marveling at Egypt&#039;s wondrous antiquities for thousands of years - even the ancient Greeks and Romans were awed by them. But today, a visit to Egypt is more than an immersion in past glories. The clamorous present is ever-present: Mud-brick villages sprout TV antennae, stone and glass high-rises tower over ancient monuments and pop music from boom boxes counterpoints the call to prayers.While modern life coexists in close proximity with the legacies of the past, it has also opened up possibilities for exploring a wider area of Egypt. In addition to the great monuments of the Nile Valley, an Egyptian itinerary is also likely to include diving along the Red Sea coast or a desert trek to remote oases or the Sinai. The hub of transportation - and most likely your first and last stop in the country - remains Cairo, a city that never fails to make a strong impression.Nearly all of Egypt is desert, but the small part that isn&#039;t - the valley of the Nile River - is vital to the nation (95% of the population lives within a few miles of the Nile&#039;s banks). Most tours of Egypt, whether by cruise, via train, on a bus or in a private car, never stray too far from the river&#039;s shores. Egypt is the largest country in the Arab world, and among African nations, is second in population only to Nigeria (Cairo, the continent&#039;s most populous city, alone has 16 million people).
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2949'>iExplore Egypt Gold</a><br />
An experienced Egyptologist accompanies you on every leg of this luxurious Nile cruise. Explore Egypt&#039;s ancient temples, from the mysterious Sphinx to the awe-inspiring Temple of Kom Ombo. Highlights include a desert camel ride, a tour of the once-flourishing city of Memphis, the opulent Grand Palace of Giza, exploring the treasure-filled tombs of the Valley of the Kings, and a tour of the Temple of Luxor, dedicated to the god Amun.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2950'>iExplore Egypt Silver</a><br />
An experienced Egyptologist accompanies you on every leg of this luxurious Nile cruise. Explore Egypt&#039;s ancient temples, from the mysterious Sphinx to the awe-inspiring Temple of Kom Ombo. Highlights include a desert camel ride, a tour of the once-flourishing city of Memphis, the opulent Grand Palace of Giza, exploring the treasure-filled tombs of the Valley of the Kings, and a tour of the Temple of Luxor, dedicated to the god Amun.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2952'>iExplore Ethiopia</a><br />
Ethiopia is the home of some of the most exotic ancient civilizations in the world - and the land where some of our earliest human ancestors have been discovered. The country&#039;s landscape is littered with old ruins and remains and wonders - ancient sculpted towers, Arab-influenced walled towns and early churches carved out of solid rock. It also has its share of wild places - of lions and hippos and untamed rivers. As English novelist Evelyn Waugh once observed, Ethiopia is a country of &quot;crazy enchantment.&quot;
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2990'>iExplore Kenya - Family</a><br />
Everyone should visit Kenya at least once - not just for the spectacular wildlife, but also for its beautiful lakes and beaches and for the sweeping vistas of the Great Rift Valley. The landscape is just as memorable and photogenic as that lion walking, right there, beside the Land Rover.Kenya is located on the east coast of Africa. Its two major rivers, the Tana and the Galana, originate in the country&#039;s midsection and flow through the eastern part of the country before emptying into the Indian Ocean. Lake Victoria (which is shared with Tanzania and Uganda) and the Rift Valley are the two main geographical features of western Kenya. Mt. Kenya, the country&#039;s highest peak, is in the central highlands.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2991'>iExplore Kenya Gold</a><br />
Get the heart-pounding thrill of a safari while still enjoying the comforts of luxury accommodations on this seven-day Kenya adventure. Depart early morning for a game drive just as the dawn sunlight begins to stir the sleeping lions, zebras, and giraffes.Stop for a delicious lunch mid-day, then it&#039;s back out for an afternoon drive on the vast grasslands of the Masai Mara. This is when the elephants, wildebeest, and hippos are most visible as they take to watering holes to cool off. Return to your rooms and sip a sundowner on your private verandah as inky darkness washes over the landscape and the night sounds of the Masai Mara come alive. A gourmet dinner ends each day of this perfect safari adventure.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2992'>iExplore Kenya Silver</a><br />
Get the heart-pounding thrill of a safari while still enjoying the comforts of luxury accommodations on this Kenya adventure. Depart early morning for a game drive just as the dawn sunlight begins to stir the sleeping lions, zebras, and giraffes. Stop for a delicious lunch mid-day, then it&#039;s back out for an afternoon drive. This is when the elephants, wildebeest, and hippos are most visible as they take to watering holes to cool off. Return to your rooms and sip a sundowner on your private verandah as inky darkness washes over the landscape and the night sounds of Africa come alive. A gourmet dinner ends each day of this perfect safari adventure.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2993'>iExplore Kenya Silver - Active</a><br />
This adventure immerses you in the active side of Kenya while leaving plenty of time to view the amazing wildlife for which the country is famous. It all begins by jumping off a bridge and swimming to our raft in the Tana River for some exciting white-water rafting.In Hell&#039;s Gate National Park hike, drive, or mountain bike through the sinuous, rocky canyons; take a stab at rock-climbing some of the canyon walls; and descend under the earth in ancient lava tubes near Mt. Suswa. Of coure, time is devoted to wildlife viewing in the Maasai Mara - East Africa&#039;s premier wildlife destination.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2994'>iExplore Kilimanjaro Climb - Machame Route</a><br />
Towering over Tanzania&#039;s northeastern plains, snow-capped Kilimanjaro commands attention. This majestic mountain is the highest on the African continent at 19,335 feet and is an ideal &quot;starter peak&quot; for novice mountaineers. Though certainly no walk in the park, Kilimanjaro offers terrain that&#039;s reasonably scalable, but the high altitude may be the biggest hurdle. After seven days of trekking from rainforest to grasslands to barren, glacier-like landscape, you reap the ultimate reward of the summit.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2995'>iExplore Kilimanjaro Climb - Marangu Route</a><br />
The Mt. Kilimanjaro Climb is considered a strenuous and physically demanding trip (reaching altitudes exceeding 19,000 ft above sea level.) It is imperative that you are fully prepared (both physically and mentally) for this trip and you must ensure you have all the appropriate equipment and clothing, which can greatly affect the overall enjoyment of your tour.You will experience equatorial to arctic conditions. The range begins with the warm dry plains with an average temperature of 30C (86F) and ascends through a wide belt of wet tropical forest, through zones with generally decreasing temperature and rainfall, to the summit where there is permanent ice and below freezing conditions. The altitude and seasons determine weather conditions. The fact that for most months of the year there are so few rainy days makes it possible to climb in relatively good conditions all year round. The rainy season is from March to June, with short rains in October and November
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2997'>iExplore Madagascar</a><br />
Madagascar, the fourth-largest island in the world, lies in the Indian Ocean off the coast of Mozambique. It includes several much smaller islands. A central chain of high mountains, the Hauts Plateaux, occupies more than half of the main island and is responsible for the marked differences  ethnically, climatically and scenically  between the east and west coasts. The narrow strip of lowlands on the east coast, settled from the sixth century by Polynesian seafarers, is largely covered by dense rainforests, whereas the broader west-coast landscape, once covered by dry deciduous forests, is now mostly savannah.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2998'>iExplore Malawi</a><br />
Most people visit tiny Malawi on their way somewhere else. Squeezed between South and East Africa, this poor, densely populated little country makes a convenient stopover for those en route from, say, Botswana to Tanzania. Those who do make the stop may be surprised. For such a thin sliver of a country, Malawi offers a variety of attractions: lakes, rivers, mountains, game parks and villages. We think it has a subtle appeal; if you get the chance to perch on a mountain cliff above Cape Maclear and watch the sun sink into Lake Malawi as fisherman return to shore with the day&#039;s catch, you&#039;ll understand what we mean.Landlocked Malawi is dominated by Lake Malawi and the Great Rift Valley, which cuts through the country north to south (on either side of the valley are plateaus 3,000-4,000 ft/900-1,200 m high). In the north, the Nyika Uplands reach 8,500 ft/2,600 m, and in the south, mountains climb to nearly 10,000 ft/3,050
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3002'>iExplore Morocco Gold - Active</a><br />
The country is one of Africa&#039;s most popular travel destinations. No matter how well-seasoned a traveler you are, you&#039;ll find plenty to see and do: fine Atlantic and Mediterranean beaches, desert excursions, wondrous imperial cities, Islamic landmarks, wild Joujoukan trance music, Roman antiquities, resort facilities, mountain villages and towering sand dunes
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3003'>iExplore Morocco Gold</a><br />
Morocco&#039;s dazzling mosaic of African, Arab and Berber cultures - with a dash of European influence - is at once strange and romantic, alluring and discomfiting. It&#039;s little wonder that Morocco has regularly drawn seekers of the exotic.The country is one of Africa&#039;s most popular travel destinations. No matter how well-seasoned a traveler you are, you&#039;ll find plenty to see and do: fine Atlantic and Mediterranean beaches, desert excursions, wondrous imperial cities, Islamic landmarks, wild Joujoukan trance music, Roman antiquities, resort facilities, mountain villages and towering sand dunes. Just be aware that the combination of heat, dust, spicy flavors and intrusive touts can be overwhelming at times.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3004'>iExplore Morocco Gold - Active</a><br />
The country is one of Africa&#039;s most popular travel destinations. No matter how well-seasoned a traveler you are, you&#039;ll find plenty to see and do: fine Atlantic and Mediterranean beaches, desert excursions, wondrous imperial cities, Islamic landmarks, wild Joujoukan trance music, Roman antiquities, resort facilities, mountain villages and towering sand dunes
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3005'>iExplore Morocco Silver - Camel Trek</a><br />
Enjoy an adventurous four-day camel trek across the sands of the Sahara. This is a true camel trek with all the magic of the Sahara, ride camel back or proceed on foot. Cobalt-blue skies, orange sand dunes, lush fertile oases, and serrated mountain summits fill the vistas, and with the grand solitude and silence of the Sahara, and nights spent under a starry sky, you&#039;ll feel the mysterious power that the desert has always had over the human soul.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3006'>iExplore Mozambique Extension</a><br />
Since 1990, Mozambique has been developing as a tourist Mecca once again. The most popular areas for holidaymakers is the South Coast, particularly Maputo, formerly known as Lourenco Marques, and the islands of Inhaca, Benguerra and Bazaruto. Maputo is an attractive port that still retains much of its Portuguese charm. Its old town is amaze of narrow streets lined with many buildings dating back to before the turn of the Century. Visitors enjoy exploring the town&#039;s many colorful markets, where one can pick up exotic spices, nuts and nick-nacks.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3008'>iExplore Namibia Gold</a><br />
At first glance, Namibia might seem one of Earth&#039;s most desolate places. With its ancient deserts, parched salt pans and a windblown shoreline littered with the weathered hulls of foundered ships, there would seem little potential for life and color - and little to interest the average traveler.But there is a startling beauty in its vistas - from the multihued dunes of the Kalahari and Namib Deserts to the foggy shores of the Skeleton Coast. The deep fissures of the Fish River Canyon make for steep but exhilarating walking. And surprisingly, Namibia is home to an incredible variety of plants and animals that have adapted to the extreme climate. Its national parks and wildlife refuges are among the finest in Africa.Perhaps most surprising are the people who have adapted to this harsh environment: San Bushmen and the Herero women with their banana-shaped headdresses and bright Victorian-style dresses patterned after those of early German missionary women. It&#039;s a great place for people watching and experiencing another way of life. The German influence can also be seen in the colonial-era towns scattered along the coast and central highlands - there is something surreal about imperial-style German architecture poking up above desert sands.Namibia is not usually listed among the top destinations in Africa, but it has a lot to offer those looking for an unusual destination off the beaten track. Although its terrain is harsh and demanding, it is actually one of the safer and more stable countries in Africa.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4405'>Day trip to Cairo from Taba by private car</a><br />
Enjoy a full day trip from Taba to Cairo, to see the Pyramids, Egyptian museum, and markets
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4352'>Backpacker Nile Adventure</a><br />
Visit the Pyramids, Sphinx. Explore Cairo's intriguing bazaars, mosques and museums. Take a Felucca journey along the Nile visiting Egypt's stopping at riverside temples and villages and visit the ancient monuments in Aswan and Luxor.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4382'>Nile Beauty</a><br />
13 days - Visit the Pyramids, Sphinx. Explore Cairo's intriguing bazaars, mosques and museums. Take a Felucca journey along the Nile visiting Egypt's stopping at riverside temples and villages and visit the ancient monuments in Aswan and Luxor. Relax on the beaches at Dahab or snorkel among the coral reefs of the Red Sea. Climb Mount Sinai for a spectacular sunrise
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4384'>Egypt & Jordan Highlights (With Felucca)</a><br />
This 15-day journey through exotic Egypt includes a visit to the Pyramids & Sphinx,, a 3-day Nile Felucca boat, with a visit to the Elephantine Island, the Botanical Gardens and the Philae Temple. Luxor. East & West Bank, then a short extension to explore Petra and Wadi Rum
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4386'>Egypt Highlights Classic tour 10 days</a><br />
This tour gives you the chance to experience Cairos many interesting sites, including the Pyramids, Sphinx and the world famous Egyptian museum before transferring to Aswan for a 5 day/4 night luxury cruise down the Nile to Luxor. You visit all the major sites en route
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4387'>Over day tour Sharm/Cairo by flight</a><br />
one day trip by domestic flights, to explore Cairo, Pyramids, Sphinx, Egyptian museum, and Khan El Khalili bazzar, back to Sharm in the evening
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4406'>Overday from Hurghada to Cairo by Flight</a><br />
Day trip to Cairo from Hurghada by domestic flight to explore the Pyramids, Egyptain museumetc
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4371'>Kilimanjaro Trek and Safari Package #1</a><br />
An ultimate Tanzania adventure awaits you! This package combines a 7-day Machame Route trek followed by a 5-day Northern Tanzania safari. Itinerary in brief: Day 1: Arrive at Kilimanjaro Airport, overnight at Springlands Hotel Day 2-8: 7-day Machame Route Day 9-13: 5-day Safari 5 days of game drives, including Lake Manyara, Serengeti, and Ngorongoro Crater Depart from Kilimanjaro Airport
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2322'>Kili, Serengeti&amp;Zanzibar</a><br />
Our popular East Africa safari, with a Kili climb added for extra excitement. This is a pure African experience, from the plains of the Serengeti to the spice island of Zanzibar and the highest peak in Africa!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2323'>Kenya and Tanzania Adventure</a><br />
An ideal safari adventure for those travellers interested in diverse wildlife, interesting people and stunning scenery, but also enjoy a bit of relaxation. From the lakes of Kenya to the plains of the Seregenti and charming Zanzibar, this is an all-encompassing East African safari.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2314'>Ethiopia Simien Mountains</a><br />
Ethiopia has a rich, fascinating history. Here we will experience ancient monasteries, castles, and rock-hewn churches, including the famous Lalibela, which is carved out of one single rock. We also hike in the Simien mountains to get a full appreciation of all that this great country has to offer.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2318'>Kenya Safari&amp;Usumbara Mountain Trek</a><br />
Now this is Africa! This trip has you on safari in Kenya, taking in unbelievable wildlife at Lake Nakuru and experiencing the culture of the Masai Mara first hand. Combine this with a 4-day trek through the Usumbara Mountains for a full picture of life in Kenya and Tanzania.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2187'>Serengeti Experience</a><br />
Tanzania, a country dominated by vast, open plains, provides some of the best wildlife viewing opportunities in Africa. Spend a day at Lake Manyara, in the hopes of seeing its famous tree-climbing lions, then continue on to marvel at the amazing wildlife found throughout Tanzania.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2331'>Victoria Falls to Nairobi Adventure</a><br />
A journey through the wild continent, from Zambia to Malawi and Tanzania, and finally into Kenya. Discover the diversity of wildlife, landscapes and people in East and southern Africa on this journey of adventure and discovery. And keep your eye out for the Big 5!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3149'>OMO VALLEY</a><br />
Visit the colourful tribes of Southern Ethiopia. Relax and bird watch in the Rift Valley.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3151'>RIFT VALLEY LAKES</a><br />
Extension tour to Shala, Abyata, Langano and Awassa Lakes in Ethiopia's Rift Valley.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3152'>RIFT VALLEY LAKES + ARBA MINCH</a><br />
Rift Valley Lakes, Arba Minch and Netch Sar Park
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3153'>HARAR</a><br />
Visit Harar, fourth most important city in the Muslim world.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3154'>BAHIR DAR AND LALIBELA</a><br />
Extension trip to the Blue Nile falls, Laka Tana and Lalibela - monasteries and rock-hewn churches
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3155'>LALIBELA</a><br />
Extension trip to Lalibela, eighth wonder of the world.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3647'>Morocco Adventure</a><br />
Moroccos location on the edge of the Sahara together with its historic trade links with the great ports of Europe have shaped its rich cultural traditions. The incomparable blend of mosques and minarets, spices and scents and great Imperial cities are a constant source of inspiration while our trek in the High Atlas provides a further compelling dimension to our journey. Our travels from Casablanca to Fes and Marrakesh provide a fascinating introduction to the souqs (the teeming markets); the medinas (the complex of palaces, mosques and minarets) and riads (the traditional houses where we sample spicy cuisine and unequalled hospitality) while in the ancient trading port of Essaouira we wander the narrow lanes that could be anywhere in southern Europe. The highlight of our journey is our trek in the Atlas Mountains. We follow trails through traditional Berber villages to alpine pastures where the summits of the High Atlas stretch before us. We also offer a non-technical ascent of Jebal Toubkal (4167m), the highest mountain in Morocco.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3648'>Morocco Explorer</a><br />
Explore Morocco&#039;s Imperial cities and appreciate the rich cultural traditions of music, dance and handicrafts. Walk through the colourful markets and renowned mediaeval medina of Fes in the company of our expert guide, before travelling across the foothills of the Middle Atlas to the deep orange dunes on the edge of the Sahara. In Marrakesh, one of the most important artistic centres in the Islamic world, there is time to bargain in the souqs which reflect a wide variety of handicrafts, crafted by coppersmiths, carpenters, potters and carpet weavers. We include a visit to an ornately decorated riad (a traditional house) to sample the fine food and traditional hospitality. Continuing to Essaouira, with its tranquil squares and cafes, there is plenty of time to explore the narrow lanes and whitewashed houses with their painted blue doors, that could be anywhere in the southern Mediterranean! Yet the massive fortifications on the eastern side of the Medina overlook the Atlantic Ocean and provide a reminder of times when trade flourished between northern Morocco and the great ports of Europe. Time in the spectacular Dades Gorges and a camel ride in the Sahara round off this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3752'>Morocco Explorer</a><br />
Explore Morocco&#039;s Imperial cities and appreciate the rich cultural traditions of music, dance and handicrafts. Walk through the colourful markets and renowned mediaeval medina of Fes in the company of our expert guide, before travelling across the foothills of the Middle Atlas to the deep orange dunes on the edge of the Sahara. In Marrakesh, one of the most important artistic centres in the Islamic world, there is time to bargain in the souqs which reflect a wide variety of handicrafts, crafted by coppersmiths, carpenters, potters and carpet weavers. We include a visit to an ornately decorated riad (a traditional house) to sample the fine food and traditional hospitality. Continuing to Essaouira, with its tranquil squares and cafes, there is plenty of time to explore the narrow lanes and whitewashed houses with their painted blue doors, that could be anywhere in the southern Mediterranean! Yet the massive fortifications on the eastern side of the Medina overlook the Atlantic Ocean and provide a reminder of times when trade flourished between northern Morocco and the great ports of Europe. Time in the spectacular Dades Gorges and a camel ride in the Sahara round off this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3802'>Morocco Explorer</a><br />
Explore Morocco&#039;s Imperial cities and appreciate the rich cultural traditions of music, dance and handicrafts. Walk through the colourful markets and renowned mediaeval medina of Fes in the company of our expert guide, before travelling across the foothills of the Middle Atlas to the deep orange dunes on the edge of the Sahara. In Marrakesh, one of the most important artistic centres in the Islamic world, there is time to bargain in the souqs which reflect a wide variety of handicrafts, crafted by coppersmiths, carpenters, potters and carpet weavers. We include a visit to an ornately decorated riad (a traditional house) to sample the fine food and traditional hospitality. Continuing to Essaouira, with its tranquil squares and cafes, there is plenty of time to explore the narrow lanes and whitewashed houses with their painted blue doors, that could be anywhere in the southern Mediterranean! Yet the massive fortifications on the eastern side of the Medina overlook the Atlantic Ocean and provide a reminder of times when trade flourished between northern Morocco and the great ports of Europe. Time in the spectacular Dades Gorges and a camel ride in the Sahara round off this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3919'>Morocco Explorer</a><br />
Explore Morocco&#039;s Imperial cities and appreciate the rich cultural traditions of music, dance and handicrafts. Walk through the colourful markets and renowned mediaeval medina of Fes in the company of our expert guide, before travelling across the foothills of the Middle Atlas to the deep orange dunes on the edge of the Sahara. In Marrakesh, one of the most important artistic centres in the Islamic world, there is time to bargain in the souqs which reflect a wide variety of handicrafts, crafted by coppersmiths, carpenters, potters and carpet weavers. We include a visit to an ornately decorated riad (a traditional house) to sample the fine food and traditional hospitality. Continuing to Essaouira, with its tranquil squares and cafes, there is plenty of time to explore the narrow lanes and whitewashed houses with their painted blue doors, that could be anywhere in the southern Mediterranean! Yet the massive fortifications on the eastern side of the Medina overlook the Atlantic Ocean and provide a reminder of times when trade flourished between northern Morocco and the great ports of Europe. Time in the spectacular Dades Gorges and a camel ride in the Sahara round off this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3969'>Morocco Explorer</a><br />
Explore Morocco&#039;s Imperial cities and appreciate the rich cultural traditions of music, dance and handicrafts. Walk through the colourful markets and renowned mediaeval medina of Fes in the company of our expert guide, before travelling across the foothills of the Middle Atlas to the deep orange dunes on the edge of the Sahara. In Marrakesh, one of the most important artistic centres in the Islamic world, there is time to bargain in the souqs which reflect a wide variety of handicrafts, crafted by coppersmiths, carpenters, potters and carpet weavers. We include a visit to an ornately decorated riad (a traditional house) to sample the fine food and traditional hospitality. Continuing to Essaouira, with its tranquil squares and cafes, there is plenty of time to explore the narrow lanes and whitewashed houses with their painted blue doors, that could be anywhere in the southern Mediterranean! Yet the massive fortifications on the eastern side of the Medina overlook the Atlantic Ocean and provide a reminder of times when trade flourished between northern Morocco and the great ports of Europe. Time in the spectacular Dades Gorges and a camel ride in the Sahara round off this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4183'>Morocco Adventure</a><br />
Moroccos location on the edge of the Sahara together with its historic trade links with the great ports of Europe have shaped its rich cultural traditions. The incomparable blend of mosques and minarets, spices and scents and great Imperial cities are a constant source of inspiration while our trek in the High Atlas provides a further compelling dimension to our journey. Our travels from Casablanca to Fes and Marrakesh provide a fascinating introduction to the souqs (the teeming markets); the medinas (the complex of palaces, mosques and minarets) and riads (the traditional houses where we sample spicy cuisine and unequalled hospitality) while in the ancient trading port of Essaouira we wander the narrow lanes that could be anywhere in southern Europe. The highlight of our journey is our trek in the Atlas Mountains. We follow trails through traditional Berber villages to alpine pastures where the summits of the High Atlas stretch before us. We also offer a non-technical ascent of Jebal Toubkal (4167m), the highest mountain in Morocco.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4184'>Morocco Explorer</a><br />
Explore Morocco&#039;s Imperial cities and appreciate the rich cultural traditions of music, dance and handicrafts. Walk through the colourful markets and renowned mediaeval medina of Fes in the company of our expert guide, before travelling across the foothills of the Middle Atlas to the deep orange dunes on the edge of the Sahara. In Marrakesh, one of the most important artistic centres in the Islamic world, there is time to bargain in the souqs which reflect a wide variety of handicrafts, crafted by coppersmiths, carpenters, potters and carpet weavers. We include a visit to an ornately decorated riad (a traditional house) to sample the fine food and traditional hospitality. Continuing to Essaouira, with its tranquil squares and cafes, there is plenty of time to explore the narrow lanes and whitewashed houses with their painted blue doors, that could be anywhere in the southern Mediterranean! Yet the massive fortifications on the eastern side of the Medina overlook the Atlantic Ocean and provide a reminder of times when trade flourished between northern Morocco and the great ports of Europe. Time in the spectacular Dades Gorges and a camel ride in the Sahara round off this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2199'>Cape Town to Nairobi</a><br />
4WD Game Drives, Bushwalks in the Kalahari, Spice Island, Serengeti, Ngorongo Crater, the&quot;Big 5&quot;. This journey is chock full of diverse cultures, abundant wildlife, spectacular landscapes, stunning beaches, and a ton of adventure. This is our ultimate African odyssey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2234'>Dunes, Deltas&amp;Falls Explorer</a><br />
Enjoy the best of southern Africa in style! Marvel at the wildlife, culture and scenery of this fascinating region. Highlights include game drives, bush walking in the Kalahari, canoeing in the Okavango Delta and visiting the mighty Victoria Falls.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2297'>Cape and Dunes Explorer</a><br />
Namibia is a nature and adventure lover&#039;s dream. The world&#039;s highest sand dunes, deep canyons, exciting activities, breathtaking scenery and a little game viewing combine for a memorable journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2302'>Botswana and Falls Adventure</a><br />
Explore Chobe by boat, admire the stunning views of Victoria Falls, enjoy game drives through some of Africa&#039;s best parks, and take a jouney into the stunning Okavango Delta by canoe. This is a true adventure into the untouched African wilderness of Botswana.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2308'>Kruger and Swaziland Express</a><br />
From the game reserves, to the beaches of Mozambique, to the frenetic vibe of Durban and everything along the way. Southern Africa has a unique and interesting cultural diversity, which you&#039;ll experience first-hand on this exciting journey through the Rainbow Nation.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2311'>South Africa Encompassed</a><br />
From exciting game drives to the cosmopolitan vibe of Cape Town and everything along the way, this adventure has it all. Enjoy big game viewing, rural cultures, stunning scenery, beaches and modern cities.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2325'>Cultural Kenya</a><br />
This cultural trip of Kenya&#039;s hidden treasures gets well off the usual tourist route. You will embark on guided walks to unique destinations, and absorb the cultures and ways of life of a number of local peoples, including a home stay with villagers from the Luo tribe.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2326'>Cultural Kenya&amp;Kilimanjaro</a><br />
A three week cultural odyssey through Kenya, with a climbing challenge in Tanzania - Mt. Kili! Climb Africa&#039;s highest peak, the tallest freestanding mountain in the world, after you go on an off-the-beaten-path safari to experience the rich cultures of the people of Kenya.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2327'>Cultural Kenya&amp;Zanzibar</a><br />
The culture of Kenya mixes with the spices and beaches of Zanzibar on this perfect trip to some of East Africa&#039;s hidden treasures and most famous island. From homestays and walks with local villagers to a spice plantation tour on Zanzibar, this trip offers up a plethora of memorable experiences.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip1978'>Africa Drums</a><br />
See an abundance of wildlife in the Ngorongoro Crater, Masai Mara and Serengeti National Parks, not forgetting the flamingos at Lake Nakuru. Visit a Masai village and find out more about these striking people, their culture and way of life. Discover the spice island of Zanzibar with its impressive architecture, beautiful beaches, excellent diving and fantastic seafood.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2329'>Nairobi to Vic Falls&amp;Botswana</a><br />
Over a month of exploring the wild continent, from Kenya, down through Tanzania, Malawi and Zambia, then over to Botswana. Amazing wildlife, intriguing cultures and breathtaking scenery make up this diverse journey of adventure and discovery.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2805'>Rift Valley Wildlife</a><br />
Introduction: The best game viewing you can fit into 13 days - elephant, lion, wildebeest, black & white rhino, antelope of every kind, zebra and giraffe seen through the great Rift Valley and in the confined space of the Ngorongoro Crater. Meet the Masai Mara people and if you're lucky, experience a migration. See Mt Kilimanjaro's snow capped peaks from a distance or for the more adventurous, add on the Kilimanjaro Climb.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3010'>Okavango and Falls</a><br />
Introduction: Francistown, inhabited for 80,000 years, is the first stop, before travelling through the Kalahari desert to the Okavango Delta. Travel through the waterways of this National Park by traditional mokoro, spotting hippos and maybe even a sitatunga(antelope). Chobe's next for an evening river cruise and game drive before finishing at Victoria Falls. The sight and sound of 550,000 cubic metres of water cascading down every minute is truly incredible; combined with adventure sports and game viewing, it makes for a unique National Park. This tour also runs in reverse - contact us for details and dates
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3028'>Livingstones Africa</a><br />
Introduction: Follow in Livingstone's footsteps on this journey taking in the Masai Mara, Ngorongoro Crater and Mikumi National Parks for exceptional game viewing. Relax on Zanzibar island and Lake Malawi, which covers a quarter of the country and is the third largest lake in Africa, before ending up at Victoria Falls. Take the Flight of Angels option to get the full magnitude of this incredible waterfall.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3030'>Southern Explorer</a><br />
Introduction: Your chance to see the migration in the Masai Mara, up to 30,000 animals in the Ngorongoro Crater and relax on Zanzibar, enjoying the beaches, diving or snorkelling. Head to Mikumi National Park to see if you can spot lion, leopard and black backed hyena. Next is a few days at Lake Malawi, preparing yourself for the adrenaline rush of Victoria Falls.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3574'>Ultimate Wildlife Safari</a><br />
Introduction: A game viewing extravaganza starting with the Masai Mara and Ngorongoro Crater. Also included are Mikumi National Park, Matobo National Park, Victoria Falls National Park, Kruger National Park and walk with lions at Antelope Park. Explore the untouched beauty of Mozambique, taking a 2 day sailing trip through the Bazaruto Islands, follow the beautiful beaches down the coastline and see the old colonial architecture of Maputo.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3589'>Africa in Focus</a><br />
Introduction: Heading out from Johannesburg, start with the water based National Parks, The Okavango Delta and Chobe, where you can spot hippos and a variety of birdlife. Then try out the adventures on offer at Victoria Falls. Lake Malawi is next, with the option of diving or snorkelling this freshwater lake. Spot elephant in Mikumi National Park before a well deserved rest on Zanzibar. Prepare for the game viewing opportunities of the Ngorongoro Crater and Lake Nakuru National Park, before ending your tour in Nairobi.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3635'>High Atlas Trek</a><br />
A superb introduction to the mountains and traditions of Morocco. The trip combines visits to the medinas and riads of Marrakesh with a trek through Berber villages in the High Atlas Mountains. We follow trails through traditional villages to alpine pastures set beneath the impressive backdrop of the High Atlas. An ascent of Jebal Toubkal is an added bonus on this exhilarating trek before travelling to the coast and the remarkable port town of Essaouira.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4129'>High Atlas Trek</a><br />
A superb introduction to the mountains and traditions of Morocco. The trip combines visits to the medinas and riads of Marrakesh with a trek through Berber villages in the High Atlas Mountains. We follow trails through traditional villages to alpine pastures set beneath the impressive backdrop of the High Atlas. An ascent of Jebal Toubkal is an added bonus on this exhilarating trek before travelling to the coast and the remarkable port town of Essaouira.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4374'>Tanzanian Safari-Usambara-Pangani-Zanzibar Adventure Package #4</a><br />
This is a wonderful adventure to "get it all"- Tanzanian wildlife safari, beaches and snorkeling, cultural tours and walks. Itinerary in brief: Day 1: Arrive at Kilimanjaro Airport, overnight at Springlands Hotel Day 2: Day trip to Marangu Water Falls Day 3-9: 7 days Safari (4 days game drive and 3 days cultural tour) Day 10-11: Easy walking in Lushoto Area in the Usambara Mountains Day 12-14: 3 days Pangani (Tanzanian coast) Day 15-18: 4 days Zanzibar Day 18: 1 day Dar es Salaam and Depart from Dar es Salaam International Airport
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2301'>Delta and Falls Explorer</a><br />
Botswana is a mecca for nature enthusiasts. From the flooded plains of the Delta to the elephant rich Chobe, Botswana is sure not to disappoint. A glimpse into Zambia offers the spectacle of Victoria Falls, one of the most amazing natural wonders of the world.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2305'>South Africa Discoverer</a><br />
Explore South Africa&#039;s fascinating cultural diversity on this exciting journey through the Rainbow Nation. This trip takes in so much of the South African experience, from the Addo Elephant Park to the unforgettable flow of Cape Town and everything along the way.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3148'>HISTORIC ROUTE</a><br />
Visit the historic North of Ethiopia - the Blue Nile, castles, monasteries, rock-hewn churches and hear the story of the Queen of Sheba.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2296'>Serengeti&amp;Masai Mara Explorer</a><br />
This accommodated safari offers fantastic insight into the diverse nature and landscape of East Africa, and is an ideal&quot;first&quot;time safari. Expect a mix of wildlife and culture experiences, with a great chance to view the&quot;Big Five&quot;or the seasonal wildebeest migration!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2299'>Masai Mara Explorer</a><br />
This is the ideal safari adventure for those travellers interested in diverse wildlife, people and scenery. A comprehensive introduction to Kenya, this tour visits all of Kenya&#039;s highlights, from Samburu Game Reserve and Lake Nakuru to the vast world famous Masai Mara Game Reserve.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2806'>Serengeti, Crater and Zanzibar</a><br />
Introduction: The open savannah of the Serengeti and enclosed eco-system of the Ngorongoro Crater provide a contrasting view of African wildlife and landscapes. Added to this is the spice island of Zanzibar; take a tour to find, smell & taste the spices, explore the alleyways of Stone Town with its imposing doors, dive or snorkel the unspoilt reefs or simply sit back in one of the bars and enjoy the African sunset.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2812'>Southern Highlights - Clockwise</a><br />
Introduction: Explore the Botswanan Okavango Delta by mokoro before heading up to the mighty Victoria Falls, where there's the option to try all the adrenaline sports on offer. Walk with lions, sail through the Bazaruto Islands on a dhow and enjoy unspoilt Indian Ocean beaches along Mozambique's coast. Be surrounded by colonial architecture in Maputo, and see how much wildlife you can spot in the Kruger National Park before ending in Johannesburg.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3029'>East Africa Express</a><br />
Introduction: From Victoria Falls head through Livingstone National Park to Lake Malawi, where you have a few days to relax on the beach before setting off for game viewing at Mikumi National Park. Another couple of days relaxing, this time on Zanzibar then its off on the game viewing trail again at the Ngorongoro Crater and Lake Nakuru National Park. The best overview of Africa in the shortest time.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3150'>HISTORY AND CULTURE</a><br />
Combine our Historic and Omo Valley Tours for a full experience of Ethiopia from North to South.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2235'>Serengeti Explorer</a><br />
A comprehensive introduction to Tanzania, this tour visits famous and wildlife rich parks such as Lake Manyara National Park, Ngorongoro crater and the vast plains of the Serengeti!
</ul></div>

</div>
</body>
</html>
