<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Welcome::News &amp; Weather Source</title>
<link href="nw-style.css" rel="stylesheet" type="text/css" />
<base target='_blank' />
</head>

<body class='scroll'>

    <p>

<div>
<ul>
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNHd78auD5qIzG8EobArc_zDzxcU3w&url=http://www.usatoday.com/story/news/world/2013/10/25/biological-mother-of-roma-girl/3187121/' target="_blank">Test proves Bulgarian woman mother of mystery girl - USA TODAY</a><br />
Washington PostTest proves Bulgarian woman mother of mystery girlUSA TODAYSOFIA, Bulgaria (AP) — Bulgarian authorities say DNA tests have confirmed that a 35-year-old Roma woman is the mother of a mysterious girl in Greece known as Maria. Bulgaria&#39;s Interior Ministry announced the results of the test Friday after matching the&nbsp;DNA test confirms mother in &#39;Maria&#39; case: Bulgarian authoritiesCTV NewsBulgarian Roma couple are parents of &#39;Maria&#39; found in Greek camp - DNA testsReuters UKTest prove Roma couple are mystery girl&#39;s parentsSan Francisco ChronicleCNN&nbsp;-Zee Newsall 1,435 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNFsJDRERZZqSUTUDI5ukulnVL8shw&url=http://www.voanews.com/content/german-european-officials-to-confront-us-over-spy-allegations/1776863.html' target="_blank">German, European Officials to Confront US Over Spy Allegations - Voice of America</a><br />
Voice of AmericaGerman, European Officials to Confront US Over Spy AllegationsVoice of AmericaSenior German officials and European lawmakers say they are going to Washington soon to confront officials about allegations the U.S. has been spying on its allies. Germany said Friday that the heads of its foreign and domestic intelligence agencies would&nbsp;EU says distrust of US on spying may harm terror fightBBC NewsEU leaders warn US spying scandal may hamper fight against terrorCNNGrowing list of countries protest US spyingUSA TODAYWall Street Journal&nbsp;-Reuters&nbsp;-CTV Newsall 1,394 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNFMzs9pXCiqMUQQzzb-GCrjzBySrw&url=http://timesofindia.indiatimes.com/world/china/China-rejects-ousted-politician-Bo-Xilais-appeal/articleshow/24689026.cms' target="_blank">China rejects ousted politician Bo Xilai's appeal - Times of India</a><br />
Times of IndiaChina rejects ousted politician Bo Xilai&#39;s appealTimes of IndiaJINAN, China: A court on Friday dismissed ousted politician Bo Xilai&#39;s appeal against his conviction and life sentence for corruption and abuse of power in one of China&#39;s most politically charged trials in decades. The ruling by the Shandong provincial higher&nbsp;China Court Upholds Bo Xilai Conviction, Life TermABC NewsChinese Court Rejects Bo Xilai&#39;s AppealVoice of AmericaBo Xilai: Court rejects appeal against convictionBBC NewsThe Australian&nbsp;-The Independentall 164 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNHnGzAVep7IMj3X8Up9Y7fhBa9jGw&url=http://www.reuters.com/article/2013/10/25/us-eu-migrants-idUSBRE99O0NB20131025' target="_blank">EU leaders rebuff calls for action on Europe's migration crisis - Reuters</a><br />
AFPEU leaders rebuff calls for action on Europe&#39;s migration crisisReutersBy Adrian Croft and Justyna Pawlak. BRUSSELS | Fri Oct 25, 2013 10:55am EDT. BRUSSELS (Reuters) - European Union leaders rebuffed calls from southern European states on Friday for emergency action to tackle a wave of illegal migration from Africa&nbsp;Italian coast guards rescue 700 migrants as EU leaders promise actionCNN InternationalEU Pledges to Share Migrant Burden With Italy After Sea DeathsBusinessweekItaly: 700 Refugees Saved at Sea Amid EU DeadlockABC NewsVoice of America&nbsp;-CBC.ca&nbsp;-euronewsall 107 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNFPmVEyNSwUmCpZzxXTd5ftO78KOg&url=http://world.time.com/2013/10/25/boxing-champ-running-for-president-in-ukraine/' target="_blank">Boxing Champ Running For President in Ukraine - TIME</a><br />
BBC NewsBoxing Champ Running For President in UkraineTIMEUkrainian heavy weight boxing champion Vitali Klitschko announced Thursday that he&#39;s running for president in 2015. Klitschcko, who BBC reports is the first declared contender against the incumbent Viktor Yanikovych, made the made the announcement on&nbsp;Vitali Klitschko to run for president in UkraineDaily MailKlitshcko Wants To Run For Ukrainian PresidencyRadioFreeEurope/RadioLibertyUkraine Boxer Klitschko to Run for PresidentVoice of AmericaHouston Chronicle&nbsp;-euronewsall 98 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNEUV0zL4inVqOfSxXB-gBHGvObL5g&url=http://www.foxnews.com/world/2013/10/24/americans-kidnapped-by-pirates-off-coast-nigeria-official-says/' target="_blank">Pirates kidnap two Americans in ship attack off coast of Nigeria - Fox News</a><br />
ABC NewsPirates kidnap two Americans in ship attack off coast of NigeriaFox NewsPirates have attacked a U.S.-flagged oil platform supply vessel off the coast of Nigeria and kidnapped two Americans, a senior U.S. official tells Fox News. The attack on the C-Retriever ship, which is owned by Louisiana-based Edison Chouest Offshore,&nbsp;Pirates Kidnap 2 Americans off Nigerian CoastU.S. News & World Report2 seized in pirate attack off Nigeria, US official saysCNNPirates kidnap two US sailors off Nigerian coast -sourcesReutersVoice of America&nbsp;-NBCNews.com&nbsp;-ABC Onlineall 268 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNHN32KS50NrmchLgVlj3cEFO81-3A&url=http://abcnews.go.com/International/wireStory/icc-kenya-deputy-president-attend-trial-20679054' target="_blank">ICC Says Kenya Deputy President Must Attend Trial - ABC News</a><br />
AFPICC Says Kenya Deputy President Must Attend TrialABC NewsThe International Criminal Court on Friday overturned a decision excusing Kenya&#39;s deputy president from attending his trial on charges of orchestrating deadly violence after his country&#39;s 2007 election. The decision by appeals judges means William Ruto&nbsp;Africa&#39;s Relationship With ICC to Be DiscussedAllAfrica.comGovt Pushes for Delay As ICC Trial of Kenyatta LoomsVoice of AmericaKenya asks Security Council to delay International Criminal Court trials of Washington PostThe Globe and Mail&nbsp;-AFP&nbsp;-Kansas City Starall 160 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNE-A0aq1xoaGTyiDbMeudFECecT6g&url=http://www.bbc.co.uk/news/uk-politics-24653147' target="_blank">Mr Cameron aims to focus EU leaders' attention on cutting bureaucracy - BBC News</a><br />
BBC NewsMr Cameron aims to focus EU leaders&#39; attention on cutting bureaucracyBBC NewsTime and again British leaders would come to Brussels pledging to defend their &quot;red lines&quot; in negotiations. As these had often been thrashed out in advance behind the scenes, they could go home with &quot;victory&quot; secured. This time it isn&#39;t red lines, but red tape.UPDATE 1-France resists British push to cut EU regulationReutersCameron says Snowden and media spy leaks &#39;helping enemies&#39;Reuters UKCameron attacks &#39;lah-di-dah, airy-fairy&#39; ideas about spy agencies, as he reveals Daily MailKL.FM 96.7&nbsp;-Financial Timesall 48 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNE3ciXpv2I_z8DF5bLbsb1gM5KcJg&url=http://ideas.time.com/2013/10/25/forbidden-to-drive-a-saudi-woman-on-life-inside-the-kingdom/?xid%3Dgonewsedit' target="_blank">Forbidden to Drive: A Saudi Woman On Life Inside the Kingdom - TIME</a><br />
The HinduForbidden to Drive: A Saudi Woman On Life Inside the KingdomTIMEA woman drives a car in Saudi Arabia October 22, 2013. A conservative Saudi Arabian cleric has said women who drive risk damaging their ovaries and bearing children with clinical problems, countering activists who are trying to end the Islamic kingdom&#39;s&nbsp;Saudi women take the wheel en masse – and dare leaders to catch upChristian Science MonitorSaudi Arabia seeks native convicted of sex assault in ColoradoFox NewsTaking the wheel in drive for rightsSydney Morning HeraldBusinessweek&nbsp;-The Hindu&nbsp;-ABC Newsall 730 news articles&nbsp;&raquo;
<li><a href='http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNHYcjP5R1a9-ITriEa9jXIqQM_PiQ&url=http://www.bbc.co.uk/news/uk-england-manchester-24666591' target="_blank">3D printer 'gun parts' found in Manchester raid - BBC News</a><br />
Daily Mail3D printer &#39;gun parts&#39; found in Manchester raidBBC NewsA 3D printer and suspected &quot;homemade&quot; gun components seized during police raids in Manchester are being examined. Detectives initially said the parts were a &quot;plastic magazine and trigger&quot; that could make a &quot;viable&quot; gun. A man who was arrested in&nbsp;UK police cast doubt on 3D-printed &#39;gun parts&#39;BusinessweekUK police raise specter of 3-D printer-made gunsCNNPolice may have jumped the gun with claims they found first 3D gun factory after Daily MailTechCrunch&nbsp;-Zee Newsall 136 news articles&nbsp;&raquo;
</ul></div>



  </p>
</body>
</html>
