<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="style.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body style="background: url(images/ssn-img-info-bkgd.jpg) no-repeat">
<h4>Europe Trips</h4>
<div id="info" class="scroll">
<div>
<ul>
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2211'>Explore England</a><br />
Journey back through time as you explore Medieval England, visiting fascinating historical sites in and around London, Cambridge and York. The year 1066 is of enormous importance in English history because the Norman invasion in that year capped a millennium of invasions, and since then there have been no more. The conquest of England, led by William the Conqueror, replaced English aristocrats with French-speaking Normans, dominating castles were built and the feudal system was imposed. This period of history continued through the 14th century, leaving behind a rich legacy of impressive architecture as well as captivating stories.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2741'>iExplore Budapest, Vienna&amp;Prague Gold</a><br />
Hungary&#039;s paprika-laced cuisine and steamy thermal spas offer a bit more heat and spice than you might expect from an eastern European country. But then Hungary, which got a jump on opening its borders to the West, also had a head start in hospitality. There are few bureaucratic barriers to exploring its attractions, from the striking capital of Budapest, curving along the grand Duna (Danube) to its remote villages, known for their superb folk art.Austria is full of such rich cultural offerings and traditions, many of them left over from the time when Vienna was the seat of a powerful empire. These days, the capital&#039;s imperial buildings may seem a bit grand and oversized for this small country. But there is nothing diminished about the country&#039;s romantic streak or its passion for rituals, whether in the coffeehouse, the church or the grand ballroom. Austria seems to blend a kind of Italian romanticism with a Germanic love for order. And that orderly romanticism can be quite captivating, particularly when experienced by way of a Sacher torte, a hike through the mountains of Tirol or a stroll along Vienna&#039;s Ringstrasse.For most visitors to the Czech Republic all roads lead no farther than Prague, the most westernized, cosmopolitan city, known for its wondrous charm and stunning beauty.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2753'>iExplore Portugal</a><br />
Savoring life slowly is a Portuguese passion, and much of the best is humble - traditional folk festivals; simple, honest food drowning in olive oil; music that pulls at the heart strings, recalling past love and glories; and markets overflowing with fish, fruit and flowers.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2754'>iExplore Russia</a><br />
Russia breathes superlatives: the world&#039;s biggest country; its largest supplier of natural gas and second-largest oil producer; and home of the planet&#039;s longest railroads, busiest subway system (Moscow&#039;s), and one of its deepest, biggest, and oldest lakes (Baikal, in Siberia). It even boasts balmy beach resorts (on the Black Sea), though the Kremlin and the snowcapped cupolas of its cathedrals seem truer reflections of this northern nation&#039;s might and mysticism.What the country lacks in climatic warmth, Russians make up for with their bottomless generosity and jovial hospitality. Survivors of despots from Ivan the Terrible to Stalin, Russians place high value on keeping their home worlds safe from the perils of without and stocking the larders with homemade jams, pickles, and desserts. The past decade has been rough on Russians, but it&#039;s sharpened their adaptation skills. Today&#039;s Russian university graduates know more languages, more about financial markets, and more about text messaging than many of their Western counterparts.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2755'>iExplore Russia Silver</a><br />
Today&#039;s Russia is often exhilarating, sometimes ominous. Everyday life goes on amid a jumble of trial-and-error capitalism, glitzy casinos, billboard politics, czar mania and slick gangster-hangout restaurants. Some observers have suggested that 30%-40% of Russia&#039;s economy is controlled by organized crime. Add to the mix a religious revival: Hundreds of newly renovated Russian Orthodox churches are offering services in Moscow alone.So far, travelers haven&#039;t been affected directly by the country&#039;s turmoil or corruption. But conditions are changing so quickly that you should keep a very close eye on the news. And you should be aware that despite all the new doors that have opened and the greater flow of information, there are still plenty of murky areas in Russia - sudden changes of rules, unexpected shortages and mysterious surcharges. Nevertheless, you&#039;ll find that the overall quality of hotels, restaurants and services, while wildly variable, is improving.In any case, travelers should be flexible, tolerant and patient - and aware of risks. Russia can be both an enthralling adventure and a tiring ordeal. For those willing to endure the risks and inconveniences, Russia is simply a fascinating place - from the imperial beauty of Moscow and St. Petersburg to the bleakly romantic Siberian countryside.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2757'>iExplore Scandinavia Gold</a><br />
Once the home of marauding Vikings, Denmark is now a snug and comfortable country. Like its people, the country&#039;s sights are impressive without being imposing. Copenhagen, the country&#039;s capital, is a modern, international city that has managed to remain cozy and compact  most of the sights are only a short walk away. Outside Copenhagen, the countryside offers graceful castles, stout churches and small fishing villages that seem to have been lifted from a story by Hans Christian Andersen.Norway is Europe&#039;s great parkland: a dramatic mix of mountains, seas, forests and fjords. While the country has tidy cities, historic buildings and distinctive artists, nature is clearly its prime attraction. The country has astonishing variety  the serene rural landscapes around Oslo are nothing like the deep fjords along the western coast, and the countryside along the zigzagging roads to Bergen could not be more unlike the stark, barren land around Alta or the sunny coves of the south coast.In Sweden, you can travel quickly from the sophisticated to the wild. Sweden is a diverse land filled with lakes, forests, mountains, valleys, beaches, islands, quaint villages and urban centers. There&#039;s a feeling of spaciousness in many regions because of Sweden&#039;s low population density. Stockholm, the country&#039;s capital, is a progressive city with pockets that maintain a village feel.Finland can appear to be two countries  one in winter, another in summer. In summer, when the sun never quite sets, you&#039;ll find a lively, outgoing people who never seem to rest. Long days mean more time for galleries, museums, cafes, live music of all kinds and, especially, the great outdoors. The country has an abundance of scenic lakes, islands, forests and pristine wilderness to explore.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2758'>iExplore Scotland Gold</a><br />
Scotland is a beautiful and sparsely populated country with rolling lowland, dramatic mountains, lochs and many offshore islands. These days, Scotland&#039;s cities  which have always been considered a bit, well, gloomy  have become as popular as the pastoral countryside. The annual Edinburgh International Festival, which gets bigger and zanier every year, is one of the hottest arts tickets in Europe. With the opening in 1999 of its Parliament, Scottish politics is abloom as well.Even with all that activity, Scotland has plenty of places to get away from it all. In the Highlands, you can walk for hours across misty moors and clamber up and down rocky slopes without seeing a soul, and only a shaggy Highland cow or a thread of smoke curling from a cottage chimney will dispel the feeling of blissful solitude. And when you&#039;re ready for company, you&#039;ll find it at friendly pubs and inns: For all its air of wildness, reinforced by its rebellious history and its moody weather, Scotland has a wonderfully cozy and warm side. The Scots (not Scotch  that&#039;s what you drink) have a strong hospitable streak and a great sense of humor.Scotland&#039;s geography is characterized by the fabled Highlands, the lowlands and its coastline, which is cut by firths (similar to fjords). The national symbol, the thistle, combines with evergreens and heather to enhance the countryside. And while the land can be bleak or even barren in places, the nation has many lush, dramatic and heart-stopping scenes of beauty in others. Industry is concentrated in the central valley of Scotland and around the main cities, especially Glasgow.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2768'>iExplore Spain</a><br />
Spain is Europe&#039;s second most mountainous country (only Switzerland has a higher terrain), and the climate varies dramatically according to altitude as well as latitude. In the province of Granada it is possible to ski in the mountains and lounge on a beach, both in the same day. True alpine conditions prevail in many of Spain&#039;s mountains, from the Pyrenees along the border with France to the Sierra Nevada above Granada in the south, while the central two-fifths of the country is primarily high plains crossed by mountain ranges and rivers. Besides the mainland peninsula, Spanish possessions include the Mediterranean Balearic Islands, the Canary Archipelago (in the Atlantic off the coast of Africa) and the Moroccan coastal enclaves of Ceuta and Melilla.Mainland Spain can be divided into three climatic zones: the Oceanic in the north (the rainiest and greenest part along the Bay of Biscay); the Mediterranean Zone (sunny and semiarid); and central Spain (hot in summer, cold in winter, relatively dry). Spain is also divided into distinctive, politically autonomous regions, each with its own culture and history, and several with their own languages (including Catalonia, Galicia and the Basque region). Hot, arid Andalusia, to the southwest, is the home of flamenco, bullfighting and spectacular Moorish architecture.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2770'>iExplore Switzerland Gold</a><br />
The popularized image of Switzerland is almost too perfect and timeless: spectacular Alpine scenery, cozy mountain chalets, dazzling ski runs, window boxes spilling over with red geraniums, tidy cities set on serene lakes, elegant grand hotels. Though you&#039;ll undoubtedly encounter these along the way, they don&#039;t present a complete picture of this modern country. Switzerland may guard its neutrality and assert its independence, but it is very much an active participant in the world.If you&#039;re going for the scenery or for the skiing, there are few places that can equal it (in quality or high prices). And there are few places as clean, safe and orderly as Switzerland. Likewise, few countries have such diversity in terms of culture and language: German is prevalent in Zurich and the northern, central and eastern regions; French in Geneva and the western region; Italian in Lugano and the southern region; and Romansh in St. Moritz and the southeastern region. Despite its varied cultures and linguistic traditions, Switzerland is one of the most politically and economically stable countries in the world.iExplore Switzerland Gold features private-guided touring in picturesque Lucerne, a journey aboard the famous Glacier Express train to Zermatt (with its spectacular views of the Matterhorn) as well as the popular Chocolate Train to Broc. Throughout your visit you will stay in Switzerlands most luxurious and historic hotels.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2771'>iExplore Switzerland Silver</a><br />
The popularized image of Switzerland is almost too perfect and timeless: spectacular Alpine scenery, cozy mountain chalets, dazzling ski runs, window boxes spilling over with red geraniums, tidy cities set on serene lakes, elegant grand hotels. Though you&#039;ll undoubtedly encounter these along the way, they don&#039;t present a complete picture of this modern country. Switzerland may guard its neutrality and assert its independence, but it is very much an active participant in the world.If you&#039;re going for the scenery or for the skiing, there are few places that can equal it (in quality or high prices). And there are few places as clean, safe and orderly as Switzerland. Likewise, few countries have such diversity in terms of culture and language: German is prevalent in Zurich and the northern, central and eastern regions; French in Geneva and the western region; Italian in Lugano and the southern region; and Romansh in St. Moritz and the southeastern region. Despite its varied cultures and linguistic traditions, Switzerland is one of the most politically and economically stable countries in the world.iExplore Switzerland Silver includes visits to picturesque Lucerne, the delightful Alpine village of Grindelwald, and trendy Montreux, with many opportunities for hiking or other activities. This trip features travel by train from city to city as well an excursion aboard the popular Chocolate Train, with accommodations in charming first class hotels throughout.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2783'>iExplore Turkey Gold</a><br />
Turkey is a paradise of sun, sea, mountains, and lakes that offers the vacationer a complete change from the stress and routine of everyday life. From April to October, most places in Turkey have an ideal climate that is perfect for relaxing on sandy beaches or enjoying the tranquility of mountains and lakes.Turkey also has a magnificent past, and is a land full of historic treasures from 13 successive civilizations spanning 10,000 years. Even if you spend only a short time in Turkey, you can see a lot of this great past.There is no doubt that one visit will not be enough, and you will want to come back again and again as you discover one extraordinary place after another. All of them, no matter how different, have one thing in common: the friendly and hospitable people of this unique country.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2784'>iExplore Turkey Silver</a><br />
Turkey is a paradise of sun, sea, mountains, and lakes that offers the vacationer a complete change from the stress and routine of everyday life. From April to October, most places in Turkey have an ideal climate that is perfect for relaxing on sandy beaches or enjoying the tranquility of mountains and lakes. Turkey also has a magnificent past, and is a land full of historic treasures from 13 successive civilizations spanning 10,000 years. Even if you spend only a short time in Turkey, you can see a lot of this great past. There is no doubt that one visit will not be enough, and you will want to come back again and again as you discover one extraordinary place after another. All of them, no matter how different, have one thing in common: the friendly and hospitable people of this unique country.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2800'>Provence: An Adventure of the Heart</a><br />
Tailor Made Tours of Provence. Where to start when visiting Provence? To reach what you are coming to this enchanted land for you will need a guide, someone to take you to the secret places that make the heart sing and allow the experience real Provence. Your choices are endless: enjoy a glass of Chateauneuf du Pape with the maker of the wine in his private cellar, visit a heavenly lavender distillery in the heart of Frances lavender production, take a speed boat to lunch in a secluded restaurant on the Mediterranean coast, be guided to your hearts desire in that chic boutique you thought only existed in your dreams, or let us take you to places you havent even imagined yet. These are experiences set up exclusively for you, to allow you to know the richness of this land and her people. Nothing like a large group tour that shows you clichés, this is for travelers with a desire for an adventure of the heart, and authentic contact with a magical place.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2926'>iExplore Baltics Gold</a><br />
Estonia is heir to a legacy of medieval castles and pagan ruins, German manor houses and grim Soviet skyscrapers. Despite the rapid changes the country has experienced since it regained its independence from the Soviet Union in 1991, there&#039;s still a lot of tradition. While Tallinn, the capital, has been dramatically transformed by the influx of foreign investment, its well-preserved Old Town retains its medieval charm.Latvia has been forging its own distinctive style in recent years. In the capital, Riga, elegant and whimsical Art Nouveau buildings are surrounded by blocks of Soviet-era concrete structures. While no longer &quot;the Paris of the north&quot; (as it was once called), Riga is the cosmopolitan hub of the Baltics. You&#039;ll find good food and nightlife, with a growing international flair.Lithuania has been busy doing away with the drab remnants of its Soviet past, and restoring the wonderful old buildings that represent its earlier history. In Vilnius, the capital, hundreds of grand old baroque buildings have been artfully renovated into well-appointed hotels, shops and cafes. Lithuania is more agricultural than the other Baltic nations, which gives it a slower pace and a bit more charm. While the nation as a whole is intensely Roman Catholic, you can still detect traces of pre-Christian religions influencing life in the countryside, where elaborate wooden sculptures of ragana (witches) and barzdukais (gnomes) are almost as common as crosses.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2936'>iExplore Croatia&amp;Slovenia Gold</a><br />
Croatia borders Slovenia, Hungary, and Bosnia and Herzegovina and is close to Austria and Italy. In the interior of the country are mountains dotted with vineyards, castles, lakes and waterfalls. Zagreb, the capital, is situated in the north-central part of the country. The rugged Dalmatia coast is simply spectacular, with towering mountains forming a backdrop for the long, narrow strip of land and rock that is washed by the clear waters of the Adriatic. Offshore, there are more than a thousand islands, some uninhabited and others endowed with ancient villages. Travelers can choose their favorites for sunbathing, swimming or exploring. Istria (or Istra to locals) is the triangular peninsula that forms the northwestern part of the Croatian coast. Its proximity to the Italian border has long made it a popular resort area for European aristocracy.Take a little bit of Bavaria, a sliver of Mediterranean Riviera, a stretch of the Danube, a touch of Venice and a slice of the Balkans - and you have Slovenia, one of Eastern Europe&#039;s best kept secrets. This charming little country, which declared independence from Yugoslavia in 1991, walked away relatively unscathed from the turmoil that engulfed the rest of the region. It took along with it some of everything that travelers enjoy in this part of the world: mountains and lakes, castles and alpine forests, vineyards and meadows, beaches and island resorts.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2937'>iExplore Croatia</a><br />
Explore the rugged Dalmatia coast with towering mountains forming a backdrop for the long, narrow strip of land and rock that is washed by the clear waters of the Adriatic.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2939'>iExplore Czech Republic</a><br />
For most visitors to the Czech Republic all roads lead no farther than Prague, the most westernized, cosmopolitan city, known for its wondrous charm and stunning beauty.If you really wish to discover the richness of this immensely cultured nation, however, venturing beyond Prague will be very rewarding. The magnificent, undulating landscape consists of mountains and upland plains, forests and farmland. Thanks to the fact that the country was spared widespread destruction during World War II, many of its cities and towns are a visual feast of medieval, baroque and art nouveau architecture and sculpture. Bohemian spa towns and sleepy Moravian wine villages alike have a historical integrity and welcoming atmosphere that gives you the feeling of being immersed in an open-air museum. The country also boasts over 100 castles - from craggy fortresses to more refined, aristocratic chateaus - that are open to the public.Today, venturing off the beaten path no longer means leaving comfort and service behind. The number and quality of restaurants and hotels in large and small towns alike has soared over the past five years, attracting more visitors while remaining relaxed and un-crowded
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2951'>iExplore England Gold</a><br />
Journey back through time as you explore Medieval England, visiting fascinating historical sites in and around London, Cambridge and York. The year 1066 is of enormous importance in English history because the Norman invasion in that year capped a millennium of invasions, and since then there have been no more. The conquest of England, led by William the Conqueror, replaced English aristocrats with French-speaking Normans, dominating castles were built and the feudal system was imposed. This period of history continued through the 14th century, leaving behind a rich legacy of impressive architecture as well as captivating stories.Your tour begins in London, where you stay in the heart of the City and explore medieval sites that survived the Great Fire of 1666. Next, visit Cambridge and discover the charming old towns and villages that dot the nearby countryside. Continue to York, the capital of the north for nearly 2000 years. Its city walls, built during the 13th century, are among the most impressive surviving medieval fortifications in Europe. They encompass a thriving centre with medieval streets, grand Georgian town houses, riverside pubs and modern shops. The crowning glory is York Minster, Englands largest Gothic cathedral.The Lake District is one of Englands most beautiful corners, a magical mix of dainty green dales, stark, rocky mountains and sparkling lakes.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2954'>iExplore France - Paris Extension</a><br />
For visitors, all of France can seem like a market  it&#039;s one of those rare countries where every region offers something worthwhile and distinctive. Paris represents the height of fashion, art and food  its sense of style is so strong it intimidates some visitors, yet the city can also be remarkably comfortable and intimate.&quot;The City of Light&quot; has been written about, filmed and photographed countless times. Although it seems as if we all know Paris even before we see it, nothing compares to actually being there. The experience of going up the Eiffel Tower, walking along the Seine at dusk or sipping coffee at an elegant sidewalk cafe are uniquely Parisian experiences  and they are nothing like they are portrayed in movies. Whether you&#039;re in Paris for work or for fun, follow the Parisians&#039; lead and enjoy yourself in this city that offers something special for everyone. For the art lover, the Louvre and the Musee d&#039;Orsay offer priceless collections, and the designer shops of the Rue du Faubourg St.-Honore tempt the serious shopper. And, for anyone who enjoys food, Paris&#039; restaurants, from inexpensive neighborhood bistros to the most refined and elegant gourmet restaurant, promise wonderful meals.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2955'>iExplore France Gold</a><br />
This popular and scenic region in the southeast corner of France has come to worldwide attention thanks in large part to the books of Peter Mayle, the British expatriate who chronicled its charms and curiosities so warmly. True to his description, the Luberon section of Provence is breathtaking: purple lavender fields, craggy olive trees, multicolored vineyards, cliffs, gorges and ancient villages. But Provence&#039;s appeal goes much further back, and artists over the centuries have been captivated by the quality of the light in the countryside. You really have to see it to believe it.The larger cities and towns of Provence  notably Aix-en-Provence, Marseille, Avignon and Arles  all have their merits, but it&#039;s the region&#039;s small towns where the true colors of Provence really shine. Take note, however, that it can be very hot (and touristy) in summer, and the famous mistral wind can be vicious in winter. Spring and fall are the best times to visit.Food in Provence is superb  this, after all, is the country&#039;s prime fruit and vegetable-producing area. Regional specialties are tapenade (an olive-and-herb paste), bouillabaisse (an outstanding fish and shellfish soup flavored with tomatoes, saffron, thyme and garlic), anchoiade (anchovy, oil and garlic paste), daube (braised meat, poultry, fish or game), marcassin (young wild boar) and panade (fruit tart). Even the common potato chip, fried in oil and spiced with various herbs, is elevated to an art in Provence.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2964'>iExplore Greece Gold</a><br />
At the ancient site of Delphi, where the Greeks once consulted the Oracle about the future, there&#039;s a small round sculpture. It&#039;s known as the omphalos - the cosmic belly button. The Greeks believed that Delphi was the very center of the world - the place where it all came into being. Indeed, many aspects of Western culture came into being in Greece - drama, art, philosophy and science.It&#039;s a heady feeling to walk on stones that may have been trod by Plato, Homer or Agamemnon. But at many places in Greece, where ancient ruins are surrounded by the noise and smells of traffic, or where pristine island beaches are packed by topless sunbathers, it&#039;s apparent that the influence works the other way as well: Greece, it sometimes seems, has been overtaken by the modern world it spawned.The trick for travelers in Greece is to find the golden mean - in this case, the balance between environment and history, between crowds and quiet, between ancient and modern. With a bit of planning (and maybe a query to the Oracle), you can find beautiful settings that can soothe your soul, while centuries of art and history invigorate your mind. And very likely, you&#039;ll be as charmed by the Greek people as you are by their landscape. During our last trip, we learned the Greek shortcut to communication - dancing. Growing frustrated with our attempts to speak in rudimentary Greek, an elderly Greek woman in a small island village grabbed us by the arm and began dancing. It was late at night, and we whirled around the terrace by moonlight, barriers dropping by the second.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2970'>iExplore Iceland Gold</a><br />
Iceland&#039;s stark, pristine scenery has been shaped by fire and ice. More than 200 volcanoes and numerous glaciers form the country&#039;s landscape. It&#039;s a frozen land that&#039;s always letting off steam. Its U-shaped valleys, jagged lava fields, monstrous icecaps, hot springs and geysers have carved a rugged, bizarre landscape you won&#039;t see anywhere else on Earth.About 80% of Icelands land is lava desert, glaciers or lakes  the only arable areas are on the coast. Despite its relative isolation and uncultivable terrain, Iceland has one of the highest standards of living in the world, with sky-high prices to match. Icelanders, like many islanders, are self-confident and reserved, but once you break the ice, so to speak, they are among the friendliest in the world.Explore the scenic highlights of both south and north Iceland by private vehicle with your own guide on this exciting itinerary. Experience Iceland&#039;s widely varied landscapes with opportunities for hiking, whale-watching and horseback riding.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2971'>iExplore Iceland Silver</a><br />
Iceland&#039;s stark, pristine scenery has been shaped by fire and ice. More than 200 volcanoes and numerous glaciers form the country&#039;s landscape. It&#039;s a frozen land that&#039;s always letting off steam. Its U-shaped valleys, jagged lava fields, monstrous icecaps, hot springs and geysers have carved a rugged, bizarre landscape you won&#039;t see anywhere else on Earth.About 80% of Icelands land is lava desert, glaciers or lakes  the only arable areas are on the coast. Despite its relative isolation and uncultivable terrain, Iceland has one of the highest standards of living in the world, with sky-high prices to match. Icelanders, like many islanders, are self-confident and reserved, but once you break the ice, so to speak, they are among the friendliest in the world.This tour offers the scenic highlights of both south and north Iceland, with sightseeing excursions by motor coach to the island&#039;s most popular destinations. Optional excursions by Super Jeep are also available at an additional charge.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2979'>iExplore Italy Gold - Venice, Florence&amp;Rome</a><br />
A visit to Italy is a lesson in living well. Open-air vegetable and fruit markets, neighborhood bakeries and fresh cheeses made daily are fixtures of Italian life. Tradition reigns: Neighbors still meet in the piazza to discuss the day, laundry is still line-dried, even in the largest of cities, and the passeggiata (leisurely stroll) is still made in the evening air  preferably with a gelato in hand. From the mountains to the coasts, the emphasis is on simple pleasures and high quality.On this essential highlights tour, visit Italys most magical cities: Venice, Florence and Rome. Built on over 100 islets, linked by 400 bridges, Venice is the only city in the world that is built entirely on water. The city has captivated poets, painters and writers for centuries and continues to charm visitors with its fragile beauty. Florence, birthplace of the Renaissance, is one of the most beautiful cities in the world. Its palaces, churches and museums overflow with masterful paintings and sculpture. The Eternal City of Rome, sprawling among its seven hills, is fascinating for both its ancient and its modern wonders. All that surrounds a visitor in Rome  the stunning art and architecture, the grandeur of scale and the citys lively citizens  guarantee an unforgettable visit.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2980'>iExplore Italy Gold - Amalfi Coast</a><br />
Stretching for 30 miles (50km) along a promontory from Sorrento to Salerno is some of Europe&#039;s most spectacular coastline: the Amalfi Coast. The road hugs the tight bends and curves of the cliffy coast, overlooking intensely blue waters and passing postcard villages that cling to the cliff walls like matchbox houses.Your tour begins in Naples, with its picturesque waterfront and historic old town center, and includes a visit to the fascinating Roman ruins of Pompeii. The coastal town of Positano provides a delightful base for further explorations of the Amalfi Coast as well as a daytrip to the romantic island of Capri.There are several opportunities for walking or hiking along beautiful coastal trails. Also enjoy a cooking class in the seaside town of Sorrento, where you can sample your own version of the region&#039;s fabulous cuisine.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2981'>iExplore Italy Gold - Tuscany</a><br />
Tuscany offers a feast for the senses: magnificent architecture, an extraordinary collection of art, picturesque countryside, and some of Italys finest cuisine and wines.Florence, birthplace of the Renaissance, is one of the most beautiful cities in the world. Its palaces, churches and museums overflow with masterful paintings and sculpture. Tuscany features some of Italys most impressive hill towns and offers great opportunities for walking. Enjoy hearty meals of Tuscan specialties, accompanied by the regions famous Chianti wines.iExplore Italy - Tuscany Gold features private guided sightseeing in Florence and the hill towns of Tuscany. This tour also includes two cooking classes offered by top local chefs, to give you an opportunity to experience Tuscan cooking first-hand.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2982'>iExplore Italy Silver - Amalfi Coast</a><br />
Stretching for 30 miles (50km) along a promontory from Sorrento to Salerno is some of Europe&#039;s most spectacular coastline: the Amalfi Coast. The road hugs the tight bends and curves of the cliffy coast, overlooking intensely blue waters and passing postcard villages that cling to the cliff walls like matchbox houses.Your tour begins in Naples, with its picturesque waterfront and historic old town center, and includes a visit to the fascinating Roman ruins of Pompeii. The coastal town of Positano provides a delightful base for further explorations of the Amalfi Coast as well as a daytrip to the romantic island of Capri.There are several opportunities for walking or hiking along beautiful coastal trails, including the aptly named Pathway of the Gods, a 5-mile (8 km) trail that leads to Positano.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2983'>iExplore Italy Silver - Venice, Florence&amp;Rome</a><br />
A visit to Italy is a lesson in living well. Open-air vegetable and fruit markets, neighborhood bakeries and fresh cheeses made daily are fixtures of Italian life. Tradition reigns: Neighbors still meet in the piazza to discuss the day, laundry is still line-dried, even in the largest of cities, and the passeggiata (leisurely stroll) is still made in the evening air  preferably with a gelato in hand. From the mountains to the coasts, the emphasis is on simple pleasures and high quality.On this essential highlights tour, visit Italys most magical cities: Venice, Florence and Rome. Built on over 100 islets, linked by 400 bridges, Venice is the only city in the world that is built entirely on water. The city has captivated poets, painters and writers for centuries and continues to charm visitors with its fragile beauty. Florence, birthplace of the Renaissance, is one of the most beautiful cities in the world. Its palaces, churches and museums overflow with masterful paintings and sculpture. The Eternal City of Rome, sprawling among its seven hills, is fascinating for both its ancient and its modern wonders. All that surrounds a visitor in Rome  the stunning art and architecture, the grandeur of scale and the citys lively citizens  guarantee an unforgettable visit.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2411'>Amalfi Coast</a><br />
Follow ancient pathways linking isolated farms, quaint villages and exquisite churches; the outstanding beauty of the Amalfi coast can only be fully appreciated on foot. Our base is a former 16th century monastery surrounded by gardens, terraces, lemon groves and grape vines, where meals are overlooking the crystalline waters of the Mediterranean.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2700'>Catalonia Walking Adventure</a><br />
Experience the medieval villages, vibrant cities and authentic culture of Catalonia, culminating in a hiking excursion to the remote Nuria Valley. For those with limited time, this 8-day hiking adventure is an ideal way to get to know this region of Spain, known for its dense forests, rolling hills, dormant volcanoes and stark cliff faces.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2701'>Spain Hike, Bike&amp;Raft</a><br />
This active adventure is the ideal way to experience the medieval villages and beautiful scenery of SpainÂs Catalonia region. Highlights include a biking adventure along SpainÂs Bici Carril, a rafting excursion and some of SpainÂs best hiking, plus some of the best food in all of Europe.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2708'>Great Moorish Experience</a><br />
Marvel at the history and beauty of Spain on this 15-day exploration that will delight your senses and stimulate your imagination. From the galleries and wild nightlife of Madrid, to the Muslim monuments, flamenco and vibrant culture of Andalucia, to the architecture, cuisine and cool style of Barcelona, Spain is sure not to disappoint.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4315'>Experience a stay at a Castle in Tuscany in comfort and luxury!</a><br />
One week stay at Castello di Orgiale breakfast included
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4317'>A wellness retreat in medieval Tuscany hamlet with utmost luxury</a><br />
One week stay at Le Case del Borgo for any of the villas including wine therapy at the on-site spa, welcome package with wine & Tuscany goods, aperitif at Vinarium wine bar with hosts & access to all facilities including Jacuzzi, pool and vita parcours.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4319'>Tuscany villa rental with a flair</a><br />
One week vacation at Casamora including welcome package & olive oil tasting tour, gift products and accomodation with access to all facilities such as library, theatre, wine-bar, restaurant and pool.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4301'>Spain and Portugal Sampler</a><br />
The Iberian Peninsula is home to two of EuropeÂs most beautiful and fascinating countries. Enjoy SpainÂs bustling cities, stunning countryside and beautiful National Parks while PortugalÂs relaxed atmosphere, interesting culture and glorious coastline will enchant you.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2260'>Day in Soomaa national park</a><br />
Soomaa means "marshland" in Estonian. Waters are extraordinary here. On the guided day-trip you will explore wetlands by walking on the bog trail and canoeing on the river.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2707'>The Moorish Empire</a><br />
The Andalucia region of Spain is home to beautiful beaches, a fascinating history and rich local culture. IslamÂs mark is deeper here than anywhere in Spain, embedded in the architecture and people alike. The home of Flamenco and birthplace of the guitar, Andalucia boasts a unique artistic tradition and some of SpainÂs most lively nightlife.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4318'>Incredible bed & breakfast, wine-tour and dining opportunity in Tuscany!</a><br />
One week stay at boutique hotel Locanda di San Francesco for 2 people, breakfast, two dinners,wine tour and special discounts included.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2454'>Italy Hike, Bike and Raft</a><br />
Tuscany and Umbria are two of ItalyÂs most spectacular regions, offering lots of natural beauty and unparalleled hiking and biking opportunities. This 15-day active tour explores the best of Italy - past and present. For those who want to experience the real Italy, this tour has it all.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2698'>Catalonia By Bike</a><br />
Enjoy scenic countryside vistas, medieval buildings and the Mediterranean Sea on this 8-day biking adventure. Travel along SpainÂs Bici Carril, passing through rural Catalonian villages and sunflower fields.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2699'>Costa Brava Explorer</a><br />
The rugged Costa Brava ranks among SpainÂs most beautiful coastlines, where history, culture, art, and scenery combine with CataloniaÂs famous cuisine to make the trip of a lifetime. Visit the ruins of Emp&uacute;ries and medieval towns and explore the exciting region that gave birth to eccentric surrealist artist Salvador Dali.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3595'>Middle East Discovery</a><br />
Introduction: Turkey is the gateway to the Middle East and Syria introduces us to the delights of a truly traditional Arab world. Turkey, Jordan and Syria blend a delightful and alluring mix of cultures, cuisine and architecture, where the people are exceptionally hospitable. From Turkey's ancient historical sites to the lunar landscape of Cappadocia, you move on to Aleppo still hawking its wares to modern day buyers, to the impressive Roman desert city of Palmyra and then to the vibrant old city of Damascus with its souks and bazaars, before arriving in Amman via the Roman ruin of Jerash. This tour also runs in reverse - call for details
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3598'>Middle East Express</a><br />
Introduction: Explore the scenes of classic Greek and Roman authors, Homer and Virgil. Visit the city of Troy and discover where Achilles was slain and the legendary wooden horse caused the defeat of the Trojans. Turkey, Syria and Jordan are steeped in legend and history and the mists of time will evaporate before your eyes as you probe deeper into this fascinating region. Plenty of opportunity for action too, swimming or diving in the Red Sea, and the Wadi Rum desert is as haunting as ever. This tour also runs in reverse - call for details
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip1988'>Central Europe</a><br />
Discover Europe's hidden gems and stunning highlights: Paris's wonderful museums and cafe society and Florence's Ponte Vecchio bridge, or take a day trip to Pompeii to marvel at the dramatic ruins in the shadow of Mount Vesuvius. Wander the canals that link Venice's 117 islands and around the fairy tale turrets of Neuschwanstein - Ludwig II's Walt Disney-like castle. Travel through chilly mountain air to Alpine lakes and forests and through two millenniums of Italian history. Participate in exciting outdoor activities then kick back and relax on a Mediterannean beach - Europe's vibrant spirit is packed into this exciting 4-week itinerary! **you can also start this tour from Paris**
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2713'>The Pilgrim&#039;s Way</a><br />
Follow the ancient pilgrimage route to the Galician city of Santiago de Compostela, which houses the tomb of the Apostle St. James. On this challenging but rewarding hike, we cover 260 km of the Spanish portion of this historic trail, visiting ancient churches and quaint mountain villages all along the way.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4292'>Deborah Krasner's Cook Umbria Culinary Vacations</a><br />
If you love Italy, you will love Cook Umbrias Culinary Vacations. Experience Italian life like a native. Be welcomed into an extended Italian artisanal food family and cook alongside them and with Deborah Krasner, James Beard Award-winning cookbook author, and Artisan Umbria's Madi Gandolfo. Hunt truffles with our friend Fausto and his truffle hound; feed wild boar in the local forest; visit inspiring home kitchens and make fresh pasta, gnocchi, pizza and bread with our friend Francesca. See mozzarella being made by hand and work alongside the village butcher to make a fabulous Italian sausage. All week long youll taste and learn to create the authentic flavors of Umbrias matchless cuisine.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4316'>All included dine & Wine, luxury tour in Tuscany</a><br />
One week luxury wine & dine tour in Tuscany all included.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip1995'>Middle East Overland</a><br />
Starting in Istanbul, a cultural melting pot of different cuisines and architectural styles, you literally spend five weeks journeying through living history. In many parts of the region, culture and lifestyle remain unchanged giving you insights into an ancient worls. You will not forget camping under the stars in the Western Desert or sailing in a felucca down the Nile.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2236'>Greek Islands Adventure (Athens to Kos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2379'>Greek Islands Adventure (Athens to Mykonos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2380'>Greek Islands Adventure (Athens to Mykonos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2381'>Greek Islands Adventure (Athens to Santorini)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2382'>Greek Islands Adventure (Athens to Santorini)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2383'>Greek Islands Adventure (Kos to Athens)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2384'>Greek Islands Adventure (Kos to Athens)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2385'>Greek Islands Adventure (Kos to Mykonos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2386'>Greek Islands Adventure (Kos to Mykonos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2387'>Greek Islands Adventure (Kos to Santorini)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2388'>Greek Islands Adventure (Kos to Santorini)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2394'>Greek Islands Adventure (Mykonos to Santorini)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail 8 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2395'>Greek Islands Adventure (Mykonos to Santorini)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2396'>Greek Islands Adventure (Mykonos to Santorini)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail 8 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4394'>Farewell Wine Tour</a><br />
A celebrated California, Charles B Mitchell, celebrates his retirement in Provence, France on a wine and food tour to beat them all. Fun, adventure, and privileged events are the highlights of this remarkable week in the south of France.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2391'>Greek Islands Adventure (Mykonos to Kos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2392'>Greek Islands Adventure (Mykonos to Kos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2397'>Greek Islands Adventure (Santorini to Athens)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2398'>Greek Islands Adventure (Santorini to Athens)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2401'>Greek Islands Adventure (Santorini to Mykonos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling, and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2402'>Greek Islands Adventure (Santorini to Mykonos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and don&#039;t forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2403'>Greek Islands Adventure (Santorini to Mykonos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail 8 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2389'>Greek Islands Adventure (Mykonos to Athens)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2390'>Greek Islands Adventure (Mykonos to Athens)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and don&#039;t forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2399'>Greek Islands Adventure (Santorini to Kos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2400'>Greek Islands Adventure (Santorini to Kos)</a><br />
A yacht adventure is the ideal way to experience what many consider the worldÂs most beautiful islands: the Greek Islands. Sail for up to 22 days aboard our 50-foot yachts, with time for hiking, snorkelling and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and donÂt forget to try the Ouzo!
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3661'>Best of Turkey</a><br />
A journey to capture the diversity of landscapes and cultural pulse of Turkey. We combine the classic highlights with forays into some of the countries more unusual places. From Istanbul we journey to the lunar landscape of Cappadocia, in central eastern Turkey, famous for the underground cities and extraordinary rock formations scattered throughout the Goreme Valley. Konya, famous for its Whirling Dervishes and Antalya where we set sail on our well-appointed &#039;gullet (wooden motorized yacht) are next on the itinerary. During our time aboard there are plenty of opportunities for swimming and snorkeling in the clear Aegean waters and exploring the ancient towns that characterise this exquisite coastline. An overland cultural odyssey takes us to the ancient cities of Ephesus and Troy, before visiting Gallipoli. Time to explore the Grand Bazaar, Topkapi Palace and Blue Mosque in Istanbul completes this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3736'>Best of Turkey</a><br />
A journey to capture the diversity of landscapes and cultural pulse of Turkey. We combine the classic highlights with forays into some of the countries more unusual places. From Istanbul we journey to the lunar landscape of Cappadocia, in central eastern Turkey, famous for the underground cities and extraordinary rock formations scattered throughout the Goreme Valley. Konya, famous for its Whirling Dervishes and Antalya where we set sail on our well-appointed &#039;gullet (wooden motorized yacht) are next on the itinerary. During our time aboard there are plenty of opportunities for swimming and snorkeling in the clear Aegean waters and exploring the ancient towns that characterise this exquisite coastline. An overland cultural odyssey takes us to the ancient cities of Ephesus and Troy, before visiting Gallipoli. Time to explore the Grand Bazaar, Topkapi Palace and Blue Mosque in Istanbul completes this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3737'>Best of Turkey</a><br />
A journey to capture the diversity of landscapes and cultural pulse of Turkey. We combine the classic highlights with forays into some of the countries more unusual places. From Istanbul we journey to the lunar landscape of Cappadocia, in central eastern Turkey, famous for the underground cities and extraordinary rock formations scattered throughout the Goreme Valley. Konya, famous for its Whirling Dervishes and Antalya where we set sail on our well-appointed &#039;gullet (wooden motorized yacht) are next on the itinerary. During our time aboard there are plenty of opportunities for swimming and snorkeling in the clear Aegean waters and exploring the ancient towns that characterise this exquisite coastline. An overland cultural odyssey takes us to the ancient cities of Ephesus and Troy, before visiting Gallipoli. Time to explore the Grand Bazaar, Topkapi Palace and Blue Mosque in Istanbul completes this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3841'>Best of Turkey</a><br />
A journey to capture the diversity of landscapes and cultural pulse of Turkey. We combine the classic highlights with forays into some of the countries more unusual places. From Istanbul we journey to the lunar landscape of Cappadocia, in central eastern Turkey, famous for the underground cities and extraordinary rock formations scattered throughout the Goreme Valley. Konya, famous for its Whirling Dervishes and Antalya where we set sail on our well-appointed &#039;gullet (wooden motorized yacht) are next on the itinerary. During our time aboard there are plenty of opportunities for swimming and snorkeling in the clear Aegean waters and exploring the ancient towns that characterise this exquisite coastline. An overland cultural odyssey takes us to the ancient cities of Ephesus and Troy, before visiting Gallipoli. Time to explore the Grand Bazaar, Topkapi Palace and Blue Mosque in Istanbul completes this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3859'>Best of Turkey</a><br />
A journey to capture the diversity of landscapes and cultural pulse of Turkey. We combine the classic highlights with forays into some of the countries more unusual places. From Istanbul we journey to the lunar landscape of Cappadocia, in central eastern Turkey, famous for the underground cities and extraordinary rock formations scattered throughout the Goreme Valley. Konya, famous for its Whirling Dervishes and Antalya where we set sail on our well-appointed &#039;gullet (wooden motorized yacht) are next on the itinerary. During our time aboard there are plenty of opportunities for swimming and snorkeling in the clear Aegean waters and exploring the ancient towns that characterise this exquisite coastline. An overland cultural odyssey takes us to the ancient cities of Ephesus and Troy, before visiting Gallipoli. Time to explore the Grand Bazaar, Topkapi Palace and Blue Mosque in Istanbul completes this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3860'>Best of Turkey</a><br />
A journey to capture the diversity of landscapes and cultural pulse of Turkey. We combine the classic highlights with forays into some of the countries more unusual places. From Istanbul we journey to the lunar landscape of Cappadocia, in central eastern Turkey, famous for the underground cities and extraordinary rock formations scattered throughout the Goreme Valley. Konya, famous for its Whirling Dervishes and Antalya where we set sail on our well-appointed &#039;gullet (wooden motorized yacht) are next on the itinerary. During our time aboard there are plenty of opportunities for swimming and snorkeling in the clear Aegean waters and exploring the ancient towns that characterise this exquisite coastline. An overland cultural odyssey takes us to the ancient cities of Ephesus and Troy, before visiting Gallipoli. Time to explore the Grand Bazaar, Topkapi Palace and Blue Mosque in Istanbul completes this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4061'>Best of Turkey</a><br />
A journey to capture the diversity of landscapes and cultural pulse of Turkey. We combine the classic highlights with forays into some of the countries more unusual places. From Istanbul we journey to the lunar landscape of Cappadocia, in central eastern Turkey, famous for the underground cities and extraordinary rock formations scattered throughout the Goreme Valley. Konya, famous for its Whirling Dervishes and Antalya where we set sail on our well-appointed &#039;gullet (wooden motorized yacht) are next on the itinerary. During our time aboard there are plenty of opportunities for swimming and snorkeling in the clear Aegean waters and exploring the ancient towns that characterise this exquisite coastline. An overland cultural odyssey takes us to the ancient cities of Ephesus and Troy, before visiting Gallipoli. Time to explore the Grand Bazaar, Topkapi Palace and Blue Mosque in Istanbul completes this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4062'>Best of Turkey</a><br />
A journey to capture the diversity of landscapes and cultural pulse of Turkey. We combine the classic highlights with forays into some of the countries more unusual places. From Istanbul we journey to the lunar landscape of Cappadocia, in central eastern Turkey, famous for the underground cities and extraordinary rock formations scattered throughout the Goreme Valley. Konya, famous for its Whirling Dervishes and Antalya where we set sail on our well-appointed &#039;gullet (wooden motorized yacht) are next on the itinerary. During our time aboard there are plenty of opportunities for swimming and snorkeling in the clear Aegean waters and exploring the ancient towns that characterise this exquisite coastline. An overland cultural odyssey takes us to the ancient cities of Ephesus and Troy, before visiting Gallipoli. Time to explore the Grand Bazaar, Topkapi Palace and Blue Mosque in Istanbul completes this fascinating journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2376'>Trekking Mont Blanc</a><br />
Trek the Alps from France to Italy and Switzerland; cross glaciers and pine forests, visit remote villages and mountain refuges and finish your days with local cuisine and wines. The Mont Blanc region boasts one of the worldÂs premier hiking circuits and the highest mountain in Western Europe.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2203'>Trans Siberian Adventure</a><br />
The Trans Siberian train journey has captured the imagination of travellers for many decades. This superb itinerary combines the classic train route with stopovers at many of the unique and exciting destinations enroute. Beginning in the Chinese capital Beijing there is ample time to witness the iconic attractions of this great city. Continuing to Ulaanbaatar, we head to the Mongolian Steppe for a taste of nomadic life, staying in comfortable ger camps and experiencing the vast grasslands and the warm hospitality of the people with some ''Airag', the fermented mares milk which is a favourite of the Mongolians. The next stage of our train journey takes us to Irkutsk in the heart of Siberia. Lake Baikal is a highlight of this region, and we take time to explore the natural beauty of the surrounds by boat and on foot. The final stage of our journey takes us to the cities of Moscow and St Petersburg where we soak up the immense history through visits to Red Square and the Kremlin in Moscow and the Hermitage in St Petersburg, as well as a multitude of lesser known sites which our Russian hosts will uncover.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2224'>Via Ferrate - Hiking In The Dolomites</a><br />
Via Ferrate - Hiking In The Dolomites The breathtaking pinnacles of the Dolomites have always been well known to climbers around the world. During the First World War, the Dolomite mountain range was the scene of heavy fighting and became an almost continuous front throughout the war, from Cortina d'Ampezzo in the west to the Predil Pass in the east. Making full use of their elite Alpine mountain troops, the Italians had to fix iron ladders and wire cables to the rock to enable them to fight on the vertical walls
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3671'>Cycling The Great Glen Scotland</a><br />
&lt;p&gt;Cycle from Inverness, the capital of the Scottish Highlands, along the shores of Loch Ness to Fort William. During this week long trip we cycle along scenic paths and quiet forest trails with opportunities enroute to spot the wildlife of the region including red deer, stag or golden eagle. A day in Fort William is set aside to rest or ascend Ben Nevis, Scotland&#039;s highest mountain. A train journey takes us across desolate Rannoch Moor to Loch Rannoch, where we continue on bike to the Victorian resort town of Pitlochry, nestled in the Perthshire hills. The final stage is the attractive cycle route to the riverside city of Perth, visiting the historic cathedral of Dunkeld enroute.&lt;/p&gt;&lt;p&gt;Ask about our self-guided version of this trip.&lt;/p&gt;
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3996'>Cycling The Great Glen Scotland</a><br />
&lt;p&gt;Cycle from Inverness, the capital of the Scottish Highlands, along the shores of Loch Ness to Fort William. During this week long trip we cycle along scenic paths and quiet forest trails with opportunities enroute to spot the wildlife of the region including red deer, stag or golden eagle. A day in Fort William is set aside to rest or ascend Ben Nevis, Scotland&#039;s highest mountain. A train journey takes us across desolate Rannoch Moor to Loch Rannoch, where we continue on bike to the Victorian resort town of Pitlochry, nestled in the Perthshire hills. The final stage is the attractive cycle route to the riverside city of Perth, visiting the historic cathedral of Dunkeld enroute.&lt;/p&gt;&lt;p&gt;Ask about our self-guided version of this trip.&lt;/p&gt;
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4094'>Cycling The Great Glen Scotland</a><br />
&lt;p&gt;Cycle from Inverness, the capital of the Scottish Highlands, along the shores of Loch Ness to Fort William. During this week long trip we cycle along scenic paths and quiet forest trails with opportunities enroute to spot the wildlife of the region including red deer, stag or golden eagle. A day in Fort William is set aside to rest or ascend Ben Nevis, Scotland&#039;s highest mountain. A train journey takes us across desolate Rannoch Moor to Loch Rannoch, where we continue on bike to the Victorian resort town of Pitlochry, nestled in the Perthshire hills. The final stage is the attractive cycle route to the riverside city of Perth, visiting the historic cathedral of Dunkeld enroute.&lt;/p&gt;&lt;p&gt;Ask about our self-guided version of this trip.&lt;/p&gt;
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3682'>High Altay Traverse</a><br />
The Altay mountain range covers a vast area stretching over the borders of China, Mongolia, Kazakhstan and into Siberian Russia. Known as the &#039;Golden Mountains&#039;, the highest peaks of the range including Mt Belukha (4506m), are located within the southern reaches of Siberia, home also to the source of Russia&#039;s great rivers, the Ob and the Irtysh. We access the start point of the trek by raft, a superb way to introduce us to the untouched mountain wilderness of birch and pine forests, high alpine meadows and snow capped mountains. In the company of our local crew we ascend through forests of spruce and pine, then flowered meadows to the Sarybel Pass, gaining spectacular views of the range and the Yarlu valley with its multicoloured rocks. Throughout the trek there are opportunities to view wildlife, including many species of deer, and a multitude of alpine flora. Combined with sightseeing in Moscow and Barnaul, this itinerary offers a rich insight into Russia&#039;s culture and vast natural environment.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3759'>High Altay Traverse</a><br />
The Altay mountain range covers a vast area stretching over the borders of China, Mongolia, Kazakhstan and into Siberian Russia. Known as the &#039;Golden Mountains&#039;, the highest peaks of the range including Mt Belukha (4506m), are located within the southern reaches of Siberia, home also to the source of Russia&#039;s great rivers, the Ob and the Irtysh. We access the start point of the trek by raft, a superb way to introduce us to the untouched mountain wilderness of birch and pine forests, high alpine meadows and snow capped mountains. In the company of our local crew we ascend through forests of spruce and pine, then flowered meadows to the Sarybel Pass, gaining spectacular views of the range and the Yarlu valley with its multicoloured rocks. Throughout the trek there are opportunities to view wildlife, including many species of deer, and a multitude of alpine flora. Combined with sightseeing in Moscow and Barnaul, this itinerary offers a rich insight into Russia&#039;s culture and vast natural environment.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3787'>High Altay Traverse</a><br />
The Altay mountain range covers a vast area stretching over the borders of China, Mongolia, Kazakhstan and into Siberian Russia. Known as the &#039;Golden Mountains&#039;, the highest peaks of the range including Mt Belukha (4506m), are located within the southern reaches of Siberia, home also to the source of Russia&#039;s great rivers, the Ob and the Irtysh. We access the start point of the trek by raft, a superb way to introduce us to the untouched mountain wilderness of birch and pine forests, high alpine meadows and snow capped mountains. In the company of our local crew we ascend through forests of spruce and pine, then flowered meadows to the Sarybel Pass, gaining spectacular views of the range and the Yarlu valley with its multicoloured rocks. Throughout the trek there are opportunities to view wildlife, including many species of deer, and a multitude of alpine flora. Combined with sightseeing in Moscow and Barnaul, this itinerary offers a rich insight into Russia&#039;s culture and vast natural environment.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3926'>High Altay Traverse</a><br />
The Altay mountain range covers a vast area stretching over the borders of China, Mongolia, Kazakhstan and into Siberian Russia. Known as the &#039;Golden Mountains&#039;, the highest peaks of the range including Mt Belukha (4506m), are located within the southern reaches of Siberia, home also to the source of Russia&#039;s great rivers, the Ob and the Irtysh. We access the start point of the trek by raft, a superb way to introduce us to the untouched mountain wilderness of birch and pine forests, high alpine meadows and snow capped mountains. In the company of our local crew we ascend through forests of spruce and pine, then flowered meadows to the Sarybel Pass, gaining spectacular views of the range and the Yarlu valley with its multicoloured rocks. Throughout the trek there are opportunities to view wildlife, including many species of deer, and a multitude of alpine flora. Combined with sightseeing in Moscow and Barnaul, this itinerary offers a rich insight into Russia&#039;s culture and vast natural environment.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3954'>High Altay Traverse</a><br />
The Altay mountain range covers a vast area stretching over the borders of China, Mongolia, Kazakhstan and into Siberian Russia. Known as the &#039;Golden Mountains&#039;, the highest peaks of the range including Mt Belukha (4506m), are located within the southern reaches of Siberia, home also to the source of Russia&#039;s great rivers, the Ob and the Irtysh. We access the start point of the trek by raft, a superb way to introduce us to the untouched mountain wilderness of birch and pine forests, high alpine meadows and snow capped mountains. In the company of our local crew we ascend through forests of spruce and pine, then flowered meadows to the Sarybel Pass, gaining spectacular views of the range and the Yarlu valley with its multicoloured rocks. Throughout the trek there are opportunities to view wildlife, including many species of deer, and a multitude of alpine flora. Combined with sightseeing in Moscow and Barnaul, this itinerary offers a rich insight into Russia&#039;s culture and vast natural environment.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4007'>High Altay Traverse</a><br />
The Altay mountain range covers a vast area stretching over the borders of China, Mongolia, Kazakhstan and into Siberian Russia. Known as the &#039;Golden Mountains&#039;, the highest peaks of the range including Mt Belukha (4506m), are located within the southern reaches of Siberia, home also to the source of Russia&#039;s great rivers, the Ob and the Irtysh. We access the start point of the trek by raft, a superb way to introduce us to the untouched mountain wilderness of birch and pine forests, high alpine meadows and snow capped mountains. In the company of our local crew we ascend through forests of spruce and pine, then flowered meadows to the Sarybel Pass, gaining spectacular views of the range and the Yarlu valley with its multicoloured rocks. Throughout the trek there are opportunities to view wildlife, including many species of deer, and a multitude of alpine flora. Combined with sightseeing in Moscow and Barnaul, this itinerary offers a rich insight into Russia&#039;s culture and vast natural environment.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4128'>High Altay Traverse</a><br />
The Altay mountain range covers a vast area stretching over the borders of China, Mongolia, Kazakhstan and into Siberian Russia. Known as the &#039;Golden Mountains&#039;, the highest peaks of the range including Mt Belukha (4506m), are located within the southern reaches of Siberia, home also to the source of Russia&#039;s great rivers, the Ob and the Irtysh. We access the start point of the trek by raft, a superb way to introduce us to the untouched mountain wilderness of birch and pine forests, high alpine meadows and snow capped mountains. In the company of our local crew we ascend through forests of spruce and pine, then flowered meadows to the Sarybel Pass, gaining spectacular views of the range and the Yarlu valley with its multicoloured rocks. Throughout the trek there are opportunities to view wildlife, including many species of deer, and a multitude of alpine flora. Combined with sightseeing in Moscow and Barnaul, this itinerary offers a rich insight into Russia&#039;s culture and vast natural environment.
</ul></div>

</div>
</body>
</html>
