<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="gnbstyle.css" rel="stylesheet" type="text/css">

<base target="_blank">
<title>economists</title>
</head>

<body>
<div id="info">
<div id="column1">
  <h4>World  NEWS From The Economist</h4>
<div>
<ul>
<li><a href='http://www.economist.com/news/briefing/21586360-fight-against-bashar-assad-switches-south-ground-truths?fsrc=rss|bri' target="_blank">The rebellion: Ground truths</a><br />
ON SYRIA’S 360km-long border with Jordan, rebel fighters are not waiting for anyone else to come and clobber Bashar Assad’s regime; they are resolved to do it themselves. They claim to control 100km (60 miles) of the frontier’s more fertile western segment, with forces reaching up to 40km north towards Damascus. On September 11th, Mr Assad’s birthday, reports suggested a significant new advance. At the start of what may prove the biggest battle yet in this region, rebel sources claimed that a force of some 8,000 fighters had captured the northern approaches to the city of Deraa. If so, they have encircled a large government garrison that has been pounding rebel-held villages with artillery.If Deraa were to fall, it would be a signal victory. It is a more important strategic prize than the town of Qusayr on the Lebanese border, the fall of which to Mr Assad’s army in May was heralded as turning the tide in his favour. Along with a heavily fortified border-post farther south, it represents the government’s last stronghold in Syria’s south-west corner. This offensive is the fruit of months of preparation, and the result of quietly intensified efforts by the
<li><a href='http://www.economist.com/news/briefing/21586359-russias-plan-provides-breathing-space-it-probably-unworkable-going-another-round?fsrc=rss|bri' target="_blank">The Syria crisis: Going another round</a><br />
“AMERICA is not the world’s policeman—terrible things happen across the globe, and it is beyond our means to right every wrong.” That world-weary run-up to his conclusion was about the clearest moment in President Barack Obama’s televised address on Syria
<li><a href='http://www.economist.com/news/briefing/21574489-britain-has-many-options-providing-extra-airport-capacity-its-capital-going-need?fsrc=rss|bri' target="_blank">London’s airports: Flight paths for a cloudy future</a><br />
Feel the economic benefit WHEN an Avro Lancastrian—a modified bomber with no gun turrets and a small amount of room for passengers—became the first scheduled flight to take off from Heathrow in 1946, the airport’s passenger terminal was just a row of tents. But it had plenty of room to grow. Within a year, it saw 63,000 passengers. Within five years that had grown to 796,000.Now, with five terminal buildings (one closed at present) and 193 destinations, Heathrow welcomes 70m passengers a year. It is the world’s third-busiest airport; only Atlanta and Beijing see more people come and go. And room to grow is hard to find. Limits on how, and at what time of day, its two runways can be used mean they can take no more flights. The London suburbs press up against the perimeter.The company that owns Heathrow has long wanted to build a third runway to the north of the existing two. The most ambitious form of such a plan, the company says, would increase the number of flights the airport could handle by 46%. But the idea is fiercely opposed by many who live near the airport. Under European Union (EU) law, big airports have to draw up action plans
<li><a href='http://www.economist.com/news/briefing/21569037-why-worlds-most-harmful-fossil-fuel-being-burned-less-america-and-more-europe?fsrc=rss|bri' target="_blank">Coal in the rich world: The mixed fortunes of a fuel</a><br />
IN A high-tech world, dirty black lumps of coal might seem like an anachronism. Yet coal is far from a thing of the past. However whizzy your iPad, your wall-mounted television or your electric car, the chances are that it is powered by the stuff. Coal-fired power stations provide two-fifths of the world’s electricity, and there are ever more of them. In the doubling of the world’s electricity production over the past decade, two-thirds of the increase came from coal. At these rates, coal will vie with oil as the world’s largest source of primary energy within five years. As recently as 2001, it was not much more than half as important as oil (see chart). The main factor has been the unslakable thirst for energy in China, which in 2011 overtook America as the world’s biggest electricity producer. In 2001, according to the International Energy Agency, a club of rich nations, Chinese coal demand was about 600m tonnes of oil equivalent (25 exajoules). By
<li><a href='http://www.economist.com/news/briefing/21569039-europes-energy-policy-delivers-worst-all-possible-worlds-unwelcome-renaissance?fsrc=rss|bri' target="_blank">Europe’s dirty secret: The unwelcome renaissance</a><br />
But wait—there’s more… WHILE coal production and use plummet in America, in Europe “we have some kind of golden age of coal,” says Anne-Sophie Corbeau of the International Energy Agency. The amount of electricity generated from coal is rising at annualised rates of as much as 50% in some European countries. Since coal is by the far the most polluting source of electricity, with more greenhouse gas produced per kilowatt hour than any other fossil fuel, this is making a mockery of European environmental aspirations. How did it happen?The story starts, again, with American shale gas. As American utilities shifted into gas, American coal miners had to look for new markets. They were doing so at a time when slowing Chinese demand was pushing down world coal prices, which fell by a third between August 2011 and August 2012 and is below $100 a tonne. These prices make European utilities willing buyers. European purchases of American coal rose by a third in the first six months of 2012.Compared with the rock-bottom price of gas in America, coal is not all that cheap. But it is a bargain compared with the price of gas in Europe. Although gas
<li><a href='http://www.economist.com/node/21564203?fsrc=rss|bri' target="_blank">Business education: No longer the place to be</a><br />
NOT so long ago business students flocked to Europe. Compared with their American counterparts, European schools were cheaper and their student bodies more diverse, both attractive features—and the salaries of European MBA graduates were often higher, too. Some of these attractions remain undimmed. But they are no longer enough to bring in the punters. Data from The Economist’s latest ranking of full-time MBA programmes (see article) suggest the appeal of an Old World business education has gone into a rapid decline.The intakes of many of Europe’s flagship full-time MBA programmes have plummeted (see chart). Enrolment on Aston Business School’s MBA, for example, more than halved in the past academic year, falling from 129 students to 59. By far the biggest drop was among Asian students. HEC School of Management in Paris enrolled 181 full-time MBAs in the past academic year compared with 233 the previous one. It is a similar story across Europe. Some smaller schools have been desperately scrabbling around to find the 30 students that some MBA rankings see
<li><a href='http://www.economist.com/node/21564204?fsrc=rss|bri' target="_blank">Our “Which MBA?” rankings: Losing the blues</a><br />
DESPITE its reputation as a finance powerhouse, and a churner-out of super-quants, the return of Chicago’s Booth School of Business to the top of The Economist’s full-time MBA rankings is proof that it is a well-rounded school. Our ranking measures the things that MBA students themselves say are important. Not surprisingly, for a degree that can cost more than $100,000, the extent to which a programme opens new career opportunities comes highest on their list. In this regard, Chicago has few peers. Its graduates find employment in the widest range of industries; its students gushed about its careers service. &nbsp;Chicago has topped the ranking for two of the past three years, briefly losing its crown to Dartmouth’s Tuck school last year. North America and Europe account for all the schools in the top 25. The highest-placed school from outside those regions is the University of Queensland, at 27th. The highest-placed Asian school is the University of Hong Kong, which ranks 41st. The Economist ranks schools on four measures: their ability to open new career opportunities; personal development and educational experience; the salary increase graduates can expect; and the potential to network. Data are collected from schools and from a student questionnaire. The full ranking and methodology can be found
<li><a href='http://www.economist.com/node/21543138?fsrc=rss|bri' target="_blank">Energy in India: The future is black</a><br />
STAB a finger at the middle of a map of India and you will hit Nagpur. Some 20 miles (32 kilometres) north-west of the city is a sloping tunnel bored into the rock. Ride two miles down into the gloom, hanging from a wire, and after a torch-lit hike past underground streams and conveyor belts you arrive at a black wall. Sweating men are rigging it with tubes of explosives and wire detonators. Soon they will blast it apart, and down should tumble tonnes of India's most important commodity: coal.In coal India has something as abundant as people. As more Indians enjoy the trappings of middle-class life and the country industrialises, demand for coal-fired electricity will continue to rise smartly, roughly in line with economic growth. India may not have much oil or gas to call its own but it has the world's fifth-largest coal reserves. And it has successfully raised a mountain of the other raw material needed to turn carbon into sparks: capital. Some $130 billion has been ploughed into the power industry in the past five years. Of that, $60 billion or so has come from the private sector—probably the largest-ever private-sector investment India has seen.
<li><a href='http://www.economist.com/node/21542755?fsrc=rss|bri' target="_blank">Natural disasters: Counting the cost of calamities</a><br />
THE world's industrial supply chains were only just recovering from Japan's earthquake and tsunami in March when a natural disaster severed them again in October. An unusually heavy monsoon season swelled rivers and overwhelmed reservoirs in northern Thailand. The floodwaters eventually reached Bangkok, causing a political crisis as residents fought over whose neighbourhoods would flood. But before that the economic toll was being felt farther north in Ayutthaya province, a manufacturing hub. The waters overwhelmed the six-metre-high dykes around the Rojana industrial estate, one of several such parks that host local- and foreign-owned factories.Honda's workers rescued newly built cars by driving them to nearby bridges and hills. The factory ended up under two metres of water and is still closed. Honda was hardly alone: the industrial estates that radiate out from Bangkok are home to many links in the world's automotive and technology supply chains. Western Digital, a maker of computer disk drives which has 60% of its production in Thailand, had two of its factories closed by the floods, sending the global price of drives soaring.Thailand is no
<li><a href='http://www.economist.com/node/21542402?fsrc=rss|bri' target="_blank">The semiconductor industry: Space invaders</a><br />
LAS VEGAS is a city of fast bucks, fast food and fast marriages. It could also be the place where a long war was declared. On January 10th Paul Otellini, the boss of Intel, will address the International Consumer Electronics Show (CES), a vast gathering of gadget-makers, sellers and aficionados in Sin City. He will introduce a phalanx of products showcasing the chips the world's largest semiconductor company most wants to hype.Up on the stage with Mr Otellini will be not just PCs of the sort that the company has powered for decades, but also new slimline PCs known as “ultrabooks”, which are being made by the likes of Toshiba and Hewlett-Packard (HP), and even a couple of smartphones. They represent the front-line of an army of Intel-powered kit going into battle against smartphones and tablets which use processors based on designs from ARM, a British firm.Intel and ARM, pretty much as different in size and approach as competitors can be, have carved up most of the world of microprocessors—the most lucrative bit of the $313 billion global semiconductor market—between them. Each has a well defined patch in which it is pre-eminent. Intel bestrides the market for
<li><a href='http://www.economist.com/node/21542174?fsrc=rss|bri' target="_blank">Heterodox economics: Marginal revolutionaries</a><br />
POINT UDALL on St Croix, one of the US Virgin Islands, is a far-flung, wind-whipped spot. You cannot travel farther east without leaving the United States. Visitors can pose next to a stone sundial commemorating America's first dawn of the third millennium. A couple named “Sigi + Ricky” have added a memento of their own, an arrowstruck heart scrawled on the perimeter wall in memory of “us”.Warren Mosler, an innovative carmaker, a successful bond-investor and an idiosyncratic economist, moved to St Croix in 2003 to take advantage of a hospitable tax code and clement weather. From his perch on America's periphery, Mr Mosler champions a doctrine on the edge of economics: neo-chartalism, sometimes called “Modern Monetary Theory”. The neo-chartalists believe that because paper currency is a creature of the state, governments enjoy more financial freedom than they recognise. The fiscal authorities are free to spend whatever is required to revive their economies and restore employment. They can spend without first collecting taxes; they can borrow without fear of default. Budget-makers need not cower before the bond-market vigilantes. In fact, they need not bother
<li><a href='http://www.economist.com/node/21541388?fsrc=rss|bri' target="_blank">Lessons of the 1930s: There could be trouble ahead</a><br />
“YOU'RE right, we did it,” Ben Bernanke told Milton Friedman in a speech celebrating the Nobel laureate's 90th birthday in 2002. He was referring to Mr Friedman's conclusion that central bankers were responsible for much of the suffering in the Depression. “But thanks to you,” the future chairman of the Federal Reserve continued, “we won't do it again.” Nine years later Mr Bernanke's peers are congratulating themselves for delivering on that promise. “We prevented a Great Depression,” the Bank of England's governor, Mervyn King, told the Daily Telegraph in March this year.The shock that hit the world economy in 2008 was on a par with that which launched the Depression. In the 12 months following the economic peak in 2008, industrial production fell by as much as it did in the first year of the Depression. Equity prices and global trade fell more. Yet this time no depression followed. Although world industrial output dropped by 13% from peak to trough in what was definitely a deep recession, it fell by nearly 40% in the 1930s. American and European unemployment rates rose to barely more than 10% in the recent crisis;
<li><a href='http://www.economist.com/node/21541008?fsrc=rss|bri' target="_blank">Africa’s hopeful economies: The sun shines bright</a><br />
HER $3 billion fortune makes Oprah Winfrey the wealthiest black person in America, a position she has held for years. But she is no longer the richest black person in the world. That honour now goes to Aliko Dangote, the Nigerian cement king. Critics grumble that he is too close to the country's soiled political class. Nonetheless his $10 billion fortune is money earned, not expropriated. The Dangote Group started as a small trading outfit in 1977. It has become a pan-African conglomerate with interests in sugar and logistics, as well as construction, and it is a real business, not a kleptocratic sham.Legitimately self-made African billionaires are harbingers of hope. Though few in number, they are growing more common. They exemplify how far Africa has come and give reason to believe that its recent high growth rates may continue. The politics of the continent's Mediterranean shore may have dominated headlines this year, but the new boom south of the Sahara will affect more lives.From Ghana in the west to Mozambique in the south, Africa's economies are consistently growing faster than those of almost any other region of the world. At least a dozen have
<li><a href='http://www.economist.com/node/21540259?fsrc=rss|bri' target="_blank">The euro: Beware of falling masonry</a><br />
FIRST Greece; then Ireland and Portugal; then Italy and Spain. Month by month, the crisis in the euro area has crept from the vulnerable periphery of the currency zone towards its core, helped by denial, misdiagnosis and procrastination by the euro-zone's policymakers. Recently Belgian and French government bonds have been in the financial markets' bad books. Investors are even sniffy about German bonds: an auction of ten-year Bunds on November 23rd shifted only €3.6 billion-worth ($4.8 billion) of the €6 billion-worth on offer.Worse, there are signs that the euro zone's economy is heading for recession, if it is not there already. Industrial orders in the euro zone fell by 6.4% in September, the steepest decline since the dark days of December 2008. A closely watched index of euro-zone sentiment, based on surveys of purchasing managers in manufacturing and services, is also signalling contraction, with a reading of 47.2: anything below 50 suggests activity is shrinking. The European Commission's index of consumer confidence fell in November for the fifth month in a row.Now an even bigger calamity is looking likelier. The intensifying financial
<li><a href='http://www.economist.com/node/21538700?fsrc=rss|bri' target="_blank">Migration and business: Weaving the world together</a><br />
IN THE flat world of maps, sharp lines show where one country ends and another begins. The real world is more fluid. Peoples do not have borders the way that parcels of land do. They seep from place to place; they wander; they migrate.Consider the difference between China and the Chinese people. One is an enormous country in Asia. The other is a nation that spans the planet. More Chinese people live outside mainland China than French people live in France, with some to be found in almost every country. Then there are some 22m ethnic Indians scattered across every continent (the third Indian base in Antarctica will open next year). Hundreds of smaller diasporas knit together far-flung lands: the Lebanese in west Africa and Latin America, the Japanese in Brazil and Peru, the smiling Mormons who knock on your door wherever you live.Diasporas have been a part of the world for millennia. Today two changes are making them matter much more. First, they are far bigger than they were. The world has some 215m first-generation migrants, 40% more than in 1990. If migrants were a nation, they would be the world's fifth-largest, a bit more numerous than Brazilians, a little
<li><a href='http://www.economist.com/node/21538104?fsrc=rss|bri' target="_blank">South Korea’s economy: What do you do when you reach the top?</a><br />
IT IS a crisp autumn morning in Seoul, and a hopeful fisherman sits dreaming by the Cheonggyecheon stream as the world bustles happily by. Glass skyscrapers rise behind him housing the capital's new financial district. The shopfronts at their base are among the swankiest in Asia. Office workers, families and schoolchildren amble past. Busking fills the air. The water tumbles past plum trees and willows.Twenty years ago, this background would itself have seemed a dream for anyone foolish enough to be trying to fish the Cheonggyecheon. Its waters, dirty and hidden, were trapped beneath a roaring highway; its surroundings were a slum of sweatshops, metal bashing and poverty. The reclamation of the Cheonggyecheon, one of the great urban-regeneration projects of the world, has about it the air of a dream achieved. So, to a large extent, has the Korea through which the stream flows.In 1960, in the aftermath of a devastating war, the exhausted south was one of the poorest countries in the world, with an income per head on a par with the poorest parts of Africa. By the end of 2011 it will be richer than the European Union average, with a gross domestic product per
<li><a href='http://www.economist.com/node/21532276?fsrc=rss|bri' target="_blank">Asset returns: I wouldn’t start from here</a><br />
IT IS better to travel hopefully than to arrive. For investors, the hopeful journey started in the 1980s as inflation came under control around the world. Yields came down, prices went up, a simple “buy and hold” strategy could often provide decent returns. Even boring old Treasury bonds returned 9.1% annually between 1982 and 2007, according to a Deutsche Bank study of long-term returns.At the end of such a journey, though, yields must reach a point where they can fall little if any further. And that explains much of the sorry pass at which investors have now arrived. Almost every asset class seems to be fraught with danger. Equities have suffered two bear markets in just over a decade and remain vulnerable to a rich-world recession; government bonds offer little protection against a resurgence of inflation; commodities are volatile and hostage to a possible drop in Chinese demand; property is still suffering from indigestion after the past decade's boom.
<li><a href='http://www.economist.com/node/21536570?fsrc=rss|bri' target="_blank">Brazil’s oil boom: Filling up the future</a><br />
GEOLOGICAL structures of vast antiquity are more often called on to bolster the arguments of atheists than enlisted as tokens of a deity's existence—let alone his nationality. But the deep Cretaceous salts which trap oil in rocks off Brazil's coast are “strong evidence”, in the words of President Dilma Rousseff, “that God is Brazilian.” It is not a new conceit, but it has rarely been a more apposite one. The pré-sal (“below the salt”) oilfields look set to generate wealth on a scale that could transform Brazil's economy.Before the pré-sal finds, which started in 2007, the country's total proven and probable reserves were 20 billion barrels. Conservative estimates for the total recoverable pré-sal oil now come in at 50 billion barrels: a little less than everything in the North Sea, all in the waters of one country. Optimists expect three times as much. “In the pré-sal area, our exploration has a success rate of 87%, compared with a world average of 20% to 25% for the industry,” says Sergio Gabrielli, the president of Petrobras, Brazil's state-
<li><a href='http://www.economist.com/node/21534753?fsrc=rss|bri' target="_blank">Hedge funds in Asia: The crocodiles are coming</a><br />
ERIC WONG, who helps run his Hong Kong family's money through an investment office, TCG Capital, looks like a hedge-fund manager's dream. He's rich, young and, having been to university there, comfortable with American ways—just the type of investor that Western hedge funds looking for Asian expansion have set their sights on. He is not, however, very interested. Real estate is the “best pension plan my family ever had,” he says. Why change?Where they are not greeted with apathy, Asia-minded hedge funds often face antipathy. Since the financial crisis of the late 1990s “fund” has been a four-letter word throughout Asia. George Soros, a famous hedge-fund investor, is still reviled for aggravating and profiting from the crisis. When the Chinese refer to hedge funds as ju e, or “big crocodiles”, it is not by way of a compliment on their killer instincts.Despite muted interest and outright scorn, though, more and more hedge-fund managers are determined to make their mark on Asia. They see a lot of money to be made, a lack of entrenched competition and a vast number of potential clients.Ravenous growth and maturing equity and credit
<li><a href='http://www.economist.com/node/21533368?fsrc=rss|bri' target="_blank">The European Central Bank: Ready for the ruck?</a><br />
AT THE end of October, after eight years in the top job, Jean-Claude Trichet will pass the presidency of the European Central Bank (ECB) to Mario Draghi. Italy's leading central banker thus takes his place in the front row of the fight to push back the euro crisis, bearing every bit as heavy a responsibility as chancellors and presidents. Whatever plans Europe's political leaders draw up at their summit on October 23rd, the ECB's new head will be a vital part of their success—or failure.Mr Draghi has much in common with the Frenchman he is following. Both have had long careers in public life, including stints at their finance ministries and heading their national central banks. As chairman of the Financial Stability Board, Mr Draghi has been leading international efforts to remedy the ills of global banking. Besides his strong credentials for the job, Mr Draghi shares with Mr Trichet a pragmatic streak, a desirable characteristic when confronting a challenge as grave as the euro crisis.Not all of Mr Draghi's background works in his favour. His brief excursion into the private sector, working at Goldman Sachs between 2002 and 2005, might in some
</ul></div>



</div>

<div id="column2_extended">
<div id="column2" class="scroll">
  <H1>NEWS SOURCES</H1>
  <ul>
  <li><a href="http://abcnews.go.com/">ABC News</a> <br /> Online, breaking news, feature stories and more.
  <li><a href="http://news.bbc.co.uk/">BBC News Front Page</a> <br /> BBC News provides trusted World and UK news as  well as local and regional perspectives.
  <li><a href="http://www.cbsnews.com/sections/world/main202.shtml">CBS News</a>  World Headlines
  <li><a href="http://www.cnn.com/">CNN.com</a> <br />World News with the International Edition
  <li><a href="http://www.msnbc.msn.com/">MSNBC News</a> - Today's news from MSNBC frontpage.
  <li><a href="http://www.msnbc.msn.com/id/3032542/site/newsweek/">Newsweek</a> Online magazine plus daily news, features and commentary from our global network of correspondents.
  <li><a href="http://us.oneworld.net/">One World.net</a>  The OneWorld network and portal brings you the latest news, action, campaigns and organisations in human righs and global issues   across five continents and in 11 different languages.
<li><a href="http://www.time.com/">Time Magazine </a>News Magazine of Current   Events. Read in depth, special reports of local and political news stories.
  <li><a href="http://www.un.org/news/">UN News Centre</a> - Official site for daily UN news, press releases, statements, briefings and calendar of events. Includes UN radio, video,  webcasts, magazines, documents, publications, conference information, photos and   additional information resources. </li>
  <li><a href="http://en.wikinews.org/wiki/Main_Page">Wikinews</a> - Free-content online news source   where any site visitor can add or edit stories.</li>
  <li><a href="http://www.worldnews.com/">World News &ndash; WN Network</a>  World News from the most comprehensive global news network on the internet.
  <li><a href="http://www.worldtribune.com/">World Tribune</a><br />
    Daily online   newspaper specializing in international affairs. Offers exclusive stories and   links to the top news of the day.

  <li>
  </ul>
</div>
<div id="column3">
  <ul>
    <h1>Additional Economist Feeds</h1>
    <li></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/daily_news_and_views_rss.xml">Daily news and views</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://feeds2.feedburner.com/economist/full_print_edition"> Full print edition </a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/the_world_this_week_rss.xml">The world this week</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/letters_rss.xml">Letters</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/leaders_rss.xml">Leaders</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/briefings_rss.xml">Briefings</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/special_reports_rss.xml">Special reports</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/britain_rss.xml">Britain</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/europe_rss.xml">Europe</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/united_states_rss.xml">United States</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/the_americas_rss.xml">The Americas</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/middle_east_and_africa_rss.xml">Middle East and Africa </a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/asia_rss.xml">Asia</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/international_rss.xml">International</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/business_rss.xml">Business</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/finance_and_economics_rss.xml">Finance and economics</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/science_and_technology_rss.xml">Science and technology</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/books_and_arts_rss.xml">Books and arts</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/obituary_rss.xml">Obituary</a></li>
    <li><img src="images/rss_icon.gif" width="12" height="12" align="top" /> <a href="http://www.economist.com/rss/indicators_rss.xml">Indicators </a></li>
    <li></li>
    <li></li>
  </ul>
</div>
<div id="features" class="box"><img src="images/photo_global.jpg" width="107" height="87" hspace="3" align="left" /><a href="http://www.globalpost.com/">Global News &nbsp; |  &nbsp; International News from Around the World</a><br />
  Global news for a digital age, the Global Post redefines
  International news reporting with a team of world
  news correspondents. </div>
<div id="features" class="box"><img src="images/photo_biz.jpg" alt="" width="107" height="87" hspace="3" align="left" /><a href="http://www.ft.com/">World Business &nbsp; |  &nbsp; Finance &nbsp; |  &nbsp; Political News
  from FT.com</a><br />
  The latest UK and international business, finance, economic and political news, comment and analysis from the Financial Times on FT.com. </div>
<div id="features" class="box"><img src="images/photo_shop.jpg" width="107" height="87" hspace="3" align="left" /><a href="http://www.amazon.com/">Amazon.com  &nbsp; |  &nbsp; Online Shopping</a><br />
  Online Shopping from the earth's biggest selection of books, magazines, music, DVDs, videos, games, electronics, computers&amp; office, software, apparel &amp; accessories, shoes, jewelry, <br />
  home &amp; garden, grocery, health &amp; beauty, toys, kids &amp; baby, <br />
  sports &amp; outdoors, tools, auto &amp; industrial.........and more &gt;</div>

</div>
</div>
</body>
</html>
