<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="allstyle.css" rel="stylesheet" type="text/css">
<base target="_blank">
</head>

<body bgcolor="#fbfbf0">
<div id="column2_wrap">
<h2>Statistical Agencies (International)</h2><p>
	<div id="column2_text" class="scrollable">
	  <ul>
	    <li>Andorra <a href="http://www.estadistica.ad/" title="This link, estadistica.ad, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Department of Studies and Statistics</a> (In Catalan Only) </li>
	    <li>Anguilla <a href="http://www.gov.ai/statistics/" title="This link, gov.ai, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Unit</a> </li>
	    <li>Argentina <a href="http://www.indec.mecon.ar/" title="This link, indec.mecon.ar, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Censuses</a> </li>
	    <li>Armenia <a href="http://www.armstat.am/" title="This link, armstat.am, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Service</a> </li>
	    <li>Aruba <a href="http://www.aruba.com/" title="This link, aruba, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Australia <a href="http://www.abs.gov.au" title="This link, www.abs.gov.au, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Australian Bureau of Statistics</a> </li>
	    <li>Austria <a href="http://www.statistik.at/index_englisch.shtml" title="This link, statistik.at, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistical Office</a></li>
	    <li>Bahamas <a href="http://statistics.bahamas.gov.bs/" title="This link, bahamas.gov.bs, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">The Department of Statistics</a> </li>
	    <li>Bahrain <a href="http://www.cio.gov.bh/cio_eng/Default_stats.aspx" title="This link, cio.gov.bh, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Informatics Organization</a> </li>
	    <li>Bangladesh <a href="http://www.bbs.gov.bd/" title="This link, bbs.gov.bd, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Bangladesh Bureau of Statistics</a> </li>
	    <li>Barbados <a href="http://www.barstats.gov.bb/" title="This link, barstats.gov.bb, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Services</a> </li>
	    <li>Belarus <a href="http://www.belstat.gov.by/homep/en/main.html" title="This link, belstat.gov.by, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Ministry of Statistics and Analysis</a> </li>
	    <li>Belgium <a href="http://statbel.fgov.be/" title="This link, statbel.fgov.be, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> </li>
	    <li>Belize <a href="http://www.statisticsbelize.org.bz/" title="This link, statisticsbelize.org.bz, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Institute</a> </li>
	    <li>Benin <a href="http://www.insae-bj.org/" title="This link, insae-bj.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Economic Analysis</a> (In French Only) </li>
	    <li>Bermuda <a href="http://www.gov.bm/portal/server.pt?space=CommunityPage&control=SetCommunity&CommunityID=227" title="This link, gov.bm, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Department       of Statistics</a></li>
	    <li>Bosnia and Herzegovina <a href="http://www.bhas.ba" title="This link, bhas.ba, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Agency for Statistics</a> (Limited English Content) </li>
	    <li>Brazil <a href="http://www.ibge.gov.br/english/default.php" title="This link, ibge.gov.br, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Brazilian Institute of Geography and Statistics (IBGE)</a> </li>
	    <li>Brunei Darussalam <a href="http://www.brunei.gov.bn/" title="This link, brunei.gov.bn, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">The Government of Brunei Darussalam</a> </li>
	    <li>Bulgaria <a href="http://www.nsi.bg" title="This link, nsi.bg, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Institute</a> </li>
	    <li>Burkina Faso <a href="http://www.insd.bf" title="This link, insd.bf, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Demography</a> (In French Only) </li>
	    <li>Canada <a href="http://www.statcan.ca/" title="This link, statcan.ca, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Canada</a> </li>
	    <li>Cape Verde <a href="http://www.ine.cv" title="This link, ine.cv, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Institute</a> (In Portuguese Only) </li>
	    <li>Central African Republic <a href="http://www.stat-centrafrique.com/" title="This link, stat-centrafrique.com, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Division of Statistics and Economic and Social Studies</a> (In French Only) </li>
	    <li>Chad <a href="http://www.inseed-tchad.org/" title="This link, inseed-tchad.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Economic and Demographic Studies</a> (In French Only) </li>
	    <li>Chile <a href="http://www.ine.cl/" title="This link, ine.cl, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics (INE)</a> (In Spanish Only) </li>
	    <li>China <a href="http://www.stats.gov.cn/english/index.htm" title="This link, stats.gov.cn, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Bureau of Statistics</a> </li>
	    <ul type="circle">
          <li>Hong Kong Special Administrative Region <a href="http://www.info.gov.hk/censtatd" title="This link, info.gov.hk, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Census and Statistics Department</a> </li>
	    </ul>
	    <li>Colombia <a href="http://www.dane.gov.co" title="This link, dane.gov.co, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Administrative Department of Statistics (DANE)</a> (In Spanish Only) </li>
	    <li>Congo (Brazzaville) <a href="http://www.cnsee.org/" title="This link, cnsee.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Center of Statistics and Economic Studies </a>(In French Only) </li>
	    <li>Cook Islands <a href="http://www.stats.gov.ck/" title="This link, stats.gov.ck, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Office</a> </li>
	    <li>Costa Rica <a href="http://www.inec.go.cr" title="This link, inec.go.cr, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Censuses</a> (In Spanish Only) </li>
	    <li>Cote d´Ivoire <a href="http://www.ins.ci/" title="This link, ins.ci, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> (In French Only) </li>
	    <li>Croatia <a href="http://www.dzs.hr/" title="This link, dzs.hr, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Cuba <a href="http://www.one.cu/" title="This link, one.cu, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Office of National Statistics</a> (In Spanish Only) </li>
	    <li>Cyprus <a href="http://www.mof.gov.cy/mof/cystat/statistics.nsf/index_en/index_en?OpenDocument" title="This link, mof.gov.cy, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Service of the Republic of Cyprus</a> </li>
	    <li>Czech Republic <a href="http://www.czso.cz" title="This link, czso.cz, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Czech Statistical Office</a> </li>
	    <ul>
          <li>Faroe Islands <a href="http://www.hagstova.fo/portal/page/portal/HAGSTOVAN/Statistics_%20Faroe_Islands" title="This link, hagstova.fo, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Faroe Islands</a> </li>
        </ul>
	    <li>Djibouti <a href="http://www.ministere-finances.dj/" title="This link, www.ministere-finances.dj, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Ministry of the Economy, Finances and Privitization Planning</a> (In French Only) </li>
	    <li>Dominican Republic <a href="http://www.one.gov.do/" title="This link, one.gov.do, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistics Office</a> (In Spanish Only)</li>
	    <li>Egypt <a href="http://www.capmas.gov.eg/" title="This link, capmas.gov.eg, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Agency for Public Mobilization and Statistics</a> </li>
	    <li>El Salvador <a href="http://www.minec.gob.sv" title="This link, minec.gob.sv, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">General Directorate of Statistics and Censuses</a> (In Spanish Only) </li>
	    <li>Estonia <a href="http://www.stat.ee/" title="This link, stat.ee, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Office of Estonia</a> </li>
	    <li>Equatorial Guinea <a href="http://www.dgecnstat-ge.org/" title="This link, dgecnstat-ge.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">General Directorate of Statistics and National Accounts</a> (In Spanish Only) </li>
	    <li>European Community <a href="http://europa.eu.int/en/comm/eurostat/eurostat.html" title="This link, europa.eu.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">EUROSTAT</a> </li>
	    <li>Fiji Islands <a href="http://www.statsfiji.gov.fj/" title="This link, statsfiji.gov.fj, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Bureau</a> </li>
	    <li>Finland <a href="http://www.stat.fi/index_en.html" title="This link, stat.fi, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Finland</a> </li>
	    <li>France </li>
	    <ul>
          <li><a href="http://www.insee.fr/" title="This link, insee.fr, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Economic Studies (INSEE)</a> </li>
	      <li><a href="http://www.ined.fr/englishversion/index.html" title="This link, ined.fr, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute for Demographic Studies (INED)</a> </li>
        </ul>
	    <li>French Polynesia <a href="http://www.ispf.pf/" title="This link, ispf.pf, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Institute</a> (In French Only) </li>
	    <li>Gambia <a href="http://www.gambia.gm/Statistics/index.htm" title="This link, csd.gm, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistics Department</a> </li>
	    <li>Germany <a href="https://www.destatis.de/EN/Homepage.html" title="This link, destatis.de, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Federal Statistical Office</a> </li>
	    <li>Gibraltar <a href="http://www.gibraltar.gov.gi" title="This link, gibraltar.gov.gi, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Office</a> </li>
	    <li>Greece <a href="http://www.statistics.gr/" title="This link, statistics.gr, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Service</a> </li>
	    <!--<li>Greenland <a href="http://www.statgreen.gl" title="This link, statgreen.gl, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Greenland</a> </li>-->
	    <li>Guatemala <a href="http://www.ine.gob.gt/" title="This link, ine.gob.gt, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Instituto Nacional de Estadistica</a> (In Spanish Only) </li>
	    <li>Guinea <a href="http://www.stat-guinee.org/" title="This link, stat-guinee.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistics Directorate</a> (In French Only) </li>
	    <li>Guinea-Bissau <a href="http://www.stat-guinebissau.com/" title="This link, stat-guinebissau.com, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Censuses </a>(In Portuguese Only) </li>
	    <li>Guyana <a href="http://www.statisticsguyana.gov.gy/" title="This link, statisticsguyana.gov, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Bureau of Statistics</a> </li>
	    <li>Honduras <a href="http://www.ine-hn.org/" title="This link, ine-hn.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Instituto Nacional de Estadistica</a> (In Spanish Only) </li>
	    <li>Iceland <a href="http://www.statice.is/" title="This link, statice.is, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Iceland</a> </li>
	    <li>India </li>
	    <ul>
          <li><a href="http://www.censusindia.net/" title="This link, ine-hn.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Registrar General</a> (Census Information) </li>
	      <li><a href="http://mospi.nic.in/" title="This link, mospi.nic.in, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Ministry of Statistics and Programme Implementation</a> </li>
        </ul>
	    <li>Indonesia <a href="http://www.bps.go.id" title="This link, bps.go.id, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Indonesia</a> </li>
	    <li>International Organizations </li>
	    <ul type="circle">
          <li><a href="http://www.afristat.org/" title="This link, afristat.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Afristat</a> (French, with limited English content) </li>
	      <li><a href="http://www.fao.org/" title="This link, fao.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Food and Agricultural Organization (FAO)</a> </li>
	      <li><a href="http://www.ilo.org" title="This link, ilo.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">International Labor Organization (ILO)</a> </li>
	      <li><a href="http://www.oecd.org" title="This link, oecd.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Organization for Economic Cooperation and Development (OECD)</a> </li>
	      <li><a href="http://www.unece.org/" title="This link, unece.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">UN Economic Commission for Europe (UN/ECE) Statistical Division</a> </li>
	      <li><a href="http://unstats.un.org/unsd/default.htm" title="This link, unstats.un.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">UN Statistics Division</a> </li>
        </ul>
	    <li>Iran <a href="http://www.amar.org.ir/default.aspx?tabid=52" title="This link, sci.org.ir, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Center of Iran</a> </li>
	    <li>Ireland <a href="http://www.cso.ie" title="This link, cso.ie, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistics Office</a> </li>
	    <li>Isle of Man <a href="http://www.gov.im/treasury/economic/census/welcome.xml" title="This link, gov.im, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Treasury Department</a> </li>
	    <li>Israel <a href="http://www.cbs.gov.il/engindex.htm" title="This link, cbs.gov.il, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Italy <a href="http://www.istat.it/" title="This link, istat.it, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Institute</a> (Limited English Content) </li>
	    <li>Jamaica <a href="http://www.statinja.com/" title="This link, statinja.com, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Institute of Jamaica</a> </li>
	    <li>Japan <a href="http://www.stat.go.jp/english/index.htm" title="This link, stat.go.jp, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Bureau</a> </li>
	    <li>Jersey <a href="http://www.gov.je/Pages/default.aspx" title="This link, gov.je, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Jersey Statistics</a> </li>
	    <li>Jordan <a href="http://www.dos.gov.jo" title="This link, dos.gov.jo, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Department of Statistics</a> </li>
	    <li>Kazakhstan <a href="http://www.stat.kz/" title="This link, stat.kz, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">The Agency of Statistics</a> </li>
	    <li>Kenya <a href="http://www.knbs.or.ke/" title="This link, cbs.go.ke, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Kiribati <a href="http://www.spc.int/prism/Country/KI/Stats/" title="This link, spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Office</a> </li>
	    <li>Korea <a href="http://www.nso.go.kr" title="This link, nso.go.kr, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Office</a> </li>
	    <li>Kosovo <a href="http://www.ks-gov.net/esk/" title="This link, ks-gov.net, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Office of Kosovo (SOK)</a> </li>
	    <li>Kyrgyzstan <a href="http://www.stat.kg/" title="This link, stat.kg, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Committee</a> </li>
	    <li>Lebanon <a href="http://www.cas.gov.lb" title="This link, cas.gov.lb, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Administration for Statistics</a> </li>
	    <li>Lithuania <a href="http://www.stat.gov.lt/en/?PHPSESSID=ba7d3519a8d80213e922867f2c0fda69" title="This link, stat.gov.lt, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Department</a> </li>
	    <li>Luxembourg <a href="http://www.statec.public.lu" title="This link, statec.public.lu, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Economic Studies</a> </li>
	    <li>Madagascar <a href="http://www.instat.mg/" title="This link, instat.mg, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> (In French Only) </li>
	    <li>Malawi <a href="http://www.nso.malawi.net/" title="This link, nso.malawi.net, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Office</a> </li>
	    <li>Malaysia <a href="http://www.statistics.gov.my/" title="This link, statistics.gov.my, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Department of Statistics</a> </li>
	    <li>Maldives <a href="http://www.planning.gov.mv/" title="This link, planning.gov.mv, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Ministry of Planning and National Development</a></li>
	    <li>Malta <a href="http://www.nso.gov.mt" title="This link, nso.gov.mt, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistics Office</a> </li>
	    <li>Marshall Islands <a href="http://www.spc.int/prism/country/mh/stats/Index.htm" title="This link, spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Economic Policy, Planning and Statistics Office</a> </li>
	    <li>Mauritius <a href="http://www.gov.mu/portal/site/cso/" title="This link, gov.mu, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistical Office</a> </li>
	    <li>Mexico <a href="http://www.inegi.gob.mx/inegi/default.asp" title="This link, inegi.gob.mx, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics, Geography, and Informatics</a> (In Spanish Only) </li>
	    <li>Micronesia <a href="http://www.spc.int/prism/country/fm/stats/" title="This link, spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Government of the Federated States of Micronesia (FSM)</a> </li>
	    <li>Moldova <a href="http://www.statistica.md/?lang=en" title="This link, statistica.md, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Department for Statistics and Sociology</a> </li>
	    <li>Monaco <a href="http://www.gouv.mc/" title="This link, gouv.mc, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Official Government Portal</a> </li>
	    <li>Mongolia <a href="http://www.nso.mn/v3/index2.php" title="This link, nso.mn, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Office</a> </li>
	    <li>Morocco <a href="http://www.hcp.ma/" title="This link, hcp.ma, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Kingdom of Morocco</a> (In French Only) </li>
	    <li>Namibia <a href="http://www.npc.gov.na/cbs/index.htm" title="This link, npc.gov.na, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Nauru <a href="http://www.spc.int/prism/country/nr/stats/" title="This link, spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Bureau of Statistics</a> </li>
	    <li>Nepal <a href="http://www.cbs.gov.np/" title="This link, cbs.gov.np, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Netherlands <a href="http://www.cbs.nl/en-GB/" title="This link, cbs.nl, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Netherlands</a> </li>
	    <li>Netherlands Antilles <a href="http://www.cbs.an/" title="This link, cbs.nl, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>New Caledonia <a href="http://www.isee.nc/" title="This link, isee.nc, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Institute of Statistics and Economic Studies</a> (In French Only)  </li>
	    <li>New Zealand <a href="http://www.stats.govt.nz/" title="This link, stats.govt.nz, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics New Zealand</a></li>
	    <li>Niger <a href="http://www.stat-niger.org/" title="This link, stat-niger.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Institut National de la Statistique</a> (In French Only) </li>
	    <li>Nigeria <a href="http://www.nigerianstat.gov.ng/" title="This link, nigerianstat.gov.ng, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Bureau of Statistics</a> </li>
	    <li>Niue <a href="http://www.spc.int/prism/Country/NU/stats/" title="This link, www.spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Niue</a> </li>
	    <li>Norfolk Island <a href="http://www.norfolk.gov.nf/" title="This link, norfolk.gov.nf, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Homepage</a> </li>
	    <li>Norway <a href="http://www.ssb.no/www-open/english/" title="This link, ssb.no, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Norway</a> </li>
	    <li>Oman </li>
	    <ul>
	      <li><a href="http://www.omancensus.net/new/" title="This link, omancensus.net, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Oman Census</a> </li>
        </ul>
	    <li>Palau <a href="http://www.palaugov.net/stats/" title="This link, palaugov.net, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Office of Planning &amp; Statistics</a> </li>
	    <li>Palestinian Authority <a href="http://pcbs.gov.ps/" title="This link, pcbs.gov.ps, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Panama <a href="http://www.contraloria.gob.pa/" title="This link, contraloria.gob.pa, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Census and Statistics Directorate</a> (In Spanish Only) </li>
<!--	<li>Paraguay <a href="http://www.dgeec.gov.py/" title="This link, dgeec.gov.py, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">General Directorate of Statistics, Surveys and Censuses</a> (In Spanish Only) </li>-->
	    <li>Peru <a href="http://www.inei.gob.pe" title="This link, inei.gob.pe, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics and Informatics</a> (In Spanish Only) </li>
	    <li>Philippines </li>
	    <ul>
          <li><a href="http://www.census.gov.ph/" title="This link, census.gov.ph, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistics Office</a> </li>
	      <li><a href="http://www.nscb.gov.ph/" title="This link, nscb.gov.ph, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Coordination Board (NSCB)</a> </li>
        </ul>
	    <li>Portugal </li>
	    <ul>
          <li><a href="http://www.ine.pt/" title="This link, ine.pt, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> </li>
	      <li><a href="http://srea.ine.pt/" title="This link, srea.ine.pt, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Regional Statistics Service of the Azores</a> (In Portuguese Only) </li>
	    </ul>
	    <li>Qatar </li>
	    <ul>
          <li><a href="http://www.gsdp.gov.qa/" title="This link, gsdp.gov.qa, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">The General Secretariat for Development Planning</a> </li>
	      <li><a href="http://www.qsa.gov.qa" title="This link, planning.gov.qa, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Qatar Statistics</a> </li>
	      <li><a href="http://www.qsa.gov.qa/eng/" title="This link, qsa.gov.qa, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Authority (QSA)</a> </li>
        </ul>
	    <li>Romania <a href="http://www.insse.ro/" title="This link, insse.ro, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> </li>
	    <li>Rwanda <a href="http://www.statistics.gov.rw/" title="This link, statistics.gov.rw, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> </li>
	    <li>Saint Lucia <a href="http://www.stats.gov.lc/" title="This link, stats.gov.lc, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Government Statistics Department</a> </li>
	    <li>Sao Tomé and Principe <a href="http://www.ine.st/" title="This link, ine.st, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> (In Portuguese Only) </li>
	    <li>Saudi Arabia <a href="http://www.planning.gov.sa/" title="This link, planning.gov.sa, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Ministry of Economy and Planning</a> </li>
<!--	<li>Senegal <a href="http://www.ansd.org/" title="This link, ansd.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Directorate of Forecasting and Statistics</a> (In French Only)</li>-->
	    <li>Sierra Leone <a href="http://www.statistics.sl/" title="This link, statistics.sl, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Online</a> </li>
	    <li>Singapore <a href="http://www.singstat.gov.sg/" title="This link, singstat.gov.sg, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Department of Statistics</a> </li>
	    <li>Slovakia <a href="http://portal.statistics.sk/showdoc.do?docid=359" title="This link, statistics.sk, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Office of the Slovak Republic</a> </li>
	    <li>Slovenia <a href="http://www.stat.si/eng/index.asp" title="This link, stat.si, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistical Office of the Republic of Slovenia</a> </li>
	    <li>Solomon Islands <a href="http://www.spc.int/prism/country/sb/stats/" title="This link, spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistics Office</a> </li>
	    <li>South Africa <a href="http://www.statssa.gov.za/" title="This link, statssa.gov.za, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics South Africa</a> </li>
	    <li>Spain </li>
	    <ul>
          <li><a href="http://www.ine.es/welcoing.htm" title="This link, ine.es, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> </li>
	      <li><a href="http://www.eustat.es/" title="This link, eustat.es, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Basque Statistics Office</a> </li>
	      <li><a href="http://www.gobiernodecanarias.org/istac/" title="This link, gobiernodecanarias.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Canary Islands:</a> Canaries Institute of Statistics (In Spanish Only) </li>
        </ul>
	    <li>Sri Lanka <a href="http://www.statistics.gov.lk/" title="This link, statistics.gov.lk, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Department of Census and Statistics</a> </li>
	    <li>Sudan <a href="http://www.sudanmfa.com" title="This link, cbs.gov.sd, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Suriname <a href="http://www.statistics-suriname.org/" title="This link, statistics-suriname.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">General Bureau of Statistics</a> </li>
	    <li>Swaziland <a href="http://www.gov.sz/" title="This link, gov.sz, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistical Office</a> </li>
	    <li>Sweden <a href="http://www.scb.se/eng/index.asp" title="This link, scb.se, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Sweden</a> </li>
	    <li>Switzerland <a href="http://www.bfs.admin.ch/bfs/portal/en/index.html" title="This link, bfs.admin.ch, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Swiss Federal Statistical Office</a> </li>
	    <li>Syria <a href="http://www.cbssyr.org/" title="This link, cbssyr.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Bureau of Statistics</a> </li>
	    <li>Tanzania <a href="http://www.tanzania.go.tz/statistics.html" title="This link, tanzania.go.tz, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Bureau of Statistics</a></li>
	    <li>Thailand <a href="http://web.nso.go.th/eng/" title="This link, web.nso.go.th, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistical Office</a> </li>
	    <li>Tokelau <a href="http://www.spc.int/prism/country/tk/stats/" title="This link, spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Unit</a> </li>
	    <li>Tonga <a href="http://www.spc.int/prism/Country/TO/stats/" title="This link, spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Statistics Department</a> </li>
	    <li>Trinidad and Tobago <a href="http://www.cso.gov.tt/" title="This link, cso.gov.tt, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistical Office</a> </li>
	    <li>Tunisia <a href="http://www.ins.nat.tn/" title="This link, ins.nat.tn, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistics Institute</a> (In French Only) </li>
	    <li>Turkish Republic of Northern Cyprus <a href="http://www.devplan.org/Frame-eng.html" title="This link, devplan.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">State        Planning Organization</a> </li>
	    <li>Turks and Caicos Islands <a href="http://www.depstc.org/" title="This link, depstc.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Department of Economic Planning and Statistics</a> </li>
	    <li>Tuvalu <a href="http://www.spc.int/prism/country/tv/stats/" title="This link, spc.int, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistics Division</a> </li>
	    <li>Uganda <a href="http://www.ubos.org" title="This link, ubos.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Bureau of Statistics</a> </li>
	    <li>Ukraine <a href="http://www.ukrstat.gov.ua/" title="This link, ukrstat.gov.ua, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">State Statistics Committee</a> </li>
	    <li>United Arab Emirates <a href="http://www.economy.ae/English/Pages/default.aspx" title="This link, economy.ae, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Ministry of Economy</a> </li>
	    <li>United Kingdom </li>
	    <ul>
          <li><a href="http://www.statistics.gov.uk/" title="This link, statistics.gov.uk, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Statistics</a> </li>
	      <li><a href="http://www.nisra.gov.uk/" title="This link, nisra.gov.uk, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Northern Ireland Statistics and Research Agency</a> </li>
        </ul>
	    <li>Uruguay <a href="http://www.ine.gub.uy/" title="This link, ine.gub.uy, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">National Institute of Statistics</a> (In Spanish Only) </li>
	    <li>Uzbekistan <a href="http://www.stat.uz/STAT/index.php?lng=1" title="This link, stat.uz, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Ministry of Statistics</a> </li>
	    <li>Venezuela <a href="http://www.ine.gov.ve/" title="This link, ine.gov.ve, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Office of Statistics and Informatics (INE)</a> (In Spanish Only) </li>
	    <li>Vietnam <a href="http://www.gso.gov.vn/default_en.aspx?tabid=491" title="This link, gso.gov.vn, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">General Statistics Office</a> </li>
	    <li>Virgin Islands, British <a href="http://www.dpu.gov.vg/" title="This link, dpu.gov.vg, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Development Planning Unit</a> </li>
	    <li>Virgin Islands, United States <a href="http://www.uvi.edu/sites/uvi/Pages/ECC-Home.aspx" title="This link, uvi.edu, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Eastern       Caribbean Center</a> </li>
<!--	    <li>Wallis and Futuna <a href="http://www.wallis.co.nc/stats/" title="This link, wallis.co.nc, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Territorial Statistical and Economic Studies Service</a> (Limited English Content) </li>-->
	    <li>Yemen <a href="http://www.cso-yemen.org/index.php?lng=english&" title="This link, cso-yemen.org, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistical Organisation</a> </li>
	    <li>Zambia <a href="http://www.zamstats.gov.zm/" title="This link, zamstats.gov.zm, is not part of the Census Bureau Web site and does not imply endorsement of any particular product, company, or content.">Central Statistical Office</a> </li>
	</ul>
</div>
        Source: <a href="http://www.census.gov/compendia/statab/">http://www.census.gov</a>
</div>

</body>
</html>
