<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link href="daily.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body>
<div id="column2">
	<div id="col2_text" class="scroll">
	<ul></li>
<div class="rss-box">
<p class="rss-title"><a class="rss-title" href="http://www.cnn.com/POLITICS/index.html?eref=rss_politics" target="_blank">CNN.com - Politics</a><br /><span class="rss-item">CNN.com delivers up-to-the-minute news and information on the latest top stories, weather, entertainment, politics and more.</span></p>
<ul class="rss-items">
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/Iw-kuf6sK9g/index.html"  title="Robert Mueller became FBI director just days before 9/11. An..." target="_blank">CNN's Q and A with FBI Director Robert Mueller</a> <br />
Robert Mueller became FBI director just days before 9/11. And now, nearly 12 years later, he's preparing to step down. CNN's Joe Johns sat down with him to get his thoughts on the war on terror, cyber security, the Boston Marathon bombing, NSA snooping and the Benghazi investigation.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Iw-kuf6sK9g:rD6-jp7Fo9s:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Iw-kuf6sK9g:rD6-jp7Fo9s:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Iw-kuf6sK9g:rD6-jp7Fo9s:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=Iw-kuf6sK9g:rD6-jp7Fo9s:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Iw-kuf6sK9g:rD6-jp7Fo9s:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Iw-kuf6sK9g:rD6-jp7Fo9s:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=Iw-kuf6sK9g:rD6-jp7Fo9s:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/Iw-kuf6sK9g" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/wTC37a3hvbw/index.html"  title="The U.S. Justice Department said Thursday that it will file ..." target="_blank">Feds sue to stop Texas voter ID law</a> <br />
The U.S. Justice Department said Thursday that it will file a lawsuit seeking to stop a controversial Texas law that would require voters to show identification at voting booths.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=wTC37a3hvbw:_lT-klZIq9s:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=wTC37a3hvbw:_lT-klZIq9s:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=wTC37a3hvbw:_lT-klZIq9s:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=wTC37a3hvbw:_lT-klZIq9s:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=wTC37a3hvbw:_lT-klZIq9s:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=wTC37a3hvbw:_lT-klZIq9s:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=wTC37a3hvbw:_lT-klZIq9s:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/wTC37a3hvbw" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/Z3ZgKvfO4zE/index.html"  title="The Obama administration on Wednesday declassified opinions ..." target="_blank">NSA misrepresented scope of data collection to secret court</a> <br />
The Obama administration on Wednesday declassified opinions from a secret court that oversees government surveillance showing the National Security Agency was broadly collecting domestic Internet communications of Americans and misrepresenting the scope of that effort to the court.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Z3ZgKvfO4zE:Xwwd9Qp_ErA:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Z3ZgKvfO4zE:Xwwd9Qp_ErA:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Z3ZgKvfO4zE:Xwwd9Qp_ErA:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=Z3ZgKvfO4zE:Xwwd9Qp_ErA:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Z3ZgKvfO4zE:Xwwd9Qp_ErA:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=Z3ZgKvfO4zE:Xwwd9Qp_ErA:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=Z3ZgKvfO4zE:Xwwd9Qp_ErA:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/Z3ZgKvfO4zE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/gE3ECYAnq6Y/tsr-acosta-cruz-takes-on-obama-health-care.cnn.html"  title="Some GOP lawmakers appear willing to shut down the governmen..." target="_blank">GOP at odds over Obama health care law</a> <br />
Some GOP lawmakers appear willing to shut down the government in their fight to defund the president's health care law.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=gE3ECYAnq6Y:5zvn492K5oQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=gE3ECYAnq6Y:5zvn492K5oQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=gE3ECYAnq6Y:5zvn492K5oQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=gE3ECYAnq6Y:5zvn492K5oQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=gE3ECYAnq6Y:5zvn492K5oQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=gE3ECYAnq6Y:5zvn492K5oQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=gE3ECYAnq6Y:5zvn492K5oQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/gE3ECYAnq6Y" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/ywdQzcyvAvY/index.html"  title="Richard Vedder says radical rethinking of college education ..." target="_blank">Opinion: How to slash college costs</a> <br />
Richard Vedder says radical rethinking of college education could cut student costs sharply<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=ywdQzcyvAvY:L20q91Koghw:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=ywdQzcyvAvY:L20q91Koghw:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=ywdQzcyvAvY:L20q91Koghw:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=ywdQzcyvAvY:L20q91Koghw:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=ywdQzcyvAvY:L20q91Koghw:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=ywdQzcyvAvY:L20q91Koghw:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=ywdQzcyvAvY:L20q91Koghw:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/ywdQzcyvAvY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/YsBKiFOsvpA/index.html"  title="The time is nearing for a potentially definitive U.S. respon..." target="_blank">Obama on Syria, Egypt</a> <br />
The time is nearing for a potentially definitive U.S. response to alleged Syrian government atrocities and an increasingly violent military crackdown in Egypt, President Obama said in an exclusive interview on CNN's "New Day."<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:wwoAyNXu1CQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:wwoAyNXu1CQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:wwoAyNXu1CQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=YsBKiFOsvpA:wwoAyNXu1CQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:wwoAyNXu1CQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:wwoAyNXu1CQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=YsBKiFOsvpA:wwoAyNXu1CQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/YsBKiFOsvpA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/i4w6p5Z1H1U/newday-cuomo-obama-tuff.cnn.html"  title="President Obama says Antoinette Tuff, a school worker who he..." target="_blank">Obama praises Antoinette Tuff</a> <br />
President Obama says Antoinette Tuff, a school worker who helped talk down a gunman, made him proud.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:5GYnAbTksdM:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:5GYnAbTksdM:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:5GYnAbTksdM:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=i4w6p5Z1H1U:5GYnAbTksdM:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:5GYnAbTksdM:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:5GYnAbTksdM:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=i4w6p5Z1H1U:5GYnAbTksdM:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/i4w6p5Z1H1U" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/F30Ps69oTLU/newday-cuomo-obama-sunny.cnn.html"  title="President Obama says Bo is getting lonely now that the atten..." target="_blank">Obama on Sunny the dog</a> <br />
President Obama says Bo is getting lonely now that the attention has turned to Sunny.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=F30Ps69oTLU:t4bkKrsTk4c:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=F30Ps69oTLU:t4bkKrsTk4c:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=F30Ps69oTLU:t4bkKrsTk4c:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=F30Ps69oTLU:t4bkKrsTk4c:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=F30Ps69oTLU:t4bkKrsTk4c:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=F30Ps69oTLU:t4bkKrsTk4c:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=F30Ps69oTLU:t4bkKrsTk4c:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/F30Ps69oTLU" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/YsBKiFOsvpA/index.html"  title="The time is nearing for a potentially definitive U.S. respon..." target="_blank">Obama: Key decisions nearing on Syria, Egypt</a> <br />
The time is nearing for a potentially definitive U.S. response to alleged Syrian government atrocities and an increasingly violent military crackdown in Egypt, President Obama said in an exclusive interview on CNN's "New Day."<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:1z3FFpMQ1WY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:1z3FFpMQ1WY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:1z3FFpMQ1WY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=YsBKiFOsvpA:1z3FFpMQ1WY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:1z3FFpMQ1WY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=YsBKiFOsvpA:1z3FFpMQ1WY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=YsBKiFOsvpA:1z3FFpMQ1WY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/YsBKiFOsvpA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/i4w6p5Z1H1U/newday-cuomo-obama-tuff.cnn.html"  title="President Obama says Antoinette Tuff, a school worker who he..." target="_blank">Obama on Tuff</a> <br />
President Obama says Antoinette Tuff, a school worker who helped talk down a gunman, made him proud.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:466m6lLNnqg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:466m6lLNnqg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:466m6lLNnqg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=i4w6p5Z1H1U:466m6lLNnqg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:466m6lLNnqg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=i4w6p5Z1H1U:466m6lLNnqg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=i4w6p5Z1H1U:466m6lLNnqg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/i4w6p5Z1H1U" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/GdmueqnvsjA/index.html"  title="A military jury considering the fate of Maj. Nidal Hasan, th..." target="_blank">Nidal Hasan found guilty of all counts in Ft. Hood shooting</a> <br />
A military jury considering the fate of Maj. Nidal Hasan, the Army psychiatrist charged with massacring soldiers at Fort Hood, Texas, resumed deliberations Friday morning in the death penalty case.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=GdmueqnvsjA:HujL__D-knA:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=GdmueqnvsjA:HujL__D-knA:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=GdmueqnvsjA:HujL__D-knA:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=GdmueqnvsjA:HujL__D-knA:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=GdmueqnvsjA:HujL__D-knA:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=GdmueqnvsjA:HujL__D-knA:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=GdmueqnvsjA:HujL__D-knA:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/GdmueqnvsjA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/-lvUIMKpdBc/index.html"  title="Paul Begala explains why Ashton Kutcher, a Hollywood liberal..." target="_blank">Begala: Kutcher is right ... because he's from the left</a> <br />
Paul Begala explains why Ashton Kutcher, a Hollywood liberal, have become the darling of conservatives.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=-lvUIMKpdBc:yWzXFFh1YzA:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=-lvUIMKpdBc:yWzXFFh1YzA:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=-lvUIMKpdBc:yWzXFFh1YzA:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=-lvUIMKpdBc:yWzXFFh1YzA:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=-lvUIMKpdBc:yWzXFFh1YzA:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=-lvUIMKpdBc:yWzXFFh1YzA:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=-lvUIMKpdBc:yWzXFFh1YzA:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/-lvUIMKpdBc" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/TTpQDkbON6A/index.html"  title="United Secretary General Ban Ki Moon said Friday that allega..." target="_blank">Syria under pressure to allow probe of chemical weapons claim</a> <br />
United Secretary General Ban Ki Moon said Friday that allegations the Syrian regime used chemical weapons should be investigated immediately, saying such a "crime against humanity should result in serious consequences for the perpetrator."<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=TTpQDkbON6A:1AdxFVSvdgg:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=TTpQDkbON6A:1AdxFVSvdgg:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=TTpQDkbON6A:1AdxFVSvdgg:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=TTpQDkbON6A:1AdxFVSvdgg:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=TTpQDkbON6A:1AdxFVSvdgg:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=TTpQDkbON6A:1AdxFVSvdgg:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=TTpQDkbON6A:1AdxFVSvdgg:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/TTpQDkbON6A" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/chQ-8xXuMgQ/index.html"  title="The U.S. military has updated options for a forceful interve..." target="_blank">Official: U.S. military updating options for strikes</a> <br />
The U.S. military has updated options for a forceful intervention in Syria to give President Barack Obama a range of choices should he decide to deepen American involvement in a civil war where new claims surfaced this week about possible chemical weapons use by the regime.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=chQ-8xXuMgQ:IKdYZtD9o1c:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=chQ-8xXuMgQ:IKdYZtD9o1c:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=chQ-8xXuMgQ:IKdYZtD9o1c:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=chQ-8xXuMgQ:IKdYZtD9o1c:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=chQ-8xXuMgQ:IKdYZtD9o1c:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=chQ-8xXuMgQ:IKdYZtD9o1c:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=chQ-8xXuMgQ:IKdYZtD9o1c:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/chQ-8xXuMgQ" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/EUBJmu-uJLE/newday-cuomo-obama-syria.cnn.html"  title="President Obama says Syria will require America's attention...." target="_blank">Obama: Syria will require America's attention</a> <br />
President Obama says Syria will require America's attention.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=EUBJmu-uJLE:u7RatvLF9LA:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=EUBJmu-uJLE:u7RatvLF9LA:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=EUBJmu-uJLE:u7RatvLF9LA:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=EUBJmu-uJLE:u7RatvLF9LA:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=EUBJmu-uJLE:u7RatvLF9LA:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=EUBJmu-uJLE:u7RatvLF9LA:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=EUBJmu-uJLE:u7RatvLF9LA:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/EUBJmu-uJLE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/DCqmr5I7DH4/index.html"  title="..." target="_blank">Photos: Syria's civil war</a> <br />
<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=DCqmr5I7DH4:oLfOddNfrxk:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=DCqmr5I7DH4:oLfOddNfrxk:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=DCqmr5I7DH4:oLfOddNfrxk:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=DCqmr5I7DH4:oLfOddNfrxk:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=DCqmr5I7DH4:oLfOddNfrxk:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=DCqmr5I7DH4:oLfOddNfrxk:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=DCqmr5I7DH4:oLfOddNfrxk:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/DCqmr5I7DH4" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/QPNsJ4cM-QY/index.html"  title="David Anderson says the growing diversity of America will le..." target="_blank">Opinion: Whites becoming minority group</a> <br />
David Anderson says the growing diversity of America will lead to a day when whites no longer command a majority<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=QPNsJ4cM-QY:YWygMNG2AgQ:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=QPNsJ4cM-QY:YWygMNG2AgQ:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=QPNsJ4cM-QY:YWygMNG2AgQ:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=QPNsJ4cM-QY:YWygMNG2AgQ:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=QPNsJ4cM-QY:YWygMNG2AgQ:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=QPNsJ4cM-QY:YWygMNG2AgQ:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=QPNsJ4cM-QY:YWygMNG2AgQ:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/QPNsJ4cM-QY" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/uAoJNMBLRUs/index.html"  title="Ruben Navarrette says it's apparent San Diego Mayor Bob Filn..." target="_blank">Will 'Mayor Naughty' please step down?</a> <br />
Ruben Navarrette says it's apparent San Diego Mayor Bob Filner, accused of sexual harassment by 16 women, is a first-class narcissist who refuses to go away.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=uAoJNMBLRUs:sM9SLdGa7jU:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=uAoJNMBLRUs:sM9SLdGa7jU:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=uAoJNMBLRUs:sM9SLdGa7jU:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=uAoJNMBLRUs:sM9SLdGa7jU:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=uAoJNMBLRUs:sM9SLdGa7jU:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=uAoJNMBLRUs:sM9SLdGa7jU:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=uAoJNMBLRUs:sM9SLdGa7jU:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/uAoJNMBLRUs" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/fX6MOw1oSJA/index.html"  title="LZ Granderson says the injustice done to civil rights leader..." target="_blank">The man black history erased</a> <br />
LZ Granderson says the injustice done to civil rights leader Bayard Rustin teaches us that bigotry of any kind is unacceptable<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=fX6MOw1oSJA:gW_rPxLs6JI:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=fX6MOw1oSJA:gW_rPxLs6JI:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=fX6MOw1oSJA:gW_rPxLs6JI:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=fX6MOw1oSJA:gW_rPxLs6JI:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=fX6MOw1oSJA:gW_rPxLs6JI:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=fX6MOw1oSJA:gW_rPxLs6JI:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=fX6MOw1oSJA:gW_rPxLs6JI:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/fX6MOw1oSJA" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/8szbWt3ifKE/index.html"  title="President Obama's policies and the GOP reaction to them has ..." target="_blank">Obama did Hillary Clinton a huge favor</a> <br />
President Obama's policies and the GOP reaction to them has made it safe for Democrats to run as liberals, writes Julian Zelizer<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=8szbWt3ifKE:Pk7jCHo-fmY:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=8szbWt3ifKE:Pk7jCHo-fmY:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=8szbWt3ifKE:Pk7jCHo-fmY:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=8szbWt3ifKE:Pk7jCHo-fmY:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=8szbWt3ifKE:Pk7jCHo-fmY:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=8szbWt3ifKE:Pk7jCHo-fmY:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=8szbWt3ifKE:Pk7jCHo-fmY:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/8szbWt3ifKE" height="1" width="1"/>
</li>
<li class="rss-item"><a class="rss-item" href="http://rss.cnn.com/~r/rss/cnn_allpolitics/~3/aW9SaSda93Q/index.html"  title="Donna Brazile says it is wrong to promote &quot;slapping&quo..." target="_blank">Stop promoting 'Slap Hillary' abuse</a> <br />
Donna Brazile says it is wrong to promote "slapping" or "shooting" of any public official, female or male.<div class="feedflare"> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=aW9SaSda93Q:U7yzRy7ybp0:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=aW9SaSda93Q:U7yzRy7ybp0:7Q72WNTAKBA"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=7Q72WNTAKBA" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=aW9SaSda93Q:U7yzRy7ybp0:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=aW9SaSda93Q:U7yzRy7ybp0:V_sGLiPBpWU" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=aW9SaSda93Q:U7yzRy7ybp0:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?d=qj6IDK7rITs" border="0"></img></a> <a href="http://rss.cnn.com/~ff/rss/cnn_allpolitics?a=aW9SaSda93Q:U7yzRy7ybp0:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/rss/cnn_allpolitics?i=aW9SaSda93Q:U7yzRy7ybp0:gIN9vFwOqvQ" border="0"></img></a> </div><img src="http://feeds.feedburner.com/~r/rss/cnn_allpolitics/~4/aW9SaSda93Q" height="1" width="1"/>
</li>
</ul></div>
</li></ul>


	</div>
</div>
</body>
</html>
