<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Welcome::News &amp; Weather Source</title>
<link href="nw-style.css" rel="stylesheet" type="text/css" />
<base target='_blank' />
</head>

<body class='scroll'>

<p>

<div>
<ul>
<li><a href='http://news.yahoo.com/eu-leaders-rebuff-calls-action-europes-migration-crisis-145541266.html' target="_blank">EU leaders rebuff calls for action on Europe's migration crisis</a><br />
<p><a href="http://news.yahoo.com/eu-leaders-rebuff-calls-action-europes-migration-crisis-145541266.html"><img src="http://l3.yimg.com/bt/api/res/1.2/Njon72zYaf_H9dBMHJCfow--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-25T145541Z_1_CBRE99O15H000_RTROPTP_2_EU-SUMMIT.JPG" width="130" height="86" alt="Lithuania&#039;s President Grybauskaite arrives at a European Union leaders summit in Brussels" align="left" title="Lithuania&#039;s President Grybauskaite arrives at a European Union leaders summit in Brussels" border="0" /></a>By Adrian Croft and Justyna Pawlak BRUSSELS (Reuters) - European Union leaders rebuffed calls from southern European states on Friday for emergency action to tackle a wave of illegal migration from Africa despite the deaths of hundreds of people in Mediterranean boat disasters. EU leaders meeting in Brussels expressed &quot;deep sadness&quot; at the drownings, which have killed up to 550 migrants this month alone, but postponed any new action until December. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/ethiopia-bans-domestic-workers-moving-overseas-142320353.html' target="_blank">Ethiopia bans domestic workers from moving overseas</a><br />
<p><a href="http://news.yahoo.com/ethiopia-bans-domestic-workers-moving-overseas-142320353.html"><img src="http://l3.yimg.com/bt/api/res/1.2/tKx1cXuG16s3LiDEhTxdsA--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/7e850bf28d556d8d39e0f3ec57eb9fdf72a213bf.jpg" width="130" height="86" alt="Ethiopian and Somali refugees form a queue to board a bus in the Kenyan port of Mombasa on November 5, 2010" align="left" title="Ethiopian and Somali refugees form a queue to board a bus in the Kenyan port of Mombasa on November 5, 2010" border="0" /></a>Addis Ababa (AFP) - Ethiopia has banned domestic workers from moving overseas for employment, following an &quot;exodus&quot; of workers leaving the country through illegal placement agencies, officials said Friday.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/saudi-arabia-warns-online-backers-women-drivers-110320846.html' target="_blank">Saudi Arabia warns online backers of women drivers</a><br />
<p><a href="http://news.yahoo.com/saudi-arabia-warns-online-backers-women-drivers-110320846.html"><img src="http://l1.yimg.com/bt/api/res/1.2/RtkRFaTaVFCOZE5DfD66Pg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/ap_webfeeds/61165e73dc2a1e23410f6a7067007f8a.jpg" width="130" height="86" alt="FILE - In this Friday, June 17, 2011 file image made from video released by Change.org, a Saudi Arabian woman drives a car as part of a campaign to defy Saudi Arabia&#039;s ban on women driving, in Riyadh, Saudi Arabia. It’s been a little more than two years since the last time women in Saudi Arabia campaigned for the right to drive. Since then, the monarchy has made incremental but key reforms, and activists hope that has readied the nation for greater change as they call for women to get behind the wheel in a new campaign Saturday, Oct. 26, 2013. Ultraconservatives are pushing back with protests, threats and even a cleric’s warning that driving a car damages a woman’s ovaries.(AP Photo/Change.org, File)" align="left" title="FILE - In this Friday, June 17, 2011 file image made from video released by Change.org, a Saudi Arabian woman drives a car as part of a campaign to defy Saudi Arabia&#039;s ban on women driving, in Riyadh, Saudi Arabia. It’s been a little more than two years since the last time women in Saudi Arabia campaigned for the right to drive. Since then, the monarchy has made incremental but key reforms, and activists hope that has readied the nation for greater change as they call for women to get behind the wheel in a new campaign Saturday, Oct. 26, 2013. Ultraconservatives are pushing back with protests, threats and even a cleric’s warning that driving a car damages a woman’s ovaries.(AP Photo/Change.org, File)" border="0" /></a>RIYADH, Saudi Arabia (AP) — Saudi officials stepped up warnings on Friday over plans by women to challenge the male-only driving rules in the ultraconservative kingdom, saying that even online support for the protest could bring arrest.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/aqap-warns-yemen-against-crackdown-over-jailbreak-bid-110121662.html' target="_blank">AQAP warns Yemen against crackdown over jailbreak bid</a><br />
<p><a href="http://news.yahoo.com/aqap-warns-yemen-against-crackdown-over-jailbreak-bid-110121662.html"><img src="http://l1.yimg.com/bt/api/res/1.2/Qj3vCEP0.Ge73.ysfsDQHg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/1a51d859011dbe4998d04d2120ecb1f17478af42.jpg" width="130" height="86" alt="Yemeni soldiers pictured outside the court in the capital Sanaa on October 2, 2013 during the trial of 11 Al-Qaeda militants" align="left" title="Yemeni soldiers pictured outside the court in the capital Sanaa on October 2, 2013 during the trial of 11 Al-Qaeda militants" border="0" /></a>Sanaa (AFP) - Al-Qaeda in the Arabian Peninsula has warned its response will be &quot;painful&quot; if Yemeni authorities punish prisoners from the extremist network who made a failed attempt to escape their jail.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/ethiopia-bans-overseas-employment-citizens-105718806.html' target="_blank">Ethiopia bans overseas employment of citizens</a><br />
NAIROBI, Kenya (AP) — The Ethiopian government has banned its citizens from travelling overseas for employment.
<li><a href='http://news.yahoo.com/gore-urges-us-stop-keystone-atrocity-214949994.html' target="_blank">Gore urges US to stop Keystone 'atrocity'</a><br />
<p><a href="http://news.yahoo.com/gore-urges-us-stop-keystone-atrocity-214949994.html"><img src="http://l1.yimg.com/bt/api/res/1.2/4XVEaUjVUX_2qTTmF9554A--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/0f8fe7dfbcf012f066b3652647b5807a56a824fb.jpg" width="130" height="86" alt="Former US Vice President Al Gore speaks during the Center for American Progress 10th Anniversary Conference in Washington, DC, October 24, 2013" align="left" title="Former US Vice President Al Gore speaks during the Center for American Progress 10th Anniversary Conference in Washington, DC, October 24, 2013" border="0" /></a>Washington (AFP) - Former US vice president Al Gore on Thursday urged President Barack Obama to block the Keystone XL oil pipeline from Canada, likening the carbon-intense project to drug addiction.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/israel-weighs-palestinian-prisoner-release-200309808.html' target="_blank">Israel weighs Palestinian prisoner release</a><br />
<p><a href="http://news.yahoo.com/israel-weighs-palestinian-prisoner-release-200309808.html"><img src="http://l3.yimg.com/bt/api/res/1.2/2OzAC6WRHdEfSF1od1MQaA--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/e51818aa2fe341867e8984b6ee9dcbe5e2a74878.jpg" width="130" height="86" alt="A Palestinian girl from the Israeli occupied West Bank waves the national flag as she and others wait close to the military prison of Ofer for the release of Palestinian prisoners on August 13, 2013" align="left" title="A Palestinian girl from the Israeli occupied West Bank waves the national flag as she and others wait close to the military prison of Ofer for the release of Palestinian prisoners on August 13, 2013" border="0" /></a>Jerusalem (AFP) - Israeli ministers are to meet Sunday to approve the release of a second batch of Palestinian prisoners under the terms of renewed peace talks, media said.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/ankara-students-revive-dormant-turkish-protest-movement-194925267.html' target="_blank">Ankara students revive dormant Turkish protest movement</a><br />
<p><a href="http://news.yahoo.com/ankara-students-revive-dormant-turkish-protest-movement-194925267.html"><img src="http://l2.yimg.com/bt/api/res/1.2/wmQRf3n6xFEODKoFZIQYWw--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/a1fa552443736d4b3522f5af80a7e6dcf54c2149.jpg" width="130" height="86" alt="Riot police watch students of the Middle East Technical University prepare to play football on October 23, 2013 to protest against the uprooting of trees by the Ankara municipality to make way for a road through the campus" align="left" title="Riot police watch students of the Middle East Technical University prepare to play football on October 23, 2013 to protest against the uprooting of trees by the Ankara municipality to make way for a road through the campus" border="0" /></a>Ankara (AFP) - Four months after protests against the planned redevelopment of an Istanbul park devolved into a violent national uproar against the government, Turkish students are taking to the streets once again to fight an all-too-familiar scheme.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/saudi-warns-women-against-defying-driving-ban-143455285.html' target="_blank">Saudi warns women against defying driving ban</a><br />
<p><a href="http://news.yahoo.com/saudi-warns-women-against-defying-driving-ban-143455285.html"><img src="http://l.yimg.com/bt/api/res/1.2/neRVu_i53vh4oCxtYcCkJg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/d3f0c8fc88b2f8ab5c263bc6648b80712ac22c58.jpg" width="130" height="86" alt="Saudi activist Manal Al Sharif, who now lives in Dubai, drives her car in the Gulf Emirate city on October 22, 2013, as she campagins in solidarity with Saudi women" align="left" title="Saudi activist Manal Al Sharif, who now lives in Dubai, drives her car in the Gulf Emirate city on October 22, 2013, as she campagins in solidarity with Saudi women" border="0" /></a>Riyadh (AFP) - Saudi Arabia on Thursday warned it will take measures against activists who go ahead with a planned weekend campaign to defy a ban on women drivers in the conservative Muslim kingdom.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/israel-saudis-speaking-same-language-iran-livni-134723856.html' target="_blank">Israel, Saudis speaking same language on Iran - Livni</a><br />
<p><a href="http://news.yahoo.com/israel-saudis-speaking-same-language-iran-livni-134723856.html"><img src="http://l3.yimg.com/bt/api/res/1.2/CyPzniRB0lzdhzNeCwQ3mQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-24T134723Z_1_CBRE99N12B200_RTROPTP_2_PALESTINIANS-ISRAEL.JPG" width="130" height="86" alt="Israel&#039;s Justice Minister Livni delivers a statement before her meeting with France&#039;s Foreign Minister Fabius in Jerusalem" align="left" title="Israel&#039;s Justice Minister Livni delivers a statement before her meeting with France&#039;s Foreign Minister Fabius in Jerusalem" border="0" /></a>By Jeffrey Heller JERUSALEM (Reuters) - Saudi Arabia and Israel are united in their opposition to Iran, but they cannot cooperate as long the Palestinian conflict continues, Israel&#039;s chief peace negotiator said on Thursday. &quot;When you hear the Saudis talking about what needs to be done in order to prevent a (nuclear-armed) Iran, I mean it sounds familiar,&quot; said Tzipi Livni, a former Israeli foreign minister who is leading talks with the Palestinians. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/u-talking-turkey-china-missile-deal-concerns-envoy-084728066.html' target="_blank">U.S. talking to Turkey about China missile deal concerns</a><br />
<p><a href="http://news.yahoo.com/u-talking-turkey-china-missile-deal-concerns-envoy-084728066.html"><img src="http://l1.yimg.com/bt/api/res/1.2/kNF_mPibKA575nHRLV7y.A--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-24T121920Z_2_CBRE99N0OFC00_RTROPTP_2_TURKEY-CHINA-DEFENCE.JPG" width="130" height="86" alt="Logo of China Precision Machinery Import and Export Corp at its headquarters in Beijing" align="left" title="Logo of China Precision Machinery Import and Export Corp at its headquarters in Beijing" border="0" /></a>By Tulay Karadeniz ANKARA (Reuters) - The United States is concerned Turkey&#039;s decision to build a missile defense system with a Chinese firm could undermine allied air defenses, its envoy said on Thursday, but dismissed talk of a broader rift with Ankara. U.S. Ambassador to Turkey Francis Ricciardone said Washington had begun &quot;expert&quot; talks with Turkey to assess the impact of its plans to co-produce the long-range air and missile defense system with a Chinese firm under U.S. sanctions. He downplayed speculation, however, that ties between the two had soured following U.S. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/exclusive-eu-graft-inquiry-shifts-ex-health-chiefs-114725332--finance.html' target="_blank">Exclusive: EU graft inquiry shifts to ex-health chief's overseas activity</a><br />
<p><a href="http://news.yahoo.com/exclusive-eu-graft-inquiry-shifts-ex-health-chiefs-114725332--finance.html"><img src="http://l2.yimg.com/bt/api/res/1.2/qfd9Tsh8wth02zgQSXS40w--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-24T114725Z_1_CBRE99N0WRB00_RTROPTP_2_EU-PHARMACEUTICALS-TRIALS.JPG" width="130" height="86" alt="John Dalli, European Commissioner for Health and Consumer Policy, speaks at a news conference at the EC headquarters in Brussels" align="left" title="John Dalli, European Commissioner for Health and Consumer Policy, speaks at a news conference at the EC headquarters in Brussels" border="0" /></a>By Charlie Dunmore and Luke Baker BRUSSELS (Reuters) - EU investigators have expanded an anti-corruption investigation into former European health commissioner John Dalli, who was forced out last year after an associate was accused of attempted bribery, to include his overseas dealings while in office. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/factbox-u-n-nuclear-agency-seeks-access-iranian-112810478.html' target="_blank">Factbox: U.N. nuclear agency seeks access to Iranian sites, officials</a><br />
VIENNA (Reuters) - The U.N. nuclear watchdog wants to inspect sensitive sites and meet important officials - including a mysterious military man - in Iran as part of an investigation into suspicions that Tehran may have worked on designing an atomic warhead. The International Atomic Energy Agency and Iran meet on Monday for the 12th time since early 2012, with the IAEA hoping to resume its long-stalled inquiry into alleged nuclear bomb research by Iran, which denies such work. Both sides signaled a desire to achieve progress after their last discussions about a month ago. 
<li><a href='http://news.yahoo.com/merkel-hollande-discuss-us-spying-revelations-095548894.html' target="_blank">Spying row hijacks EU summit, testing Europe's unity</a><br />
<p><a href="http://news.yahoo.com/merkel-hollande-discuss-us-spying-revelations-095548894.html"><img src="http://l3.yimg.com/bt/api/res/1.2/UApkSR8F.KwK4KbAB7cgmg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/83034adaa3982ca8aed5370f5b2933cbb53c00df.jpg" width="130" height="86" alt="German Chancellor Angela Merkel holds a tapping proof BlackBerry mobile device at the CeBIT high-tech fair on March 5, 2013 in Hanover, central Germany" align="left" title="German Chancellor Angela Merkel holds a tapping proof BlackBerry mobile device at the CeBIT high-tech fair on March 5, 2013 in Hanover, central Germany" border="0" /></a>Brussels (AFP) - Mounting ire over alleged US snooping on its allies will test Europe&#039;s unity at a summit Thursday after German and French leaders Angela Merkel and Francois Hollande demanded Washington provide an explanation.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/senior-parliamentarian-says-iran-halted-20-pct-enrichment-074501243.html' target="_blank">Senior parliamentarian says Iran has halted 20 pct enrichment</a><br />
<p><a href="http://news.yahoo.com/senior-parliamentarian-says-iran-halted-20-pct-enrichment-074501243.html"><img src="http://l2.yimg.com/bt/api/res/1.2/50iNGYSRgedKVIKzQYxAsQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-24T074501Z_1_CBRE99N0LJ900_RTROPTP_2_FEATURE-NUCLEAR-STORY.JPG" width="130" height="86" alt="Disused equipment for enriching uranium is shown at the French nuclear Pierrelatte site in southeastern France" align="left" title="Disused equipment for enriching uranium is shown at the French nuclear Pierrelatte site in southeastern France" border="0" /></a>DUBAI (Reuters) - Iran has stopped enriching uranium to 20 percent, a main demand of world powers in talks over Tehran&#039;s disputed nuclear program, a senior Iranian parliamentarian was quoted as saying. The International Atomic Energy Agency in Vienna, which regularly inspects Iranian nuclear sites, said it had no comment for now. IAEA inspectors are believed to visit Iran&#039;s enrichment facilities about once a week. Iran enriches uranium to 20 percent fissile concentration at the Fordow underground site and also at a research and development site at Natanz. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/immigration-us-spying-row-gatecrash-eu-summit-032532477.html' target="_blank">US spying row to eclipse EU summit as Merkel demands answers</a><br />
<p><a href="http://news.yahoo.com/immigration-us-spying-row-gatecrash-eu-summit-032532477.html"><img src="http://l.yimg.com/bt/api/res/1.2/KB8myRw469IfrApDaa7qAQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/335c802f9b0fd6594be6eac26f9d30dc9c8e8e28.jpg" width="130" height="86" alt="File picture taken on June 19, 2013 shows US President Barack Obama wiping his brow as he and German Chancellor Angela Merkel leave the stage after his speech at the Brandenburg Gate in Berlin" align="left" title="File picture taken on June 19, 2013 shows US President Barack Obama wiping his brow as he and German Chancellor Angela Merkel leave the stage after his speech at the Brandenburg Gate in Berlin" border="0" /></a>Brussels (AFP) - A growing row over US spying is set to dominate an EU summit in Brussels starting Thursday, after revelations German Chancellor Angela Merkel&#039;s calls may have been monitored.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/indonesian-designers-defy-stereotypes-muslim-fashion-042451745.html' target="_blank">Indonesian designers defy stereotypes of Muslim fashion</a><br />
<p><a href="http://news.yahoo.com/indonesian-designers-defy-stereotypes-muslim-fashion-042451745.html"><img src="http://l2.yimg.com/bt/api/res/1.2/8pSsFfD79QXxx7tIgUWLUg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-24T061349Z_2_CBRE99N0CA200_RTROPTP_2_CNEWS-US-INDONESIA-FASHION.JPG" width="130" height="86" alt="Models present creations by designer Somarta during a Fashion Week show in Jakarta" align="left" title="Models present creations by designer Somarta during a Fashion Week show in Jakarta" border="0" /></a>By Andjarsari Paramaditha JAKARTA (Reuters) - As the world&#039;s most populous Muslim country, Indonesia has high demand for clothing that adheres to religious rules emphasizing modesty for women. But as the stylish, colorful and cool outfits at Jakarta Fashion Week showed, the Southeast Asian nation also aims to be the global leader in the Muslim fashion industry that is worth nearly $100 billion by some estimates. Indonesia&#039;s government is championing young designers and the garment trade, which employs more than 3 million people and contributes about $15 billion to the economy. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/israel-minister-small-differences-us-over-iran-075439416.html' target="_blank">Israel minister: 'small differences' with US over Iran</a><br />
<p><a href="http://news.yahoo.com/israel-minister-small-differences-us-over-iran-075439416.html"><img src="http://l2.yimg.com/bt/api/res/1.2/x.Qvd889ndiTRTanJktzMA--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/bcc6365f5fec95a9a0d998de7cb813fa51d25c2d.jpg" width="130" height="86" alt="US President Barack Obama (R)and Israeli Prime Minister Benjamin Netanyahu hold a meeting in the Oval Office of the White House in Washington, DC, September 30, 2013" align="left" title="US President Barack Obama (R)and Israeli Prime Minister Benjamin Netanyahu hold a meeting in the Oval Office of the White House in Washington, DC, September 30, 2013" border="0" /></a>Jerusalem (AFP) - Israel&#039;s international affairs minister on Thursday said there were &quot;small differences&quot; with the United States over the Iranian nuclear issue, a week after direct talks between Tehran and world powers.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/u-israel-differ-resolve-iran-nuclear-issue-220006059.html' target="_blank">U.S., Israel differ on how to resolve Iran nuclear issue</a><br />
<p><a href="http://news.yahoo.com/u-israel-differ-resolve-iran-nuclear-issue-220006059.html"><img src="http://l3.yimg.com/bt/api/res/1.2/dRaunA6ajkq2NRr2tI1K0g--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-23T220006Z_1_CBRE99M1P4F00_RTROPTP_2_CNEWS-US-IRAN-US-KERRY.JPG" width="130" height="86" alt="U.S. Secretary of State Kerry poses with Israeli Prime Minister Netanyahu at Villa Taverna in Rome" align="left" title="U.S. Secretary of State Kerry poses with Israeli Prime Minister Netanyahu at Villa Taverna in Rome" border="0" /></a>By Arshad Mohammed ROME (Reuters) - U.S. and Israeli officials differed over Iran&#039;s nuclear program on Wednesday as Israel called for its effective dismantlement and the United States suggested better safeguards could assure that it is peaceful rather than military in nature. U.S. Secretary of State John Kerry and Israeli Prime Minister Benjamin Netanyahu spoke as they began seven hours of talks that also covered Israeli-Palestinian peace negotiations, which resumed in July after a nearly three-year hiatus. Hints of a possible U.S. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/test-saudis-far-push-ire-over-america-195629406.html' target="_blank">Test for Saudis: How far to push ire over America?</a><br />
<p><a href="http://news.yahoo.com/test-saudis-far-push-ire-over-america-195629406.html"><img src="http://l.yimg.com/bt/api/res/1.2/b9fJ3OIVhWtDjjRzXkEhaA--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/ap_webfeeds/e6ebda26bdbd0823410f6a7067002bff.jpg" width="130" height="86" alt="FILE - In this Tuesday, June 25, 2013 file photo, U.S. Secretary of State John Kerry, left, is greeted by Saudi Foreign Minister Prince Saud al-Faisal upon arrival in Jeddah, Saudi Arabia. One day, Saudi Arabia looks to spend $6.8 billion in its latest buying spree of American weapons. Two days later, the kingdom vents its anger at the U.S. ‘s Mideast policy by snubbing a seat on the U.N. Security Council in a show of discontent. A mix of both customer and critic, Saudi Arabia is trying to carve out its own path to counter U.S. moves such as outreach to Iran, while knowing it still needs its longtime ally as a powerful big brother. (AP Photo/Jacquelyn Martin, Pool, File)" align="left" title="FILE - In this Tuesday, June 25, 2013 file photo, U.S. Secretary of State John Kerry, left, is greeted by Saudi Foreign Minister Prince Saud al-Faisal upon arrival in Jeddah, Saudi Arabia. One day, Saudi Arabia looks to spend $6.8 billion in its latest buying spree of American weapons. Two days later, the kingdom vents its anger at the U.S. ‘s Mideast policy by snubbing a seat on the U.N. Security Council in a show of discontent. A mix of both customer and critic, Saudi Arabia is trying to carve out its own path to counter U.S. moves such as outreach to Iran, while knowing it still needs its longtime ally as a powerful big brother. (AP Photo/Jacquelyn Martin, Pool, File)" border="0" /></a>DUBAI, United Arab Emirates (AP) — In Washington last week, arms regulators announced that Saudi Arabia is seeking $6.8 billion in advanced missiles and other equipment in its latest military buying spree. Days later, Saudi officials snubbed a seat on the U.N. Security Council in a stunning protest mostly aimed at U.S. policies in the Middle East.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/un-rights-review-urged-press-jordan-freedoms-195518160.html' target="_blank">UN rights review urged to press Jordan on freedoms</a><br />
<p><a href="http://news.yahoo.com/un-rights-review-urged-press-jordan-freedoms-195518160.html"><img src="http://l.yimg.com/bt/api/res/1.2/8jLBpcrxSCKv87UqXeLSfQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/098d45b572fcaedd6b7ae954b7a917602581d678.jpg" width="130" height="86" alt="A woman walks by riot police standing guard during a protest in Amman on August 14, 2013" align="left" title="A woman walks by riot police standing guard during a protest in Amman on August 14, 2013" border="0" /></a>Amman (AFP) - Human Rights Watch on Wednesday called on rights officials meeting in Geneva for a UN review of Jordan&#039;s record to press Amman to lift restrictions on freedom of expression.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/brides-bombs-nigerian-city-fights-terrorism-mass-weddings-195429642.html' target="_blank">Brides Before Bombs: Nigerian City Fights Terrorism With Mass Weddings</a><br />
In countries around the world, campaigns against terrorism have largely focused on the hard challenges of security, employing intelligence services and specialized military and police units to take the lead. But to complement those efforts, counterterrorist strategies also look at the root causes of radicalization itself. Security services have tried community engagement and monitoring of religious groups — and in some cases governments have even encouraged weddings to bring alienated young men back into the fold. 
<li><a href='http://news.yahoo.com/syria-releases-13-women-detainees-172218754.html' target="_blank">Syria releases 13 women detainees</a><br />
<p><a href="http://news.yahoo.com/syria-releases-13-women-detainees-172218754.html"><img src="http://l.yimg.com/bt/api/res/1.2/PI5rimhXZOvVmIW8Kh7ItQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/ap_webfeeds/0cfbe7528093db23400f6a706700d032.jpg" width="130" height="86" alt="In this photo, which AP obtained from Syrian official news agency SANA and which has been authenticated based on its contents and other AP reporting, President Bashar Assad, right, gestures as he speaks during an interview with Lebanon’s Al-Mayadeen TV, at the presidential palace in Damascus, Syria, Monday, Oct. 21, 2013. Syria’s president said Monday that the factors that would allow a landmark conference aimed at ending the country’s civil war do not yet exist, throwing further doubt on international efforts to hold peace talks that have already been repeatedly delayed. (AP Photo/SANA)" align="left" title="In this photo, which AP obtained from Syrian official news agency SANA and which has been authenticated based on its contents and other AP reporting, President Bashar Assad, right, gestures as he speaks during an interview with Lebanon’s Al-Mayadeen TV, at the presidential palace in Damascus, Syria, Monday, Oct. 21, 2013. Syria’s president said Monday that the factors that would allow a landmark conference aimed at ending the country’s civil war do not yet exist, throwing further doubt on international efforts to hold peace talks that have already been repeatedly delayed. (AP Photo/SANA)" border="0" /></a>BEIRUT (AP) — The Syrian government released 13 female detainees, an official and an activist group said Wednesday, in a move that appeared to be part of an ambitious regional prisoner exchange.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/analysis-saudi-move-reflects-fears-u-falling-iranian-180118004.html' target="_blank">Analysis: Saudi move reflects fears U.S. falling for Iranian charm</a><br />
<p><a href="http://news.yahoo.com/analysis-saudi-move-reflects-fears-u-falling-iranian-180118004.html"><img src="http://l1.yimg.com/bt/api/res/1.2/sOqgVTTGn.EjunGGXV_ARg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-23T181203Z_1_CBRE99M1EJH00_RTROPTP_2_USA-SAUDI.JPG" width="130" height="86" alt="U.S. President Obama meets with King Abdullah of Saudi Arabia at the White House in Washington" align="left" title="U.S. President Obama meets with King Abdullah of Saudi Arabia at the White House in Washington" border="0" /></a>By Angus McDowall and William Maclean RIYADH/DUBAI (Reuters) - Saudi Arabia&#039;s warning that it will downgrade its relationship with the United States is based on a fear that President Barack Obama lacks both the mettle and the guile to confront mutual adversaries, and is instead handing them a strategic advantage. Riyadh is locked in what it sees as a pivotal battle over the fate of the Middle East with its arch-rival Iran, a country it believes is meddling in the affairs of allies and seeking to build a nuclear bomb, charges Tehran denies. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/ap-photos-30-years-marine-barracks-blast-171445148.html' target="_blank">AP PHOTOS: 30 years after Marine barracks blast</a><br />
<p><a href="http://news.yahoo.com/ap-photos-30-years-marine-barracks-blast-171445148.html"><img src="http://l1.yimg.com/bt/api/res/1.2/WzPOFTu304G9gynYROSVIg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/ap_webfeeds/b99fbcc6bd6b0723410f6a706700719f.jpg" width="130" height="86" alt="FILE -This Sunday, Oct. 23, 1983 file photo shows the aftermath of a suicide truck bombing of the U.S. Marines barracks in Beirut, Lebanon. The blast _ the single deadliest attack on U.S. forces abroad since World War II _ claimed the lives of 241 American service members.(AP Photo/Jim Bourdier, File)" align="left" title="FILE -This Sunday, Oct. 23, 1983 file photo shows the aftermath of a suicide truck bombing of the U.S. Marines barracks in Beirut, Lebanon. The blast _ the single deadliest attack on U.S. forces abroad since World War II _ claimed the lives of 241 American service members.(AP Photo/Jim Bourdier, File)" border="0" /></a>It had been a massive, four-story building that had withstood air strikes and artillery — now reduced to a mountain of rubble. Enormous chunks of concrete, their twisted steel reinforcements ripped bare, balanced precariously on piles of debris. Only cracked concrete frames on the ground floor bore any semblance to what had stood there before.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/6-tunisian-police-killed-protests-hit-capital-163637498.html' target="_blank">6 Tunisian police killed; protests hit capital</a><br />
<p><a href="http://news.yahoo.com/6-tunisian-police-killed-protests-hit-capital-163637498.html"><img src="http://l1.yimg.com/bt/api/res/1.2/ThFxxptEO96iOwYuEO9BCQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/ap_webfeeds/7c7bf71dbd390623410f6a706700a019.jpg" width="130" height="86" alt="A man shouts during a protest in Tunis, Wednesday, Oct. 23, 2013, calling for the resignation of the government. Some thousands demonstrated in Tunisia on the day of the opening of the country&#039;s national dialogue calling for the Islamist-led government to keep its promise and resign to allow fresh elections. (AP Photo/Hassene Dridi)" align="left" title="A man shouts during a protest in Tunis, Wednesday, Oct. 23, 2013, calling for the resignation of the government. Some thousands demonstrated in Tunisia on the day of the opening of the country&#039;s national dialogue calling for the Islamist-led government to keep its promise and resign to allow fresh elections. (AP Photo/Hassene Dridi)" border="0" /></a>TUNIS, Tunisia (AP) — Suspected Islamic militants killed six Tunisian policemen in the impoverished south of the country on Wednesday, while thousands of protesters in the capital called for the government&#039;s resignation, citing growing insecurity in the country.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/kerry-meets-italian-pm-amid-media-furore-over-100655330.html' target="_blank">Italian PM raises spy claims at Kerry talks</a><br />
<p><a href="http://news.yahoo.com/kerry-meets-italian-pm-amid-media-furore-over-100655330.html"><img src="http://l.yimg.com/bt/api/res/1.2/DQU9nJEuNbLha8YixLtVLQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/032b97a76b3effae1bae14ce8210a82911df43d7.jpg" width="130" height="86" alt="US Secretary of State John Kerry (left) poses with Prime Minister Enrico Letta and Foreign Affairs Minister Emma Bonino before their meeting at the Palazzo Chigi in Rome on October 23, 2013" align="left" title="US Secretary of State John Kerry (left) poses with Prime Minister Enrico Letta and Foreign Affairs Minister Emma Bonino before their meeting at the Palazzo Chigi in Rome on October 23, 2013" border="0" /></a>Rome (AFP) - Prime Minister Enrico Letta discussed claims of US snooping on Italian communications with US Secretary of State John Kerry on Wednesday during talks in Rome, a government spokeswoman said.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/jerusalem-mayor-wins-election-boost-netanyahu-012818879.html' target="_blank">Jerusalem mayor re-elected in blow to ex-Foreign Minister Lieberman</a><br />
<p><a href="http://news.yahoo.com/jerusalem-mayor-wins-election-boost-netanyahu-012818879.html"><img src="http://l2.yimg.com/bt/api/res/1.2/tBrgb9hN3Q0kocfblbluag--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-23T132329Z_1_CBRE99M117800_RTROPTP_2_ISRAEL-POLITICS-MAYOR.JPG" width="130" height="86" alt="Jerusalem Mayor Nir Barkat prays at the Western Wall in Jerusalem&#039;s Old City" align="left" title="Jerusalem Mayor Nir Barkat prays at the Western Wall in Jerusalem&#039;s Old City" border="0" /></a>By Jeffrey Heller JERUSALEM (Reuters) - The Israeli mayor of Jerusalem won re-election on Wednesday in a hotly contested race that dealt a political blow to his challenger&#039;s main backers, former Foreign Minister Avigdor Lieberman and the ultra-Orthodox Shas party. Lieberman, a legislator whose far-right Yisrael Beitenu party is allied with Prime Minister Benjamin Netanyahu&#039;s Likud, is embroiled in a corruption case, with a court verdict next month likely to determine whether he returns to the cabinet. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/13-jailed-syrian-women-released-121436925.html' target="_blank">13 jailed Syrian women released</a><br />
<p><a href="http://news.yahoo.com/13-jailed-syrian-women-released-121436925.html"><img src="http://l.yimg.com/bt/api/res/1.2/PI5rimhXZOvVmIW8Kh7ItQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/ap_webfeeds/0cfbe7528093db23400f6a706700d032.jpg" width="130" height="86" alt="In this photo, which AP obtained from Syrian official news agency SANA and which has been authenticated based on its contents and other AP reporting, President Bashar Assad, right, gestures as he speaks during an interview with Lebanon’s Al-Mayadeen TV, at the presidential palace in Damascus, Syria, Monday, Oct. 21, 2013. Syria’s president said Monday that the factors that would allow a landmark conference aimed at ending the country’s civil war do not yet exist, throwing further doubt on international efforts to hold peace talks that have already been repeatedly delayed. (AP Photo/SANA)" align="left" title="In this photo, which AP obtained from Syrian official news agency SANA and which has been authenticated based on its contents and other AP reporting, President Bashar Assad, right, gestures as he speaks during an interview with Lebanon’s Al-Mayadeen TV, at the presidential palace in Damascus, Syria, Monday, Oct. 21, 2013. Syria’s president said Monday that the factors that would allow a landmark conference aimed at ending the country’s civil war do not yet exist, throwing further doubt on international efforts to hold peace talks that have already been repeatedly delayed. (AP Photo/SANA)" border="0" /></a>BEIRUT (AP) — The Syrian government has released 13 jailed women, an official and an activist group said on Wednesday — a move that may be part of an ambitious regional prisoner exchange.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/activists-13-jailed-syrian-women-released-083434193.html' target="_blank">Activists: 13 jailed Syrian women released</a><br />
BEIRUT (AP) — The Syrian government has released 13 jailed women, an official and an activist group said on Wednesday — a move that may be part of an ambitious regional prisoner exchange.
<li><a href='http://news.yahoo.com/fearing-retribution-syrian-minorities-keep-low-profile-exile-111656356.html' target="_blank">Fearing retribution, Syrian minorities keep low profile in exile</a><br />
By Humeyra Pamuk ISTANBUL (Reuters) - In a small park on the edge of old Istanbul's Eminonu square, women sit begging, Syrian passports in their outstretched hands, "Please help in the name of God" on sheets of paper at their feet. In this bustling city, where fisherman line the shore of the Golden Horn and tourists mingle with traders in the alleyways of the spice bazaar, the war raging just over Turkey's southern border feels very distant. 
<li><a href='http://news.yahoo.com/saudi-arabia-warns-shift-away-u-over-syria-002703562.html' target="_blank">Saudi Arabia warns of shift away from U.S. over Syria, Iran</a><br />
<p><a href="http://news.yahoo.com/saudi-arabia-warns-shift-away-u-over-syria-002703562.html"><img src="http://l2.yimg.com/bt/api/res/1.2/D3BLvU2BqkYeeKVgVdzKLw--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-23T002703Z_3_CBRE99L14GF00_RTROPTP_2_CNEWS-US-SAUDI-USA.JPG" width="130" height="86" alt="Prince Bandar bin Sultan, Secretary-General of Saudi Arabia&#039;s National Security Council shakes hands with Russia&#039;s Prime Minister Vladimir Putin as they meet in Moscow" align="left" title="Prince Bandar bin Sultan, Secretary-General of Saudi Arabia&#039;s National Security Council shakes hands with Russia&#039;s Prime Minister Vladimir Putin as they meet in Moscow" border="0" /></a>By Amena Bakr and Warren Strobel DOHA/WASHINGTON (Reuters) - Upset at President Barack Obama&#039;s policies on Iran and Syria, members of Saudi Arabia&#039;s ruling family are threatening a rift with the United States that could take the alliance between Washington and the kingdom to its lowest point in years. Saudi Arabia&#039;s intelligence chief is vowing that the kingdom will make a &quot;major shift&quot; in relations with the United States to protest perceived American inaction over Syria&#039;s civil war as well as recent U.S. overtures to Iran, a source close to Saudi policy said on Tuesday. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/focus-arab-states-fill-saudi-security-council-seat-001819435.html' target="_blank">Focus on Arab states to fill Saudi Security Council seat, Kuwait a front-runner</a><br />
By Michelle Nichols UNITED NATIONS (Reuters) - Saudi Arabia's unprecedented rejection of a U.N. Security Council place has pushed the world body into uncharted territory, but fellow Gulf nation Kuwait is emerging as an early front-runner to fill the seat. With 10 weeks until Saudi Arabia's term on the 15-member Security Council was due to start - on January 1 - U.N. diplomats do not appear to be in a rush to fill the vacancy and some are hoping Riyadh might still change its mind. "One waits to see what will happen," British U.N. Ambassador Mark Lyall Grant said on Tuesday. 
<li><a href='http://news.yahoo.com/syria-opposition-under-pressure-negotiate-201958378.html' target="_blank">Syria opposition under pressure to negotiate</a><br />
<p><a href="http://news.yahoo.com/syria-opposition-under-pressure-negotiate-201958378.html"><img src="http://l1.yimg.com/bt/api/res/1.2/VHpkprXAnV9Xl7Q29.VuWg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/ap_webfeeds/dbfbd5ab9f0cf123400f6a706700c530.jpg" width="130" height="86" alt="Members of the Syrian Opposition Coalition, including the group&#039;s President Ahmed Jarba, center, Heitham Al-Maleh, left, and Salem Al-Muslit speak to the media at the British Foreign Office in London Tuesday, Oct. 22, 2013. Foreign ministers and representatives of eleven nations from the West and Mideast met in London on Tuesday to discuss ways to reach a negotiated end to the war in Syria. (AP Photo/Alastair Grant)" align="left" title="Members of the Syrian Opposition Coalition, including the group&#039;s President Ahmed Jarba, center, Heitham Al-Maleh, left, and Salem Al-Muslit speak to the media at the British Foreign Office in London Tuesday, Oct. 22, 2013. Foreign ministers and representatives of eleven nations from the West and Mideast met in London on Tuesday to discuss ways to reach a negotiated end to the war in Syria. (AP Photo/Alastair Grant)" border="0" /></a>BEIRUT (AP) — The U.S. and Europe are putting intense pressure on the main Syrian opposition group to attend a long-delayed peace conference aimed at ending Syria&#039;s civil war, even though agreeing to join the talks could irreparably split the already-fragmented opposition in exile.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/texas-m-plans-israel-campus-165604014.html' target="_blank">Texas A&M plans Israel campus</a><br />
<p><a href="http://news.yahoo.com/texas-m-plans-israel-campus-165604014.html"><img src="http://l1.yimg.com/bt/api/res/1.2/n2z00L7UetqXKoszicBRtA--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/ap_webfeeds/c40f44999eeef123400f6a70670047fb.jpg" width="130" height="86" alt="FILE - In this Friday, May 8, 2009 file photo, the Church of Annunciation, one of Christianity&#039;s holiest sites, is seen in the background as Israeli Arab Muslim worshippers pray during Friday noon prayers in the northern Israeli city of Nazareth. Texas A&amp;M University said it plans on opening a branch campus in Israel, a first-of-its-kind project that will expand the American university’s growing overseas presence. Texas A&amp;M&#039;s chancellor, John Sharp, said Tuesday, Oct. 22, 2013, that the city, which is best known for being the place of Jesus&#039; childhood, was chosen to help bring Israel&#039;s Arabs and Jews together in a center of learning. (AP Photo/Tara Todras-Whitehill, File)" align="left" title="FILE - In this Friday, May 8, 2009 file photo, the Church of Annunciation, one of Christianity&#039;s holiest sites, is seen in the background as Israeli Arab Muslim worshippers pray during Friday noon prayers in the northern Israeli city of Nazareth. Texas A&amp;M University said it plans on opening a branch campus in Israel, a first-of-its-kind project that will expand the American university’s growing overseas presence. Texas A&amp;M&#039;s chancellor, John Sharp, said Tuesday, Oct. 22, 2013, that the city, which is best known for being the place of Jesus&#039; childhood, was chosen to help bring Israel&#039;s Arabs and Jews together in a center of learning. (AP Photo/Tara Todras-Whitehill, File)" border="0" /></a>JERUSALEM (AP) — The head of Texas A&amp;M University said Tuesday that he plans on opening a branch campus in Israel, a project meant to bring Arabs and Jews together and expand the school&#039;s growing overseas presence.</p><br clear="all"/>
<li><a href='http://news.yahoo.com/white-house-cooperation-saudis-continue-173837070--politics.html' target="_blank">White House: cooperation with Saudis to continue</a><br />
WASHINGTON (AP) — The Obama administration says its cooperation with Saudi Arabia will continue despite the kingdom's rejection of a coveted seat on the U.N. Security Council.
<li><a href='http://news.yahoo.com/foreign-rivals-radical-islam-weaken-russia-putin-132615813.html' target="_blank">Putin says foreign foes use radical Islam to weaken Russia</a><br />
<p><a href="http://news.yahoo.com/foreign-rivals-radical-islam-weaken-russia-putin-132615813.html"><img src="http://l1.yimg.com/bt/api/res/1.2/_OsyOG8CZwDnVJhCO710pQ--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-22T171249Z_3_CBRE99L11BV00_RTROPTP_2_ASIA-APEC.JPG" width="130" height="86" alt="Russia&#039;s President Putin leaves the APEC Leaders Press Conference and Joint Declaration in Nusa Dua" align="left" title="Russia&#039;s President Putin leaves the APEC Leaders Press Conference and Joint Declaration in Nusa Dua" border="0" /></a>By Alexei Anishchuk UFA, Russia (Reuters) - President Vladimir Putin accused foreign rivals on Tuesday of using radical Islam to weaken Russia and appealed to Muslim clerics to help reduce tensions after a deadly suicide bombing and nationalist riots. The comments, his first on this month&#039;s riots in Moscow, were delivered in the mainly Muslim region of Bashkortostan and underlined Kremlin concerns that ethnic or religious tensions could threaten the unity of the Russian state. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/obama--france%E2%80%99s-hollande--one-nsa-call--two-stories-144039070.html' target="_blank">Obama, France’s Hollande: One NSA call, 2 stories</a><br />
<p><a href="http://news.yahoo.com/obama--france%E2%80%99s-hollande--one-nsa-call--two-stories-144039070.html"><img src="http://l2.yimg.com/bt/api/res/1.2/1xZZmwPx.hjmqLB6_fgLTg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/afp.com/aabc40a48ff8fc9c1badeb21c84de9169babe00e.jpg" width="130" height="86" alt="Graphic showing the structure of alleged eavesdropping activities by the NSA" align="left" title="Graphic showing the structure of alleged eavesdropping activities by the NSA" border="0" /></a>Very different versions of a tense chat about U.S. spying</p><br clear="all"/>
<li><a href='http://news.yahoo.com/eu-revives-membership-talks-turkey-three-hiatus-124546480.html' target="_blank">EU revives membership talks with Turkey after three-year hiatus</a><br />
<p><a href="http://news.yahoo.com/eu-revives-membership-talks-turkey-three-hiatus-124546480.html"><img src="http://l1.yimg.com/bt/api/res/1.2/ttLAk7ENVRziC1BF6_tGCg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTg2O3E9NzU7dz0xMzA-/http://media.zenfs.com/en_us/News/Reuters/2013-10-22T124546Z_1_CBRE99L0ZGG00_RTROPTP_2_TURKEY-REFORM.JPG" width="130" height="86" alt="Turkish PM Erdogan waves as he leaves news conference in Ankara" align="left" title="Turkish PM Erdogan waves as he leaves news conference in Ankara" border="0" /></a>By Justyna Pawlak BRUSSELS (Reuters) - The European Union will launch a new round of accession talks with Turkey next month following a three-year hiatus after Germany dropped opposition prompted by Ankara&#039;s crackdown on street protests. Turkey began negotiations to join the EU in 2005, 18 years after applying, but a series of political obstacles, notably over Cyprus and resistance to Turkish membership in Germany and France, have slowed progress. </p><br clear="all"/>
<li><a href='http://news.yahoo.com/markets-flat-ahead-delayed-us-jobs-report-094917544--finance.html' target="_blank">Markets flat ahead of delayed US jobs report</a><br />
LONDON (AP) — Financial markets were steady Tuesday ahead of the next round of U.S. corporate and economic news that includes the delayed nonfarm payrolls data for September.
</ul></div>



</p>
</body>
</html>
