<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="style.css" rel="stylesheet" type="text/css" />
<base target="_blank" />
</head>

<body style="background: url(images/ssn-img-info-bkgd.jpg) no-repeat">
<h4>Middle East Trips</h4>
<div id="info" class="scroll">
<div>
<ul>
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2940'>iExplore Dubai Gold</a><br />
Dubai is the quintessential home of sand, sun and shopping. A century ago, it was a tranquil town whose coral-and-gypsum huts housed Bedouin traders and pearl divers. Today the merchants have gone international and science-fiction skyscrapers stand alongside the mosques and wind towers of Old Dubai.The audacity of the city&#039;s rulers is breathtaking. Running out of coastline to build hotels? Build vast artificial islands with 120km (74.5mi) of new beachfront. Need better connections with the world? Build up an award-winning international airline in 15 years.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2941'>iExplore Dubai Silver</a><br />
Dubai is the quintessential home of sand, sun and shopping. A century ago, it was a tranquil town whose coral-and-gypsum huts housed Bedouin traders and pearl divers. Today the merchants have gone international and science-fiction skyscrapers stand alongside the mosques and wind towers of Old Dubai.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2978'>iExplore Israel Gold</a><br />
At times, Israel can seem like a country obsessed by spirituality. In Jerusalem, you may hear the Muslim call to prayer competing with the clanging of bells from Christian churches and the prayers of Jews before the Western Wall. In other parts of the country, you&#039;ll find yourself walking in the exact places where the events of the Bible unfolded. Everywhere you turn, you&#039;ll see reminders of the three religions - Islam, Judaism and Christianity - that have shaped this part of the world.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2986'>iExplore Jordan and Syria Gold</a><br />
Set on the ancient crossroads between Arabia and the Mediterranean Sea, Jordan is full of historic sites. Crusaders&#039; forts along old trade routes and ancient cities carved from stone will captivate anyone in search of the past. And while the land might be ancient, Jordan&#039;s cities offer the modern conveniences that help make your trip to the past a little less demanding.Syria is home to some of the best ruins in the world. For those interested in ancient history and the culture of the Middle East, it&#039;s an absolute treasure trove. Clubs, bars and cafes have sprouted all over Damascus, the capital, and it&#039;s quite common to see wizened old men in traditional kaffiyehs talking with young men in T-shirts or to spot old women in chadors mingling with young women in short skirts and makeup. The odd juxtapositions actually add to the country&#039;s allure.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2987'>iExplore Jordan and Syria Silver</a><br />
Set on the ancient crossroads between Arabia and the Mediterranean Sea, Jordan is full of historic sites. Crusaders&#039; forts along old trade routes and ancient cities carved from stone will captivate anyone in search of the past. And while the land might be ancient, Jordan&#039;s cities offer the modern conveniences that help make your trip to the past a little less demanding. When you tire of desert ardors, you can relax at a Dead Sea spa or go scuba diving in the Red Sea.Although it&#039;s mostly covered by desert, Jordan also has mountains, forests, marshes, beaches, plains, rolling hills and fertile river valleys. The Jordan Valley is actually an extension of the Great Rift Valley, which runs through Kenya and Tanzania in Africa.Syria is home to some of the best ruins in the world. For those interested in ancient history and the culture of the Middle East, it&#039;s an absolute treasure trove. Clubs, bars and cafes have sprouted all over Damascus, the capital, and it&#039;s quite common to see wizened old men in traditional kaffiyehs talking with young men in T-shirts or to spot old women in chadors mingling with young women in short skirts and makeup. The odd juxtapositions actually add to the country&#039;s allure.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2988'>iExplore Jordan Gold</a><br />
Desert adventurer T. E. Lawrence&#039;s wartime trek across Jordan, from Wadi Rum to Aqaba, was one of the most arduous journeys of modern times. These days, however, you can explore Jordan&#039;s challenging terrain with considerably less effort. You&#039;ll probably forego camels for, say, an air-conditioned four-wheel-drive. But you might well echo Lawrence of Arabia&#039;s awestruck description of Jordan&#039;s dramatic desert-scapes as &quot;vast, echoing, and God-like.&quot;Set on the ancient crossroads between Arabia and the Mediterranean Sea, Jordan is full of historic sites. Crusaders&#039; forts along old trade routes and ancient cities carved from stone will captivate anyone in search of the past. And while the land might be ancient, Jordan&#039;s cities offer the modern conveniences that help make your trip to the past a little less demanding. When you tire of desert ardors, you can relax at a Dead Sea spa or go scuba diving in the Red Sea.Although it&#039;s mostly covered by desert, Jordan also has mountains, forests, marshes, beaches, plains, rolling hills and fertile river valleys. The Jordan Valley is actually an extension of the Great Rift Valley, which runs through Kenya and Tanzania in Africa.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2989'>iExplore Jordan Silver</a><br />
Desert adventurer T. E. Lawrence&#039;s wartime trek across Jordan, from Wadi Rum to Aqaba, was one of the most arduous journeys of modern times. These days, however, you can explore Jordan&#039;s challenging terrain with considerably less effort. You&#039;ll probably forego camels for, say, an air-conditioned four-wheel-drive. But you might well echo Lawrence of Arabia&#039;s awestruck description of Jordan&#039;s dramatic desertscapes as &quot;vast, echoing, and God-like.&quot;Set on the ancient crossroads between Arabia and the Mediterranean Sea, Jordan is full of historic sites. Crusaders&#039; forts along old trade routes and ancient cities carved from stone will captivate anyone in search of the past. And while the land might be ancient, Jordan&#039;s cities offer the modern conveniences that help make your trip to the past a little less demanding. When you tire of desert ardors, you can relax at a Dead Sea spa or go scuba diving in the Red Sea.Although it&#039;s mostly covered by desert, Jordan also has mountains, forests, marshes, beaches, plains, rolling hills and fertile river valleys. The Jordan Valley is actually an extension of the Great Rift Valley, which runs through Kenya and Tanzania in Africa
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip2216'>Jordan Explorer</a><br />
For such a compact country, Jordan has an overwhelming array of historical sites and geographical features ripe for exploration. From the magical hidden city of Petra where the Queen of Sheba once showered her gifts on King Solomon, to the Wadi Rum where Lawrence of Arabia spent time during the Arab Revolt, and from the Dead Sea to the Red Sea coast and the Crusader Castles dotted throughout the country, this journey manages to encompass all of the highlights. Our day walks in Petra take us to the High Place of Sacrifice at sunrise and the monastery.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3711'>Ancient Cities Of Jordan And Syria</a><br />
Few places offer the diverse cultural past of Jordan and Syria. A past that reflects all the great early civilisations - the Egyptians, Assyrians, Babylonians, Hittites, Greeks, Romans, Arabs, Turks and the Crusaders that made their mark across these ancient lands. Our journey combines visits to the main historical sites that shaped and inspired Jordan and Syria&#039;s rich and varied cultural history with a modern day perspective of the Middle East. In Jordan we absorb the country&#039;s many highlights including Petra, a hidden city carved out of rock and journey by camel through the spectacular Wadi Rum with the local Bedouin. Snorkelling in the Red Sea, floating in the Dead Sea, exploring Crusader castles, the bustling city of Amman and the ancient city of Jerash, &#039;the Pompeii of the East&#039; round off our time in Jordan before the journey continues to Syria. In Damascus we wander the labyrinth of alleyways and visit the impressive Ommayad Mosque before heading to the &#039;Bronze Age&#039; city of Ugarit with its incredible archaeological finds. The ancient city of Aleppo with its souqs, castles and museums and the oasis city of Palmyra are the historical highlights of our time in Syria.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3853'>Ancient Cities Of Jordan And Syria</a><br />
Few places offer the diverse cultural past of Jordan and Syria. A past that reflects all the great early civilisations - the Egyptians, Assyrians, Babylonians, Hittites, Greeks, Romans, Arabs, Turks and the Crusaders that made their mark across these ancient lands. Our journey combines visits to the main historical sites that shaped and inspired Jordan and Syria&#039;s rich and varied cultural history with a modern day perspective of the Middle East. In Jordan we absorb the country&#039;s many highlights including Petra, a hidden city carved out of rock and journey by camel through the spectacular Wadi Rum with the local Bedouin. Snorkelling in the Red Sea, floating in the Dead Sea, exploring Crusader castles, the bustling city of Amman and the ancient city of Jerash, &#039;the Pompeii of the East&#039; round off our time in Jordan before the journey continues to Syria. In Damascus we wander the labyrinth of alleyways and visit the impressive Ommayad Mosque before heading to the &#039;Bronze Age&#039; city of Ugarit with its incredible archaeological finds. The ancient city of Aleppo with its souqs, castles and museums and the oasis city of Palmyra are the historical highlights of our time in Syria.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3886'>Jordan Explorer</a><br />
For such a compact country, Jordan has an overwhelming array of historical sites and geographical features ripe for exploration. From the magical hidden city of Petra where the Queen of Sheba once showered her gifts on King Solomon, to the Wadi Rum where Lawrence of Arabia spent time during the Arab Revolt, and from the Dead Sea to the Red Sea coast and the Crusader Castles dotted throughout the country, this journey manages to encompass all of the highlights. Our day walks in Petra take us to the High Place of Sacrifice at sunrise and the monastery. We visit Madaba and Mt Nebo - from where Moses is said to have seen the &#039;Promised Land&#039;, and travel the Kings Highway to the prominent crusader castle of Kerak. A journey into the Wadi Rum allows us to spend time among the local Bedouin people sharing songs and stories beneath the starry night before continuing south to the azure waters of the red sea where we will spend time snorkeling amongst the coral. Returning north via the desert highway, our adventure itinerary continues with time at the desert castles west of Amman, before a visit to Jerash, &#039;the Pompeii of the East&#039; , a fitting end to this historical journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4036'>Ancient Cities Of Jordan And Syria</a><br />
Few places offer the diverse cultural past of Jordan and Syria. A past that reflects all the great early civilisations - the Egyptians, Assyrians, Babylonians, Hittites, Greeks, Romans, Arabs, Turks and the Crusaders that made their mark across these ancient lands. Our journey combines visits to the main historical sites that shaped and inspired Jordan and Syria&#039;s rich and varied cultural history with a modern day perspective of the Middle East. In Jordan we absorb the country&#039;s many highlights including Petra, a hidden city carved out of rock and journey by camel through the spectacular Wadi Rum with the local Bedouin. Snorkelling in the Red Sea, floating in the Dead Sea, exploring Crusader castles, the bustling city of Amman and the ancient city of Jerash, &#039;the Pompeii of the East&#039; round off our time in Jordan before the journey continues to Syria. In Damascus we wander the labyrinth of alleyways and visit the impressive Ommayad Mosque before heading to the &#039;Bronze Age&#039; city of Ugarit with its incredible archaeological finds. The ancient city of Aleppo with its souqs, castles and museums and the oasis city of Palmyra are the historical highlights of our time in Syria.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip4149'>Jordan Explorer</a><br />
For such a compact country, Jordan has an overwhelming array of historical sites and geographical features ripe for exploration. From the magical hidden city of Petra where the Queen of Sheba once showered her gifts on King Solomon, to the Wadi Rum where Lawrence of Arabia spent time during the Arab Revolt, and from the Dead Sea to the Red Sea coast and the Crusader Castles dotted throughout the country, this journey manages to encompass all of the highlights. Our day walks in Petra take us to the High Place of Sacrifice at sunrise and the monastery. We visit Madaba and Mt Nebo - from where Moses is said to have seen the &#039;Promised Land&#039;, and travel the Kings Highway to the prominent crusader castle of Kerak. A journey into the Wadi Rum allows us to spend time among the local Bedouin people sharing songs and stories beneath the starry night before continuing south to the azure waters of the red sea where we will spend time snorkeling amongst the coral. Returning north via the desert highway, our adventure itinerary continues with time at the desert castles west of Amman, before a visit to Jerash, &#039;the Pompeii of the East&#039; , a fitting end to this historical journey.
<li><a href='http://www.adventureengine.com/sch_moreResults.php?tripid=trip3597'>Caravan Route</a><br />
Introduction: With permanent settlements dating back to 9000 BC, Jordan and Egypt can lay claim to being the most historically revealing countries in the world. Few people who have stood before the massive rock facades of Petra or Egypts great pyramids would argue with this. From the fun of bathing in the Dead Sea and the eerily beautiful scenery at Wadi Rum to the spiritual summit of Mount Sinai and the chaos of Cairo, you will find the Jordanian and Egyptian people warm and welcoming and you will leave with a positive message from life in the Arab world. This tour also runs in reverse - call for details
</ul></div>

</div>
</body>
</html>
