<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>

<link href="styles.css" rel="stylesheet" type="text/css"></head>

<body>

<div id="textwrap" class="midbak">
<h3>Home : What's Happening</h3>

<div id="textmain" class="scroll">

<div>
<ul>
<li><a href='http://www.southeastasianews.net/index.php/sid/216286877/scat/303b19022816233b' target="_blank">Gavaskar `real Little Master` says cancer-battling Hanif Mohammad</a><br />
Pakistan legend Hanif Mohammad has praised prolific former Indian batsman Sunil Gavaskar, calling him the 'real Little Master'. According to The Dawn, Hanif, known as the Little Master of cricket, magnanimously conferred the honour on the Indian icon, who called him to inquire about his health and wished him a speedy recovery from his battle with cancer. Stating that he was 'highly impressed' 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286872/scat/303b19022816233b' target="_blank">Thai badminton player slapped with two-year ban for fighting with ex-doubles partner</a><br />
A Thai badminton player has reportedly been handed a two-year ban over a fight with his former doubles partner during last month's Yonex Canada Open in Richmond, British Columbia. According to the Guardian, while Bodin Issara has been banned for two years, his compatriot Maneepong Jongjit has been suspended for three months for his part in the incident. The report further said that Issara was 
<li><a href='http://www.southeastasianews.net/index.php/sid/216285787/scat/303b19022816233b' target="_blank">11 kids dead in Karachi bombing</a><br />
At least 11 children were killed while 24 injured when a bomb exploded near a market in Pakistan's port city of Karachi early Wednesday, the Geo News reported citing a political leader. The explosive material was planted on a motorbike, said police. The explosion occurred in the city's Lyari area shortly after a football match ended, said Member Provincial Assembly (MPA) Sania Naz, who was 
<li><a href='http://www.southeastasianews.net/index.php/sid/216274379/scat/303b19022816233b' target="_blank">LoC killing We know our national interests and responsibilities says Khurshid</a><br />
Hours after the Bharatiya Janata Party (BJP) questioned the government on foreign policy and asserted that New Delhi must not resume talks with Islamabad, External Affairs Minister Salman Khurshid on Tuesday assured that appropriate steps will be taken in the matter concerning the killing of five Indian soldiers by Pakistani troops along the Line of Control (LoC) in Jammu and Kashmir's Poonch 
<li><a href='http://www.southeastasianews.net/index.php/sid/216274377/scat/303b19022816233b' target="_blank">PM Antony should resign or give befitting reply to Pak Anurag ThakurUpdate</a><br />
Bharatiya Janata Yuva Morcha (BJYM) President Anurag Thakur on Tuesday said Prime Minister Dr. Manmohan Singh and Defence Minister A.K. Antony should tender their resignations if they are 'incompetent to give a befitting reply to Islamabad' following the killing of five Indian soldiers on the Line of Control in Jammu and Kashmir by Pakistani troops. Thakur question the government's inaction 
<li><a href='http://www.southeastasianews.net/index.php/sid/216271743/scat/303b19022816233b' target="_blank">BJP workers protest outside Antonys residence demand action against PakUpdate</a><br />
The Bharatiya Janata Party (BJP) youth wing activists and workers staged a protest outside Defence Minister A.K. Antony's residence here on Tuesday evening to vent their ire over the killing of five Indian soldiers on the Line of Control in Jammu and Kashmir by Pakistani troops. The BJP youth wing activists, who were led by Bharatiya Janata Yuva Morcha (BJYM) President Anurag Thakur, raised 
<li><a href='http://www.southeastasianews.net/index.php/sid/216271494/scat/303b19022816233b' target="_blank">Chinese hoopsters beat India at Asian championships</a><br />
Defending champion China defeated India 79-45 to win back-to-back games in Group F at the 27th Asian Men's Basketball Championship here Tuesday. But the match wasn't easy for China as they lost two key players, reports Xinhua. Former NBA player Yi Jianlian strained his thigh muscle before the tournament and only played China's opening match against South Korea and point guard Liu Xiaoyu injured 
<li><a href='http://www.southeastasianews.net/index.php/sid/216271489/scat/303b19022816233b' target="_blank">Benazir murder Musharraf to face charges Aug 20</a><br />
A Rawalpindi court Tuesday ruled that former Pakistan president Pervez Musharraf would be indicted for the murder of former prime minister Benazir Bhutto Aug 20 after he failed to appear before it due to security concerns, a leading Pakistani daily said. Musharraf had been summoned to face charges of criminal conspiracy and the murder of Bhutto, according to The Dawn. Police and Musharraf's 
<li><a href='http://www.southeastasianews.net/index.php/sid/216271305/scat/303b19022816233b' target="_blank">LoC killing Jaitley asks India to give befitting message to Pakistan</a><br />
Leader of Opposition in the Rajya Sabha, Arun Jaitley, on Tuesday condemned the killing of five Indian soldiers in Jammu and Kashmir's Poonch area, and asked New Delhi to give a befitting message to Islamabad. "Today's incident is condemnable. We join the Defence Minister (A.K. Antony) in saluting the families of the deceased. We can't make a spectacle of ourselves in front of the world, we 
<li><a href='http://www.southeastasianews.net/index.php/sid/216270823/scat/303b19022816233b' target="_blank">Pakistan rejects Indian allegations of killing of its soldiers</a><br />
The Pakistan Government on Tuesday categorically rejected the allegations carried by some sections of the Indian media of an attack across the LoC in the Poonch sector in which five Indian soldiers were killed. In a statement, the Pakistan Foreign Office said: "These are baseless and unfounded allegations. Our military authorities have confirmed that there had been no exchange of fire that 
<li><a href='http://www.southeastasianews.net/index.php/sid/216270817/scat/303b19022816233b' target="_blank">India cant be cowed down by such blatant attack Sonia Gandhi</a><br />
Congress president Sonia Gandhi on Tuesday condemned the killing of five Indian soldiers by Pakistani troops in Jammu and Kashmir's Poonch District, saying that India can't be cowed down by such a blatant attack. Urging the government to take appropriate action in the matter, Gandhi said:"The Congress party and the nation stand by the martyred soldiers. We will not be cowed down by such blatant 
<li><a href='http://www.southeastasianews.net/index.php/sid/216270129/scat/303b19022816233b' target="_blank">Defense analysts urge Centre to take tough stand against Pakistan</a><br />
Defense experts have urged the Central Government to take immediate and stiff action against Pakistan, after five Indian soldiers were killed in an ambush by their troops in Jammu and Kashmir's Poonch District late on Monday night. Defence Minister A. K. Antony confirmed that about 20 heavily armed men dressed in Pakistani military uniforms carried out the attack on the Indian soldiers. 
<li><a href='http://www.southeastasianews.net/index.php/sid/216268976/scat/303b19022816233b' target="_blank">Pakistan citizen files petition in SC against Nawaz Sharif for naming next Army Chief</a><br />
A Pakistani resident has filed a petition in the Supreme Court to challenge Prime Minister Nawaz Sharif's stated policy of appointing the senior most general as the next Chief of Army Staff. According to Express Tribune, Shahid Orakzai had appealed against the earlier Islamabad High Court verdict by approaching the apex court with the plea that an ordinary citizen could raise the fundamental 
<li><a href='http://www.southeastasianews.net/index.php/sid/216268975/scat/303b19022816233b' target="_blank">Gulam Nabi Azad expresses concern over Poonch incident accuses Pakistan</a><br />
Expressing concern over the death of five Indian soldiers following an attack by Pakistani troops along the Line of Control (LoC) in Jammu and Kashmir's Poonch District late on Monday night, Minister of Health and Family Welfare Gulam Nabi Azad on Tuesday said that neighbouring countries are taking undue advantage of India efforts to maintain good relations with her neighbours. Every time a 
<li><a href='http://www.southeastasianews.net/index.php/sid/216268958/scat/303b19022816233b' target="_blank">Pak court defers Musharrafs indictment in Bhutto murder case</a><br />
A Pakistani court has adjourned the hearing of former president Pervez Musharraf in Benazir Bhutto murder case after he failed to appear on time for the hearing over security reasons. Musharraf had been summoned to face charges of criminal conspiracy and the murder of Bhutto in December 2007. According to Dawn News, police and his lawyer told the court in Rawalpindi, the city where Bhutto was 
<li><a href='http://www.southeastasianews.net/index.php/sid/216267998/scat/303b19022816233b' target="_blank">Pakistan has violated cease-fire 57 times in 2013</a><br />
The Pakistan Army and its affiliates have violated the cease-fire established in November 2003 57 times in 2013, which is almost 50 per cent more than the violations that took place in the previous year, sources said. According to sources, effective counter-infiltration measures along the border separating India and Pakistan resulted in 17 bids being foiled. The sources further stated that 
<li><a href='http://www.southeastasianews.net/index.php/sid/216267997/scat/303b19022816233b' target="_blank">Border Action team of Pak Army killed Indian Army soldiers</a><br />
The Border Action Team (BAC) of the Pakistan Army, comprising of militants and Pakistan Army regulars, organised the ambush and killing of five Indian Army soldiers, sources here said on Tuesday. According to sources, the five dead soldiers were part of a six-member patrol team, and belonged to the 21 Bihar Regiment. Sources further revealed that after carrying out their attack, 15 to 20 
<li><a href='http://www.southeastasianews.net/index.php/sid/216267977/scat/303b19022816233b' target="_blank">Oz woman accused of racial rant against Asian schoolboy escapes conviction</a><br />
The Australian woman who was accused of racially abusing an Asian schoolboy Sydney bus earlier this year has reportedly escaped a conviction although she had pleaded guilty to the offence. According to News.com.au, Susan Bernobich from Sydney had pleaded guilty to one charge of using offensive language in or near a public place or school and has apologised for her actions outside the court. The 
<li><a href='http://www.southeastasianews.net/index.php/sid/216267782/scat/303b19022816233b' target="_blank">Friendship talks and killings cannot go on simultaneously says BJP</a><br />
After five Indian soldiers were killed in an ambush by Pakistani troops in Jammu and Kashmir's Poonch District late on Monday night, the Bharatiya Janata Party (BJP) launched a frontal attack on the Central Government on Tuesday, demanding that they take a tougher stance on border violence. Former BJP President Nitin Gadkari criticised the Central Government for its apathetic attitude towards 
<li><a href='http://www.southeastasianews.net/index.php/sid/216267781/scat/303b19022816233b' target="_blank">Defence Ministry will come out with appropriate response on Pakistans attack Manish Tewari</a><br />
Following the killing of five Indian soldiers by Pakistani troops along the Line of Control (LoC) in Jammu and Kashmir's Poonch District late on Monday night, Minister of Information and Broadcasting Manish Tewari on Tuesday assured that the Ministry of Defence would come out with an appropriate response. "It is very unfortunate that even before the full details of the incident are in, people 
<li><a href='http://www.southeastasianews.net/index.php/sid/216266959/scat/303b19022816233b' target="_blank">Pak beefs up security following Taliban threat to high-profile targets in Islamabad</a><br />
The Pakistani security agencies have reportedly beefed up security at prominent places, including the parliament and the Navy and Air Force headquarters, after a message from a militant group was intercepted which said that their next target would be where the 'big bosses' sit. According to the Express Tribune, Pakistani intelligence intercepted the message between two commanders of the 
<li><a href='http://www.southeastasianews.net/index.php/sid/216266101/scat/303b19022816233b' target="_blank">Is Congress with Pakistan or India questions BJPs Yashwant Sinha</a><br />
Senior Bharatiya Janata Party (BJP) leader Yashwant Sinha on Tuesday criticised the Congress-led UPA Government for its less than forthright response to the killing of five Indian soldiers along the Line of Control in Poonch by Pakistani troops, and said that the ruling party should say whether it is with India or Pakistan. "Is the Congress with India or with Pakistan? They should come clear on 
<li><a href='http://www.southeastasianews.net/index.php/sid/216266088/scat/303b19022816233b' target="_blank">Pak U19 cricket captain calls for PCB to organise more tours outside Asia</a><br />
Pakistan U19 captain Sami Aslam has expressed his concern at the lack of U19 tours organised by the PCB of late, which has meant that young up and coming cricketers in the country have been limited to playing only in domestic competitions unlike other countries. In an interview with pakpassion.net, Aslam expressed that the lack of U19 tours was an issue and it would most certainly help with the 
<li><a href='http://www.southeastasianews.net/index.php/sid/216266087/scat/303b19022816233b' target="_blank">Chennai Express derails Main Hoon Shahid Afridi ahead of Id in Pak</a><br />
The makers of 'Main Hoon Shahid Afridi' have decided to delay the release of the film fearing to clash with Shahrukh Khan starrer 'Chennai Express' which is all set to release in Pakistan on Eid after an import ban was overruled. However, MHSH's writer, Vasay Chaudhry told The Express Tribune that the most anticipated Pakistani film this year is taking its time to hit the box office because of 
<li><a href='http://www.southeastasianews.net/index.php/sid/216266083/scat/303b19022816233b' target="_blank">Pak should know if they want to get rid of terror they need Indias help Farooq Abdullah</a><br />
Reacting to the killing of five Indian soldiers along the Line of Control in Poonch, Union Minister for Non-Renewable Energy Farooq Abdullah on Tuesday said Pakistan should know that if they want to get rid of terror, they need India's help. "They (Pakistan) have to stop all this incursion and killing of our jawans. Pakistan should know that if they want to get rid of terror, they need India's 
<li><a href='http://www.southeastasianews.net/index.php/sid/216265144/scat/303b19022816233b' target="_blank">Aam Aadmi Party volunteers protest globally against planned RTI amendments</a><br />
Volunteers and Friends of Aam Aadmi Party in the United States, Singapore and Australia organised protests during the weekend against the planned amendment to the Right to Information (RTI) Act in the upcoming parliament session. The protests were planned to show the strong public demand for transparency in political parties as well as the anger against the any amendments to the act by vested 
<li><a href='http://www.southeastasianews.net/index.php/sid/216265133/scat/303b19022816233b' target="_blank">Tibetan monk self-immolates in Nepal</a><br />
A Tibetan died after self-immolating himself in Nepal's capital town Kathmandu Tuesday, the Central Tibetan Administration (CTA) said here. This was the second self-immolation death in the Himalayan country this year. "A monk set himself afire near a monastery in Kathmandu this (Tuesday) morning. He was taken to a nearby hospital where he was declared dead," CTA spokesperson Tashi Phuntsok told 
<li><a href='http://www.southeastasianews.net/index.php/sid/216264199/scat/303b19022816233b' target="_blank">Pak to host world champs Indian blind cricket team in February 2014</a><br />
The Indian blind cricket team will reportedly come on tour to Pakistan in February next year, which will be their third tour to their arch-rivals, to play in three one-days and three Twenty20 internationals The last time the Indian side played in Pakistan was in December 2011 when they lost both the one-day and Twenty20 series. According to the Daily Times, Pakistan's blind team toured India 
<li><a href='http://www.southeastasianews.net/index.php/sid/216285813/scat/303b19022816233b' target="_blank">Mead Johnson Biostime announce fines in China price-fixing probe by milk suppliers</a><br />
BEIJING -- Two suppliers of infant formula, Mead Johnson and Hong Kong&#039;s Biostime, say Chinese authorities have imposed multimillion-dollar fines on them in a price-fixing probe. Mead Johnson Nutrition Co. said Wednesday its China unit was fined 203.8 million yuan ($33 million). Biostime International Holdings Ltd. said its local arm was fined 162.9 million yuan ($26.3 million). Chinese 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286063/scat/303b19022816233b' target="_blank">Indian Shares Follow Asian Markets Lower</a><br />
Indian shares fell on Tuesday, mirroring weakness across the Asia-Pacific region as encouraging U.S. service-sector data fueled speculation the Federal Reserve may reduce the pace of bond buying sooner rather than later. Dallas Federal Reserve Bank President Richard Fisher, one of the most vocal critics of quantitative easing, likened the Fed&#039;s stimulus efforts to &quot;a monetary Gordian 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286065/scat/303b19022816233b' target="_blank">AFC Asian Cup 2019 bid workshop in Sept</a><br />
Eight countries keep their interest to host the 2019 Asian Cup soccer tournament and will be invited to attend a workshop on bidding processes, Asian football&#039;s governing body said.Eleven countries had expressed their interest to host the competition when the bidding started but three - Lebanon, Malaysia and Myanmar - have since pulled out of the race. Representatives from the remaining 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286066/scat/303b19022816233b' target="_blank">BWF suspends Thai shuttlers for brawl</a><br />
The Badminton World Federation (BWF) on Tuesday announced the suspension of two Thai shuttlers who involved in a brawl during a game last month.Bodin Issara beat his former men&#039;s doubles partner Maneepong Jongjit during the final of Canada Open on July 21 after a spat with his Thai compatriot.Bodin&#039;s pair was disqualified after a black card was issued and Maneepong got the champion.BWF 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286067/scat/303b19022816233b' target="_blank">India summons Pakistani envoy over attack</a><br />
India yesterday summoned the Pakistan Deputy High Commissioner, Mansoor Ahmad Khan, to lodge a strong protest against the killing of five Indian soldiers by Pakistan across the Line of Control (LoC) in Jammu. Sources in the government said India made it quite clear that it was taking a serious view of the incident and Pakistan needs to investigate and find out as to who is behind these attacks. 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286005/scat/303b19022816233b' target="_blank">Philippines rejects anew Chinas indisputable claim over seas</a><br />
The Philippines&#039; Department of Foreign Affairs (DFA) rejects China&#039;s &quot;indisputable&quot; claim over the entire West Philippine Sea (South China Sea), including parts of the country&#039;s 200-mile Exclusive Economic Zone (EEZ) - the &quot;core issue&quot; of the territorial dispute between the two countries, a spokesman for the DFA said Tuesday. &quot;We once again redirect China 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286068/scat/303b19022816233b' target="_blank">JPKE fixes prices of more milk cooking oil products</a><br />
A shelf of cooking oil products at a supermarket. The government has fixed the pricing of nine more brands of cooking oil in the sultanate. Picture: BT 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286069/scat/303b19022816233b' target="_blank">Generators to light up Raya for Tutong Belait converts</a><br />
Da&#039;wah Centre yesterday.&quot;We have never had electricity. Household chores had to be done by hand. I hope we will now be able to install proper light bulbs so our house will be lit up like every other house for 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286070/scat/303b19022816233b' target="_blank">Exit visa no longer required for officials diplomats in Laos</a><br />
Diplomats and official passport holders will soon no longer require exit visas to make official foreign trips to countries in which Laos has agreements on visa exemption after the Cabinet approved a new regulation last week. The new regulation is expected to take effect in September, a senior official of the Consular Department, Ministry of Foreign Affairs told 
<li><a href='http://www.southeastasianews.net/index.php/sid/216285897/scat/303b19022816233b' target="_blank">Seven killed in bomb blast in Pakistans Karachi Police</a><br />
bomb blast in Pakistan&#039;s port city of Karachi early on Wednesday killed seven people and wounded 26 others, police said. The blast took place in the impoverished Lyari neighbourhood of the city after 
<li><a href='http://www.southeastasianews.net/index.php/sid/216285937/scat/303b19022816233b' target="_blank">Since The Ted Talk Michael Pritchard On How He’s Helping End Water Poverty In Malaysia</a><br />
Photo: Kedume/ Flickr By Helen Walters Michael Pritchard is very likely the only person to have stood on the TED stage and uttered the immortal phrase, &quot;Let&#039;s get a bit of that poo in there.&quot; At TEDGlobal 2009 in Oxford, he demonstrated his then-new product, the Lifesaver bottle, which can be used to turn filthy, rabbit-dropping-infested water into sparklingly clean liquid 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286072/scat/303b19022816233b' target="_blank">Pakistani TV Host Gives Away Babies Live on Air Calls It Real Islam</a><br />
A childless couple kisses their newly adopted daughter, Fatima, whom Pakistani television talk show host Aamir Liaquat Hussain gave them on his show, as they sit at the Chhipa Welfare Association office in Karachi August 1, 
<li><a href='http://www.southeastasianews.net/index.php/sid/216285817/scat/303b19022816233b' target="_blank">Asian stocks follow Wall Street down dollar dips</a><br />
Tokyo&#039;s Nikkei shed 2.4 percent to trade at one-week lows, with exporters such as Toyota Corp losing ground on concerns the stronger yen would erode their dollar earnings when 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284988/scat/303b19022816233b' target="_blank">Countries recall NZ milk as Fonterra says sorry</a><br />
Many countries across the region have recalled products from Fonterra Cooperative Group, the New Zealand-based company at the centre of a milk powder safety scare.Fonterra apologised on Monday and pledged that all the contaminated material would be brought under control within 48 hours.&quot;We really regret the distress and anxiety which this issue could have caused,&quot; said Fonterra CEO Theo 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284987/scat/303b19022816233b' target="_blank">Malaysia still safe despite shooting cases says police chief</a><br />
The spate of shooting cases does not make Malaysia an unsafe country, said Malaysia&#039;s Inspector-General of Police Khalid Abu Bakar.&quot;I would like to urge Malaysians to put their trust in the police force to solve these cases. Certain people have taken the opportunity to blame us and make us the scapegoat.&quot;It may look like there are a lot of firearms in the country but let us monitor 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284986/scat/303b19022816233b' target="_blank">Salamdander Discovers Oil at G450-5 Well off Thailand</a><br />
Surin prospect in the central portion of the Western sub-basin, Block G4/50, Gulf of Thailand. Oil was discovered in good quality Miocene fluvial sandstones in the primary N40 target zone over the interval 5,003 to 5,030 feet (1,525 to 1,533 meters) TVDSS (True Vertical Depth SubSea). Wire-line logs and pressure data confirmed the presence of approximately 26 feet (8 meters) of oil pay. Oil 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284625/scat/303b19022816233b' target="_blank">Asian stocks drop amid stimulus cutback worries</a><br />
Asian stocks outside Japan fell on Tuesday amid believes the US Federal Reserve will soon reduce stimulus as stringer growth was seen in the services 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284985/scat/303b19022816233b' target="_blank">Asia Roundup Marts mixed on stimulus cut concern</a><br />
Asian markets were mixed yesterday Tuesday August 06 2013 as investor concerns lingered over a potential tapering of US monetary stimulus. Tokyo gained 1.00 per cent, or 143.02 points, to 14,401.06 after a late buying surge as the greenback rose against the yen. But Sydney dropped 0.11 per cent, or 5.7 points, to 5,105.6 after Australia&rsquo;s central bank cut interest rates to a new record 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284984/scat/303b19022816233b' target="_blank">QSM Announces Expansion Into Asia Pacific Market</a><br />
Quantitative Software Management, Inc. (QSM), a leader in software process improvement and systems development estimation, today announced a partnership with RedBay Consulting to sell QSM&rsquo;s SLIM tools in the Asia Pacific region. When working on behalf of QSM, they will conduct business as Quantitative Software Management-Asia/Pacific. Through this partnership, Quantitative Software 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284983/scat/303b19022816233b' target="_blank">Indonesia temple blast protests violence against Burma Muslims government</a><br />
A small bomb exploded at a Buddhist temple in Indonesia&rsquo;s capital, slightly injuring three people, in protest against violence against Rohingya Muslims in Buddhist-majority Myanmar, a government official said. The device was detonated late on Sunday at the entrance of the Ekayana temple in West Jakarta as people were praying inside, while another bomb failed to explode, police said. The 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284982/scat/303b19022816233b' target="_blank">Airbus delivers its 8000th A320 to Air Asia Indonesia</a><br />
Airbus today delivered its 8,000th A320 aircraft to the Indonesian wing of Air Asia at its base in Jakarta. Group Chief Executive Officer Tan Sri Tony Fernandez said Air Asia had a long-standing, special relationship with Airbus, making it proud to have the 8,000th Airbus aircraft as a member of its fleet. &#039;;It&rsquo;s the same pioneering, forward-looking mindset and a lot of hard work 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284981/scat/303b19022816233b' target="_blank">Transportation concerns as millions embark on Indonesia’s annual exodus</a><br />
Officials in Indonesia are hoping to ease the nation&rsquo;s famous traffic congestion, as millions of Indonesians travel across the country for their annual Eid holiday. The obligation to return home at the end of the Muslim month of fasting &ndash; an annual tradition known as mudik &ndash; sees tens of millions of people moving at the same time. Indonesia&rsquo;s President Susilo Bambang 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284662/scat/303b19022816233b' target="_blank">Garuda Indonesia Liverpool FC launch special edition frequent flyer card</a><br />
Garuda Indonesia, the airline of Indonesia, has launched the &lsquo;Garuda Frequent Flyer &ndash; Liverpool Football Club edition card&rsquo;, a special edition in line with the airline&rsquo;s effort to continuously deliver added value to loyal customers. The &lsquo;GFF-LFC Edition Card&rsquo; is an exclusively designed card which is dedicated to loyal customers of Garuda Indonesia and 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284728/scat/303b19022816233b' target="_blank">Duties adjusted on Indonesian Thai food additives</a><br />
China&#039;s Ministry of Commerce (MOC) will adjust anti-dumping duties on certain food additives imported from Indonesia and Thailand starting 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284980/scat/303b19022816233b' target="_blank">Education officers bring aid to needy</a><br />
Raya goodies brought over by a group of officers from the Curriculum Development Department at the Ministry of Education who paid the family a visit at their flat in 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284979/scat/303b19022816233b' target="_blank">Bruneian MOS bronze medallist returns as champion</a><br />
Billah College was placed third at the annual Microsoft Office Specialist (MOS) World Championship that was held from July 31 to August 3.The student, 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284978/scat/303b19022816233b' target="_blank">Raya revellers reminded of road safety</a><br />
MinComm Permanent Secretary Abdul Mutalib Pehin Orang Kaya Seri Setia Dato Paduka Hj Mohd Yusof handing over brochures and Hari Raya greeting cards to motorists at Tungku Link Highway yesterday. Picture: 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284977/scat/303b19022816233b' target="_blank">His Majesty greets Iranian President</a><br />
Darussalam said the friendship and goodwill shared by the two countries was much appreciated, and that he looked forward to working with the president in strengthening the much-valued ties in the coming year.His Majesty also extended his best wishes to 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284976/scat/303b19022816233b' target="_blank">Parabola to be phased out in 5 years</a><br />
TVRO (TV Receive Only) systems, locally known as &quot;parabola&quot; or satellite dish television, will be phased out within five years, the Ministry of Communications 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284975/scat/303b19022816233b' target="_blank">Philippines Aseans main economic engine</a><br />
The Philippines is now Southeast Asia&#039;s main economic engine, fuelled by strong domestic demand, to lead the rest of the region ahead of Asia this year, rating firm Standard &amp; Poor&#039;s (S&amp;P) said. While growth across Asia will continue to be dragged by worsening economic conditions in China and the tepid recovery in the US and Europe, S&amp;P said in a report this week that 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284974/scat/303b19022816233b' target="_blank">Warship arrives in Philippines amid sea row</a><br />
Philippine President Benigno Aquino III on Tuesday called the second Hamilton class-cutter from the United States a big boost to the Navy in patrolling the seas amid a territorial row with China. In the drizzly morning but with a fiesta-like atmosphere, the President, Cabinet members and the military top brass watched from the BRP Ang Pangulo as the 3,250-ton decommissioned warship from the US 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284973/scat/303b19022816233b' target="_blank">Attack on soldiers puts India-Pakistan talks under cloud</a><br />
Despite the attack which left 5 Indian soldiers dead, New Delhi had responded positively to Pak&rsquo;s proposal for ameeting between Manmohan Singh and Nawaz Sharif in New York in 
<li><a href='http://www.southeastasianews.net/index.php/sid/216285750/scat/303b19022816233b' target="_blank">Dolphins display memory better than elephants study finds</a><br />
Mar. 18, 2003: A bottle nose dolphin trained by the U.S. Navy to detect mines leaps out of the water in front Sgt. Andrew Garrett while training near the USS Gunston Hall (LSD 44) in the Arabian Gulf. Attached to the dolphin&#039;s pectoral fin is a &quot;pinger&quot; that allows the handler to keep track of the dolphin when out of 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284972/scat/303b19022816233b' target="_blank">Bomb blast at soccer field kills 7 wounds over 20 in southern Pakistan</a><br />
People look at the lifeless bodies of victims shot by gunmen at a local hospital in Quetta, Pakistan, Tuesday, Aug. 6, 2013. Dozens of gunmen disguised in police uniforms shot to death more than a dozen they pulled off of a convoy of buses in southwest Pakistan and dumped their bodies in a nearby ravine, officials said Tuesday. (AP Photo/Arshad 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284548/scat/303b19022816233b' target="_blank">Attacks kill 28 people across Pakistan</a><br />
KARACHI, Pakistan A bomb blast that appeared to be targeting a provincial government minister killed 11 people before dawn Wednesday at a soccer field in southern Pakistan, the latest in a series of attacks that left 28 people dead across the country, officials said. The bomb planted next to the field in the city of Karachi was hidden in a motorcycle, said senior police official Razaq Dharejo. 
<li><a href='http://www.southeastasianews.net/index.php/sid/216286071/scat/303b19022816233b' target="_blank">CORRECTED-Singapores Soilbuild REIT to price share listing at low end-IFR</a><br />
Tue Aug 6, 2013 9:17pm EDT (Corrects price range in paragraph 2) SINGAPORE Aug 6 (Reuters) - Singapore&#39;s Soilbuild Business Space REIT is set to price its S$457 million ($360 million) stock market listing at the lower end of its indicative price range, Thomson Reuters publication IFR reported. Sponsored by property developer Soilbuild Group Holdings Ltd , the REIT is expected to price its 
<li><a href='http://www.southeastasianews.net/index.php/sid/216284971/scat/303b19022816233b' target="_blank">Pakistan flood death tool reaches at least 80</a><br />
A U.N. relief agency said Tuesday more than 81,000 Pakistanis have been displaced by flooding that has killed at least 80 people. The U.N. Office for the Coordination of Humanitarian Affairs said in a release issued in New York the monsoon rains also have inundated thousands of acres of standing crops and damaged many houses and infrastructure. OCHA representative Jens Laerke told reporters in 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283617/scat/303b19022816233b' target="_blank">Analysts See Washington Post Purchase As Timely</a><br />
Amazon founder Jeff Bezos is buying one of the top U.S. newspapers. The Washington Post announced Monday that Bezos is buying the paper and its affiliated publications for $250 million. The news surprised many in the news industry. But as Some analysts say the deal may be good for the struggling newspaper business. Known for breaking major stories - it&rsquo;s been an icon of print journalism 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283455/scat/303b19022816233b' target="_blank">Ghana Steps Up Security Ahead of Supreme Court Ruling</a><br />
Ghana&rsquo;s Supreme Court plans to hear final oral arguments Wednesday on the dispute over the December 2012 presidential election. Both the petitioners and the defendants will have 30 minutes each to present their cases before the judges. According to the constitution, the court must issue its decision within 15 days after oral arguments are finished. Deputy information minister Felix 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283618/scat/303b19022816233b' target="_blank">First Probable Person-to-Person Bird Flu Case Reported in China</a><br />
Scientists researching a new strain of bird flu in eastern China are reporting the first case of probable person-to-person transmission of the so-called H7N9 virus. The findings were reported Tuesday in the British Medical Journal and focus on the case of an adult woman and her 60-year-old father, who became ill in March after a routine visit to a live poultry market. Despite medical care and 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283677/scat/303b19022816233b' target="_blank">Evidence suggests new bird flu spread among people</a><br />
Chinese scientists have found the strongest evidence yet that a new bird flu strain is sometimes able to spread from person to person, but they are emphasizing that the virus still does not transmit easily.The new bird flu strain, known as H7N9, was first reported by Chinese authorities in March. As of the end of May, there were 132 cases and 37 deaths in China and Taiwan linked to the 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283442/scat/303b19022816233b' target="_blank">Fayette County Thai street food festival and Central Park Five community event Saturday</a><br />
The Bluegrass of Kentucky Chapter of Love on a Leash celebrated its first anniversary recently at Morning Pointe of Lexington with a dog parade. Five trained therapy dogs wore costumes and performed tricks for the facility&#039;s residents. Pictured, from left, Kim Burford with Buddy, Warren Watts with Chip, Corie Patterson with Edith, Ken Boden with Lucy, Bonnie Cesna with 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283678/scat/303b19022816233b' target="_blank">Asian Stocks Drop on Concern Fed Will Reduce Stimulus</a><br />
Asian stocks fell for a second day as stronger growth in US service industries fueled speculation the Federal Reserve will soon be able to reduce economic stimulus. HSBC Holdings Plc (5) slumped 4.5 percent in Hong Kong after earnings at Europe&rsquo;s biggest bank missed analysts&rsquo; estimates. Sony Corp. (6758) sank 5.5 percent in Tokyo after its board rejected billionaire Daniel 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283679/scat/303b19022816233b' target="_blank">Investors Turn HK’s Red Taxis Into Latest Bubble Market</a><br />
Allan Shek, the owner of a Hong Kong shop selling gold and jade jewellery, says he&rsquo;s made millions on the side by riding wild swings in the stock market and by buying into the city&rsquo;s property boom. No more. Last month, he bought five Hong Kong taxis and the licenses to operate them. Seven or eight of his friends have bought taxis too, he says. &#039;;If I have the ability, I will 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283681/scat/303b19022816233b' target="_blank">PHL to apologise for Taiwan fisherman’s death daughter</a><br />
The Philippines will send a special envoy to Taiwan to apologise for the fatal shooting of a Taiwanese fisherman, his daughter said Monday, signaling a potential breakthrough in a major row. The remarks sparked hopes that the conciliatory move, if realised, could ease the strained relationship between Taipei and Manila following the shooting of 65-year-old Hung Shih-cheng on May 9 in disputed 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283682/scat/303b19022816233b' target="_blank">After N Korea- Bound Cargo Seizure Panama Warns Canal Users To Declare Everything</a><br />
Panama is not having it anymore. After the controversy around the North Korean ship Chong Chon Gang, caught in July going through the canal with an undeclared hold full of weapons &ndash; old Soviet jet fighters and anti-aircraft missiles &ndash; the government has warned every country using the waterway. The Panamanian government is telling the world that trying to sneak clandestine cargo 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283683/scat/303b19022816233b' target="_blank">N Korea Two million have mobile phones</a><br />
North Koreans may be isolated from the rest of the world, but it seems that they have more chances to talk to one another. The Egyptian company that holds the mobile phone license for North Korea says there are now more than two million people with mobiles in the country. Naguib Sawiris of Orascom Telecom told South Korea&rsquo;s Choson Ilbo newspaper that the North hit the landmark figure in 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283684/scat/303b19022816233b' target="_blank">National Geographic Korea and the 38th Parallel</a><br />
Sixty years ago North and South Korea ended the &#039;;Korean Conflict&#039;; by agreeing to the Armistice Agreement for the Restoration of the South Korean State. The agreement &ndash; a cease-fire, not a peace treaty &ndash; called for the Korean peninsula to be divided by a Military Demarcation Line (MDL) and a buffer, the demilitarised zone (DMZ), whose function would be to &#039;;prevent the 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283685/scat/303b19022816233b' target="_blank">Video from Asiana crash rescue effort shows girl overlooked – report</a><br />
A video obtained by the San Francisco Chronicle newspaper shows that the supervisor directing the firefighting effort at an airport crash site was not told that a teenage girl was on the ground until after she was mistakenly run over and killed by a fire truck, the paper said on Monday. The video, which the Chronicle obtained from an undisclosed source, was taken from a camera mounted on the 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283686/scat/303b19022816233b' target="_blank">China’s Debt Surge Pressures Xi-Li to Avert Lost Decade</a><br />
A Chinese lending spree of the magnitude that tipped Asian nations into crisis in the late 1990s and preceded Japan&rsquo;s lost decades is putting pressure on top leaders to map out a strategy to tackle the threat. Half of the economists in a Bloomberg News survey say non-performing local-government and corporate debt will probably have a &#039;;significant impact&#039;; on China&rsquo;s 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283687/scat/303b19022816233b' target="_blank">Fonterra Tainted Items Add to Woes of Consumers in China</a><br />
Fonterra Cooperative Group Ltd&rsquo;s warnings of tainted ingredients in some products of the world&rsquo;s largest dairy exporter is the latest blow to baby formula sellers amid Chinese consumers&rsquo; concerns about food safety. The Auckland-based company found bacteria causing a rare illness called botulism in about 38 metric tonnes of whey protein concentrate it produced, Fonterra said 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283688/scat/303b19022816233b' target="_blank">China agency sued over oil production in spill-hit bay</a><br />
China&rsquo;s State Oceanic Administration (SOA) is being sued for allowing US oil major ConocoPhillips to resume production after spills off northern China in 2011, state media reported on Monday. The Global Times newspaper, affiliated with the ruling Communist Party, said the SOA confirmed it was being pursued for administrative misconduct. The action is being mounted by the All-China 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283689/scat/303b19022816233b' target="_blank">Veolia profits slow to a trickle shares sparkle</a><br />
French utilities group Veolia Environnement reported a six-month profits slump owing to provisions and warned that its activities in China were slowing, in a results statement on Monday, but its shares firmed. The group, which provides water and waste management services in many countries, held to its targets for this year with the emphasis on reducing costs and debt. For the first half of 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283690/scat/303b19022816233b' target="_blank">China heat ‘foils man’s plan to fake beating death’</a><br />
A Chinese vendor&rsquo;s plan to fake his own death at the hands of social enforcers failed when he could not play dead long enough in scorching heat, state media reported Monday. More than 10 men claimed the soft drinks vendor had been beaten to death in the central city of Wuhan by chengguan, who are tasked with enforcing non-criminal regulations in towns and cities. Chengguan have long 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283691/scat/303b19022816233b' target="_blank">Chinese online game lets players fight Japan over disputed islands</a><br />
In &#039;;Glorious Mission Online,&#039;; China&rsquo;s first online game co-developed by the People&rsquo;s Liberation Army and released to the public, players join the ranks of the country&rsquo;s military to take on the enemy. The game was originally developed by China&rsquo;s military as a training and recruitment tool and featured Chinese forces taking on American soldiers. But the game 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283692/scat/303b19022816233b' target="_blank">China’s CNPC Seen Tapping Exxon-Rosneft Assets Real MA</a><br />
China National Petroleum Corp. already spent more money this year on energy assets than any other global producer. Oil and gas fields controlled by Exxon Mobil Corp. (XOM) and Russia&rsquo;s OAO Rosneft may be next on the list. China&rsquo;s largest oil producer, known as CNPC, has made more than $9 billion of purchases this year &ndash; and has considered another $4 billion, according to 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283693/scat/303b19022816233b' target="_blank">China’s Top Countries For Second Homes</a><br />
This fall in Hawaii, the people over at LA bound Affinity China will be hosting hundreds of affluent Chinese looking for a piece of real estate in the US Countries around the world are watching affluent Chinese gobble up property, most of it prime-time. In some countries, this will have ramifications on social services &ndash; as is the case in places like New Zealand &ndash; and Canada, as the 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283694/scat/303b19022816233b' target="_blank">Viewpoint Why is China investigating GlaxoSmithKline</a><br />
The corruption investigation launched by the Chinese authorities against GlaxoSmithKline (GSK) continues to pass like a whirlwind through the firm&rsquo;s Chinese operations, throwing into chaos the company&rsquo;s carefully laid plans for expansion in one of its most promising markets. Other foreign investors have looked on with a mixture of horror and sympathy: China is a complicated market 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283695/scat/303b19022816233b' target="_blank">China Probe Pressures Glaxo CEO Anew</a><br />
Andrew Witty has spent several years talking about his efforts to clean up the aggressive marketing tactics he inherited as GlaxoSmithKline GSK.LN -0.44 percent PLC&rsquo;s chief executive. Now he faces the uncomfortable problem of defending the company against bribery allegations in China that occurred on his watch. Witty took over as Glaxo&rsquo;s chief in 2008, when the company was the 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283696/scat/303b19022816233b' target="_blank">Exclusive Japan nuclear body says radioactive water at Fukushima an ‘emergency’</a><br />
Highly radioactive water seeping into the ocean from Japan&rsquo;s crippled Fukushima nuclear plant is creating an &#039;;emergency&#039;; that the operator is struggling to contain, an official from the country&rsquo;s nuclear watchdog said on Monday. This contaminated groundwater has breached an underground barrier, is rising toward the surface and is exceeding legal limits of radioactive 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283697/scat/303b19022816233b' target="_blank">Nothing to fear now that Japan is rising again</a><br />
Japan has a problem. It feels more and more threatened by China&rsquo;s growing power and ambitions, and less confident of America&rsquo;s protection. But any step to bolster its own defence is immediately suspected, even by its closest friends, of reviving the militarism that led to war in the 1930s and 1940s. What is Japan to do? Worries about militarism have spiked since prime minister 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283698/scat/303b19022816233b' target="_blank">Global Banks in Japan Boost Profit on Abenomics Job Cuts</a><br />
Bank of America Corp. led a fivefold increase in profit at foreign banks&rsquo; Japan securities units last fiscal year as they accelerated job cuts and increased fees and commissions during the country&rsquo;s stock-market rebound. Combined net income at the Japanese units of 10 global banks rose to 32.8 billion yen ($332 million) for the year ended March 31 from 5.7 billion yen a year 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283700/scat/303b19022816233b' target="_blank">IMF Warns of Risk Unless Japan Reins In Its Debt</a><br />
The International Monetary Fund on Monday made a fresh call on Japan&rsquo;s government to bring its flow of red ink under control, saying the central bank&rsquo;s monetary easing could backfire if investors believe it is &#039;;monetising&#039;; the growing mountain of government debt, a step that often leads to financial turmoil. The IMF has recently hardened its rhetoric toward Japan, 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283699/scat/303b19022816233b' target="_blank">Communist Party makes a comeback… in Japan</a><br />
A smiling, smartly attired 30-year-old woman sits at an expansive table in a meeting room decorated with simple elegance on the fourth floor of a modern office building in central Tokyo. Only the sunflower broach &ndash; an anti-nuclear symbol &ndash; on the woman&rsquo;s suit, and perhaps that the large calligraphy scroll on the wall behind her that isn&rsquo;t hung perfectly straight, betray 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283701/scat/303b19022816233b' target="_blank">Japan’s tough choice on tax hike</a><br />
Japan is beginning to emerge from 15 years of economic stagnation but a tax rise aimed at controlling sky-high borrowing could spoil the party. The government is planning to double consumption tax to 10 percent by 2015. Paid by consumers when they buy goods or services, the tax will be increased in two stages, rising first to 8 percent in April 2014. The country&rsquo;s leaders face a tough 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283702/scat/303b19022816233b' target="_blank">Singapore traveller arrested for $50k methamphetamine</a><br />
A 38 year-old Singaporean man has appeared in the Manukau District Court today, charged with importing methamphetamine with an estimated street value of up to $50,000. He was arrested by Customs officers at Auckland International Airport last night after being found in possession of 55g of methamphetamine. The man arrived on a flight from Sydney and was questioned by Customs officers, and his 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283703/scat/303b19022816233b' target="_blank">Singapore Land Bids ‘Suicidal’ With Rules Billionaire Kwek Says</a><br />
Buying land in Singapore at current high prices would be &#039;;suicidal&#039;; given the government&rsquo;s requirement that new homes must be sold within two years of completion, City Developments Ltd (CIT) Chair Kwek Leng Beng said. Developers of land for high-end residential projects are subject to conditions of a so-called qualifying certificate, which includes the two-year deadline, 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283608/scat/303b19022816233b' target="_blank">Indias tensions with Pakistan rise after five soldiers killed along their border</a><br />
Indian army soldiers salute as they pay tribute to their colleagues at a wreath-laying ceremony in Poonch, India. India&#039;s army says five of its soldiers were killed and another wounded when Pakistani troops fired at a patrol near the the disputed Himalayan region of Kashmir yesterday. Photograph: 
<li><a href='http://www.southeastasianews.net/index.php/sid/216283704/scat/303b19022816233b' target="_blank">Hold back talks with Pakistan BJP</a><br />
Bharatiya Janata Party has demanded a befitting reply to Pakistan after the killing of Indian soldiers along the Line of Control in Jammu &amp; 
<li><a href='http://www.southeastasianews.net/index.php/sid/216282350/scat/303b19022816233b' target="_blank">Obama Warns Against Re-inflating Housing Bubble</a><br />
WHITE HOUSE -- In his latest speech on the U.S. economy, President Barack Obama has outlined steps he says need to be taken to strengthen the U.S. housing market. The president flew to Phoenix, which was among American cities that suffered the most from the housing market collapse of 2009, to deliver his latest speech on the economy and his proposals to help extend recovery and help the middle 
<li><a href='http://www.southeastasianews.net/index.php/sid/216282093/scat/303b19022816233b' target="_blank">Analysis - Rising Thai household debt spurs rate tussle as economy slows</a><br />
Reuters &copy; Visitors look at Subaru cars on display in an exhibition booth at a department store in Bangkok August 4, 2013. REUTERS/Athit 
<li><a href='http://www.southeastasianews.net/index.php/sid/216282423/scat/303b19022816233b' target="_blank">PST 15000 turn out for FC Barcelona’s training session in Bangkok</a><br />
European soccer&#039;s massive Asian fan base delivered again on Tuesday, as 15,000 spectators took in FC Barcelona&#039;s open training session in Bangkok, Thailand&#039;s Rajamangala National Stadium. Bara will take on Thailand&#039;s national team on Wednesday, followed by a Malaysian selection on Saturday, before returning to Spain in time for the La Liga season to kick off on Aug. 18. The 
</ul></div>



</div>
</div>
</body>
</html>